// packages/heroui/src/components/auth/two-factor/disable-two-factor-dialog.tsx
import type { TwoFactorAuthClient } from "@better-auth-ui/core/plugins/two-factor"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useDisableTwoFactor } from "@better-auth-ui/react/plugins/two-factor"
import { ShieldExclamation } from "@gravity-ui/icons"
import {
  AlertDialog,
  Button,
  FieldError,
  Input,
  Label,
  Spinner,
  TextField,
  toast
} from "@heroui/react"

import { twoFactorPlugin } from "../../../lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "../../../lib/auth/use-two-factor-password"
import { useAuthForm } from "../auth-form"

export type DisableTwoFactorDialogProps = {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Confirm turning two-factor off.
 *
 * @param isOpen - Whether the dialog is open.
 * @param onOpenChange - Called when the dialog requests an open state change.
 */
export function DisableTwoFactorDialog({
  isOpen,
  onOpenChange
}: DisableTwoFactorDialogProps) {
  const { authClient, localization } = useAuth()
  const { localization: twoFactorLocalization } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const { mutateAsync: disableTwoFactor, isPending: isDisabling } =
    useDisableTwoFactor(authClient as TwoFactorAuthClient, {
      onSuccess: () => {
        toast.success(twoFactorLocalization.twoFactorDisabled)
        onOpenChange(false)
      }
    })

  const isPending = isDisabling || isResolvingPasswordRequirement

  const form = useAuthForm({
    defaultValues: { password: "" },
    onSubmit: async ({ value }) =>
      await disableTwoFactor(
        requiresPassword ? { password: value.password } : {}
      )
  })

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={onOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog>
          <form.AppForm>
            <form.AuthFormRoot>
              <AlertDialog.CloseTrigger />

              <AlertDialog.Header>
                <AlertDialog.Icon status="danger">
                  <ShieldExclamation />
                </AlertDialog.Icon>

                <AlertDialog.Heading>
                  {twoFactorLocalization.disableTwoFactor}
                </AlertDialog.Heading>
              </AlertDialog.Header>

              <AlertDialog.Body className="overflow-visible">
                <p className="text-muted text-sm">
                  {requiresPassword
                    ? twoFactorLocalization.passwordConfirmation
                    : twoFactorLocalization.twoFactorDescription}
                </p>

                {requiresPassword && (
                  <form.AppField name="password">
                    {(field) => (
                      <TextField
                        className="mt-4"
                        name={field.name}
                        autoComplete="current-password"
                        isDisabled={isPending}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={field.handleChange}
                      >
                        <Label>{localization.auth.password}</Label>

                        <Input
                          autoFocus
                          required
                          type="password"
                          placeholder={localization.auth.passwordPlaceholder}
                          variant="secondary"
                        />

                        <FieldError />
                      </TextField>
                    )}
                  </form.AppField>
                )}
              </AlertDialog.Body>

              <AlertDialog.Footer>
                <Button slot="close" variant="tertiary" isDisabled={isPending}>
                  {localization.settings.cancel}
                </Button>

                <form.AuthFormSubmitButton
                  variant="danger"
                  isDisabled={isPending}
                >
                  {isPending && <Spinner color="current" size="sm" />}

                  {twoFactorLocalization.disableTwoFactor}
                </form.AuthFormSubmitButton>
              </AlertDialog.Footer>
            </form.AuthFormRoot>
          </form.AppForm>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/two-factor/disable-two-factor-dialog.tsx
import {
  disableTwoFactorOptions,
  type TwoFactorAuthClient
} from "@better-auth-ui/core/plugins/two-factor"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { ShieldAlert } from "lucide-solid"
import { Show } from "solid-js"
import { toast } from "solid-sonner"

import {
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle
} from "@/components/ui/alert-dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "@/lib/auth/use-two-factor-password"
import { createAuthForm } from "../auth-form"

/** Confirm turning two-factor off. */
export function DisableTwoFactorDialog(props: {
  onOpenChange: (open: boolean) => void
}) {
  const auth = useAuth()
  const { localization: twoFactorLocalization } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const disableTwoFactor = createMutation(() => ({
    ...disableTwoFactorOptions(auth.authClient as TwoFactorAuthClient),
    onSuccess: () => {
      toast.success(twoFactorLocalization.twoFactorDisabled)
      props.onOpenChange(false)
    }
  }))

  const isPending = () =>
    disableTwoFactor.isPending || isResolvingPasswordRequirement()

  const form = createAuthForm(() => ({
    defaultValues: { password: "" },
    onSubmit: async ({ value }) => {
      await disableTwoFactor.mutateAsync(
        (requiresPassword() ? { password: value.password } : {}) as Parameters<
          typeof disableTwoFactor.mutateAsync
        >[0]
      )
    }
  }))

  return (
    <AlertDialogContent>
      <form.AppForm>
        <form.AuthFormRoot class="flex flex-col gap-6">
          <AlertDialogHeader>
            <AlertDialogMedia>
              <ShieldAlert />
            </AlertDialogMedia>

            <AlertDialogTitle>
              {twoFactorLocalization.disableTwoFactor}
            </AlertDialogTitle>

            <AlertDialogDescription>
              {requiresPassword()
                ? twoFactorLocalization.passwordConfirmation
                : twoFactorLocalization.twoFactorDescription}
            </AlertDialogDescription>
          </AlertDialogHeader>

          <Show when={requiresPassword()}>
            <form.AppField name="password">
              {(field) => (
                <Field>
                  <FieldLabel for="disable-two-factor-password">
                    {auth.localization.auth.password}
                  </FieldLabel>

                  <Input
                    autocomplete="current-password"
                    autofocus
                    disabled={isPending()}
                    id="disable-two-factor-password"
                    name={field().name}
                    placeholder={auth.localization.auth.passwordPlaceholder}
                    value={field().state.value}
                    onBlur={field().handleBlur}
                    onInput={(event) =>
                      field().handleChange(event.currentTarget.value)
                    }
                    type="password"
                  />
                  <field.AuthFormFieldError />
                </Field>
              )}
            </form.AppField>
          </Show>

          <AlertDialogFooter>
            <AlertDialogCancel disabled={isPending()} type="button">
              {auth.localization.settings.cancel}
            </AlertDialogCancel>

            <form.AuthFormSubmitButton
              disabled={isPending()}
              variant="destructive"
            >
              <Show when={isPending()}>
                <Spinner />
              </Show>

              {twoFactorLocalization.disableTwoFactor}
            </form.AuthFormSubmitButton>
          </AlertDialogFooter>
          <form.AuthFormServerError />
        </form.AuthFormRoot>
      </form.AppForm>
    </AlertDialogContent>
  )
}
