// examples/start-solid-zaidan-example/src/components/auth/two-factor/backup-codes.tsx
import { downloadTextFile, printTextFile } from "@better-auth-ui/core"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { Copy, Download, Printer } from "lucide-solid"
import { For } from "solid-js"
import { toast } from "solid-sonner"

import { Button } from "@/components/ui/button"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"

export type BackupCodesProps = {
  codes: string[]
}

/**
 * One-time display of freshly generated backup codes.
 *
 * The codes are never persisted anywhere on the client. They live in the
 * calling component's state until the dialog closes, so the save actions
 * matter.
 */
export function BackupCodes(props: BackupCodesProps) {
  const auth = useAuth()
  const { localization: twoFactorLocalization } = useAuthPlugin(twoFactorPlugin)
  const getBackupCodesText = () =>
    [
      twoFactorLocalization.backupCodesForWebsite.replace(
        "{{website}}",
        window.location.origin
      ),
      twoFactorLocalization.backupCodesDescription,
      "",
      ...props.codes
    ].join("\n")

  // Clipboard writes reject on insecure origins and when the user denies the
  // permission, so the codes stay on screen and the toast tells them to copy
  // by hand rather than leaving a rejected promise behind.
  const copyCodes = async () => {
    try {
      await navigator.clipboard.writeText(getBackupCodesText())
      toast.success(twoFactorLocalization.backupCodesCopied)
    } catch {
      toast.error(twoFactorLocalization.backupCodesCopyFailed)
    }
  }

  return (
    <div class="flex flex-col gap-3">
      <p class="text-muted-foreground text-sm">
        {twoFactorLocalization.backupCodesDescription}
      </p>

      <ul class="grid grid-cols-2 gap-2 rounded-md border bg-muted/40 p-4 font-mono text-sm">
        <For each={props.codes}>
          {(backupCode) => <li class="tracking-wide">{backupCode}</li>}
        </For>
      </ul>

      <div class="flex flex-wrap gap-2">
        <Button onClick={copyCodes} size="sm" type="button" variant="outline">
          <Copy />
          {auth.localization.settings.copyToClipboard}
        </Button>

        <Button
          onClick={() =>
            downloadTextFile(getBackupCodesText(), "backup-codes.txt")
          }
          size="sm"
          type="button"
          variant="outline"
        >
          <Download />
          {twoFactorLocalization.downloadBackupCodes}
        </Button>

        <Button
          onClick={() => printTextFile(getBackupCodesText())}
          size="sm"
          type="button"
          variant="outline"
        >
          <Printer />
          {twoFactorLocalization.printBackupCodes}
        </Button>
      </div>
    </div>
  )
}

// examples/start-shadcn-baseui-example/src/components/auth/two-factor/backup-codes.tsx
"use client"

import { downloadTextFile, printTextFile } from "@better-auth-ui/core"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { Copy, Download, Printer } from "lucide-react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"

export type BackupCodesProps = {
  codes: string[]
}

/**
 * One-time display of freshly generated backup codes.
 *
 * The codes are never persisted anywhere on the client. They live in the
 * calling component's state until the dialog closes, so the save actions
 * matter.
 *
 * @param codes - Backup codes returned by enable or regenerate.
 */
export function BackupCodes({ codes }: BackupCodesProps) {
  const { localization } = useAuth()
  const { localization: twoFactorLocalization } = useAuthPlugin(twoFactorPlugin)
  const getBackupCodesText = () =>
    [
      twoFactorLocalization.backupCodesForWebsite.replace(
        "{{website}}",
        window.location.origin
      ),
      twoFactorLocalization.backupCodesDescription,
      "",
      ...codes
    ].join("\n")

  // Clipboard writes reject on insecure origins and when the user denies the
  // permission, so the codes stay on screen and the toast tells them to copy
  // by hand rather than leaving a rejected promise behind.
  const copyCodes = async () => {
    try {
      await navigator.clipboard.writeText(getBackupCodesText())
      toast.success(twoFactorLocalization.backupCodesCopied)
    } catch {
      toast.error(twoFactorLocalization.backupCodesCopyFailed)
    }
  }

  return (
    <div className="flex flex-col gap-3">
      <p className="text-muted-foreground text-sm">
        {twoFactorLocalization.backupCodesDescription}
      </p>

      <ul className="grid grid-cols-2 gap-2 rounded-md border bg-muted/40 p-4 font-mono text-sm">
        {codes.map((backupCode) => (
          <li className="tracking-wide" key={backupCode}>
            {backupCode}
          </li>
        ))}
      </ul>

      <div className="flex flex-wrap gap-2">
        <Button type="button" size="sm" variant="outline" onClick={copyCodes}>
          <Copy data-icon="inline-start" />
          {localization.settings.copyToClipboard}
        </Button>

        <Button
          type="button"
          size="sm"
          variant="outline"
          onClick={() =>
            downloadTextFile(getBackupCodesText(), "backup-codes.txt")
          }
        >
          <Download data-icon="inline-start" />
          {twoFactorLocalization.downloadBackupCodes}
        </Button>

        <Button
          type="button"
          size="sm"
          variant="outline"
          onClick={() => printTextFile(getBackupCodesText())}
        >
          <Printer data-icon="inline-start" />
          {twoFactorLocalization.printBackupCodes}
        </Button>
      </div>
    </div>
  )
}
