// examples/start-solid-zaidan-example/src/components/auth/agent-auth/agent-authorizations.tsx
import type {
  AgentAuthClient,
  AgentAuthorization,
  AgentCapabilityGrant
} from "@better-auth-ui/core/plugins/agent-auth"
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/solid"
import {
  useAgentAuthorizations,
  useRevokeAgentCapability
} from "@better-auth-ui/solid/plugins/agent-auth"
import { BotIcon, ShieldAlertIcon, XIcon } from "lucide-solid"
import { createSignal, For, Match, Show, Switch } from "solid-js"

import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle
} from "@/components/ui/alert-dialog"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { agentAuthPlugin } from "@/lib/auth/agent-auth-plugin"
import { cn } from "cn"

type RevokeTarget = {
  agent: AgentAuthorization
  grant: AgentCapabilityGrant
}

export type AgentAuthorizationsProps = {
  class?: string
}

/** List user-owned agents and revoke individual active capability grants. */
export function AgentAuthorizations(props: AgentAuthorizationsProps) {
  const auth = useAuth<AgentAuthClient>()
  const plugin = useAuthPlugin(agentAuthPlugin)
  // The Solid agent-auth hooks take the user id directly, unlike the React
  // ones which resolve it from the client.
  const session = useSession(auth.authClient)
  const userId = () => session.data?.user.id
  const agents = useAgentAuthorizations(plugin.adapter, userId)
  const revoke = useRevokeAgentCapability(plugin.adapter, userId)
  const [target, setTarget] = createSignal<RevokeTarget>()

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <div class="flex flex-col gap-1">
        <h2 class="text-sm font-semibold">{plugin.localization.agents}</h2>
        <p class="text-xs text-muted-foreground">
          {plugin.localization.agentsDescription}
        </p>
      </div>

      <Card class="p-0">
        <CardContent class="flex flex-col gap-5 p-4">
          <Switch>
            <Match when={agents.isPending}>
              <Skeleton class="h-24 rounded-xl" />
              <Skeleton class="h-24 rounded-xl" />
            </Match>

            <Match when={agents.data?.length}>
              <For each={agents.data}>
                {(agent) => (
                  <div class="flex flex-col gap-3">
                    <div class="flex items-center gap-3">
                      <div class="flex size-10 shrink-0 items-center justify-center rounded-xl bg-muted">
                        <BotIcon class="size-4" />
                      </div>
                      <div class="flex min-w-0 flex-1 flex-col">
                        <span class="truncate text-sm font-semibold">
                          {agent.name}
                        </span>
                        <span class="truncate text-xs text-muted-foreground">
                          {agent.hostName ?? agent.hostId}
                        </span>
                      </div>
                      <Badge variant="secondary">
                        {agent.mode === "autonomous"
                          ? plugin.localization.autonomousAgent
                          : plugin.localization.delegatedAgent}
                      </Badge>
                    </div>

                    <div class="flex flex-col gap-2 pl-13">
                      <For each={agent.grants}>
                        {(grant) => (
                          <div class="flex items-center gap-2">
                            <div class="flex min-w-0 flex-1 flex-col">
                              <span class="truncate text-sm">
                                {grant.capability}
                              </span>
                              <Show when={grant.description}>
                                <span class="truncate text-xs text-muted-foreground">
                                  {grant.description}
                                </span>
                              </Show>
                            </div>
                            <Badge variant="secondary">
                              {plugin.localization[grant.status]}
                            </Badge>
                            <Show when={grant.status === "active"}>
                              <Button
                                aria-label={`${plugin.localization.revoke} ${grant.capability}`}
                                onClick={() => setTarget({ agent, grant })}
                                size="icon-sm"
                                type="button"
                                variant="ghost"
                              >
                                <XIcon />
                              </Button>
                            </Show>
                          </div>
                        )}
                      </For>
                    </div>
                  </div>
                )}
              </For>
            </Match>

            <Match when={!agents.data?.length}>
              <div class="flex items-center gap-3 text-muted-foreground">
                <BotIcon class="size-5" />
                <p class="text-sm">{plugin.localization.noAgents}</p>
              </div>
            </Match>
          </Switch>
        </CardContent>
      </Card>

      <AlertDialog
        onOpenChange={(open) => {
          if (!open) setTarget(undefined)
        }}
        open={Boolean(target())}
      >
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogMedia>
              <ShieldAlertIcon />
            </AlertDialogMedia>
            <AlertDialogTitle>
              {plugin.localization.revokeTitle}
            </AlertDialogTitle>
            <AlertDialogDescription>
              {plugin.localization.revokeDescription}
            </AlertDialogDescription>
          </AlertDialogHeader>

          <code class="rounded-lg bg-muted p-3 text-xs">
            {target()?.grant.capability}
          </code>

          <AlertDialogFooter>
            <AlertDialogCancel disabled={revoke.isPending}>
              {auth.localization.settings.cancel}
            </AlertDialogCancel>
            <Button
              disabled={revoke.isPending}
              onClick={() => {
                const revokeTarget = target()
                if (!revokeTarget) return

                revoke.mutate(
                  {
                    agentId: revokeTarget.agent.id,
                    capability: revokeTarget.grant.capability
                  },
                  { onSuccess: () => setTarget(undefined) }
                )
              }}
              type="button"
              variant="destructive"
            >
              <Show when={revoke.isPending}>
                <Spinner data-icon="inline-start" />
              </Show>
              {plugin.localization.confirmRevoke}
            </Button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </div>
  )
}

// packages/heroui/src/components/auth/agent-auth/agent-authorizations.tsx
"use client"

import type {
  AgentAuthClient,
  AgentAuthorization,
  AgentCapabilityGrant
} from "@better-auth-ui/core/plugins/agent-auth"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useAgentAuthorizations,
  useRevokeAgentCapability
} from "@better-auth-ui/react/plugins/agent-auth"
import { FaceRobot, ShieldExclamation, Xmark } from "@gravity-ui/icons"
import {
  AlertDialog,
  Button,
  Card,
  type CardProps,
  Chip,
  cn,
  Skeleton,
  Spinner
} from "@heroui/react"
import { useState } from "react"

import { agentAuthPlugin } from "../../../lib/auth/agent-auth-plugin"

type RevokeTarget = {
  agent: AgentAuthorization
  grant: AgentCapabilityGrant
}

const statusColor = (status: AgentCapabilityGrant["status"]) =>
  status === "active"
    ? "success"
    : status === "pending"
      ? "warning"
      : status === "denied"
        ? "danger"
        : "default"

export type AgentAuthorizationsProps = Omit<CardProps, "children">

/** List user-owned agents and revoke individual active capability grants. */
export function AgentAuthorizations({
  className,
  variant,
  ...props
}: AgentAuthorizationsProps) {
  const { authClient, localization } = useAuth()
  const plugin = useAuthPlugin(agentAuthPlugin)
  const agents = useAgentAuthorizations(
    authClient as AgentAuthClient,
    plugin.adapter
  )
  const revoke = useRevokeAgentCapability(
    authClient as AgentAuthClient,
    plugin.adapter
  )
  const [target, setTarget] = useState<RevokeTarget>()

  return (
    <div className={cn("flex flex-col gap-3", className)}>
      <div className="flex flex-col gap-1">
        <h2 className="text-sm font-semibold">{plugin.localization.agents}</h2>
        <p className="text-muted text-xs">
          {plugin.localization.agentsDescription}
        </p>
      </div>
      <Card variant={variant} {...props}>
        <Card.Content className="flex flex-col gap-5">
          {agents.isPending ? (
            <>
              <Skeleton className="h-24 rounded-xl" />
              <Skeleton className="h-24 rounded-xl" />
            </>
          ) : agents.data?.length ? (
            agents.data.map((agent) => (
              <div key={agent.id} className="flex flex-col gap-3">
                <div className="flex items-center gap-3">
                  <div className="bg-surface-secondary flex size-10 shrink-0 items-center justify-center rounded-xl">
                    <FaceRobot className="size-4.5" />
                  </div>
                  <div className="flex min-w-0 flex-1 flex-col">
                    <span className="truncate text-sm font-semibold">
                      {agent.name}
                    </span>
                    <span className="text-muted truncate text-xs">
                      {agent.hostName ?? agent.hostId}
                    </span>
                  </div>
                  <Chip size="sm" variant="soft">
                    {agent.mode === "autonomous"
                      ? plugin.localization.autonomousAgent
                      : plugin.localization.delegatedAgent}
                  </Chip>
                </div>
                <div className="flex flex-col gap-2 pl-13">
                  {agent.grants.map((grant) => (
                    <div
                      key={grant.capability}
                      className="flex items-center gap-2"
                    >
                      <div className="flex min-w-0 flex-1 flex-col">
                        <span className="truncate text-sm">
                          {grant.capability}
                        </span>
                        {grant.description && (
                          <span className="text-muted truncate text-xs">
                            {grant.description}
                          </span>
                        )}
                      </div>
                      <Chip
                        color={statusColor(grant.status)}
                        size="sm"
                        variant="soft"
                      >
                        {plugin.localization[grant.status]}
                      </Chip>
                      {grant.status === "active" && (
                        <Button
                          aria-label={`${plugin.localization.revoke} ${grant.capability}`}
                          isIconOnly
                          size="sm"
                          variant="ghost"
                          onPress={() => setTarget({ agent, grant })}
                        >
                          <Xmark />
                        </Button>
                      )}
                    </div>
                  ))}
                </div>
              </div>
            ))
          ) : (
            <div className="text-muted flex items-center gap-3">
              <FaceRobot className="size-5" />
              <p className="text-sm">{plugin.localization.noAgents}</p>
            </div>
          )}
        </Card.Content>
      </Card>
      <AlertDialog.Backdrop
        isOpen={Boolean(target)}
        onOpenChange={(isOpen) => {
          if (!isOpen) setTarget(undefined)
        }}
      >
        <AlertDialog.Container>
          <AlertDialog.Dialog>
            <AlertDialog.CloseTrigger />
            <AlertDialog.Header>
              <AlertDialog.Icon status="danger">
                <ShieldExclamation />
              </AlertDialog.Icon>
              <AlertDialog.Heading>
                {plugin.localization.revokeTitle}
              </AlertDialog.Heading>
            </AlertDialog.Header>
            <AlertDialog.Body className="flex flex-col gap-2">
              <p className="text-muted text-sm">
                {plugin.localization.revokeDescription}
              </p>
              <code className="bg-surface-secondary rounded-lg p-3 text-xs">
                {target?.grant.capability}
              </code>
            </AlertDialog.Body>
            <AlertDialog.Footer>
              <Button
                slot="close"
                variant="tertiary"
                isDisabled={revoke.isPending}
              >
                {localization.settings.cancel}
              </Button>
              <Button
                variant="danger"
                isPending={revoke.isPending}
                onPress={() => {
                  if (!target) return
                  revoke.mutate(
                    {
                      agentId: target.agent.id,
                      capability: target.grant.capability
                    },
                    { onSuccess: () => setTarget(undefined) }
                  )
                }}
              >
                {revoke.isPending && <Spinner color="current" size="sm" />}
                {plugin.localization.confirmRevoke}
              </Button>
            </AlertDialog.Footer>
          </AlertDialog.Dialog>
        </AlertDialog.Container>
      </AlertDialog.Backdrop>
    </div>
  )
}
