// examples/start-solid-zaidan-example/src/components/auth/username/sign-in-username.tsx
import { authQueryKeys } from "@better-auth-ui/core"
import {
  isPasskeyAutoFillEnabled,
  withPasskeyAutoFill
} from "@better-auth-ui/core/plugins/passkey"
import type { UsernameAuthClient } from "@better-auth-ui/core/plugins/username"
import {
  type UsernameLocalization,
  usernameLocalization
} from "@better-auth-ui/core/plugins/username"
import {
  AuthLink,
  type AuthPlugin,
  AuthPrompts,
  useAuth,
  useFetchOptions,
  useSignInEmail
} from "@better-auth-ui/solid"
import { useSignInUsername } from "@better-auth-ui/solid/plugins/username"
import { useQueryClient } from "@tanstack/solid-query"
import type { BetterFetchError } from "better-auth/client"
import { Eye, EyeOff } from "lucide-solid"
import { type Component, createSignal, For, Show } from "solid-js"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { useSignInContinuation } from "@/lib/auth/use-sign-in-continuation"
import { cn } from "cn"
import { createAuthForm, isAuthFormFieldInvalid } from "../auth-form"
import { LastUsedBadge } from "../last-login-method/last-used-badge"
import type { SocialLayout } from "../provider-buttons"
import { ProviderButtons } from "../provider-buttons"
import { ReauthenticationNotice } from "../reauthentication"
import { resolveSignInPath } from "../sign-in-path"

export type SignInUsernameProps = {
  class?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
}

type AuthButtonComponent = Component<{ view?: string }>

type AuthPluginWithButtons = {
  authButtons?: AuthButtonComponent[]
  id: string
}

export function SignInUsername(props: SignInUsernameProps) {
  const auth = useAuth<UsernameAuthClient>()
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const queryClient = useQueryClient()
  const [isPasswordVisible, setIsPasswordVisible] = createSignal(false)
  const continueSignIn = useSignInContinuation()
  const onSignInSuccess = (data: unknown) => {
    queryClient.invalidateQueries({ queryKey: authQueryKeys.session })
    continueSignIn(data)
  }
  const signIn = useSignInEmail(auth.authClient, () => ({
    onError: (error, variables) => {
      if ((error as BetterFetchError).error?.code === "EMAIL_NOT_VERIFIED") {
        sessionStorage.setItem("better-auth-ui.verify-email", variables.email)
        auth.navigate({
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.verifyEmail}`
        })
      }

      resetFetchOptions()
    },
    onSuccess: onSignInSuccess
  }))
  const signInUsername = useSignInUsername(auth.authClient, () => ({
    onError: () => {
      resetFetchOptions()
    },
    onSuccess: onSignInSuccess
  }))
  const usernamePlugin = auth.plugins.find((plugin) => plugin.id === "username")
  const usernameAuth = Boolean(usernamePlugin)
  const usernameLabels: UsernameLocalization = {
    ...usernameLocalization,
    ...(usernamePlugin?.localization as
      | Partial<UsernameLocalization>
      | undefined)
  }
  const captchaComponent = () =>
    (auth.plugins as AuthPlugin[]).find((plugin) => plugin.captchaComponent)
      ?.captchaComponent
  const passkeyAutoFill = isPasskeyAutoFillEnabled(auth.plugins)
  const socialPosition = () => props.socialPosition ?? "bottom"
  const showSeparator = () =>
    Boolean(auth.emailAndPassword?.enabled && auth.socialProviders?.length)

  const form = createAuthForm(() => ({
    defaultValues: { identifier: "", password: "" },
    onSubmit: async ({ value }) => {
      const signInPath = resolveSignInPath({
        identifier: value.identifier,
        usernameAuth
      })
      if (signInPath.kind === "username") {
        await signInUsername.mutateAsync({
          fetchOptions: fetchOptions(),
          password: value.password,
          username: signInPath.username
        })
        return
      }
      await signIn.mutateAsync({
        email: signInPath.email,
        fetchOptions: fetchOptions(),
        password: value.password
      })
    }
  }))

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <AuthPrompts view="signIn" />
      <ReauthenticationNotice />
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.signIn}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <Show when={socialPosition() === "top"}>
          <Show when={auth.socialProviders?.length}>
            <ProviderButtons socialLayout={props.socialLayout} view="signIn" />
          </Show>
          <Show when={showSeparator()}>
            <div class="my-4 text-center text-muted-foreground text-xs">
              {auth.localization.auth.or}
            </div>
          </Show>
        </Show>

        <form.AppForm>
          <form.AuthFormRoot aria-label="Sign in">
            <div class="flex flex-col gap-6">
              <form.AppField
                name="identifier"
                validators={{
                  onChange: ({ value }) =>
                    value.trim()
                      ? undefined
                      : auth.localization.auth.fieldRequired
                }}
              >
                {(field) => (
                  <Field
                    data-invalid={isAuthFormFieldInvalid(field().state.meta)}
                  >
                    <FieldLabel for="sign-in-email">
                      {usernameAuth
                        ? usernameLabels.username
                        : auth.localization.auth.email}
                    </FieldLabel>
                    <Input
                      aria-invalid={isAuthFormFieldInvalid(field().state.meta)}
                      autocomplete={withPasskeyAutoFill(
                        usernameAuth ? "username" : "email",
                        passkeyAutoFill
                      )}
                      id="sign-in-email"
                      name={field().name}
                      onBlur={field().handleBlur}
                      onInput={(event) =>
                        field().handleChange(event.currentTarget.value)
                      }
                      placeholder={
                        usernameAuth
                          ? usernameLabels.usernameOrEmailPlaceholder
                          : auth.localization.auth.emailPlaceholder
                      }
                      type={usernameAuth ? "text" : "email"}
                      value={field().state.value}
                    />
                    <field.AuthFormFieldError />
                  </Field>
                )}
              </form.AppField>

              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    value ? undefined : auth.localization.auth.fieldRequired
                }}
              >
                {(field) => (
                  <Field
                    data-invalid={isAuthFormFieldInvalid(field().state.meta)}
                  >
                    <FieldLabel for="sign-in-password">
                      {auth.localization.auth.password}
                    </FieldLabel>
                    <div class="relative">
                      <Input
                        aria-invalid={isAuthFormFieldInvalid(
                          field().state.meta
                        )}
                        autocomplete={withPasskeyAutoFill(
                          "current-password",
                          passkeyAutoFill
                        )}
                        class="pr-12"
                        id="sign-in-password"
                        maxLength={auth.emailAndPassword.maxPasswordLength}
                        minLength={auth.emailAndPassword.minPasswordLength}
                        name={field().name}
                        onBlur={field().handleBlur}
                        onInput={(event) =>
                          field().handleChange(event.currentTarget.value)
                        }
                        placeholder={auth.localization.auth.passwordPlaceholder}
                        type={isPasswordVisible() ? "text" : "password"}
                        value={field().state.value}
                      />

                      <Button
                        aria-label={
                          isPasswordVisible()
                            ? auth.localization.auth.hidePassword
                            : auth.localization.auth.showPassword
                        }
                        class="absolute right-1 top-1/2 -translate-y-1/2"
                        onClick={() =>
                          setIsPasswordVisible((visible) => !visible)
                        }
                        size="icon-sm"
                        title={
                          isPasswordVisible()
                            ? auth.localization.auth.hidePassword
                            : auth.localization.auth.showPassword
                        }
                        type="button"
                        variant="ghost"
                      >
                        {isPasswordVisible() ? (
                          <EyeOff aria-hidden class="size-4" />
                        ) : (
                          <Eye aria-hidden class="size-4" />
                        )}
                      </Button>
                    </div>

                    <field.AuthFormFieldError />
                  </Field>
                )}
              </form.AppField>

              <Show when={captchaComponent()} keyed>
                {(Captcha) => <Captcha />}
              </Show>

              <form.AuthFormSubmitButton
                class="relative overflow-visible"
                disabled={signIn.isPending || signInUsername.isPending}
              >
                {auth.localization.auth.signIn}

                <LastUsedBadge floating method={["email", "username"]} />
              </form.AuthFormSubmitButton>

              <For
                each={(auth.plugins as AuthPluginWithButtons[]).flatMap(
                  (plugin) =>
                    (plugin.authButtons ?? []).map((AuthButton, index) => ({
                      AuthButton,
                      key: `${plugin.id}-${index.toString()}`
                    }))
                )}
              >
                {({ AuthButton }) => <AuthButton view="signIn" />}
              </For>

              <form.AuthFormServerError />
            </div>
          </form.AuthFormRoot>
        </form.AppForm>

        <Show
          when={socialPosition() === "bottom" && auth.socialProviders?.length}
        >
          <div class="my-4 text-center text-muted-foreground text-xs">
            {auth.localization.auth.or}
          </div>
          <ProviderButtons socialLayout={props.socialLayout} view="signIn" />
        </Show>

        <div class="mt-4 flex w-full flex-col items-center gap-3">
          <Show when={auth.emailAndPassword.forgotPassword}>
            <AuthLink
              class="text-sm underline-offset-4 hover:underline"
              href={`${auth.basePaths.auth}/${auth.viewPaths.auth.forgotPassword}`}
            >
              {auth.localization.auth.forgotPasswordLink}
            </AuthLink>
          </Show>

          <p class="text-center text-sm text-muted-foreground">
            {auth.localization.auth.needToCreateAnAccount}{" "}
            <AuthLink
              class="underline underline-offset-4"
              href={`${auth.basePaths.auth}/${auth.viewPaths.auth.signUp}`}
            >
              {auth.localization.auth.signUp}
            </AuthLink>
          </p>
        </div>
      </CardContent>
    </Card>
  )
}

// packages/heroui/src/components/auth/username/sign-in-username.tsx
import { authMutationKeys, validateStringLength } from "@better-auth-ui/core"
import {
  isPasskeyAutoFillEnabled,
  withPasskeyAutoFill
} from "@better-auth-ui/core/plugins/passkey"
import type { UsernameAuthClient } from "@better-auth-ui/core/plugins/username"
import {
  AuthPrompts,
  useAuth,
  useAuthPlugin,
  useFetchOptions,
  useSignInEmail
} from "@better-auth-ui/react"
import { useSignInUsername } from "@better-auth-ui/react/plugins/username"
import { Eye, EyeSlash } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  Checkbox,
  cn,
  Description,
  Input,
  InputGroup,
  Label,
  Link,
  Spinner,
  TextField
} from "@heroui/react"
import { useIsMutating } from "@tanstack/react-query"
import { useState } from "react"
import { useSignInContinuation } from "../../../lib/auth/use-sign-in-continuation"
import { usernamePlugin } from "../../../lib/auth/username-plugin"
import { useAuthForm } from "../auth-form"
import { FieldSeparator } from "../field-separator"
import { LastUsedBadge } from "../last-login-method/last-used-badge"
import { ProviderButtons, type SocialLayout } from "../provider-buttons"
import { ReauthenticationNotice } from "../reauthentication"

export interface SignInUsernameProps {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardProps["variant"]
}

/**
 * Render the username-based sign-in UI.
 *
 * @returns The sign-in JSX element containing username/password fields, optional magic-link button, and social provider buttons.
 */
export function SignInUsername({
  className,
  socialLayout,
  socialPosition = "bottom",
  variant
}: SignInUsernameProps) {
  const {
    authClient,
    basePaths,
    emailAndPassword,
    localization,
    plugins,
    socialProviders,
    viewPaths,
    navigate
  } = useAuth()

  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const continueSignIn = useSignInContinuation()

  const { localization: usernameLocalization } = useAuthPlugin(usernamePlugin)

  const [isPasswordVisible, setIsPasswordVisible] = useState(false)

  function isEmail(value: string): boolean {
    return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value)
  }

  const { mutateAsync: signInEmail, isPending: isSignInEmailPending } =
    useSignInEmail(authClient, {
      onError: (error, { email }) => {
        form.setFieldValue("password", "")

        if (error.error?.code === "EMAIL_NOT_VERIFIED") {
          sessionStorage.setItem("better-auth-ui.verify-email", email)
          navigate({
            to: `${basePaths.auth}/${viewPaths.auth.verifyEmail}`
          })
        }

        resetFetchOptions()
      },
      onSuccess: (data) => {
        sessionStorage.removeItem("better-auth-ui.verify-email")
        continueSignIn(data)
      }
    })

  const { mutateAsync: signInUsername, isPending: isSignInUsernamePending } =
    useSignInUsername(authClient as UsernameAuthClient, {
      onError: (error) => {
        form.setFieldValue("password", "")

        if (error.error?.code === "EMAIL_NOT_VERIFIED") {
          sessionStorage.removeItem("better-auth-ui.verify-email")

          navigate({
            to: `${basePaths.auth}/${viewPaths.auth.verifyEmail}`
          })
        }

        resetFetchOptions()
      },
      onSuccess: (data) => {
        sessionStorage.removeItem("better-auth-ui.verify-email")
        continueSignIn(data)
      }
    })

  const form = useAuthForm({
    defaultValues: { email: "", password: "", rememberMe: false },
    onSubmit: async ({ value }) => {
      const email = value.email
      if (isEmail(email)) {
        await signInEmail({
          email,
          password: value.password,
          ...(emailAndPassword?.rememberMe
            ? { rememberMe: value.rememberMe }
            : {}),
          fetchOptions
        })
      } else {
        await signInUsername({
          username: email,
          password: value.password,
          ...(emailAndPassword?.rememberMe
            ? { rememberMe: value.rememberMe }
            : {}),
          fetchOptions
        })
      }
    }
  })

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0
  const isSignInPending = isSignInEmailPending || isSignInUsernamePending

  const Captcha = plugins.find(
    (plugin) => plugin.captchaComponent
  )?.captchaComponent

  const passkeyAutoFill = isPasskeyAutoFillEnabled(plugins)

  const showSeparator = emailAndPassword?.enabled && !!socialProviders?.length

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <AuthPrompts view="signIn" />
      <ReauthenticationNotice />
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.signIn}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        {socialPosition === "top" && (
          <>
            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="signIn" />
            )}

            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}
          </>
        )}

        {emailAndPassword?.enabled && (
          <form.AppForm>
            <form.AuthFormRoot className="flex flex-col gap-4">
              <form.AppField
                name="email"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: localization.auth.fieldRequired,
                      trim: true
                    })
                }}
              >
                {(field) => (
                  <TextField
                    name={field.name}
                    type="text"
                    autoComplete={withPasskeyAutoFill(
                      "username",
                      passkeyAutoFill
                    )}
                    isDisabled={isPending}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    validationBehavior="aria"
                  >
                    <Label>{usernameLocalization.username}</Label>

                    <Input
                      placeholder={
                        usernameLocalization.usernameOrEmailPlaceholder
                      }
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                      required
                    />

                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>

              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      maxLength: emailAndPassword?.maxPasswordLength,
                      maxLengthMessage: localization.auth.tooLong.replace(
                        "{{max}}",
                        String(emailAndPassword?.maxPasswordLength)
                      ),
                      minLength: emailAndPassword?.minPasswordLength,
                      minLengthMessage: localization.auth.tooShort.replace(
                        "{{min}}",
                        String(emailAndPassword?.minPasswordLength)
                      ),
                      requiredMessage: localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => (
                  <TextField
                    minLength={emailAndPassword?.minPasswordLength}
                    maxLength={emailAndPassword?.maxPasswordLength}
                    name={field.name}
                    autoComplete={withPasskeyAutoFill(
                      "current-password",
                      passkeyAutoFill
                    )}
                    isDisabled={isPending}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    validationBehavior="aria"
                  >
                    <Label>{localization.auth.password}</Label>

                    <InputGroup
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    >
                      <InputGroup.Input
                        placeholder={localization.auth.passwordPlaceholder}
                        type={isPasswordVisible ? "text" : "password"}
                        required
                      />

                      <InputGroup.Suffix className="px-0">
                        <Button
                          isIconOnly
                          aria-label={
                            isPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          size="sm"
                          variant="ghost"
                          onPress={() =>
                            setIsPasswordVisible(!isPasswordVisible)
                          }
                          isDisabled={isPending}
                        >
                          {isPasswordVisible ? <EyeSlash /> : <Eye />}
                        </Button>
                      </InputGroup.Suffix>
                    </InputGroup>

                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>

              {emailAndPassword?.rememberMe && (
                <form.AppField name="rememberMe">
                  {(field) => (
                    <Checkbox
                      name={field.name}
                      isDisabled={isPending}
                      isSelected={field.state.value}
                      onChange={field.handleChange}
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    >
                      <Checkbox.Content>
                        <Checkbox.Control>
                          <Checkbox.Indicator />
                        </Checkbox.Control>

                        {localization.auth.rememberMe}
                      </Checkbox.Content>
                    </Checkbox>
                  )}
                </form.AppField>
              )}

              {Captcha && <div className="flex justify-center">{Captcha}</div>}

              <form.AuthFormServerError />

              <div className="flex flex-col gap-3">
                <form.AuthFormSubmitButton
                  className="relative w-full overflow-visible"
                  isDisabled={isSignInPending || isPending}
                >
                  {isSignInPending && <Spinner color="current" size="sm" />}

                  {localization.auth.signIn}

                  <LastUsedBadge method={["email", "username"]} floating />
                </form.AuthFormSubmitButton>

                {plugins.flatMap((plugin) =>
                  plugin.authButtons?.map((AuthButton, index) => (
                    <AuthButton
                      key={`${plugin.id}-${index.toString()}`}
                      view="signIn"
                    />
                  ))
                )}
              </div>
            </form.AuthFormRoot>
          </form.AppForm>
        )}

        {socialPosition === "bottom" && (
          <>
            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}

            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="signIn" />
            )}
          </>
        )}
      </Card.Content>

      <Card.Footer className="flex-col gap-3">
        {emailAndPassword?.enabled && emailAndPassword?.forgotPassword && (
          <Link
            href={`${basePaths.auth}/${viewPaths.auth.forgotPassword}`}
            className="text-sm no-underline hover:underline"
          >
            {localization.auth.forgotPasswordLink}
          </Link>
        )}

        {emailAndPassword?.enabled && (
          <Description className="text-sm">
            {localization.auth.needToCreateAnAccount}{" "}
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
              className="text-accent no-underline hover:underline decoration-accent-hover"
            >
              {localization.auth.signUp}
            </Link>
          </Description>
        )}
      </Card.Footer>
    </Card>
  )
}
