// examples/start-solid-zaidan-example/src/components/auth/organization/organization-table-renderer.tsx
import type { AppSolidTable, RowData } from "@tanstack/solid-table"
import { For, type JSX, Show } from "solid-js"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import type { organizationTableFeatures } from "./organization-table"

type OrganizationTableInstance<TData extends RowData> = AppSolidTable<
  typeof organizationTableFeatures,
  TData,
  Record<string, never>,
  Record<string, never>,
  Record<string, never>
>

export function OrganizationTableRenderer<TData extends RowData>(props: {
  empty: JSX.Element
  table: OrganizationTableInstance<TData>
}) {
  return (
    <Table>
      <TableHeader>
        <For each={props.table.getHeaderGroups()}>
          {(headerGroup) => (
            <TableRow>
              <For each={headerGroup.headers}>
                {(header) => (
                  <TableHead colspan={header.colSpan}>
                    <Show when={!header.isPlaceholder}>
                      <props.table.FlexRender header={header} />
                    </Show>
                  </TableHead>
                )}
              </For>
            </TableRow>
          )}
        </For>
      </TableHeader>
      <TableBody>
        <Show
          fallback={
            <TableRow>
              <TableCell colspan={props.table.getVisibleLeafColumns().length}>
                {props.empty}
              </TableCell>
            </TableRow>
          }
          when={props.table.getRowModel().rows.length}
        >
          <For each={props.table.getRowModel().rows}>
            {(row) => (
              <TableRow
                data-state={row.getIsSelected() ? "selected" : undefined}
              >
                <For each={row.getVisibleCells()}>
                  {(cell) => (
                    <TableCell>
                      <props.table.FlexRender cell={cell} />
                    </TableCell>
                  )}
                </For>
              </TableRow>
            )}
          </For>
        </Show>
      </TableBody>
    </Table>
  )
}

// apps/docs/src/components/auth/organization/organization-table-renderer.tsx
"use client"

import type { ReactNode } from "react"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { useOrganizationTableContext } from "./organization-table"

export function OrganizationTableRenderer({ empty }: { empty: ReactNode }) {
  const table = useOrganizationTableContext()
  const rows = table.getRowModel().rows

  return (
    <Table>
      <TableHeader>
        {table.getHeaderGroups().map((headerGroup) => (
          <TableRow key={headerGroup.id}>
            {headerGroup.headers.map((header) => (
              <TableHead colSpan={header.colSpan} key={header.id}>
                {header.isPlaceholder ? null : (
                  <table.FlexRender header={header} />
                )}
              </TableHead>
            ))}
          </TableRow>
        ))}
      </TableHeader>
      <TableBody>
        {rows.length ? (
          rows.map((row) => (
            <TableRow
              data-state={row.getIsSelected() ? "selected" : undefined}
              key={row.id}
            >
              {row.getVisibleCells().map((cell) => (
                <TableCell key={cell.id}>
                  <table.FlexRender cell={cell} />
                </TableCell>
              ))}
            </TableRow>
          ))
        ) : (
          <TableRow>
            <TableCell colSpan={table.getVisibleLeafColumns().length}>
              {empty}
            </TableCell>
          </TableRow>
        )}
      </TableBody>
    </Table>
  )
}
