// examples/start-solid-zaidan-example/src/components/auth/organization/organization-settings.tsx
import { useAuth } from "@better-auth-ui/solid"
import { For } from "solid-js"
import type { OrganizationCardsPlugin } from "@/components/auth/settings/shared/types"
import { OrganizationDangerZone } from "./organization-danger-zone"
import { OrganizationProfile } from "./organization-profile"

export type OrganizationSettingsProps = {
  class?: string
  organizationId: string
  organizationSlug: string
}

export function OrganizationSettings(props: OrganizationSettingsProps) {
  const auth = useAuth()
  const organizationCards = () =>
    (auth.plugins as OrganizationCardsPlugin[]).flatMap(
      (plugin) => plugin.organizationCards ?? []
    )

  return (
    <div class={props.class ?? "grid gap-4 md:gap-6"}>
      <OrganizationProfile />
      <For each={organizationCards()}>
        {(OrganizationCard) => (
          <OrganizationCard
            organizationId={props.organizationId}
            organizationSlug={props.organizationSlug}
          />
        )}
      </For>
      <OrganizationDangerZone />
    </div>
  )
}

// apps/docs/src/components/auth/organization/organization-settings.tsx
"use client"

import { useAuth } from "@better-auth-ui/react"
import type { ComponentProps } from "react"

import { cn } from "@/lib/utils"
import { OrganizationDangerZone } from "./organization-danger-zone"
import { OrganizationProfile } from "./organization-profile"

export type OrganizationSettingsProps = {
  className?: string
}

/**
 * Organization settings UI: profile card, plugin-contributed cards
 * (`organizationCards`), then danger zone.
 */
export function OrganizationSettings({
  className,
  ...props
}: OrganizationSettingsProps & ComponentProps<"div">) {
  const { plugins } = useAuth()

  return (
    <div className={cn("flex flex-col gap-4 md:gap-6", className)} {...props}>
      <OrganizationProfile />

      {plugins.flatMap((plugin) =>
        plugin.organizationCards?.map((Card) => (
          <Card key={`${plugin.id}-${Card.displayName ?? Card.name}`} />
        ))
      )}

      <OrganizationDangerZone />
    </div>
  )
}
