// examples/start-solid-zaidan-example/src/components/auth/organization/organization-switcher.tsx
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import {
  organizationLocalization as defaultOrganizationLocalization,
  type OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useSession } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useListOrganizations,
  useSetActiveOrganization
} from "@better-auth-ui/solid/plugins/organization"
import type { Organization } from "better-auth/client"
import {
  ChevronsUpDown,
  PlusCircle,
  Settings as SettingsIcon
} from "lucide-solid"
import type { JSX } from "solid-js"
import { createMemo, createSignal, For, onMount, Show } from "solid-js"
import { UserView } from "@/components/auth/user/user-view"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { CreateOrganizationDialog } from "./create-organization-dialog"
import { createOrganizationPath } from "./organization-path"
import { OrganizationView } from "./organization-view"

export type OrganizationSwitcherProps = {
  class?: string
  trigger?: JSX.Element
  hidePersonal?: boolean
  hideSettings?: boolean
  hideSlug?: boolean
  hideCreate?: boolean
  setActive?: (organization: Organization | null) => void
}

type OrganizationPluginConfig = {
  slug?: string | null
  hideSlug?: boolean
  slugPrefix?: string
  localization?: Pick<
    OrganizationLocalization,
    "createOrganization" | "organization" | "organizations" | "manage"
  >
}

function OrganizationSwitcherTrigger(rawProps: OrganizationSwitcherProps = {}) {
  const props = rawProps
  const auth = useAuth()
  const hideSlug = () =>
    props.hideSlug ??
    (
      auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
        | OrganizationPluginConfig
        | undefined
    )?.hideSlug ??
    true

  return (
    <Show
      when={props.trigger}
      fallback={
        <Button
          class={cn("h-auto px-2 py-2 text-left", props.class)}
          disabled
          variant="ghost"
        >
          <OrganizationView isPending hideRole hideSlug={hideSlug()} />
          <ChevronsUpDown class="size-4 shrink-0 text-muted-foreground" />
        </Button>
      }
    >
      {props.trigger}
    </Show>
  )
}

function MountedOrganizationSwitcher(rawProps: OrganizationSwitcherProps = {}) {
  const props = rawProps
  const auth = useAuth<OrganizationAuthClient>()
  const client = auth.authClient
  const session = useSession(client)
  const activeOrganization = useActiveOrganization(client)
  const organizations = useListOrganizations(client)
  const setActiveOrganization = useSetActiveOrganization(client)
  const [createOpen, setCreateOpen] = createSignal(false)
  const [isOpen, setIsOpen] = createSignal(false)
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | OrganizationPluginConfig
      | undefined
  const organizationViewPaths = () =>
    organizationPlugin().viewPaths.organization ?? { settings: "settings" }
  const localization = () =>
    organizationPluginConfig()?.localization ?? defaultOrganizationLocalization
  const isSlugMode = () => {
    const plugin = organizationPluginConfig()

    if (!plugin) return false

    return plugin.slug !== undefined
  }
  const isPending = () =>
    session.isPending ||
    (!!session.data &&
      (organizations.isPending || activeOrganization.isPending))
  const hideSlug = () =>
    props.hideSlug ?? organizationPluginConfig()?.hideSlug ?? true
  const shouldShowSlug = () => !hideSlug()
  const selectableOrganizations = () =>
    ((organizations.data ?? []) as Organization[]).filter(
      (organization) => organization.id !== activeOrganization.data?.id
    )
  const hasOtherEntries = () =>
    selectableOrganizations().length > 0 ||
    (!!activeOrganization.data && !props.hidePersonal)

  const navigateToOrganization = (organization: Organization) => {
    auth.navigate({
      to: createOrganizationPath({
        basePath: auth.basePaths.organization,
        slugPrefix: organizationPluginConfig()?.slugPrefix,
        slug: organization.slug,
        path: organizationViewPaths().settings
      })
    })
  }

  const navigateToPersonal = () => {
    auth.navigate({
      to: `${auth.basePaths.settings}/${auth.viewPaths.settings.account}`
    })
  }

  const navigateToActiveOrganizationSettings = () => {
    const active = activeOrganization.data

    if (!active) {
      navigateToPersonal()
      return
    }

    if (isSlugMode()) {
      navigateToOrganization(active as Organization)
      return
    }

    auth.navigate({
      to: `${auth.basePaths.organization}/${organizationViewPaths().settings}`
    })
  }

  const handleSetActive = (organization: Organization | null) => {
    setIsOpen(false)

    if (organization) props.setActive?.(organization)
    if (!organization) props.setActive?.(null)
    if (props.setActive) return

    if (isSlugMode()) {
      if (organization) {
        navigateToOrganization(organization)
        return
      }

      navigateToPersonal()
      return
    }

    setActiveOrganization.mutate(
      { organizationId: organization?.id ?? null },
      {
        onSuccess: () => {
          if (organization) {
            auth.navigate({
              to: `${auth.basePaths.organization}/${organizationViewPaths().settings}`
            })
            return
          }

          navigateToPersonal()
        }
      }
    )
  }

  return (
    <>
      <DropdownMenu open={isOpen()} onOpenChange={setIsOpen}>
        <Show
          when={props.trigger}
          fallback={
            <DropdownMenuTrigger
              as={Button}
              variant="ghost"
              class={cn("h-auto px-2 py-2 text-left", props.class)}
              disabled={!session.data || isPending()}
            >
              <Show
                when={!isPending()}
                fallback={
                  <OrganizationView isPending hideRole hideSlug={hideSlug()} />
                }
              >
                <Show
                  when={activeOrganization.data}
                  fallback={
                    <Show
                      when={
                        !props.hidePersonal ? session.data?.user : undefined
                      }
                      fallback={
                        <OrganizationView
                          hideRole
                          hideSlug={hideSlug()}
                          organization={{
                            name: localization().organization
                          }}
                        />
                      }
                    >
                      {(user) => (
                        <UserView hideSubtitle={hideSlug()} user={user()} />
                      )}
                    </Show>
                  }
                >
                  {(organization) => (
                    <OrganizationView
                      hideRole
                      hideSlug={!shouldShowSlug()}
                      organization={organization()}
                    />
                  )}
                </Show>
              </Show>

              <ChevronsUpDown class="size-4 shrink-0 text-muted-foreground" />
            </DropdownMenuTrigger>
          }
        >
          <DropdownMenuTrigger as="span" class={props.class}>
            {props.trigger}
          </DropdownMenuTrigger>
        </Show>
        <DropdownMenuContent class="min-w-64 max-w-svw">
          <Show when={activeOrganization.data}>
            {(organization) => (
              <div class="flex items-center justify-between gap-4 px-2 py-2">
                <OrganizationView
                  hideRole
                  hideSlug={hideSlug()}
                  organization={organization()}
                />

                <Show when={!props.hideSettings}>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={navigateToActiveOrganizationSettings}
                  >
                    <SettingsIcon class="text-muted-foreground" />
                    {localization().manage}
                  </Button>
                </Show>
              </div>
            )}
          </Show>

          <Show
            when={
              !activeOrganization.data && !isPending() && !props.hidePersonal
                ? session.data?.user
                : undefined
            }
          >
            {(resolvedSession) => (
              <div class="flex items-center justify-between gap-4 px-2 py-2">
                <UserView hideSubtitle={hideSlug()} user={resolvedSession()} />

                <Show when={!props.hideSettings}>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={navigateToPersonal}
                  >
                    <SettingsIcon class="text-muted-foreground" />
                    {auth.localization.settings.settings}
                  </Button>
                </Show>
              </div>
            )}
          </Show>

          <DropdownMenuSeparator />

          <Show when={activeOrganization.data && !props.hidePersonal}>
            <DropdownMenuItem onSelect={() => handleSetActive(null)}>
              <UserView hideSubtitle={hideSlug()} />
            </DropdownMenuItem>
          </Show>

          <For each={selectableOrganizations()}>
            {(organization) => (
              <DropdownMenuItem onSelect={() => handleSetActive(organization)}>
                <OrganizationView
                  hideRole
                  hideSlug={hideSlug()}
                  organization={organization}
                />
              </DropdownMenuItem>
            )}
          </For>

          <Show when={!props.hideCreate}>
            <Show when={hasOtherEntries()}>
              <DropdownMenuSeparator />
            </Show>

            <DropdownMenuItem
              onSelect={() => {
                setIsOpen(false)
                setCreateOpen(true)
              }}
            >
              <PlusCircle class="text-muted-foreground" />
              {localization().createOrganization}
            </DropdownMenuItem>
          </Show>
        </DropdownMenuContent>
      </DropdownMenu>
      <CreateOrganizationDialog
        hideSlug={hideSlug()}
        open={createOpen()}
        onOpenChange={setCreateOpen}
      />
    </>
  )
}

export function OrganizationSwitcher(props: OrganizationSwitcherProps = {}) {
  const [isMounted, setIsMounted] = createSignal(false)

  onMount(() => setIsMounted(true))

  const content = createMemo(() =>
    isMounted() ? (
      <MountedOrganizationSwitcher {...props} />
    ) : (
      <OrganizationSwitcherTrigger {...props} />
    )
  )

  return <>{content()}</>
}

// apps/docs/src/components/auth/organization/organization-switcher.tsx
"use client"

import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import {
  useActiveOrganization,
  useListOrganizations,
  useSetActiveOrganization
} from "@better-auth-ui/react/plugins/organization"
import type { Organization } from "better-auth/client"
import {
  ChevronsUpDown,
  PlusCircle,
  Settings as SettingsIcon
} from "lucide-react"
import { type ComponentProps, type ReactElement, useState } from "react"

import { buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { UserView } from "../user/user-view"
import { CreateOrganizationDialog } from "./create-organization-dialog"
import { OrganizationView } from "./organization-view"

/** Props for the `OrganizationSwitcher` component. */
export type OrganizationSwitcherProps = {
  className?: string
  align?: "center" | "end" | "start"
  side?: "top" | "right" | "bottom" | "left"
  sideOffset?: number
  trigger?: ReactElement<ComponentProps<typeof DropdownMenuTrigger>>
  hideCreate?: boolean
  hidePersonal?: boolean
  hideSettings?: boolean
  hideSlug?: boolean
  setActive?: (organization: Organization | null) => void
}

/**
 * Renders an organizations dropdown with a trigger button,
 * header summary, and a menu of organizations to switch to.
 */
export function OrganizationSwitcher({
  className,
  align,
  side,
  sideOffset,
  hideCreate,
  hidePersonal,
  hideSettings,
  hideSlug: hideSlugProp,
  setActive,
  trigger
}: OrganizationSwitcherProps) {
  const { authClient, navigate, basePaths, localization, viewPaths, Link } =
    useAuth<OrganizationAuthClient>()
  const { data: session, isPending: sessionPending } = useSession(authClient)
  const {
    localization: organizationLocalization,
    viewPaths: organizationViewPaths,
    slug,
    slugPrefix,
    hideSlug: pluginHideSlug
  } = useAuthPlugin(organizationPlugin)
  const hideSlug = hideSlugProp ?? pluginHideSlug ?? true

  const { data: activeOrganization, isPending: activeOrganizationPending } =
    useActiveOrganization(authClient)

  const { data: organizations, isPending: organizationsPending } =
    useListOrganizations(authClient)

  const { mutate: setActiveOrganization } = useSetActiveOrganization(authClient)

  const isPending =
    sessionPending ||
    (!!session && (organizationsPending || activeOrganizationPending))

  const [createOpen, setCreateOpen] = useState(false)
  const [dropdownOpen, setDropdownOpen] = useState(false)

  const otherOrganizations =
    organizations?.filter(
      (organization) => organization.id !== activeOrganization?.id
    ) ?? []

  const hasOtherEntries =
    otherOrganizations.length > 0 || (!!activeOrganization && !hidePersonal)

  function handleSetActive(organization: Organization | null) {
    setDropdownOpen(false)

    if (setActive) {
      setActive(organization)
    } else if (slug !== undefined) {
      navigate({
        to: organization
          ? `${basePaths.organization}/${slugPrefix}${organization.slug}/${organizationViewPaths.organization.settings}`
          : `${basePaths.settings}/${viewPaths.settings.account}`
      })
    } else {
      setActiveOrganization({ organizationId: organization?.id ?? null })
    }
  }

  return (
    <>
      <DropdownMenu open={dropdownOpen} onOpenChange={setDropdownOpen}>
        {trigger ?? (
          <DropdownMenuTrigger
            className={cn(
              buttonVariants({ variant: "ghost" }),
              "h-auto px-2 py-2 text-left",
              className
            )}
            disabled={!session || isPending}
          >
            {isPending ? (
              <OrganizationView isPending hideRole hideSlug={hideSlug} />
            ) : activeOrganization ? (
              <OrganizationView hideRole hideSlug={hideSlug} />
            ) : session && !hidePersonal ? (
              <UserView hideSubtitle={hideSlug} />
            ) : (
              <OrganizationView
                hideRole
                hideSlug={hideSlug}
                organization={{ name: organizationLocalization.organization }}
              />
            )}

            <ChevronsUpDown className="size-4 shrink-0 text-muted-foreground" />
          </DropdownMenuTrigger>
        )}

        <DropdownMenuContent
          align={align}
          side={side}
          sideOffset={sideOffset}
          className="min-w-64 max-w-svw"
        >
          {activeOrganization ? (
            <div className="flex items-center justify-between gap-4 px-2 py-2">
              <OrganizationView
                hideRole
                hideSlug={hideSlug}
                organization={activeOrganization}
              />

              {!hideSettings && (
                <Link
                  href={
                    slug
                      ? `${basePaths.organization}/${slugPrefix}${slug}/${organizationViewPaths.organization.settings}`
                      : `${basePaths.organization}/${organizationViewPaths.organization.settings}`
                  }
                  className={cn(
                    buttonVariants({ variant: "outline", size: "sm" })
                  )}
                >
                  <SettingsIcon className="text-muted-foreground" />

                  {organizationLocalization.manage}
                </Link>
              )}
            </div>
          ) : !isPending && session?.user && !hidePersonal ? (
            <div className="flex items-center justify-between gap-4 px-2 py-2">
              <UserView hideSubtitle={hideSlug} />

              {!hideSettings && (
                <Link
                  href={`${basePaths.settings}/${viewPaths.settings.account}`}
                  className={cn(
                    buttonVariants({ variant: "outline", size: "sm" })
                  )}
                >
                  <SettingsIcon className="text-muted-foreground" />

                  {localization.settings.settings}
                </Link>
              )}
            </div>
          ) : null}

          <DropdownMenuSeparator />

          {!!activeOrganization && !hidePersonal && (
            <DropdownMenuItem onClick={() => handleSetActive(null)}>
              <UserView hideSubtitle={hideSlug} />
            </DropdownMenuItem>
          )}

          {otherOrganizations.map((organization) => (
            <DropdownMenuItem
              key={organization.id}
              onClick={() => handleSetActive(organization)}
            >
              <OrganizationView
                hideRole
                hideSlug={hideSlug}
                organization={organization}
              />
            </DropdownMenuItem>
          ))}

          {!hideCreate && (
            <>
              {hasOtherEntries && <DropdownMenuSeparator />}

              <DropdownMenuItem
                onClick={() => {
                  setDropdownOpen(false)
                  setCreateOpen(true)
                }}
              >
                <PlusCircle className="text-muted-foreground" />

                {organizationLocalization.createOrganization}
              </DropdownMenuItem>
            </>
          )}
        </DropdownMenuContent>
      </DropdownMenu>

      <CreateOrganizationDialog
        open={createOpen}
        onOpenChange={setCreateOpen}
      />
    </>
  )
}
