// packages/react/src/hooks/auth/use-authenticate.ts
import type { AuthClient } from "@better-auth-ui/core"
import type { QueryClient } from "@tanstack/react-query"
import { useEffect } from "react"
import { useAuth } from "../../components/auth/auth-provider"
import { type UseSessionOptions, useSession } from "../queries/use-session"

/**
 * Calls `useSession` and redirects unauthenticated users to the sign-in page,
 * preserving the current URL as a `redirectTo` query param.
 *
 * @param authClient - The Better Auth client.
 * @param options - `getSession` params & `useQuery` options.
 * @param queryClient - Optional React Query client override.
 */
export function useAuthenticate<TAuthClient extends AuthClient>(
  authClient: TAuthClient,
  options?: UseSessionOptions<TAuthClient>,
  queryClient?: QueryClient
) {
  const { basePaths, viewPaths, navigate } = useAuth()
  const session = useSession(authClient, options, queryClient)

  useEffect(() => {
    if (session.data || session.isPending) return

    const signInBase = `${basePaths.auth}/${viewPaths.auth.signIn}`

    // `window.location` is web-only; under React Native there is no URL to
    // preserve, so we redirect to sign-in by view identity instead.
    const currentURL =
      typeof window !== "undefined"
        ? window.location.pathname + window.location.search
        : undefined

    const signInPath = currentURL
      ? `${signInBase}?redirectTo=${encodeURIComponent(currentURL)}`
      : signInBase

    navigate({
      to: signInPath,
      view: "signIn",
      params: currentURL ? { redirectTo: currentURL } : undefined,
      replace: true
    })
  }, [
    basePaths.auth,
    session.data,
    session.isPending,
    viewPaths.auth.signIn,
    navigate
  ])

  return session
}

// packages/solid/src/hooks/auth/use-authenticate.ts
import type { AuthClient } from "@better-auth-ui/core"
import type { QueryClient } from "@tanstack/solid-query"
import { type Accessor, createEffect } from "solid-js"
import { isServer } from "solid-js/web"
import { useAuth } from "../../lib/auth-provider"
import { type UseSessionOptions, useSession } from "../queries/use-session"

/**
 * Calls `useSession` and redirects unauthenticated users to the sign-in page.
 *
 * @param authClient - The Better Auth client.
 * @param options - `getSession` params and Solid Query options.
 * @param queryClient - Optional Solid Query client accessor override.
 */
export function useAuthenticate<TAuthClient extends AuthClient>(
  authClient: TAuthClient,
  options?: UseSessionOptions<TAuthClient>,
  queryClient?: Accessor<QueryClient>
) {
  const config = useAuth()
  const session = useSession(authClient, options, queryClient)

  createEffect(() => {
    if (session.data || session.isPending) return

    const currentURL = isServer
      ? "/"
      : window.location.pathname + window.location.search
    const redirectTo = encodeURIComponent(currentURL)
    const signInPath = `${config.basePaths.auth}/${config.viewPaths.auth.signIn}?redirectTo=${redirectTo}`

    config.navigate({ to: signInPath, replace: true })
  })

  return session
}
