// examples/start-solid-zaidan-example/src/components/auth/auth-result.tsx
import {
  type AuthResult,
  getAuthResultMessage,
  parseAuthResult
} from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import { CircleCheck, CircleX, TriangleAlert } from "lucide-solid"
import { createSignal, onMount, Show } from "solid-js"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { cn } from "cn"

type AuthResultProps = {
  class?: string
  fallbackIntent: "danger" | "success"
}

function AuthResultView(props: AuthResultProps) {
  const auth = useAuth()
  const [result, setResult] = createSignal<AuthResult>(
    parseAuthResult("", props.fallbackIntent)
  )

  onMount(() => {
    setResult(parseAuthResult(window.location.search, props.fallbackIntent))
  })

  const message = () => getAuthResultMessage(result(), auth.localization)
  const action = () => {
    switch (result().action) {
      case "accountSettings":
        return {
          label: auth.localization.auth.callbackViewAccountSettings,
          to: `${auth.basePaths.settings}/${auth.viewPaths.settings.security}`
        }
      case "continue":
        return {
          label: auth.localization.auth.callbackContinue,
          to: result().redirectTo ?? "/"
        }
      case "forgotPassword":
        return {
          label: auth.localization.auth.forgotPassword,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.forgotPassword}`
        }
      case "signUp":
        return {
          label: auth.localization.auth.signUp,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signUp}`
        }
      case "verifyEmail":
        return {
          label: auth.localization.auth.verifyEmail,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.verifyEmail}`
        }
      default:
        return {
          label: auth.localization.auth.signIn,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
        }
    }
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader class="justify-items-center text-center">
        <Show
          when={result().intent === "success"}
          fallback={
            <Show
              when={result().intent === "warning"}
              fallback={
                <CircleX
                  aria-hidden="true"
                  class="mb-1 size-10 text-destructive"
                />
              }
            >
              <TriangleAlert
                aria-hidden="true"
                class="mb-1 size-10 text-warning"
              />
            </Show>
          }
        >
          <CircleCheck aria-hidden="true" class="mb-1 size-10 text-primary" />
        </Show>
        <CardTitle class="text-xl">{message().title}</CardTitle>
        <CardDescription>{message().description}</CardDescription>
      </CardHeader>
      <CardContent>
        <Button
          class="w-full"
          onClick={() => auth.navigate({ to: action().to })}
        >
          {action().label}
        </Button>
      </CardContent>
    </Card>
  )
}

export function AuthCallback(props: Omit<AuthResultProps, "fallbackIntent">) {
  return <AuthResultView {...props} fallbackIntent="success" />
}

export function AuthError(props: Omit<AuthResultProps, "fallbackIntent">) {
  return <AuthResultView {...props} fallbackIntent="danger" />
}

// packages/heroui/src/components/auth/auth-result.tsx
import {
  type AuthResult,
  getAuthResultMessage,
  parseAuthResult
} from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/react"
import {
  CircleCheck,
  CircleXmark,
  TriangleExclamation
} from "@gravity-ui/icons"
import { Button, Card, type CardProps, cn } from "@heroui/react"
import { useEffect, useState } from "react"

type AuthResultProps = {
  className?: string
  fallbackIntent: "danger" | "success"
  variant?: CardProps["variant"]
}

function AuthResultView({
  className,
  fallbackIntent,
  variant
}: AuthResultProps) {
  const { basePaths, localization, navigate, viewPaths } = useAuth()
  const [result, setResult] = useState<AuthResult>(() =>
    parseAuthResult("", fallbackIntent)
  )

  useEffect(() => {
    setResult(parseAuthResult(window.location.search, fallbackIntent))
  }, [fallbackIntent])

  const message = getAuthResultMessage(result, localization)
  const action = (() => {
    switch (result.action) {
      case "accountSettings":
        return {
          label: localization.auth.callbackViewAccountSettings,
          to: `${basePaths.settings}/${viewPaths.settings.security}`
        }
      case "continue":
        return {
          label: localization.auth.callbackContinue,
          to: result.redirectTo ?? "/"
        }
      case "forgotPassword":
        return {
          label: localization.auth.forgotPassword,
          to: `${basePaths.auth}/${viewPaths.auth.forgotPassword}`
        }
      case "signUp":
        return {
          label: localization.auth.signUp,
          to: `${basePaths.auth}/${viewPaths.auth.signUp}`
        }
      case "verifyEmail":
        return {
          label: localization.auth.verifyEmail,
          to: `${basePaths.auth}/${viewPaths.auth.verifyEmail}`
        }
      default:
        return {
          label: localization.auth.signIn,
          to: `${basePaths.auth}/${viewPaths.auth.signIn}`
        }
    }
  })()
  const Icon =
    result.intent === "success"
      ? CircleCheck
      : result.intent === "warning"
        ? TriangleExclamation
        : CircleXmark

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header className="items-center text-center">
        <Icon
          aria-hidden="true"
          className={cn(
            "mb-2 size-10",
            result.intent === "success"
              ? "text-success"
              : result.intent === "warning"
                ? "text-warning"
                : "text-danger"
          )}
        />
        <Card.Title className="text-xl font-semibold">
          {message.title}
        </Card.Title>
        <Card.Description>{message.description}</Card.Description>
      </Card.Header>
      <Card.Footer>
        <Button className="w-full" onPress={() => navigate({ to: action.to })}>
          {action.label}
        </Button>
      </Card.Footer>
    </Card>
  )
}

export function AuthCallback(props: Omit<AuthResultProps, "fallbackIntent">) {
  return <AuthResultView {...props} fallbackIntent="success" />
}

export function AuthError(props: Omit<AuthResultProps, "fallbackIntent">) {
  return <AuthResultView {...props} fallbackIntent="danger" />
}
