// examples/start-solid-zaidan-example/src/components/auth/sign-up.tsx
import {
  authQueryKeys,
  getAdditionalFieldDefaultValues,
  getAdditionalFieldSubmitValues,
  getAuthCallbackURL,
  getAuthLinkURL,
  getFormFieldErrors,
  isPasswordCompromisedError,
  validateEmailAddress,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import {
  AuthLink,
  type AuthPlugin,
  AuthPrompts,
  useAuth,
  useFetchOptions,
  useSignUpEmail
} from "@better-auth-ui/solid"
import { useQueryClient } from "@tanstack/solid-query"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, For, Show } from "solid-js"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { cn } from "cn"
import {
  createAuthForm,
  getAuthAdditionalFieldValidators,
  isAuthFormFieldInvalid
} from "./auth-form"
import { PasswordStrengthMeter } from "./password-strength-meter"
import { ProviderButtons, type SocialLayout } from "./provider-buttons"

export type SignUpProps = {
  class?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  /**
   * Runs instead of the post-sign-up redirect, but only when the sign-up
   * created an immediately usable session. Email verification still takes
   * priority, and social sign-ups are unaffected.
   */
  onSignUpSuccess?: () => void
}

export function SignUp(props: SignUpProps) {
  const auth = useAuth()
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const queryClient = useQueryClient()
  const [passwordError, setPasswordError] = createSignal<string>()
  const [isPasswordVisible, setIsPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const signUp = useSignUpEmail(auth.authClient, () => ({
    onError: (error) => {
      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setPasswordError(auth.localization.auth.passwordCompromised)
      }

      form.setFieldValue("password", "")
      form.setFieldValue("confirmPassword", "")
      resetFetchOptions()
    },
    onSuccess: (_data, variables) => {
      if (auth.emailAndPassword.requireEmailVerification) {
        sessionStorage.setItem("better-auth-ui.verify-email", variables.email)
        auth.navigate({
          to: getAuthLinkURL(
            `${auth.basePaths.auth}/${auth.viewPaths.auth.verifyEmail}`,
            auth.redirectTo
          )
        })
        return
      }

      queryClient.invalidateQueries({ queryKey: authQueryKeys.session })

      if (props.onSignUpSuccess) {
        props.onSignUpSuccess()
        return
      }

      auth.navigate({ to: auth.redirectTo })
    }
  }))
  const captchaComponent = () =>
    (auth.plugins as AuthPlugin[]).find((plugin) => plugin.captchaComponent)
      ?.captchaComponent
  const socialPosition = () => props.socialPosition ?? "bottom"
  const showSeparator = () =>
    Boolean(auth.emailAndPassword?.enabled && auth.socialProviders?.length)

  const signUpFieldsAbove = () =>
    auth.additionalFields?.filter((field) => field.signUp === "above") ?? []
  const signUpFieldsBelow = () =>
    auth.additionalFields?.filter(
      (field) => field.signUp && field.signUp !== "above"
    ) ?? []
  const signUpFields = () => [...signUpFieldsAbove(), ...signUpFieldsBelow()]
  const form = createAuthForm(() => ({
    defaultValues: {
      additionalFields: getAdditionalFieldDefaultValues(signUpFields()),
      confirmPassword: "",
      email: "",
      name: "",
      password: ""
    },
    onSubmit: async ({ value }) => {
      try {
        await signUp.mutateAsync({
          email: value.email.trim(),
          fetchOptions: fetchOptions(),
          name: auth.emailAndPassword.name ? value.name : "",
          password: value.password,
          ...getAdditionalFieldSubmitValues(
            signUpFields(),
            value.additionalFields
          ),
          callbackURL: getAuthCallbackURL(auth.baseURL, auth.redirectTo)
        } as Parameters<typeof signUp.mutate>[0])
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  }))

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <AuthPrompts view="signUp" />
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.signUp}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <Show when={socialPosition() === "top"}>
          <Show when={auth.socialProviders?.length}>
            <ProviderButtons socialLayout={props.socialLayout} view="signUp" />
          </Show>
          <Show when={showSeparator()}>
            <div class="my-4 text-center text-muted-foreground text-xs">
              {auth.localization.auth.or}
            </div>
          </Show>
        </Show>

        <form.AppForm>
          <form.AuthFormRoot aria-label="Sign up">
            <div class="flex flex-col gap-6">
              <Show when={auth.emailAndPassword.name}>
                <form.AppField
                  name="name"
                  validators={{
                    onChange: ({ value }) =>
                      validateStringLength(value, {
                        requiredMessage: auth.localization.auth.fieldRequired,
                        trim: true
                      })
                  }}
                >
                  {(field) => {
                    const isInvalid = () =>
                      isAuthFormFieldInvalid(field().state.meta)

                    return (
                      <Field data-invalid={isInvalid()}>
                        <FieldLabel for="sign-up-name">
                          {auth.localization.auth.name}
                        </FieldLabel>
                        <Input
                          aria-invalid={isInvalid()}
                          autocomplete="name"
                          id="sign-up-name"
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) =>
                            field().handleChange(event.currentTarget.value)
                          }
                          placeholder={auth.localization.auth.namePlaceholder}
                          required={auth.emailAndPassword.name}
                          type="text"
                          value={field().state.value}
                        />

                        <FieldError
                          errors={getFormFieldErrors(field().state.meta.errors)}
                        />
                      </Field>
                    )
                  }}
                </form.AppField>
              </Show>
              <form.AppField
                name="email"
                validators={{
                  onChange: ({ value }) =>
                    validateEmailAddress(value, {
                      invalidMessage: auth.localization.auth.invalidEmail,
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta)

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="sign-up-email">
                        {auth.localization.auth.email}
                      </FieldLabel>
                      <Input
                        aria-invalid={isInvalid()}
                        autocomplete="email"
                        id="sign-up-email"
                        name={field().name}
                        onBlur={field().handleBlur}
                        onInput={(event) =>
                          field().handleChange(event.currentTarget.value)
                        }
                        placeholder={auth.localization.auth.emailPlaceholder}
                        required
                        type="email"
                        value={field().state.value}
                      />

                      <FieldError
                        errors={getFormFieldErrors(field().state.meta.errors)}
                      />
                    </Field>
                  )
                }}
              </form.AppField>
              <For each={signUpFieldsAbove()}>
                {(configuredField) => (
                  <form.AppField
                    name={`additionalFields.${configuredField.name}`}
                    validators={getAuthAdditionalFieldValidators(
                      configuredField,
                      auth.localization.auth.fieldRequired
                    )}
                  >
                    {(field) => (
                      <field.AuthFormAdditionalField
                        field={configuredField}
                        isPending={signUp.isPending}
                        optionalLabel={auth.localization.auth.optional}
                      />
                    )}
                  </form.AppField>
                )}
              </For>
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      maxLength: auth.emailAndPassword.maxPasswordLength,
                      maxLengthMessage: auth.localization.auth.tooLong.replace(
                        "{{max}}",
                        String(auth.emailAndPassword.maxPasswordLength)
                      ),
                      minLength: auth.emailAndPassword.minPasswordLength,
                      minLengthMessage: auth.localization.auth.tooShort.replace(
                        "{{min}}",
                        String(auth.emailAndPassword.minPasswordLength)
                      ),
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta) ||
                    Boolean(passwordError())

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="sign-up-password">
                        {auth.localization.auth.password}
                      </FieldLabel>
                      <div class="relative">
                        <Input
                          aria-invalid={isInvalid()}
                          autocomplete="new-password"
                          class="pr-12"
                          id="sign-up-password"
                          maxLength={auth.emailAndPassword.maxPasswordLength}
                          minLength={auth.emailAndPassword.minPasswordLength}
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) => {
                            field().handleChange(event.currentTarget.value)
                            setPasswordError(undefined)
                          }}
                          placeholder={
                            auth.localization.auth.passwordPlaceholder
                          }
                          required
                          type={isPasswordVisible() ? "text" : "password"}
                          value={field().state.value}
                        />

                        <Button
                          aria-label={
                            isPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          class="absolute right-1 top-1/2 -translate-y-1/2"
                          onClick={() =>
                            setIsPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          type="button"
                          variant="ghost"
                        >
                          {isPasswordVisible() ? (
                            <EyeOff aria-hidden class="size-4" />
                          ) : (
                            <Eye aria-hidden class="size-4" />
                          )}
                        </Button>
                      </div>

                      <Show when={passwordError()}>
                        {(message) => <FieldError>{message()}</FieldError>}
                      </Show>
                      <Show when={!passwordError()}>
                        <FieldError
                          errors={getFormFieldErrors(field().state.meta.errors)}
                        />
                      </Show>

                      <PasswordStrengthMeter password={field().state.value} />
                    </Field>
                  )
                }}
              </form.AppField>
              <Show when={auth.emailAndPassword.confirmPassword}>
                <form.AppField
                  name="confirmPassword"
                  validators={{
                    onChangeListenTo: ["password"],
                    onChange: ({ fieldApi, value }) =>
                      validateStringLength(value, {
                        maxLength: auth.emailAndPassword.maxPasswordLength,
                        maxLengthMessage:
                          auth.localization.auth.tooLong.replace(
                            "{{max}}",
                            String(auth.emailAndPassword.maxPasswordLength)
                          ),
                        minLength: auth.emailAndPassword.minPasswordLength,
                        minLengthMessage:
                          auth.localization.auth.tooShort.replace(
                            "{{min}}",
                            String(auth.emailAndPassword.minPasswordLength)
                          ),
                        requiredMessage: auth.localization.auth.fieldRequired
                      }) ??
                      validateMatchingValue(
                        value,
                        fieldApi.form.getFieldValue("password"),
                        auth.localization.auth.passwordsDoNotMatch
                      )
                  }}
                >
                  {(field) => {
                    const isInvalid = () =>
                      isAuthFormFieldInvalid(field().state.meta)

                    return (
                      <Field data-invalid={isInvalid()}>
                        <FieldLabel for="sign-up-confirm-password">
                          {auth.localization.auth.confirmPassword}
                        </FieldLabel>
                        <div class="relative">
                          <Input
                            aria-invalid={isInvalid()}
                            autocomplete="new-password"
                            class="pr-12"
                            id="sign-up-confirm-password"
                            maxLength={auth.emailAndPassword.maxPasswordLength}
                            minLength={auth.emailAndPassword.minPasswordLength}
                            name={field().name}
                            onBlur={field().handleBlur}
                            onInput={(event) =>
                              field().handleChange(event.currentTarget.value)
                            }
                            placeholder={
                              auth.localization.auth.confirmPasswordPlaceholder
                            }
                            required
                            type={
                              isConfirmPasswordVisible() ? "text" : "password"
                            }
                            value={field().state.value}
                          />

                          <Button
                            aria-label={
                              isConfirmPasswordVisible()
                                ? auth.localization.auth.hidePassword
                                : auth.localization.auth.showPassword
                            }
                            class="absolute right-1 top-1/2 -translate-y-1/2"
                            onClick={() =>
                              setIsConfirmPasswordVisible((visible) => !visible)
                            }
                            size="icon-sm"
                            title={
                              isConfirmPasswordVisible()
                                ? auth.localization.auth.hidePassword
                                : auth.localization.auth.showPassword
                            }
                            type="button"
                            variant="ghost"
                          >
                            {isConfirmPasswordVisible() ? (
                              <EyeOff aria-hidden class="size-4" />
                            ) : (
                              <Eye aria-hidden class="size-4" />
                            )}
                          </Button>
                        </div>

                        <FieldError
                          errors={getFormFieldErrors(field().state.meta.errors)}
                        />
                      </Field>
                    )
                  }}
                </form.AppField>
              </Show>
              <For each={signUpFieldsBelow()}>
                {(configuredField) => (
                  <form.AppField
                    name={`additionalFields.${configuredField.name}`}
                    validators={getAuthAdditionalFieldValidators(
                      configuredField,
                      auth.localization.auth.fieldRequired
                    )}
                  >
                    {(field) => (
                      <field.AuthFormAdditionalField
                        field={configuredField}
                        isPending={signUp.isPending}
                        optionalLabel={auth.localization.auth.optional}
                      />
                    )}
                  </form.AppField>
                )}
              </For>
              <Show when={captchaComponent()} keyed>
                {(Captcha) => <Captcha />}
              </Show>
              <form.AuthFormSubmitButton disabled={signUp.isPending}>
                {auth.localization.auth.signUp}
              </form.AuthFormSubmitButton>
              <Show when={signUp.isSuccess}>
                <Alert>
                  <AlertDescription role="status">
                    Account created. Check your email if verification is
                    required.
                  </AlertDescription>
                </Alert>
              </Show>
              <Show
                when={
                  signUp.isError && !isPasswordCompromisedError(signUp.error)
                }
              >
                <Alert variant="destructive">
                  <AlertDescription>
                    Unable to create an account. Try again.
                  </AlertDescription>
                </Alert>
              </Show>
            </div>
          </form.AuthFormRoot>
        </form.AppForm>

        <Show
          when={socialPosition() === "bottom" && auth.socialProviders?.length}
        >
          <div class="my-4 text-center text-muted-foreground text-xs">
            {auth.localization.auth.or}
          </div>
          <ProviderButtons socialLayout={props.socialLayout} view="signUp" />
        </Show>

        <div class="mt-4 flex w-full flex-col items-center gap-3">
          <p class="text-center text-sm text-muted-foreground">
            {auth.localization.auth.alreadyHaveAnAccount}{" "}
            <AuthLink
              class="underline underline-offset-4"
              href={getAuthLinkURL(
                `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`,
                auth.redirectTo
              )}
            >
              {auth.localization.auth.signIn}
            </AuthLink>
          </p>
        </div>
      </CardContent>
    </Card>
  )
}

// packages/heroui/src/components/auth/sign-up.tsx
import {
  authMutationKeys,
  getAdditionalFieldDefaultValues,
  getAdditionalFieldSubmitValues,
  getAuthLinkURL,
  isPasswordCompromisedError,
  validateEmailAddress,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import {
  AuthPrompts,
  useAuth,
  useFetchOptions,
  useSignUpEmail
} from "@better-auth-ui/react"
import { Eye, EyeSlash } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Description,
  FieldError,
  Input,
  InputGroup,
  Label,
  Link,
  TextField
} from "@heroui/react"
import { useIsMutating } from "@tanstack/react-query"
import { useMemo, useState } from "react"
import {
  getAuthAdditionalFieldValidators,
  isAuthFormFieldInvalid,
  useAuthForm
} from "./auth-form"
import { FieldSeparator } from "./field-separator"
import { PasswordStrengthMeter } from "./password-strength-meter"
import { ProviderButtons, type SocialLayout } from "./provider-buttons"

export type SignUpProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardProps["variant"]
  /**
   * Runs instead of the post-sign-up redirect, but only when the sign-up
   * created an immediately usable session. Email verification still takes
   * priority, and social sign-ups are unaffected.
   */
  onSignUpSuccess?: () => void
}

/**
 * Render a sign-up form with name, email, password (and optional confirm password) fields, optional social provider buttons, and password visibility controls.
 *
 * The component reflects request state by disabling inputs and showing a pending indicator during sign-up or social sign-in.
 *
 * @param className - Additional CSS classes applied to the outer card container
 * @param socialLayout - Social layout to apply to the provider buttons component
 * @param socialPosition - Position of social provider buttons relative to the form; `"top"` or `"bottom"` (default `"bottom"`)
 * @param onSignUpSuccess - Replaces the post-sign-up redirect when the new account is immediately usable
 * @returns The sign-up form React element
 */
export function SignUp({
  className,
  socialLayout,
  socialPosition = "bottom",
  variant,
  onSignUpSuccess
}: SignUpProps) {
  const {
    additionalFields,
    authClient,
    basePaths,
    baseURL,
    emailAndPassword,
    localization,
    plugins,
    redirectTo,
    socialProviders,
    viewPaths,
    navigate
  } = useAuth()

  const { fetchOptions, resetFetchOptions } = useFetchOptions()

  const [isCompromised, setIsCompromised] = useState(false)

  const { mutateAsync: signUpEmail } = useSignUpEmail(authClient, {
    onError: (error) => {
      // The haveIBeenPwned plugin rejects on the password itself, so
      // it belongs against the field rather than in a toast.
      setIsCompromised(isPasswordCompromisedError(error))

      form.setFieldValue("password", "")
      form.setFieldValue("confirmPassword", "")
      resetFetchOptions()
    },
    onSuccess: (_data, { email }) => {
      if (emailAndPassword?.requireEmailVerification) {
        sessionStorage.setItem("better-auth-ui.verify-email", email)
        navigate({
          to: getAuthLinkURL(
            `${basePaths.auth}/${viewPaths.auth.verifyEmail}`,
            redirectTo
          )
        })
      } else if (onSignUpSuccess) {
        onSignUpSuccess()
      } else {
        navigate({ to: redirectTo })
      }
    }
  })

  const [isPasswordVisible, setIsPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0

  const Captcha = plugins.find(
    (plugin) => plugin.captchaComponent
  )?.captchaComponent
  const signUpFields = useMemo(
    () => additionalFields?.filter((field) => field.signUp) ?? [],
    [additionalFields]
  )
  const form = useAuthForm({
    defaultValues: {
      additionalFields: getAdditionalFieldDefaultValues(signUpFields),
      confirmPassword: "",
      email: "",
      name: "",
      password: ""
    },
    onSubmit: async ({ value }) => {
      try {
        await signUpEmail({
          name: emailAndPassword?.name === false ? "" : value.name,
          email: value.email.trim(),
          password: value.password,
          ...getAdditionalFieldSubmitValues(
            signUpFields,
            value.additionalFields
          ),
          callbackURL: `${baseURL}${redirectTo}`,
          fetchOptions
        })
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  })

  const showSeparator = emailAndPassword?.enabled && !!socialProviders?.length

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <AuthPrompts view="signUp" />
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.signUp}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        {socialPosition === "top" && (
          <>
            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="signUp" />
            )}

            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}
          </>
        )}

        {emailAndPassword?.enabled && (
          <form.AppForm>
            <form.AuthFormRoot className="flex flex-col gap-4">
              {emailAndPassword.name !== false && (
                <form.AppField
                  name="name"
                  validators={{
                    onChange: ({ value }) =>
                      validateStringLength(value, {
                        requiredMessage: localization.auth.fieldRequired,
                        trim: true
                      })
                  }}
                >
                  {(field) => (
                    <TextField
                      name={field.name}
                      type="text"
                      autoComplete="name"
                      isDisabled={isPending}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={field.handleChange}
                      isInvalid={
                        isAuthFormFieldInvalid(field.state.meta) || undefined
                      }
                      validationBehavior="aria"
                    >
                      <Label>{localization.auth.name}</Label>

                      <Input
                        placeholder={localization.auth.namePlaceholder}
                        required
                        variant={
                          variant === "transparent" ? "primary" : "secondary"
                        }
                      />

                      <field.AuthFormFieldError />
                    </TextField>
                  )}
                </form.AppField>
              )}

              <form.AppField
                name="email"
                validators={{
                  onChange: ({ value }) =>
                    validateEmailAddress(value, {
                      invalidMessage: localization.auth.invalidEmail,
                      requiredMessage: localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => (
                  <TextField
                    name={field.name}
                    type="email"
                    autoComplete="email"
                    isDisabled={isPending}
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    isInvalid={
                      isAuthFormFieldInvalid(field.state.meta) || undefined
                    }
                    validationBehavior="aria"
                  >
                    <Label>{localization.auth.email}</Label>

                    <Input
                      placeholder={localization.auth.emailPlaceholder}
                      required
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    />

                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>

              {signUpFields.map(
                (configuredField) =>
                  configuredField.signUp === "above" && (
                    <form.AppField
                      key={configuredField.name}
                      name={`additionalFields.${configuredField.name}`}
                      validators={getAuthAdditionalFieldValidators(
                        configuredField,
                        localization.auth.fieldRequired
                      )}
                    >
                      {(field) => (
                        <field.AuthFormAdditionalField
                          field={configuredField}
                          isPending={isPending}
                          optionalLabel={localization.auth.optional}
                          variant={variant}
                        />
                      )}
                    </form.AppField>
                  )
              )}

              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      maxLength: emailAndPassword?.maxPasswordLength,
                      maxLengthMessage: localization.auth.tooLong.replace(
                        "{{max}}",
                        String(emailAndPassword?.maxPasswordLength)
                      ),
                      minLength: emailAndPassword?.minPasswordLength,
                      minLengthMessage: localization.auth.tooShort.replace(
                        "{{min}}",
                        String(emailAndPassword?.minPasswordLength)
                      ),
                      requiredMessage: localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid =
                    isAuthFormFieldInvalid(field.state.meta) || isCompromised

                  return (
                    <TextField
                      minLength={emailAndPassword?.minPasswordLength}
                      maxLength={emailAndPassword?.maxPasswordLength}
                      name={field.name}
                      autoComplete="new-password"
                      isDisabled={isPending}
                      onBlur={field.handleBlur}
                      value={field.state.value}
                      onChange={(value) => {
                        field.handleChange(value)
                        setIsCompromised(false)
                      }}
                      isInvalid={isInvalid || undefined}
                      validationBehavior="aria"
                    >
                      <Label>{localization.auth.password}</Label>

                      <InputGroup
                        variant={
                          variant === "transparent" ? "primary" : "secondary"
                        }
                      >
                        <InputGroup.Input
                          placeholder={localization.auth.passwordPlaceholder}
                          type={isPasswordVisible ? "text" : "password"}
                          name="password"
                          required
                        />

                        <InputGroup.Suffix className="px-0">
                          <Button
                            isIconOnly
                            aria-label={
                              isPasswordVisible
                                ? localization.auth.hidePassword
                                : localization.auth.showPassword
                            }
                            size="sm"
                            variant="ghost"
                            onPress={() =>
                              setIsPasswordVisible(!isPasswordVisible)
                            }
                            isDisabled={isPending}
                          >
                            {isPasswordVisible ? <EyeSlash /> : <Eye />}
                          </Button>
                        </InputGroup.Suffix>
                      </InputGroup>

                      {isCompromised ? (
                        <FieldError>
                          {localization.auth.passwordCompromised}
                        </FieldError>
                      ) : (
                        <field.AuthFormFieldError />
                      )}

                      <PasswordStrengthMeter password={field.state.value} />
                    </TextField>
                  )
                }}
              </form.AppField>

              {emailAndPassword?.confirmPassword && (
                <form.AppField
                  name="confirmPassword"
                  validators={{
                    onChangeListenTo: ["password"],
                    onChange: ({ fieldApi, value }) =>
                      validateStringLength(value, {
                        maxLength: emailAndPassword?.maxPasswordLength,
                        maxLengthMessage: localization.auth.tooLong.replace(
                          "{{max}}",
                          String(emailAndPassword?.maxPasswordLength)
                        ),
                        minLength: emailAndPassword?.minPasswordLength,
                        minLengthMessage: localization.auth.tooShort.replace(
                          "{{min}}",
                          String(emailAndPassword?.minPasswordLength)
                        ),
                        requiredMessage: localization.auth.fieldRequired
                      }) ??
                      validateMatchingValue(
                        value,
                        fieldApi.form.getFieldValue("password"),
                        localization.auth.passwordsDoNotMatch
                      )
                  }}
                >
                  {(field) => (
                    <TextField
                      minLength={emailAndPassword?.minPasswordLength}
                      maxLength={emailAndPassword?.maxPasswordLength}
                      name={field.name}
                      autoComplete="new-password"
                      isDisabled={isPending}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={field.handleChange}
                      isInvalid={
                        isAuthFormFieldInvalid(field.state.meta) || undefined
                      }
                      validationBehavior="aria"
                    >
                      <Label>{localization.auth.confirmPassword}</Label>

                      <InputGroup
                        variant={
                          variant === "transparent" ? "primary" : "secondary"
                        }
                      >
                        <InputGroup.Input
                          name="confirmPassword"
                          placeholder={
                            localization.auth.confirmPasswordPlaceholder
                          }
                          type={isConfirmPasswordVisible ? "text" : "password"}
                          required
                        />

                        <InputGroup.Suffix className="px-0">
                          <Button
                            isIconOnly
                            aria-label={
                              isConfirmPasswordVisible
                                ? localization.auth.hidePassword
                                : localization.auth.showPassword
                            }
                            size="sm"
                            variant="ghost"
                            onPress={() =>
                              setIsConfirmPasswordVisible(
                                !isConfirmPasswordVisible
                              )
                            }
                            isDisabled={isPending}
                          >
                            {isConfirmPasswordVisible ? <EyeSlash /> : <Eye />}
                          </Button>
                        </InputGroup.Suffix>
                      </InputGroup>

                      <field.AuthFormFieldError />
                    </TextField>
                  )}
                </form.AppField>
              )}

              {signUpFields.map(
                (configuredField) =>
                  configuredField.signUp !== "above" && (
                    <form.AppField
                      key={configuredField.name}
                      name={`additionalFields.${configuredField.name}`}
                      validators={getAuthAdditionalFieldValidators(
                        configuredField,
                        localization.auth.fieldRequired
                      )}
                    >
                      {(field) => (
                        <field.AuthFormAdditionalField
                          field={configuredField}
                          isPending={isPending}
                          optionalLabel={localization.auth.optional}
                          variant={variant}
                        />
                      )}
                    </form.AppField>
                  )
              )}

              {Captcha && <div className="flex justify-center">{Captcha}</div>}

              <div className="flex flex-col gap-3">
                <form.AuthFormSubmitButton
                  className="w-full"
                  isDisabled={isPending}
                >
                  {localization.auth.signUp}
                </form.AuthFormSubmitButton>

                {plugins.flatMap((plugin) =>
                  plugin.authButtons?.map((AuthButton, index) => (
                    <AuthButton
                      key={`${plugin.id}-${index.toString()}`}
                      view="signUp"
                    />
                  ))
                )}
              </div>
            </form.AuthFormRoot>
          </form.AppForm>
        )}

        {socialPosition === "bottom" && (
          <>
            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}

            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="signUp" />
            )}
          </>
        )}
      </Card.Content>

      <Card.Footer className="flex-col gap-3">
        <Description className="text-sm">
          {localization.auth.alreadyHaveAnAccount}{" "}
          <Link
            href={getAuthLinkURL(
              `${basePaths.auth}/${viewPaths.auth.signIn}`,
              redirectTo
            )}
            className="text-accent no-underline hover:underline decoration-accent-hover"
          >
            {localization.auth.signIn}
          </Link>
        </Description>
      </Card.Footer>
    </Card>
  )
}
