// examples/start-solid-zaidan-example/src/components/auth/passkey/passkeys.tsx
import type { PasskeyAuthClient } from "@better-auth-ui/core/plugins/passkey"
import { useAuth } from "@better-auth-ui/solid"
import { useListPasskeys } from "@better-auth-ui/solid/plugins/passkey"
import { createSignal, For, Show } from "solid-js"
import { AddPasskeyDialog } from "@/components/auth/passkey/add-passkey-dialog"
import { Passkey } from "@/components/auth/passkey/passkey"
import { passkeyLabels } from "@/components/auth/passkey/passkey-localization"
import { PasskeySkeleton } from "@/components/auth/passkey/passkey-skeleton"
import { PasskeysEmpty } from "@/components/auth/passkey/passkeys-empty"
import type { ListedPasskey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"
import { ItemGroup, ItemSeparator } from "@/components/ui/item"
import { cn } from "@/lib/utils"

export type PasskeysSettingsProps = {
  class?: string
}

export function PasskeysSettings(props: PasskeysSettingsProps) {
  const auth = useAuth<PasskeyAuthClient>()
  const labels = () => passkeyLabels(auth)
  const [isAddDialogOpen, setIsAddDialogOpen] = createSignal(false)
  const passkeys = useListPasskeys(auth.authClient)
  const items = () => passkeys.data ?? []

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <div class="flex items-end justify-between gap-3">
        <h2 class="truncate text-sm font-semibold">{labels().passkeys}</h2>
        <Dialog open={isAddDialogOpen()} onOpenChange={setIsAddDialogOpen}>
          <DialogTrigger
            as={Button}
            class="shrink-0"
            disabled={passkeys.isPending}
            size="sm"
          >
            {labels().addPasskey}
          </DialogTrigger>
          <AddPasskeyDialog
            onOpenChange={setIsAddDialogOpen}
            onPasskeyAdded={() => passkeys.refetch()}
          />
        </Dialog>
      </div>

      <Card class="z-card-padding-none">
        <CardContent class="z-card-content-padding-none">
          <Show when={!passkeys.isPending} fallback={<PasskeySkeleton />}>
            <Show
              when={items().length > 0}
              fallback={
                <PasskeysEmpty onAddPress={() => setIsAddDialogOpen(true)} />
              }
            >
              <ItemGroup class="gap-0">
                <For each={items()}>
                  {(passkey, index) => (
                    <>
                      <Show when={index() > 0}>
                        <ItemSeparator />
                      </Show>
                      <Passkey passkey={passkey as ListedPasskey} />
                    </>
                  )}
                </For>
              </ItemGroup>
            </Show>
          </Show>
        </CardContent>
      </Card>
    </div>
  )
}

// packages/heroui/src/components/auth/passkey/passkeys.tsx
import type { PasskeyAuthClient } from "@better-auth-ui/core/plugins/passkey"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useListPasskeys } from "@better-auth-ui/react/plugins/passkey"
import { Button, Card, type CardProps, cn } from "@heroui/react"
import { useState } from "react"

import { passkeyPlugin } from "../../../lib/auth/passkey-plugin"
import { AddPasskeyDialog } from "./add-passkey-dialog"
import { Passkey } from "./passkey"
import { PasskeySkeleton } from "./passkey-skeleton"
import { PasskeysEmpty } from "./passkeys-empty"

export type PasskeysProps = {
  className?: string
  variant?: CardProps["variant"]
}

export function Passkeys({
  className,
  variant,
  ...props
}: PasskeysProps & Omit<CardProps, "children">) {
  const { authClient } = useAuth()
  const { localization: passkeyLocalization } = useAuthPlugin(passkeyPlugin)

  const { data: passkeys, isPending } = useListPasskeys(
    authClient as PasskeyAuthClient
  )

  const [addOpen, setAddOpen] = useState(false)

  return (
    <div className={cn("flex flex-col gap-3", className)}>
      <div className="flex items-end justify-between gap-3">
        <h2 className="text-sm font-semibold truncate">
          {passkeyLocalization.passkeys}
        </h2>

        <Button
          className="shrink-0"
          size="sm"
          isDisabled={isPending}
          onPress={() => setAddOpen(true)}
        >
          {passkeyLocalization.addPasskey}
        </Button>
      </div>

      <Card variant={variant} {...props}>
        <Card.Content>
          {isPending ? (
            <PasskeySkeleton />
          ) : !passkeys?.length ? (
            <PasskeysEmpty onAddPress={() => setAddOpen(true)} />
          ) : (
            passkeys.map((passkey, index) => (
              <div key={passkey.id}>
                {index > 0 && (
                  <div className="border-b border-dashed -mx-4 my-4" />
                )}

                <Passkey passkey={passkey} />
              </div>
            ))
          )}
        </Card.Content>
      </Card>

      <AddPasskeyDialog isOpen={addOpen} onOpenChange={setAddOpen} />
    </div>
  )
}
