// examples/start-solid-zaidan-example/src/components/auth/passkey/rename-passkey-dialog.tsx
import { validateStringLength } from "@better-auth-ui/core"
import type { PasskeyAuthClient } from "@better-auth-ui/core/plugins/passkey"
import { useAuth } from "@better-auth-ui/solid"
import { useUpdatePasskey } from "@better-auth-ui/solid/plugins/passkey"
import { createEffect } from "solid-js"
import { passkeyLabels } from "@/components/auth/passkey/passkey-localization"
import type { ListedPasskey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { createAuthForm } from "../auth-form"

export function RenamePasskeyDialog(props: {
  open: boolean
  onOpenChange: (open: boolean) => void
  passkey: ListedPasskey
}) {
  const auth = useAuth<PasskeyAuthClient>()
  const labels = () => passkeyLabels(auth)
  const updatePasskey = useUpdatePasskey(auth.authClient, () => ({
    onSuccess: () => props.onOpenChange(false)
  }))
  const form = createAuthForm(() => ({
    defaultValues: { name: props.passkey.name ?? "" },
    onSubmit: async ({ value }) => {
      await updatePasskey.mutateAsync({
        id: props.passkey.id,
        name: value.name.trim()
      })
    }
  }))
  createEffect(() => {
    if (props.open) form.setFieldValue("name", props.passkey.name ?? "")
  })

  return (
    <DialogContent>
      <form.AppForm>
        <form.AuthFormRoot class="flex flex-col gap-6">
          <DialogHeader>
            <DialogTitle>{labels().renamePasskey}</DialogTitle>
          </DialogHeader>
          <form.AppField
            name="name"
            validators={{
              onChange: ({ value }) =>
                validateStringLength(value, {
                  requiredMessage: auth.localization.auth.fieldRequired,
                  trim: true
                })
            }}
          >
            {(field) => (
              <Field>
                <FieldLabel for={`passkey-name-${props.passkey.id}`}>
                  {labels().name}
                </FieldLabel>
                <Input
                  id={`passkey-name-${props.passkey.id}`}
                  autofocus
                  name={field().name}
                  value={field().state.value}
                  onBlur={field().handleBlur}
                  onInput={(event) =>
                    field().handleChange(event.currentTarget.value)
                  }
                />
                <field.AuthFormFieldError />
              </Field>
            )}
          </form.AppField>
          <DialogFooter>
            <DialogClose as={Button} type="button" variant="outline">
              {auth.localization.settings.cancel}
            </DialogClose>
            <form.AuthFormSubmitButton
              isPending={updatePasskey.isPending}
              disabled={updatePasskey.isPending}
            >
              {auth.localization.settings.saveChanges}
            </form.AuthFormSubmitButton>
          </DialogFooter>
          <form.AuthFormServerError />
        </form.AuthFormRoot>
      </form.AppForm>
    </DialogContent>
  )
}

// packages/heroui/src/components/auth/passkey/rename-passkey-dialog.tsx
import type { PasskeyAuthClient } from "@better-auth-ui/core/plugins/passkey"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useUpdatePasskey } from "@better-auth-ui/react/plugins/passkey"
import { AlertDialog, Button, Input, Label, TextField } from "@heroui/react"
import { useSelector } from "@tanstack/react-form"
import { useEffect } from "react"
import { passkeyPlugin } from "../../../lib/auth/passkey-plugin"
import { useAuthForm } from "../auth-form"
import type { ListedPasskey } from "./delete-passkey-dialog"

export function RenamePasskeyDialog({
  isOpen,
  onOpenChange,
  passkey
}: {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
  passkey: ListedPasskey
}) {
  const { authClient, localization } = useAuth()
  const { localization: labels } = useAuthPlugin(passkeyPlugin)
  const updatePasskey = useUpdatePasskey(authClient as PasskeyAuthClient, {
    onSuccess: () => onOpenChange(false)
  })
  const form = useAuthForm({
    defaultValues: { name: passkey.name ?? "" },
    onSubmit: async ({ value }) => {
      const nextName = value.name.trim()
      if (nextName) {
        await updatePasskey.mutateAsync({ id: passkey.id, name: nextName })
      }
    }
  })
  const nameIsEmpty = useSelector(
    form.store,
    (state) => state.values.name.trim().length === 0
  )
  useEffect(() => {
    if (isOpen) form.setFieldValue("name", passkey.name ?? "")
  }, [form.setFieldValue, isOpen, passkey.name])

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={onOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog>
          <form.AppForm>
            <form.AuthFormRoot>
              <AlertDialog.CloseTrigger />
              <AlertDialog.Header>
                <AlertDialog.Heading>
                  {labels.renamePasskey}
                </AlertDialog.Heading>
              </AlertDialog.Header>
              <AlertDialog.Body>
                <form.AppField name="name">
                  {(field) => (
                    <TextField
                      isDisabled={updatePasskey.isPending}
                      value={field.state.value}
                      onChange={field.handleChange}
                      onBlur={field.handleBlur}
                    >
                      <Label>{labels.name}</Label>
                      <Input autoFocus variant="secondary" required />
                    </TextField>
                  )}
                </form.AppField>
                <form.AuthFormServerError />
              </AlertDialog.Body>
              <AlertDialog.Footer>
                <Button slot="close" variant="tertiary">
                  {localization.settings.cancel}
                </Button>
                <form.AuthFormSubmitButton
                  isPending={updatePasskey.isPending}
                  isDisabled={nameIsEmpty || updatePasskey.isPending}
                >
                  {localization.settings.saveChanges}
                </form.AuthFormSubmitButton>
              </AlertDialog.Footer>
            </form.AuthFormRoot>
          </form.AppForm>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}
