// examples/start-solid-zaidan-example/src/components/auth/two-factor/two-factor-settings.tsx
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/solid"
import { ShieldCheck } from "lucide-solid"
import { createSignal, Show } from "solid-js"

import { DisableTwoFactorDialog } from "@/components/auth/two-factor/disable-two-factor-dialog"
import { EnableTwoFactorDialog } from "@/components/auth/two-factor/enable-two-factor-dialog"
import { RegenerateBackupCodesDialog } from "@/components/auth/two-factor/regenerate-backup-codes-dialog"
import { AlertDialog, AlertDialogTrigger } from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle
} from "@/components/ui/empty"
import { Skeleton } from "@/components/ui/skeleton"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { cn } from "@/lib/utils"

export type TwoFactorSettingsProps = {
  class?: string
}

/**
 * Security-settings card for enrolling in and managing two-factor auth.
 *
 * Reads `user.twoFactorEnabled` from the session — the field the Better Auth
 * two-factor plugin adds — so the card reflects enrollment without an extra
 * request.
 */
export function TwoFactorSettings(props: TwoFactorSettingsProps = {}) {
  const auth = useAuth()
  const {
    backupCodes: backupCodesEnabled,
    localization: twoFactorLocalization
  } = useAuthPlugin(twoFactorPlugin)

  const session = useSession(auth.authClient)
  const isEnabled = () =>
    Boolean(
      (session.data?.user as { twoFactorEnabled?: boolean } | undefined)
        ?.twoFactorEnabled
    )

  const [isEnableOpen, setIsEnableOpen] = createSignal(false)
  const [isDisableOpen, setIsDisableOpen] = createSignal(false)
  const [isRegenerateOpen, setIsRegenerateOpen] = createSignal(false)

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <div class="flex items-end justify-between gap-3">
        <h2 class="truncate text-sm font-semibold">
          {twoFactorLocalization.twoFactor}
        </h2>

        <Show
          when={isEnabled()}
          fallback={
            <Dialog open={isEnableOpen()} onOpenChange={setIsEnableOpen}>
              <DialogTrigger
                as={Button}
                class="shrink-0"
                disabled={session.isPending}
                size="sm"
              >
                {twoFactorLocalization.enableTwoFactor}
              </DialogTrigger>

              <EnableTwoFactorDialog onOpenChange={setIsEnableOpen} />
            </Dialog>
          }
        >
          <AlertDialog open={isDisableOpen()} onOpenChange={setIsDisableOpen}>
            <AlertDialogTrigger
              as={Button}
              class="shrink-0"
              disabled={session.isPending}
              size="sm"
              variant="destructive"
            >
              {twoFactorLocalization.disableTwoFactor}
            </AlertDialogTrigger>

            <DisableTwoFactorDialog onOpenChange={setIsDisableOpen} />
          </AlertDialog>
        </Show>
      </div>

      <Show
        when={session.isPending || isEnabled()}
        fallback={
          <Card class="z-card-padding-none">
            <CardContent class="z-card-content-padding-none">
              <Empty>
                <EmptyHeader>
                  <EmptyMedia variant="icon">
                    <ShieldCheck />
                  </EmptyMedia>
                  <EmptyTitle>
                    {twoFactorLocalization.twoFactorDisabled}
                  </EmptyTitle>
                  <EmptyDescription>
                    {twoFactorLocalization.twoFactorDescription}
                  </EmptyDescription>
                </EmptyHeader>
                <EmptyContent>
                  <Button
                    onClick={() => setIsEnableOpen(true)}
                    size="sm"
                    type="button"
                  >
                    {twoFactorLocalization.enableTwoFactor}
                  </Button>
                </EmptyContent>
              </Empty>
            </CardContent>
          </Card>
        }
      >
        <Card>
          <CardContent class="flex flex-col gap-4">
            <Show
              when={!session.isPending}
              fallback={<Skeleton class="h-5 w-48" />}
            >
              <p class="text-sm font-medium">
                {twoFactorLocalization.twoFactorEnabled}
              </p>
            </Show>

            <p class="text-muted-foreground text-sm">
              {twoFactorLocalization.twoFactorDescription}
            </p>

            <Show when={isEnabled() && backupCodesEnabled}>
              <AlertDialog
                open={isRegenerateOpen()}
                onOpenChange={setIsRegenerateOpen}
              >
                <AlertDialogTrigger
                  as={Button}
                  class="self-start"
                  size="sm"
                  variant="outline"
                >
                  {twoFactorLocalization.regenerateBackupCodes}
                </AlertDialogTrigger>

                <RegenerateBackupCodesDialog
                  onOpenChange={setIsRegenerateOpen}
                />
              </AlertDialog>
            </Show>
          </CardContent>
        </Card>
      </Show>
    </div>
  )
}

// apps/docs/src/components/auth/two-factor/two-factor-settings.tsx
"use client"

import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import { ShieldCheck } from "lucide-react"
import { useState } from "react"

import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle
} from "@/components/ui/empty"
import { Skeleton } from "@/components/ui/skeleton"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { cn } from "@/lib/utils"
import { DisableTwoFactorDialog } from "./disable-two-factor-dialog"
import { EnableTwoFactorDialog } from "./enable-two-factor-dialog"
import { RegenerateBackupCodesDialog } from "./regenerate-backup-codes-dialog"

export type TwoFactorSettingsProps = {
  className?: string
}

/**
 * Security-settings card for enrolling in and managing two-factor auth.
 *
 * Reads `user.twoFactorEnabled` from the session — the field the Better Auth
 * two-factor plugin adds — so the card reflects enrollment without an extra
 * request.
 *
 * @param className - Additional CSS classes applied to the card.
 */
export function TwoFactorSettings({ className }: TwoFactorSettingsProps) {
  const { authClient } = useAuth()
  const {
    backupCodes: backupCodesEnabled,
    localization: twoFactorLocalization
  } = useAuthPlugin(twoFactorPlugin)

  const { data: session, isPending } = useSession(authClient)
  const isEnabled = Boolean(
    (session?.user as { twoFactorEnabled?: boolean } | undefined)
      ?.twoFactorEnabled
  )

  const [enableOpen, setEnableOpen] = useState(false)
  const [disableOpen, setDisableOpen] = useState(false)
  const [regenerateOpen, setRegenerateOpen] = useState(false)

  return (
    <div className={cn("flex flex-col gap-3", className)}>
      <div className="flex items-end justify-between gap-3">
        <h2 className="truncate text-sm font-semibold">
          {twoFactorLocalization.twoFactor}
        </h2>

        <Button
          className="shrink-0"
          size="sm"
          variant={isEnabled ? "destructive" : "default"}
          disabled={isPending}
          onClick={() =>
            isEnabled ? setDisableOpen(true) : setEnableOpen(true)
          }
        >
          {isEnabled
            ? twoFactorLocalization.disableTwoFactor
            : twoFactorLocalization.enableTwoFactor}
        </Button>
      </div>

      {!isPending && !isEnabled ? (
        <Card className="p-0">
          <CardContent className="p-0">
            <Empty>
              <EmptyHeader>
                <EmptyMedia variant="icon">
                  <ShieldCheck />
                </EmptyMedia>
                <EmptyTitle>
                  {twoFactorLocalization.twoFactorDisabled}
                </EmptyTitle>
                <EmptyDescription>
                  {twoFactorLocalization.twoFactorDescription}
                </EmptyDescription>
              </EmptyHeader>
              <EmptyContent>
                <Button size="sm" onClick={() => setEnableOpen(true)}>
                  {twoFactorLocalization.enableTwoFactor}
                </Button>
              </EmptyContent>
            </Empty>
          </CardContent>
        </Card>
      ) : (
        <Card>
          <CardContent className="flex flex-col gap-4">
            {isPending ? (
              <Skeleton className="h-5 w-48" />
            ) : (
              <p className="text-sm font-medium">
                {twoFactorLocalization.twoFactorEnabled}
              </p>
            )}

            <p className="text-muted-foreground text-sm">
              {twoFactorLocalization.twoFactorDescription}
            </p>

            {isEnabled && backupCodesEnabled && (
              <Button
                className="self-start"
                size="sm"
                variant="outline"
                onClick={() => setRegenerateOpen(true)}
              >
                {twoFactorLocalization.regenerateBackupCodes}
              </Button>
            )}
          </CardContent>
        </Card>
      )}

      <EnableTwoFactorDialog open={enableOpen} onOpenChange={setEnableOpen} />
      <DisableTwoFactorDialog
        open={disableOpen}
        onOpenChange={setDisableOpen}
      />
      <RegenerateBackupCodesDialog
        open={regenerateOpen}
        onOpenChange={setRegenerateOpen}
      />
    </div>
  )
}
