// apps/docs/src/components/auth/dash/activity.tsx
"use client"

import {
  type DashAuditLog,
  type DashAuthClient,
  formatDashEventName,
  getDashEventDetail,
  getDashEventKey,
  getDashEventLocation
} from "@better-auth-ui/core/plugins/dash"
import {
  hasMemberRole,
  type OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useDashAllAuditLogs,
  useDashAuditLogs,
  useDashUserAuditLogs
} from "@better-auth-ui/react/plugins/dash"
import { useActiveMemberRole } from "@better-auth-ui/react/plugins/organization"
import { keepPreviousData } from "@tanstack/react-query"
import {
  type ColumnFiltersState,
  columnFilteringFeature,
  createTableHook,
  functionalUpdate,
  globalFilteringFeature,
  type PaginationState,
  rowPaginationFeature,
  tableFeatures,
  type Updater
} from "@tanstack/react-table"
import {
  Activity,
  Building2,
  ChevronLeft,
  ChevronRight,
  MonitorDot,
  Search,
  ShieldCheck,
  UserRound,
  Users
} from "lucide-react"
import { Fragment, useDeferredValue, useMemo, useState } from "react"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle
} from "@/components/ui/empty"
import { Field, FieldLabel } from "@/components/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { dashPlugin } from "@/lib/auth/dash-plugin"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"

type ActivityAccess = "admin" | "admin-user" | "organization" | "user"

const { createAppColumnHelper, useAppTable: useActivityTable } =
  createTableHook({
    features: tableFeatures({
      columnFilteringFeature,
      globalFilteringFeature,
      rowPaginationFeature
    })
  })

const activityColumnHelper = createAppColumnHelper<DashAuditLog>()
const activityColumns = activityColumnHelper.columns([
  activityColumnHelper.accessor("eventType", { id: "eventType" })
])
const EMPTY_EVENTS: DashAuditLog[] = []

type ActivityFeedProps = {
  access: ActivityAccess
  organizationId?: string
  ready?: boolean
  className?: string
  userId?: string
}

export type AdminUserActivityProps = {
  className?: string
  userId: string
}

export type AdminActivityProps = { className?: string }

export type UserActivityProps = { className?: string }

export type OrganizationActivityProps = {
  className?: string
  organizationId: string
  organizationSlug: string
}

const generateN = (count: number) =>
  Array.from(
    { length: Math.max(0, Math.floor(count)) },
    (_, index) => index + 1
  )

const formatRelativeTime = (value: string) => {
  const date = new Date(value)
  const seconds = Math.floor((Date.now() - date.getTime()) / 1000)
  if (!Number.isFinite(seconds)) return value

  const formatter = new Intl.RelativeTimeFormat(undefined, { numeric: "auto" })
  const units: [Intl.RelativeTimeFormatUnit, number][] = [
    ["year", 31_536_000],
    ["month", 2_592_000],
    ["week", 604_800],
    ["day", 86_400],
    ["hour", 3_600],
    ["minute", 60],
    ["second", 1]
  ]

  for (const [unit, threshold] of units) {
    if (Math.abs(seconds) >= threshold) {
      return formatter.format(-Math.trunc(seconds / threshold), unit)
    }
  }

  return formatter.format(0, "second")
}

const getEventIcon = (eventType: string) => {
  if (
    eventType.includes("password") ||
    eventType.includes("two_factor") ||
    eventType.includes("banned") ||
    eventType === "user_sign_in_failed"
  ) {
    return ShieldCheck
  }
  if (eventType.startsWith("organization_member")) return Users
  if (eventType.startsWith("organization_")) return Building2
  if (eventType.includes("session") || eventType.includes("signed_")) {
    return MonitorDot
  }
  if (
    eventType.startsWith("user_") ||
    eventType.startsWith("profile_") ||
    eventType.startsWith("email_") ||
    eventType.startsWith("account_")
  ) {
    return UserRound
  }
  return Activity
}

function ActivityRow({ event }: { event: DashAuditLog }) {
  const { localization, showIpAddress } = useAuthPlugin(dashPlugin)
  const Icon = getEventIcon(event.eventType)
  const title =
    (localization.eventLabels as Record<string, string>)[event.eventType] ??
    formatDashEventName(event.eventType) ??
    localization.unknownEvent
  const detail = getDashEventDetail(event)
  const location = getDashEventLocation(event, showIpAddress)
  const absoluteTime = new Date(event.createdAt).toLocaleString()

  return (
    <li className="flex items-start gap-3 py-4 first:pt-0 last:pb-0">
      <div className="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground">
        <Icon className="size-4" />
      </div>
      <div className="flex min-w-0 flex-1 flex-col gap-1">
        <div className="flex flex-col gap-0.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-3">
          <p className="truncate text-sm font-medium">{title}</p>
          <time
            className="shrink-0 text-xs text-muted-foreground"
            dateTime={event.createdAt}
            title={absoluteTime}
          >
            {formatRelativeTime(event.createdAt)}
          </time>
        </div>
        {(detail || location) && (
          <p className="truncate text-xs text-muted-foreground">
            {[detail, location].filter(Boolean).join(" · ")}
          </p>
        )}
      </div>
    </li>
  )
}

function ActivityRowSkeleton() {
  return (
    <li className="flex items-start gap-3 py-4 first:pt-0 last:pb-0">
      <Skeleton className="size-9 shrink-0 rounded-lg" />
      <div className="flex min-w-0 flex-1 flex-col gap-2 pt-0.5">
        <Skeleton className="h-4 w-36" />
        <Skeleton className="h-3 w-52 max-w-full" />
      </div>
    </li>
  )
}

function ActivityFeed({
  access,
  organizationId,
  ready = true,
  className,
  userId
}: ActivityFeedProps) {
  const { authClient } = useAuth()
  const { localization, pageSize } = useAuthPlugin(dashPlugin)
  const [pagination, setPaginationState] = useState<PaginationState>({
    pageIndex: 0,
    pageSize
  })
  const [columnFilters, setColumnFiltersState] = useState<ColumnFiltersState>(
    []
  )
  const [globalFilter, setGlobalFilterState] = useState("")
  const eventType = String(
    columnFilters.find((filter) => filter.id === "eventType")?.value ?? "all"
  )
  const deferredIdentifier = useDeferredValue(globalFilter.trim())
  const eventOptions = useMemo(
    () => Object.entries(localization.eventLabels),
    [localization.eventLabels]
  )
  const offset = pagination.pageIndex * pagination.pageSize
  const params = {
    eventType: eventType === "all" ? undefined : eventType,
    identifier: deferredIdentifier || undefined,
    limit: pagination.pageSize,
    offset,
    organizationId
  }
  const userQuery = useDashAuditLogs(authClient as DashAuthClient, {
    enabled: ready && access === "user",
    params,
    placeholderData: keepPreviousData
  })
  const organizationQuery = useDashAllAuditLogs(authClient as DashAuthClient, {
    enabled: ready && (access === "admin" || access === "organization"),
    params,
    placeholderData: keepPreviousData
  })
  const adminUserQuery = useDashUserAuditLogs(
    authClient as DashAuthClient,
    userId,
    {
      enabled: ready && access === "admin-user",
      params: {
        eventType: params.eventType,
        identifier: params.identifier,
        limit: pagination.pageSize,
        offset
      }
    }
  )
  const query =
    access === "admin" || access === "organization"
      ? organizationQuery
      : access === "admin-user"
        ? adminUserQuery
        : userQuery
  const { data, error, isFetching, isPending } = query
  const showPending = !ready || isPending
  const pageEnd = offset + (data?.events.length ?? 0)
  const setPagination = (updater: Updater<PaginationState>) =>
    setPaginationState((current) => functionalUpdate(updater, current))
  const setColumnFilters = (updater: Updater<ColumnFiltersState>) => {
    setColumnFiltersState((current) => functionalUpdate(updater, current))
    setPaginationState((current) => ({ ...current, pageIndex: 0 }))
  }
  const setGlobalFilter = (updater: Updater<string>) => {
    setGlobalFilterState((current) => functionalUpdate(updater, current))
    setPaginationState((current) => ({ ...current, pageIndex: 0 }))
  }
  const table = useActivityTable({
    columns: activityColumns,
    data: data?.events ?? EMPTY_EVENTS,
    getRowId: getDashEventKey,
    manualFiltering: true,
    manualPagination: true,
    rowCount: data?.total ?? 0,
    state: { columnFilters, globalFilter, pagination },
    onColumnFiltersChange: setColumnFilters,
    onGlobalFilterChange: setGlobalFilter,
    onPaginationChange: setPagination
  })

  return (
    <Card
      className={cn("w-full", className)}
      aria-busy={showPending || isFetching}
    >
      <CardHeader>
        <CardTitle>{localization.activity}</CardTitle>
        <CardDescription>
          {access === "admin"
            ? localization.adminActivityDescription
            : access === "admin-user"
              ? localization.adminUserActivityDescription
              : organizationId
                ? localization.organizationActivityDescription
                : localization.activityDescription}
        </CardDescription>
        {organizationId && (
          <CardAction>
            <Badge variant="secondary">
              {access === "organization"
                ? localization.organizationWide
                : localization.personalOnly}
            </Badge>
          </CardAction>
        )}
      </CardHeader>

      <CardContent className="flex flex-col gap-4">
        <div className="grid gap-2 sm:grid-cols-[12rem_minmax(14rem,1fr)]">
          <Field>
            <FieldLabel htmlFor="dash-event-type">
              {localization.eventType}
            </FieldLabel>
            <Select
              value={eventType}
              onValueChange={(value) => {
                table
                  .getColumn("eventType")
                  ?.setFilterValue(value === "all" ? undefined : value)
              }}
            >
              <SelectTrigger id="dash-event-type" className="w-full">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">{localization.allEvents}</SelectItem>
                {eventOptions.map(([key, label]) => (
                  <SelectItem key={key} value={key}>
                    {label}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </Field>
          <Field>
            <FieldLabel htmlFor="dash-identifier">
              {localization.identifier}
            </FieldLabel>
            <InputGroup>
              <InputGroupAddon>
                <Search />
              </InputGroupAddon>
              <InputGroupInput
                id="dash-identifier"
                onChange={(event) => {
                  table.setGlobalFilter(event.target.value)
                }}
                placeholder={localization.identifierPlaceholder}
                value={globalFilter}
              />
            </InputGroup>
          </Field>
        </div>
        {showPending ? (
          <ul>
            {generateN(3).map((skeletonId, position) => (
              <Fragment key={skeletonId}>
                {position > 0 && <Separator />}
                <ActivityRowSkeleton />
              </Fragment>
            ))}
          </ul>
        ) : error ? (
          <Empty className="min-h-48 border-0 p-4">
            <EmptyHeader>
              <EmptyMedia variant="icon">
                <Activity />
              </EmptyMedia>
              <EmptyTitle>{localization.activityLoadError}</EmptyTitle>
              <EmptyDescription>
                {localization.activityLoadErrorDescription}
              </EmptyDescription>
            </EmptyHeader>
            <EmptyContent>
              <Button
                size="sm"
                variant="outline"
                onClick={() => query.refetch()}
              >
                {localization.retry}
              </Button>
            </EmptyContent>
          </Empty>
        ) : data?.events.length ? (
          <ul>
            {table.getRowModel().rows.map((row, position) => (
              <Fragment key={row.id}>
                {position > 0 && <Separator />}
                <ActivityRow event={row.original} />
              </Fragment>
            ))}
          </ul>
        ) : (
          <Empty className="min-h-48 border-0 p-4">
            <EmptyHeader>
              <EmptyMedia variant="icon">
                <Activity />
              </EmptyMedia>
              <EmptyTitle>{localization.noActivity}</EmptyTitle>
              <EmptyDescription>
                {localization.noActivityDescription}
              </EmptyDescription>
            </EmptyHeader>
          </Empty>
        )}
      </CardContent>

      {!error && !!data?.total && (
        <CardFooter className="justify-between gap-3">
          <div className="flex items-center gap-2">
            <p className="text-xs tabular-nums text-muted-foreground">
              {localization.paginationRange
                .replace("{{from}}", String(offset + 1))
                .replace("{{to}}", String(pageEnd))
                .replace("{{total}}", String(data.total))}
            </p>
            {isFetching && <Spinner />}
          </div>
          <div className="flex gap-1">
            <Button
              aria-label={localization.previousPage}
              disabled={isFetching || !table.getCanPreviousPage()}
              size="icon-sm"
              variant="ghost"
              onClick={() => table.previousPage()}
            >
              <ChevronLeft />
            </Button>
            <Button
              aria-label={localization.nextPage}
              disabled={isFetching || !table.getCanNextPage()}
              size="icon-sm"
              variant="ghost"
              onClick={() => table.nextPage()}
            >
              <ChevronRight />
            </Button>
          </div>
        </CardFooter>
      )}
    </Card>
  )
}

/** Authentication and account activity for a user selected by an administrator. */
export function AdminUserActivity(props: AdminUserActivityProps) {
  return <ActivityFeed key={props.userId} access="admin-user" {...props} />
}

/** Activity across every organization the current owner or administrator can manage. */
export function AdminActivity(props: AdminActivityProps) {
  return <ActivityFeed access="admin" {...props} />
}

/** Personal authentication and account activity. */
export function UserActivity(props: UserActivityProps) {
  return <ActivityFeed access="user" {...props} />
}

/** Activity for an explicit organization. */
export function OrganizationActivity({
  organizationId,
  organizationSlug: _organizationSlug,
  ...props
}: OrganizationActivityProps) {
  const { authClient } = useAuth()
  const { creatorRole } = useAuthPlugin(organizationPlugin)
  const { data: memberRole, isPending } = useActiveMemberRole(
    authClient as OrganizationAuthClient,
    { query: { organizationId } }
  )
  const canViewOrganization =
    hasMemberRole(memberRole?.role, creatorRole) ||
    hasMemberRole(memberRole?.role, "admin")

  if (isPending) {
    return (
      <ActivityFeed
        key={organizationId}
        access="user"
        organizationId={organizationId}
        ready={false}
        {...props}
      />
    )
  }

  return (
    <ActivityFeed
      key={organizationId}
      access={canViewOrganization ? "organization" : "user"}
      organizationId={organizationId}
      {...props}
    />
  )
}

// examples/start-solid-zaidan-example/src/components/auth/dash/activity.tsx
import {
  type DashAuditLog,
  type DashAuthClient,
  formatDashEventName,
  getDashEventDetail,
  getDashEventKey,
  getDashEventLocation
} from "@better-auth-ui/core/plugins/dash"
import {
  hasMemberRole,
  type OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import {
  useDashAllAuditLogs,
  useDashAuditLogs,
  useDashUserAuditLogs
} from "@better-auth-ui/solid/plugins/dash"
import { useActiveMemberRole } from "@better-auth-ui/solid/plugins/organization"
import { keepPreviousData } from "@tanstack/solid-query"
import {
  type ColumnFiltersState,
  columnFilteringFeature,
  createTableHook,
  functionalUpdate,
  globalFilteringFeature,
  type PaginationState,
  rowPaginationFeature,
  tableFeatures,
  type Updater
} from "@tanstack/solid-table"
import {
  Activity,
  Building2,
  ChevronLeft,
  ChevronRight,
  MonitorDot,
  Search,
  ShieldCheck,
  UserRound,
  Users
} from "lucide-solid"
import {
  createDeferred,
  createEffect,
  createMemo,
  createSignal,
  For,
  on,
  Show
} from "solid-js"
import { Dynamic } from "solid-js/web"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardAction,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import {
  Empty,
  EmptyContent,
  EmptyDescription,
  EmptyHeader,
  EmptyMedia,
  EmptyTitle
} from "@/components/ui/empty"
import { Field, FieldLabel } from "@/components/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { dashPlugin } from "@/lib/auth/dash-plugin"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"

type ActivityAccess = "admin" | "admin-user" | "organization" | "user"

const { createAppColumnHelper, createAppTable: createActivityTable } =
  createTableHook({
    features: tableFeatures({
      columnFilteringFeature,
      globalFilteringFeature,
      rowPaginationFeature
    })
  })

const activityColumnHelper = createAppColumnHelper<DashAuditLog>()
const activityColumns = activityColumnHelper.columns([
  activityColumnHelper.accessor("eventType", { id: "eventType" })
])
const EMPTY_EVENTS: DashAuditLog[] = []

type ActivityFeedProps = {
  access: ActivityAccess
  organizationId?: string
  ready?: boolean
  class?: string
  userId?: string
}

export type AdminUserActivityProps = {
  class?: string
  userId: string
}

export type AdminActivityProps = { class?: string }

export type UserActivityProps = { class?: string }

export type OrganizationActivityProps = {
  class?: string
  organizationId: string
  organizationSlug: string
}

const generateN = (count: number) =>
  Array.from(
    { length: Math.max(0, Math.floor(count)) },
    (_, index) => index + 1
  )

const formatRelativeTime = (value: string) => {
  const date = new Date(value)
  const seconds = Math.floor((Date.now() - date.getTime()) / 1000)
  if (!Number.isFinite(seconds)) return value

  const formatter = new Intl.RelativeTimeFormat(undefined, { numeric: "auto" })
  const units: [Intl.RelativeTimeFormatUnit, number][] = [
    ["year", 31_536_000],
    ["month", 2_592_000],
    ["week", 604_800],
    ["day", 86_400],
    ["hour", 3_600],
    ["minute", 60],
    ["second", 1]
  ]

  for (const [unit, threshold] of units) {
    if (Math.abs(seconds) >= threshold) {
      return formatter.format(-Math.trunc(seconds / threshold), unit)
    }
  }

  return formatter.format(0, "second")
}

const getEventIcon = (eventType: string) => {
  if (
    eventType.includes("password") ||
    eventType.includes("two_factor") ||
    eventType.includes("banned") ||
    eventType === "user_sign_in_failed"
  ) {
    return ShieldCheck
  }
  if (eventType.startsWith("organization_member")) return Users
  if (eventType.startsWith("organization_")) return Building2
  if (eventType.includes("session") || eventType.includes("signed_")) {
    return MonitorDot
  }
  if (
    eventType.startsWith("user_") ||
    eventType.startsWith("profile_") ||
    eventType.startsWith("email_") ||
    eventType.startsWith("account_")
  ) {
    return UserRound
  }
  return Activity
}

function ActivityRow(props: { event: DashAuditLog }) {
  const { localization, showIpAddress } = useAuthPlugin(dashPlugin)
  const title = () =>
    (localization.eventLabels as Record<string, string>)[
      props.event.eventType
    ] ??
    formatDashEventName(props.event.eventType) ??
    localization.unknownEvent
  const detail = () => getDashEventDetail(props.event)
  const location = () => getDashEventLocation(props.event, showIpAddress)
  const metadata = () => [detail(), location()].filter(Boolean).join(" · ")
  const absoluteTime = () => new Date(props.event.createdAt).toLocaleString()

  return (
    <li class="flex items-start gap-3 py-4 first:pt-0 last:pb-0">
      <div class="flex size-9 shrink-0 items-center justify-center rounded-lg bg-muted text-muted-foreground">
        <Dynamic
          component={getEventIcon(props.event.eventType)}
          class="size-4"
        />
      </div>
      <div class="flex min-w-0 flex-1 flex-col gap-1">
        <div class="flex flex-col gap-0.5 sm:flex-row sm:items-baseline sm:justify-between sm:gap-3">
          <p class="truncate text-sm font-medium">{title()}</p>
          <time
            class="shrink-0 text-xs text-muted-foreground"
            dateTime={props.event.createdAt}
            title={absoluteTime()}
          >
            {formatRelativeTime(props.event.createdAt)}
          </time>
        </div>
        <Show when={metadata()}>
          <p class="truncate text-xs text-muted-foreground">{metadata()}</p>
        </Show>
      </div>
    </li>
  )
}

function ActivityRowSkeleton() {
  return (
    <li class="flex items-start gap-3 py-4 first:pt-0 last:pb-0">
      <Skeleton class="size-9 shrink-0 rounded-lg" />
      <div class="flex min-w-0 flex-1 flex-col gap-2 pt-0.5">
        <Skeleton class="h-4 w-36" />
        <Skeleton class="h-3 w-52 max-w-full" />
      </div>
    </li>
  )
}

function ActivityFeed(props: ActivityFeedProps) {
  const auth = useAuth()
  const { localization, pageSize } = useAuthPlugin(dashPlugin)
  const [pagination, setPaginationState] = createSignal<PaginationState>({
    pageIndex: 0,
    pageSize
  })
  const [columnFilters, setColumnFiltersState] =
    createSignal<ColumnFiltersState>([])
  const [globalFilter, setGlobalFilterState] = createSignal("")
  const eventType = () =>
    String(
      columnFilters().find((filter) => filter.id === "eventType")?.value ??
        "all"
    )
  const deferredIdentifier = createDeferred(() => globalFilter().trim())
  const eventOptions = createMemo(() =>
    Object.entries(localization.eventLabels)
  )
  createEffect(
    on(
      () => [props.access, props.organizationId, props.userId] as const,
      () => setPaginationState((current) => ({ ...current, pageIndex: 0 })),
      { defer: true }
    )
  )
  const offset = () => pagination().pageIndex * pagination().pageSize
  const params = () => ({
    eventType: eventType() === "all" ? undefined : eventType(),
    identifier: deferredIdentifier() || undefined,
    limit: pagination().pageSize,
    offset: offset(),
    organizationId: props.organizationId
  })
  const userQuery = useDashAuditLogs(auth.authClient as DashAuthClient, () => ({
    enabled: (props.ready ?? true) && props.access === "user",
    params: params(),
    placeholderData: keepPreviousData
  }))
  const organizationQuery = useDashAllAuditLogs(
    auth.authClient as DashAuthClient,
    () => ({
      enabled:
        (props.ready ?? true) &&
        (props.access === "admin" || props.access === "organization"),
      params: params(),
      placeholderData: keepPreviousData
    })
  )
  const adminUserQuery = useDashUserAuditLogs(
    auth.authClient as DashAuthClient,
    () => props.userId,
    () => ({
      enabled: (props.ready ?? true) && props.access === "admin-user",
      params: {
        eventType: params().eventType,
        identifier: params().identifier,
        limit: pagination().pageSize,
        offset: offset()
      }
    })
  )
  const query = () =>
    props.access === "admin" || props.access === "organization"
      ? organizationQuery
      : props.access === "admin-user"
        ? adminUserQuery
        : userQuery
  const showPending = () => !(props.ready ?? true) || query().isPending
  const pageEnd = () => offset() + (query().data?.events.length ?? 0)
  const setPagination = (updater: Updater<PaginationState>) =>
    setPaginationState((current) => functionalUpdate(updater, current))
  const setColumnFilters = (updater: Updater<ColumnFiltersState>) => {
    setColumnFiltersState((current) => functionalUpdate(updater, current))
    setPaginationState((current) => ({ ...current, pageIndex: 0 }))
  }
  const setGlobalFilter = (updater: Updater<string>) => {
    setGlobalFilterState((current) => functionalUpdate(updater, current))
    setPaginationState((current) => ({ ...current, pageIndex: 0 }))
  }
  const table = createActivityTable({
    columns: activityColumns,
    get data() {
      return query().data?.events ?? EMPTY_EVENTS
    },
    get rowCount() {
      return query().data?.total ?? 0
    },
    get state() {
      return {
        columnFilters: columnFilters(),
        globalFilter: globalFilter(),
        pagination: pagination()
      }
    },
    getRowId: getDashEventKey,
    manualFiltering: true,
    manualPagination: true,
    onColumnFiltersChange: setColumnFilters,
    onGlobalFilterChange: setGlobalFilter,
    onPaginationChange: setPagination
  })

  return (
    <Card
      aria-busy={showPending() || query().isFetching}
      class={cn("w-full", props.class)}
    >
      <CardHeader>
        <CardTitle>{localization.activity}</CardTitle>
        <CardDescription>
          {props.access === "admin"
            ? localization.adminActivityDescription
            : props.access === "admin-user"
              ? localization.adminUserActivityDescription
              : props.organizationId
                ? localization.organizationActivityDescription
                : localization.activityDescription}
        </CardDescription>
        <Show when={props.organizationId}>
          <CardAction>
            <Badge variant="secondary">
              {props.access === "organization"
                ? localization.organizationWide
                : localization.personalOnly}
            </Badge>
          </CardAction>
        </Show>
      </CardHeader>

      <CardContent class="flex flex-col gap-4">
        <div class="grid gap-2 sm:grid-cols-[12rem_minmax(14rem,1fr)]">
          <Field>
            <FieldLabel for="solid-dash-event-type">
              {localization.eventType}
            </FieldLabel>
            <NativeSelect
              id="solid-dash-event-type"
              onChange={(event) => {
                const value = event.currentTarget.value
                table
                  .getColumn("eventType")
                  ?.setFilterValue(value === "all" ? undefined : value)
              }}
              value={eventType()}
            >
              <NativeSelectOption value="all">
                {localization.allEvents}
              </NativeSelectOption>
              <For each={eventOptions()}>
                {([key, label]) => (
                  <NativeSelectOption value={key}>{label}</NativeSelectOption>
                )}
              </For>
            </NativeSelect>
          </Field>
          <Field>
            <FieldLabel for="solid-dash-identifier">
              {localization.identifier}
            </FieldLabel>
            <InputGroup>
              <InputGroupAddon>
                <Search />
              </InputGroupAddon>
              <InputGroupInput
                id="solid-dash-identifier"
                onInput={(event) => {
                  table.setGlobalFilter(event.currentTarget.value)
                }}
                placeholder={localization.identifierPlaceholder}
                value={globalFilter()}
              />
            </InputGroup>
          </Field>
        </div>
        <Show
          when={!showPending()}
          fallback={
            <ul>
              <For each={generateN(3)}>
                {(_skeletonId, position) => (
                  <>
                    <Show when={position() > 0}>
                      <Separator />
                    </Show>
                    <ActivityRowSkeleton />
                  </>
                )}
              </For>
            </ul>
          }
        >
          <Show
            when={!query().error}
            fallback={
              <Empty class="min-h-48 gap-4 p-4">
                <EmptyHeader class="gap-2">
                  <EmptyMedia variant="icon">
                    <Activity />
                  </EmptyMedia>
                  <EmptyTitle>{localization.activityLoadError}</EmptyTitle>
                  <EmptyDescription>
                    {localization.activityLoadErrorDescription}
                  </EmptyDescription>
                </EmptyHeader>
                <EmptyContent class="gap-2.5">
                  <Button
                    onClick={() => query().refetch()}
                    size="sm"
                    variant="outline"
                  >
                    {localization.retry}
                  </Button>
                </EmptyContent>
              </Empty>
            }
          >
            <Show
              when={query().data?.events.length}
              fallback={
                <Empty class="min-h-48 gap-4 p-4">
                  <EmptyHeader class="gap-2">
                    <EmptyMedia variant="icon">
                      <Activity />
                    </EmptyMedia>
                    <EmptyTitle>{localization.noActivity}</EmptyTitle>
                    <EmptyDescription>
                      {localization.noActivityDescription}
                    </EmptyDescription>
                  </EmptyHeader>
                </Empty>
              }
            >
              <ul>
                <For each={table.getRowModel().rows}>
                  {(row, position) => (
                    <>
                      <Show when={position() > 0}>
                        <Separator />
                      </Show>
                      <ActivityRow event={row.original} />
                    </>
                  )}
                </For>
              </ul>
            </Show>
          </Show>
        </Show>
      </CardContent>

      <Show when={!query().error && !!query().data?.total}>
        <CardFooter class="justify-between gap-3">
          <div class="flex items-center gap-2">
            <p class="text-xs tabular-nums text-muted-foreground">
              {localization.paginationRange
                .replace("{{from}}", String(offset() + 1))
                .replace("{{to}}", String(pageEnd()))
                .replace("{{total}}", String(query().data?.total ?? 0))}
            </p>
            <Show when={query().isFetching}>
              <Spinner />
            </Show>
          </div>
          <div class="flex gap-1">
            <Button
              aria-label={localization.previousPage}
              disabled={query().isFetching || !table.getCanPreviousPage()}
              onClick={() => table.previousPage()}
              size="icon-sm"
              variant="ghost"
            >
              <ChevronLeft />
            </Button>
            <Button
              aria-label={localization.nextPage}
              disabled={query().isFetching || !table.getCanNextPage()}
              onClick={() => table.nextPage()}
              size="icon-sm"
              variant="ghost"
            >
              <ChevronRight />
            </Button>
          </div>
        </CardFooter>
      </Show>
    </Card>
  )
}

/** Authentication and account activity for a user selected by an administrator. */
export function AdminUserActivity(props: AdminUserActivityProps) {
  return <ActivityFeed access="admin-user" {...props} />
}

/** Activity across every organization the current owner or administrator can manage. */
export function AdminActivity(props: AdminActivityProps) {
  return <ActivityFeed access="admin" {...props} />
}

/** Personal authentication and account activity. */
export function UserActivity(props: UserActivityProps) {
  return <ActivityFeed access="user" {...props} />
}

/** Activity for an explicit organization. */
export function OrganizationActivity(props: OrganizationActivityProps) {
  const auth = useAuth()
  const { creatorRole } = useAuthPlugin(organizationPlugin)
  const memberRole = useActiveMemberRole(
    auth.authClient as OrganizationAuthClient,
    () => ({ query: { organizationId: props.organizationId } })
  )
  const canViewOrganization = () =>
    hasMemberRole(memberRole.data?.role, creatorRole) ||
    hasMemberRole(memberRole.data?.role, "admin")

  return (
    <Show
      when={!memberRole.isPending}
      fallback={
        <ActivityFeed
          access="user"
          class={props.class}
          organizationId={props.organizationId}
          ready={false}
        />
      }
    >
      <ActivityFeed
        access={canViewOrganization() ? "organization" : "user"}
        class={props.class}
        organizationId={props.organizationId}
      />
    </Show>
  )
}
