// packages/heroui/src/components/auth/phone-number/international-phone-field.tsx
import {
  createPhoneNumberValue,
  getPhoneNumberCountries,
  type PhoneNumberAdapter,
  type PhoneNumberCountryCode,
  type PhoneNumberValue
} from "@better-auth-ui/core/plugins/phone-number"
import {
  FieldError,
  Input,
  Label,
  ListBox,
  Select,
  TextField
} from "@heroui/react"
import { useMemo } from "react"

type InternationalPhoneFieldProps = {
  adapter: PhoneNumberAdapter
  countryLabel: string
  countryCodes?: readonly PhoneNumberCountryCode[]
  error?: string
  isDisabled?: boolean
  locale?: string
  name?: string
  phoneLabel: string
  placeholder: string
  value: PhoneNumberValue
  variant?: "primary" | "secondary"
  onChange: (value: PhoneNumberValue) => void
}

export function InternationalPhoneField({
  adapter,
  countryLabel,
  countryCodes,
  error,
  isDisabled,
  locale,
  name = "phoneNumber",
  phoneLabel,
  placeholder,
  value,
  variant,
  onChange
}: InternationalPhoneFieldProps) {
  const countries = useMemo(
    () => getPhoneNumberCountries(locale, countryCodes),
    [countryCodes, locale]
  )
  const selectedCountry = countries.find(
    (country) => country.code === value.country
  )

  return (
    <div className="grid grid-cols-[8.5rem_minmax(0,1fr)] gap-2">
      <Select
        aria-label={countryLabel}
        isDisabled={isDisabled}
        value={value.country}
        onChange={(country) => {
          if (!country) return
          const nextCountry = country as PhoneNumberCountryCode
          const input = value.display.startsWith("+") ? "" : value.display
          onChange(createPhoneNumberValue(input, nextCountry, adapter))
        }}
      >
        <Label>{countryLabel}</Label>
        <Select.Trigger>
          <Select.Value>
            {selectedCountry ? (
              <span className="flex items-center gap-2">
                <span aria-hidden="true">{selectedCountry.flag}</span>
                <span>{selectedCountry.callingCode}</span>
              </span>
            ) : null}
          </Select.Value>
          <Select.Indicator />
        </Select.Trigger>
        <Select.Popover>
          <ListBox>
            {countries.map((country) => (
              <ListBox.Item
                key={country.code}
                id={country.code}
                textValue={`${country.label} ${country.callingCode}`}
              >
                <span className="flex w-full items-center justify-between gap-4">
                  <span className="flex min-w-0 items-center gap-2">
                    <span aria-hidden="true">{country.flag}</span>
                    <span>{country.label}</span>
                  </span>
                  <span className="text-muted">{country.callingCode}</span>
                </span>
                <ListBox.ItemIndicator />
              </ListBox.Item>
            ))}
          </ListBox>
        </Select.Popover>
      </Select>
      <TextField
        name={name}
        type="tel"
        autoComplete="tel-national"
        isDisabled={isDisabled}
        isInvalid={Boolean(error)}
        value={value.display}
        onChange={(input) =>
          onChange(createPhoneNumberValue(input, value.country, adapter))
        }
      >
        <Label>{phoneLabel}</Label>
        <Input
          inputMode="tel"
          placeholder={placeholder}
          required
          variant={variant}
        />
        <FieldError>{error}</FieldError>
      </TextField>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/phone-number/international-phone-field.tsx
import {
  createPhoneNumberValue,
  getPhoneNumberCountries,
  type PhoneNumberAdapter,
  type PhoneNumberCountry,
  type PhoneNumberCountryCode,
  type PhoneNumberValue
} from "@better-auth-ui/core/plugins/phone-number"
import { createMemo, createUniqueId } from "solid-js"

import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"

type InternationalPhoneFieldProps = {
  adapter: PhoneNumberAdapter
  countryLabel: string
  countryCodes?: readonly PhoneNumberCountryCode[]
  disabled?: boolean
  error?: string
  locale?: string
  name?: string
  phoneLabel: string
  placeholder: string
  value: PhoneNumberValue
  onChange: (value: PhoneNumberValue) => void
}

export function InternationalPhoneField(props: InternationalPhoneFieldProps) {
  const id = createUniqueId()
  const countries = createMemo(() =>
    getPhoneNumberCountries(props.locale, props.countryCodes)
  )

  return (
    <div class="grid grid-cols-[8.5rem_minmax(0,1fr)] gap-2">
      <Field>
        <FieldLabel for={`${id}-country`}>{props.countryLabel}</FieldLabel>
        <Select<PhoneNumberCountry>
          disabled={props.disabled}
          itemComponent={(itemProps) => (
            <SelectItem item={itemProps.item}>
              <span class="flex w-full items-center justify-between gap-4">
                <span class="flex min-w-0 items-center gap-2">
                  <span aria-hidden="true">{itemProps.item.rawValue.flag}</span>
                  <span>{itemProps.item.rawValue.label}</span>
                </span>
                <span class="text-muted-foreground">
                  {itemProps.item.rawValue.callingCode}
                </span>
              </span>
            </SelectItem>
          )}
          onChange={(country) => {
            if (!country) return
            const input = props.value.display.startsWith("+")
              ? ""
              : props.value.display
            props.onChange(
              createPhoneNumberValue(input, country.code, props.adapter)
            )
          }}
          options={countries()}
          optionTextValue="label"
          optionValue="code"
          value={countries().find(
            (country) => country.code === props.value.country
          )}
        >
          <SelectTrigger id={`${id}-country`} class="w-full">
            <SelectValue<PhoneNumberCountry>>
              {(state) => {
                const country = state.selectedOption()

                return country ? (
                  <span class="flex items-center gap-2">
                    <span aria-hidden="true">{country.flag}</span>
                    <span>{country.callingCode}</span>
                  </span>
                ) : null
              }}
            </SelectValue>
          </SelectTrigger>
          <SelectContent />
        </Select>
      </Field>
      <Field data-invalid={Boolean(props.error)}>
        <FieldLabel for={`${id}-number`}>{props.phoneLabel}</FieldLabel>
        <Input
          id={`${id}-number`}
          aria-invalid={Boolean(props.error)}
          autocomplete="tel-national"
          disabled={props.disabled}
          inputmode="tel"
          name={props.name ?? "phoneNumber"}
          placeholder={props.placeholder}
          required
          type="tel"
          value={props.value.display}
          onInput={(event) =>
            props.onChange(
              createPhoneNumberValue(
                event.currentTarget.value,
                props.value.country,
                props.adapter
              )
            )
          }
        />
        <FieldError>{props.error}</FieldError>
      </Field>
    </div>
  )
}
