// examples/start-shadcn-baseui-example/src/components/auth/phone-number/international-phone-field.tsx
"use client"

import {
  createPhoneNumberValue,
  getPhoneNumberCountries,
  type PhoneNumberAdapter,
  type PhoneNumberCountryCode,
  type PhoneNumberValue
} from "@better-auth-ui/core/plugins/phone-number"
import { useId, useMemo } from "react"

import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"

type InternationalPhoneFieldProps = {
  adapter: PhoneNumberAdapter
  countryLabel: string
  countryCodes?: readonly PhoneNumberCountryCode[]
  disabled?: boolean
  error?: string
  locale?: string
  name?: string
  phoneLabel: string
  placeholder: string
  value: PhoneNumberValue
  onChange: (value: PhoneNumberValue) => void
}

export function InternationalPhoneField({
  adapter,
  countryLabel,
  countryCodes,
  disabled,
  error,
  locale,
  name = "phoneNumber",
  phoneLabel,
  placeholder,
  value,
  onChange
}: InternationalPhoneFieldProps) {
  const id = useId()
  const countries = useMemo(
    () => getPhoneNumberCountries(locale, countryCodes),
    [countryCodes, locale]
  )
  const countryItems = countries.map((country) => ({
    label: `${country.label} ${country.callingCode}`,
    value: country.code
  }))

  return (
    <div className="grid grid-cols-[8.5rem_minmax(0,1fr)] gap-2">
      <Field>
        <FieldLabel htmlFor={`${id}-country`}>{countryLabel}</FieldLabel>
        <Select
          items={countryItems}
          disabled={disabled}
          value={value.country}
          onValueChange={(country) => {
            if (!country) return
            const nextCountry = country as PhoneNumberCountryCode
            const input = value.display.startsWith("+") ? "" : value.display
            onChange(createPhoneNumberValue(input, nextCountry, adapter))
          }}
        >
          <SelectTrigger id={`${id}-country`} className="w-full">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectGroup>
              {countries.map((country) => (
                <SelectItem key={country.code} value={country.code}>
                  <span className="flex w-full items-center justify-between gap-4">
                    <span>{country.label}</span>
                    <span className="text-muted-foreground">
                      {country.callingCode}
                    </span>
                  </span>
                </SelectItem>
              ))}
            </SelectGroup>
          </SelectContent>
        </Select>
      </Field>
      <Field data-invalid={Boolean(error)}>
        <FieldLabel htmlFor={`${id}-number`}>{phoneLabel}</FieldLabel>
        <Input
          id={`${id}-number`}
          aria-invalid={Boolean(error)}
          autoComplete="tel-national"
          disabled={disabled}
          inputMode="tel"
          name={name}
          placeholder={placeholder}
          required
          type="tel"
          value={value.display}
          onChange={(event) =>
            onChange(
              createPhoneNumberValue(event.target.value, value.country, adapter)
            )
          }
        />
        <FieldError>{error}</FieldError>
      </Field>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/phone-number/international-phone-field.tsx
import {
  createPhoneNumberValue,
  getPhoneNumberCountries,
  type PhoneNumberAdapter,
  type PhoneNumberCountry,
  type PhoneNumberCountryCode,
  type PhoneNumberValue
} from "@better-auth-ui/core/plugins/phone-number"
import { createMemo, createUniqueId } from "solid-js"

import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"

type InternationalPhoneFieldProps = {
  adapter: PhoneNumberAdapter
  countryLabel: string
  countryCodes?: readonly PhoneNumberCountryCode[]
  disabled?: boolean
  error?: string
  locale?: string
  name?: string
  phoneLabel: string
  placeholder: string
  value: PhoneNumberValue
  onChange: (value: PhoneNumberValue) => void
}

export function InternationalPhoneField(props: InternationalPhoneFieldProps) {
  const id = createUniqueId()
  const countries = createMemo(() =>
    getPhoneNumberCountries(props.locale, props.countryCodes)
  )

  return (
    <div class="grid grid-cols-[8.5rem_minmax(0,1fr)] gap-2">
      <Field>
        <FieldLabel for={`${id}-country`}>{props.countryLabel}</FieldLabel>
        <Select<PhoneNumberCountry>
          disabled={props.disabled}
          itemComponent={(itemProps) => (
            <SelectItem item={itemProps.item}>
              <span class="flex w-full items-center justify-between gap-4">
                <span class="flex min-w-0 items-center gap-2">
                  <span aria-hidden="true">{itemProps.item.rawValue.flag}</span>
                  <span>{itemProps.item.rawValue.label}</span>
                </span>
                <span class="text-muted-foreground">
                  {itemProps.item.rawValue.callingCode}
                </span>
              </span>
            </SelectItem>
          )}
          onChange={(country) => {
            if (!country) return
            const input = props.value.display.startsWith("+")
              ? ""
              : props.value.display
            props.onChange(
              createPhoneNumberValue(input, country.code, props.adapter)
            )
          }}
          options={countries()}
          optionTextValue="label"
          optionValue="code"
          value={countries().find(
            (country) => country.code === props.value.country
          )}
        >
          <SelectTrigger id={`${id}-country`} class="w-full">
            <SelectValue<PhoneNumberCountry>>
              {(state) => {
                const country = state.selectedOption()

                return country ? (
                  <span class="flex items-center gap-2">
                    <span aria-hidden="true">{country.flag}</span>
                    <span>{country.callingCode}</span>
                  </span>
                ) : null
              }}
            </SelectValue>
          </SelectTrigger>
          <SelectContent />
        </Select>
      </Field>
      <Field data-invalid={Boolean(props.error)}>
        <FieldLabel for={`${id}-number`}>{props.phoneLabel}</FieldLabel>
        <Input
          id={`${id}-number`}
          aria-invalid={Boolean(props.error)}
          autocomplete="tel-national"
          disabled={props.disabled}
          inputmode="tel"
          name={props.name ?? "phoneNumber"}
          placeholder={props.placeholder}
          required
          type="tel"
          value={props.value.display}
          onInput={(event) =>
            props.onChange(
              createPhoneNumberValue(
                event.currentTarget.value,
                props.value.country,
                props.adapter
              )
            )
          }
        />
        <FieldError>{props.error}</FieldError>
      </Field>
    </div>
  )
}
