// packages/heroui/src/components/auth/phone-number/remove-phone-number-dialog.tsx
import { AlertDialog, Button, Spinner } from "@heroui/react"

export type RemovePhoneNumberDialogProps = {
  cancelLabel: string
  description: string
  isPending: boolean
  label: string
  title: string
  onConfirm: () => void
}

/** Confirm removal because it can disable a sign-in and recovery method. */
export function RemovePhoneNumberDialog({
  cancelLabel,
  description,
  isPending,
  label,
  onConfirm,
  title
}: RemovePhoneNumberDialogProps) {
  return (
    <AlertDialog>
      <Button size="sm" variant="tertiary" isDisabled={isPending}>
        {label}
      </Button>
      <AlertDialog.Backdrop>
        <AlertDialog.Container>
          <AlertDialog.Dialog className="sm:max-w-sm">
            <AlertDialog.CloseTrigger />
            <AlertDialog.Header>
              <AlertDialog.Icon status="danger" />
              <AlertDialog.Heading>{title}</AlertDialog.Heading>
            </AlertDialog.Header>
            <AlertDialog.Body>{description}</AlertDialog.Body>
            <AlertDialog.Footer>
              <Button slot="close" variant="tertiary" isDisabled={isPending}>
                {cancelLabel}
              </Button>
              <Button
                slot="close"
                variant="danger"
                isDisabled={isPending}
                isPending={isPending}
                onPress={onConfirm}
              >
                {isPending && <Spinner color="current" size="sm" />}
                {label}
              </Button>
            </AlertDialog.Footer>
          </AlertDialog.Dialog>
        </AlertDialog.Container>
      </AlertDialog.Backdrop>
    </AlertDialog>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/phone-number/remove-phone-number-dialog.tsx
import { Show } from "solid-js"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"

export type RemovePhoneNumberDialogProps = {
  cancelLabel: string
  description: string
  isPending: boolean
  label: string
  title: string
  onConfirm: () => void
}

/** Confirm removal because it can disable a sign-in and recovery method. */
export function RemovePhoneNumberDialog(props: RemovePhoneNumberDialogProps) {
  return (
    <AlertDialog>
      <AlertDialogTrigger
        as={Button}
        disabled={props.isPending}
        size="sm"
        variant="outline"
      >
        {props.label}
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{props.title}</AlertDialogTitle>
          <AlertDialogDescription>{props.description}</AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={props.isPending}>
            {props.cancelLabel}
          </AlertDialogCancel>
          <AlertDialogAction
            disabled={props.isPending}
            variant="destructive"
            onClick={props.onConfirm}
          >
            <Show when={props.isPending}>
              <Spinner />
            </Show>
            {props.label}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
