// packages/shadcn/src/components/user/user-button.tsx
"use client"

import type { AnyAuthConfig } from "@better-auth-ui/react"
import {
  ChevronsUpDown,
  CirclePlus,
  LogIn,
  LogOut,
  Settings,
  UserPlus2
} from "lucide-react"

import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { useAuth } from "@/hooks/auth/use-auth"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"
import { UserView } from "./user-view"

export type UserButtonProps = AnyAuthConfig & {
  className?: string
  align?: "center" | "end" | "start" | undefined
  sideOffset?: number
  size?: "default" | "icon"
  variant?:
    | "default"
    | "destructive"
    | "ghost"
    | "link"
    | "outline"
    | "secondary"
}

/**
 * Renders a user button with dropdown menu showing user info and sign out option.
 */
export function UserButton({
  className,
  align,
  sideOffset,
  size = "default",
  variant = "ghost",
  ...config
}: UserButtonProps) {
  const { authClient, basePaths, viewPaths, localization, Link, multiSession } =
    useAuth(config)

  const { data: sessionData } = authClient.useSession()

  const user = sessionData?.user

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild={size === "default"}>
        {size === "icon" ? (
          <UserAvatar {...config} />
        ) : (
          <Button
            variant={variant}
            className={cn("h-auto font-normal", className)}
          >
            {user ? (
              <UserView {...config} />
            ) : (
              <>
                <UserAvatar {...config} />
                <div className="grid flex-1 text-left text-sm leading-tight">
                  {localization.auth.account}
                </div>
              </>
            )}

            <ChevronsUpDown className="ml-auto" />
          </Button>
        )}
      </DropdownMenuTrigger>

      <DropdownMenuContent
        className="w-[--radix-dropdown-menu-trigger-width] min-w-56 rounded-lg"
        sideOffset={sideOffset}
        align={align}
        onCloseAutoFocus={(e) => e.preventDefault()}
      >
        {user && (
          <>
            <DropdownMenuLabel className="text-sm font-normal">
              <UserView {...config} />
            </DropdownMenuLabel>

            <DropdownMenuSeparator />
          </>
        )}

        {user ? (
          <>
            <DropdownMenuItem asChild>
              <Link
                href={`${basePaths.settings}/${viewPaths.settings.account}`}
              >
                <Settings />

                {localization.settings.settings}
              </Link>
            </DropdownMenuItem>

            {multiSession && (
              <>
                <DropdownMenuSeparator />

                <DropdownMenuItem className="px-2">
                  <UserView
                    {...config}
                    user={{
                      id: "",
                      name: "John Doe",
                      email: "john.doe@example.com",
                      emailVerified: false,
                      createdAt: new Date(),
                      updatedAt: new Date()
                    }}
                  />
                </DropdownMenuItem>

                <DropdownMenuSeparator />

                <DropdownMenuItem asChild>
                  <Link href={`${basePaths.auth}/${viewPaths.auth.signIn}`}>
                    <CirclePlus />
                    Add Account
                  </Link>
                </DropdownMenuItem>
              </>
            )}

            <DropdownMenuSeparator />

            <DropdownMenuItem asChild>
              <Link href={`${basePaths.auth}/${viewPaths.auth.signOut}`}>
                <LogOut />

                {localization.auth.signOut}
              </Link>
            </DropdownMenuItem>
          </>
        ) : (
          <>
            <DropdownMenuItem asChild>
              <Link href={`${basePaths.auth}/${viewPaths.auth.signIn}`}>
                <LogIn />

                {localization.auth.signIn}
              </Link>
            </DropdownMenuItem>

            <DropdownMenuItem asChild>
              <Link href={`${basePaths.auth}/${viewPaths.auth.signUp}`}>
                <UserPlus2 />

                {localization.auth.signUp}
              </Link>
            </DropdownMenuItem>
          </>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/user/user-button.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import { Link } from "@tanstack/solid-router"
import {
  ChevronsUpDown,
  LogIn,
  LogOut,
  Settings,
  User,
  UserPlus2
} from "lucide-solid"
import { createSignal, mergeProps, onMount, Show } from "solid-js"
import { ThemeToggleItem } from "@/components/auth/theme/theme-toggle-item"
import { UserAvatar } from "@/components/auth/user/user-avatar"
import { UserView } from "@/components/auth/user/user-view"
import { buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuLabel,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

const menuLinkClass = "flex w-full items-center gap-1.5"

const resolveUserLabel = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => username || name || email || "Account"

const resolveUserSecondaryLabel = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => (username || name ? email : undefined)

const resolveUserInitials = (
  username?: string | null,
  name?: string | null,
  email?: string | null
) => resolveUserLabel(username, name, email).slice(0, 2).toUpperCase()

type UserButtonProps = {
  class?: string
  align?: "center" | "end" | "start"
  sideOffset?: number
  size?: "default" | "icon"
  variant?:
    | "default"
    | "destructive"
    | "ghost"
    | "link"
    | "outline"
    | "secondary"
}

function UserButtonPendingView() {
  return (
    <div class="flex items-center gap-2 text-left">
      <Skeleton class="size-8 rounded-full" />
      <div class="grid flex-1 gap-1 text-left text-sm">
        <Skeleton class="h-4 w-24" />
        <Skeleton class="h-3 w-32" />
      </div>
    </div>
  )
}

export function UserButton(rawProps: UserButtonProps = {}) {
  const props = mergeProps(
    {
      align: "center" as const,
      size: "default" as const,
      variant: "ghost" as const
    },
    rawProps
  )
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !import.meta.env.SSR
  })
  const [isUserButtonHydrated, setIsUserButtonHydrated] = createSignal(false)
  const settingsLabel = () => auth.localization.settings.settings
  const size = () => props.size
  const contentClass = () =>
    cn(
      "w-[--kb-popper-anchor-width] min-w-40 md:min-w-56 max-w-[48svw] rounded-lg bg-popover p-1 text-popover-foreground shadow-md",
      props.align === "end" && "origin-top-right"
    )
  const triggerClass = () =>
    cn(
      buttonVariants({
        size: size() === "icon" ? "icon" : "lg",
        variant: props.variant
      }),
      size() === "icon"
        ? "rounded-full! border-0! p-0"
        : "py-2.5 h-auto font-normal justify-between gap-3 rounded-full",
      props.class
    )

  onMount(() => setIsUserButtonHydrated(true))

  const signInPath = auth.viewPaths.auth.signIn
  const signUpPath = auth.viewPaths.auth.signUp
  const signOutPath = auth.viewPaths.auth.signOut
  const settingsPath = auth.viewPaths.settings.account

  const userLabel = () =>
    resolveUserLabel(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  const userSecondaryLabel = () =>
    resolveUserSecondaryLabel(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  const userInitials = () =>
    resolveUserInitials(
      undefined,
      session.data?.user.name,
      session.data?.user.email
    )

  return (
    <Show
      when={isUserButtonHydrated()}
      fallback={
        <div aria-hidden="true" class={triggerClass()}>
          <Show
            when={size() === "icon"}
            fallback={
              <>
                <UserButtonPendingView />
                <ChevronsUpDown class="size-4 text-muted-foreground" />
              </>
            }
          >
            <Skeleton class="size-8 rounded-full" />
          </Show>
        </div>
      }
    >
      <DropdownMenu gutter={props.sideOffset ?? 4} modal={false}>
        <DropdownMenuTrigger class={triggerClass()}>
          <Show
            when={size() === "icon"}
            fallback={
              <>
                <div class="flex min-w-0 items-center gap-3 text-left">
                  <Show
                    when={!session.isPending}
                    fallback={<UserButtonPendingView />}
                  >
                    <UserView
                      image={session.data?.user.image}
                      initials={session.data ? userInitials() : undefined}
                      label={userLabel()}
                      secondaryLabel={userSecondaryLabel()}
                    />
                  </Show>
                </div>

                <ChevronsUpDown class="size-4 text-muted-foreground" />
              </>
            }
          >
            <Show
              when={!session.isPending}
              fallback={<Skeleton class="size-8 rounded-full" />}
            >
              <UserAvatar
                fallback={<User class="size-4" />}
                image={session.data?.user.image}
                initials={session.data ? userInitials() : undefined}
                label={userLabel()}
              />
            </Show>
          </Show>
        </DropdownMenuTrigger>

        <DropdownMenuContent
          class={contentClass()}
          style={{
            "min-width": "min(14rem, 48svw)",
            "max-width": "48svw",
            width: "max-content"
          }}
        >
          <Show when={session.data}>
            <DropdownMenuLabel class="px-2 py-1.5 text-sm font-normal text-foreground">
              <div class="flex items-center gap-3">
                <UserAvatar
                  class="size-10 rounded-full bg-muted text-muted-foreground"
                  image={session.data?.user.image}
                  initials={userInitials()}
                  label={userLabel()}
                />

                <div class="grid min-w-0 flex-1 gap-0.5">
                  <span class="truncate font-medium text-foreground">
                    {userLabel()}
                  </span>
                  <Show when={session.data?.user.email}>
                    <span class="truncate text-xs text-muted-foreground">
                      {session.data?.user.email}
                    </span>
                  </Show>
                </div>
              </div>
            </DropdownMenuLabel>

            <Separator class="my-1" />
          </Show>

          <Show
            when={!session.isPending}
            fallback={
              <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm">
                <UserButtonPendingView />
              </DropdownMenuItem>
            }
          >
            <Show
              when={session.data}
              fallback={
                <>
                  <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                    <Link
                      class={menuLinkClass}
                      params={{ path: signInPath }}
                      to="/auth/$path"
                    >
                      <LogIn class="size-4 text-muted-foreground" />
                      {auth.localization.auth.signIn}
                    </Link>
                  </DropdownMenuItem>

                  <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                    <Link
                      class={menuLinkClass}
                      params={{ path: signUpPath }}
                      to="/auth/$path"
                    >
                      <UserPlus2 class="size-4 text-muted-foreground" />
                      {auth.localization.auth.signUp}
                    </Link>
                  </DropdownMenuItem>

                  <ThemeToggleItem />
                </>
              }
            >
              <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                <Link
                  class={menuLinkClass}
                  params={{ path: settingsPath }}
                  to="/settings/$path"
                >
                  <Settings class="size-4 text-muted-foreground" />
                  {settingsLabel()}
                </Link>
              </DropdownMenuItem>

              <ThemeToggleItem />

              <DropdownMenuSeparator class="my-1 bg-border" />

              <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
                <Link
                  class={menuLinkClass}
                  params={{ path: signOutPath }}
                  to="/auth/$path"
                >
                  <LogOut class="size-4 text-muted-foreground" />
                  {auth.localization.auth.signOut}
                </Link>
              </DropdownMenuItem>
            </Show>
          </Show>
        </DropdownMenuContent>
      </DropdownMenu>
    </Show>
  )
}
