// packages/shadcn/src/components/user/user-avatar.tsx
"use client"

import type { AnyAuthConfig } from "@better-auth-ui/react"
import type { User } from "better-auth"
import { User2 } from "lucide-react"
import type { ReactNode } from "react"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Skeleton } from "@/components/ui/skeleton"
import { useAuth } from "@/hooks/auth/use-auth"
import { cn } from "@/lib/utils"

export type UserAvatarProps = AnyAuthConfig & {
  className?: string
  fallback?: ReactNode
  isPending?: boolean
  user?: User & { username?: string | null; displayUsername?: string | null }
}

/**
 * Display a user's avatar using session information or an explicit user prop.
 *
 * Renders a circular avatar that shows the user's image when available, a fallback node if provided, or the user's first two initials; while the session is loading (or when `isPending` is true) and no `user` prop is supplied, renders a skeleton placeholder.
 *
 * @param className - Additional CSS classes applied to the avatar container
 * @param user - Optional user object to display instead of the session user
 * @param isPending - When true, treat the component as loading and show the skeleton if no `user` is provided
 * @param fallback - Node to render inside the avatar fallback area before initials or the default icon
 * @returns The avatar element to render (JSX)
 */
export function UserAvatar({
  className,
  user,
  isPending,
  fallback,
  ...config
}: UserAvatarProps) {
  const { authClient } = useAuth(config)

  const { data: sessionData, isPending: sessionPending } =
    authClient.useSession()

  if ((isPending || sessionPending) && !user) {
    return <Skeleton className={cn("size-8 rounded-full", className)} />
  }

  const resolvedUser = user ?? sessionData?.user

  const initials = (
    resolvedUser?.username ||
    resolvedUser?.name ||
    resolvedUser?.email
  )
    ?.slice(0, 2)
    .toUpperCase()

  return (
    <Avatar
      className={cn(
        "size-8 bg-muted text-foreground text-sm rounded-full",
        className
      )}
    >
      <AvatarImage
        src={resolvedUser?.image ?? undefined}
        alt={
          resolvedUser?.displayUsername ||
          resolvedUser?.name ||
          resolvedUser?.email
        }
      />

      <AvatarFallback delayMs={resolvedUser?.image ? 600 : undefined}>
        {fallback || initials || <User2 className="size-4" />}
      </AvatarFallback>
    </Avatar>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/user/user-avatar.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import type { User as AuthUserBase } from "better-auth"
import { User } from "lucide-solid"
import type { JSX } from "solid-js"
import { Show } from "solid-js"
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

type AuthUser = AuthUserBase & {
  displayUsername?: string | null
  username?: string | null
}

export type UserAvatarProps = {
  class?: string
  fallback?: JSX.Element
  image?: string | null
  initials?: string
  isPending?: boolean
  label?: string
  user?: AuthUser
}

const resolveAvatarLabel = (user?: AuthUser, label?: string) =>
  label ??
  user?.displayUsername ??
  user?.username ??
  user?.name ??
  user?.email ??
  "Account"

const resolveAvatarInitials = (
  user?: AuthUser,
  initials?: string,
  label?: string
) => initials ?? resolveAvatarLabel(user, label).slice(0, 2).toUpperCase()

export function UserAvatar(props: UserAvatarProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient, () => ({
    enabled: !props.user && !props.isPending
  }))
  const sessionPending = () => session.isPending
  const resolvedUser = () =>
    props.user ?? (session.data?.user as AuthUser | undefined)
  const label = () => resolveAvatarLabel(resolvedUser(), props.label)
  const initials = () =>
    resolveAvatarInitials(resolvedUser(), props.initials, props.label)

  if ((props.isPending || sessionPending()) && !props.user) {
    return (
      <Skeleton
        class={cn(
          "size-9 rounded-full bg-muted text-muted-foreground",
          props.class
        )}
      />
    )
  }

  return (
    <Avatar
      class={cn(
        "size-9 rounded-full bg-muted text-muted-foreground",
        props.class
      )}
    >
      <AvatarImage
        alt={label()}
        src={props.image ?? resolvedUser()?.image ?? undefined}
      />
      <AvatarFallback class="rounded-full bg-muted text-muted-foreground">
        <Show
          fallback={props.fallback ?? <User class="size-4" />}
          when={initials()}
        >
          {(initials) => initials()}
        </Show>
      </AvatarFallback>
    </Avatar>
  )
}
