// packages/shadcn/src/components/user/user-view.tsx
"use client"

import type { User } from "better-auth"

import { Skeleton } from "@/components/ui/skeleton"
import { useSession } from "@/hooks/auth/use-session"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"

export type UserViewProps = {
  className?: string
  isPending?: boolean
  user?: User & { username?: string | null; displayUsername?: string | null }
}

/**
 * Display a user's avatar alongside their primary display name and email.
 *
 * If `user` is omitted, the current session user is used when available. When `isPending` is true (or the session is pending) and no explicit `user` is provided, a loading skeleton is shown instead of user details.
 *
 * @param isPending - When true, force rendering of the loading skeleton unless an explicit `user` prop is provided
 * @param user - Optional user object to display; when omitted the current session user is used if available
 * @returns A React element containing the user's avatar and name/email, or a skeleton loading state when pending and no explicit user is provided
 */
export function UserView({ className, isPending, user }: UserViewProps) {
  const { data: sessionData, isPending: sessionPending } = useSession()

  const resolvedUser = user ?? sessionData?.user

  if ((isPending || sessionPending) && !user) {
    return (
      <div className={cn("flex items-center gap-2", className)}>
        <UserAvatar isPending />

        <div className="grid flex-1 gap-1 text-left text-sm">
          <Skeleton className="h-4 w-24" />
          <Skeleton className="h-3 w-32" />
        </div>
      </div>
    )
  }

  return (
    <div className={cn("flex items-center gap-2", className)}>
      <UserAvatar user={resolvedUser} />

      <div className="grid flex-1 text-left text-sm leading-tight">
        <span className="truncate font-medium">
          {resolvedUser?.displayUsername ||
            resolvedUser?.name ||
            resolvedUser?.email}
        </span>

        {(resolvedUser?.displayUsername || resolvedUser?.name) && (
          <span className="text-muted-foreground truncate text-xs">
            {resolvedUser?.email}
          </span>
        )}
      </div>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/user/user-view.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import type { User as AuthUserBase } from "better-auth"
import { Show } from "solid-js"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"
import { UserAvatar } from "./user-avatar"

type AuthUser = AuthUserBase & {
  displayUsername?: string | null
  username?: string | null
}

export type UserViewProps = {
  class?: string
  hideSubtitle?: boolean
  image?: string | null
  initials?: string
  isPending?: boolean
  label?: string
  secondaryLabel?: string | null
  user?: AuthUser
}

const resolvePrimaryLabel = (user?: AuthUser, label?: string) =>
  label ??
  user?.displayUsername ??
  user?.username ??
  user?.name ??
  user?.email ??
  "Account"

const resolveSecondaryLabel = (
  user?: AuthUser,
  secondaryLabel?: string | null
) =>
  secondaryLabel ??
  (user?.displayUsername || user?.username || user?.name
    ? user?.email
    : undefined)

export function UserView(props: UserViewProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient, () => ({
    enabled: !props.user && !props.isPending && !props.label
  }))
  const sessionPending = () => session.isPending
  const resolvedUser = () =>
    props.user ?? (session.data?.user as AuthUser | undefined)
  const label = () => resolvePrimaryLabel(resolvedUser(), props.label)
  const secondaryLabel = () =>
    props.hideSubtitle
      ? null
      : resolveSecondaryLabel(resolvedUser(), props.secondaryLabel)

  if ((props.isPending || sessionPending()) && !props.user && !props.label) {
    return (
      <div class={cn("flex items-center gap-2", props.class)}>
        <UserAvatar isPending />
        <div class="grid flex-1 gap-1 text-left text-sm">
          <Skeleton class="h-4 w-24" />
          <Skeleton class="h-3 w-32" />
        </div>
      </div>
    )
  }

  return (
    <div class={cn("flex min-w-0 items-center gap-2", props.class)}>
      <UserAvatar
        user={resolvedUser()}
        image={props.image}
        initials={props.initials}
        label={label()}
      />

      <div class="grid min-w-0 flex-1 gap-0.5 text-left text-sm">
        <span class="truncate font-medium leading-4 text-foreground">
          {label()}
        </span>

        <Show when={secondaryLabel()}>
          <span class="truncate text-xs leading-4 text-muted-foreground">
            {secondaryLabel()}
          </span>
        </Show>
      </div>
    </div>
  )
}
