// packages/react/src/plugins/passkey/hooks/use-passkey-auto-fill.ts
"use client"

import {
  isConditionalMediationAvailable,
  isPasskeyAutoFillEnabled,
  type PasskeyAuthClient,
  passkeyAutoFillOptions,
  type SignInPasskeyOptions
} from "@better-auth-ui/core/plugins/passkey"
import { useMutation } from "@tanstack/react-query"
import type { BetterFetchOption } from "better-auth/client"
import { useEffect, useRef } from "react"
import { useAuth } from "../../../components/auth/auth-provider"

export type UsePasskeyAutoFillOptions<TAuthClient extends PasskeyAuthClient> =
  SignInPasskeyOptions<TAuthClient> & {
    /**
     * Skip the conditional request on views where passkey sign-in doesn't
     * apply, such as sign-up.
     * @default true
     */
    enabled?: boolean
    /** Fetch callbacks for the passkey verification request. */
    fetchOptions?: BetterFetchOption
  }

/**
 * Offer the user's passkeys through the browser's autofill dropdown (WebAuthn
 * conditional UI) for as long as the calling component is mounted.
 *
 * Does nothing when the passkey plugin isn't registered, when its `autoFill`
 * option is off, or when the browser can't service a conditionally mediated
 * request. Pair it with the `webauthn` autocomplete token on the identifier
 * field. See `withPasskeyAutoFill` in `@better-auth-ui/core/plugins/passkey`.
 *
 * The request stays open until the user picks a passkey or the page
 * navigates. The Better Auth passkey client doesn't expose WebAuthn's abort
 * signal, so unmounting only stops a pending availability probe from starting
 * one.
 *
 * @param authClient - The Better Auth client with the passkey plugin.
 * @param options - React Query options forwarded to the sign-in mutation.
 */
export function usePasskeyAutoFill<TAuthClient extends PasskeyAuthClient>(
  authClient: TAuthClient,
  options?: UsePasskeyAutoFillOptions<TAuthClient>
) {
  const { plugins } = useAuth()
  const { enabled = true, fetchOptions, ...mutationOptions } = options ?? {}
  const { mutate: signInPasskey } = useMutation({
    ...passkeyAutoFillOptions(authClient),
    ...mutationOptions
  })
  const started = useRef(false)

  const active = enabled && isPasskeyAutoFillEnabled(plugins)

  useEffect(() => {
    if (started.current || !active) return

    let cancelled = false

    void isConditionalMediationAvailable().then((available) => {
      if (!available || cancelled) return

      started.current = true
      signInPasskey({ autoFill: true, fetchOptions })
    })

    return () => {
      cancelled = true
    }
  }, [active, fetchOptions, signInPasskey])
}

// packages/solid/src/plugins/passkey/hooks/use-passkey-auto-fill.ts
import {
  isConditionalMediationAvailable,
  isPasskeyAutoFillEnabled,
  type PasskeyAuthClient,
  passkeyAutoFillOptions
} from "@better-auth-ui/core/plugins/passkey"
import { useMutation } from "@tanstack/solid-query"
import type { BetterFetchOption } from "better-auth/client"
import { onCleanup, onMount } from "solid-js"
import { useAuth } from "../../../lib/auth-provider"
import type { UseSignInPasskeyOptions } from "./mutations/use-sign-in-passkey"

export type UsePasskeyAutoFillOptions<TAuthClient extends PasskeyAuthClient> = {
  /**
   * Skip the conditional request on views where passkey sign-in doesn't
   * apply, such as sign-up.
   * @default true
   */
  enabled?: boolean
  /** Fetch callbacks for the passkey verification request. */
  fetchOptions?: BetterFetchOption
  /** Solid Query options forwarded to the sign-in mutation. */
  mutation?: UseSignInPasskeyOptions<TAuthClient>
}

/**
 * Offer the user's passkeys through the browser's autofill dropdown (WebAuthn
 * conditional UI) for as long as the calling component is mounted.
 *
 * Does nothing when the passkey plugin isn't registered, when its `autoFill`
 * option is off, or when the browser can't service a conditionally mediated
 * request. Pair it with the `webauthn` autocomplete token on the identifier
 * field. See `withPasskeyAutoFill` in `@better-auth-ui/core/plugins/passkey`.
 *
 * The request stays open until the user picks a passkey or the page
 * navigates. The Better Auth passkey client doesn't expose WebAuthn's abort
 * signal, so cleanup only stops a pending availability probe from starting
 * one.
 *
 * @param authClient - The Better Auth client with the passkey plugin.
 * @param options - Enablement flag and mutation options.
 */
export function usePasskeyAutoFill<TAuthClient extends PasskeyAuthClient>(
  authClient: TAuthClient,
  options?: UsePasskeyAutoFillOptions<TAuthClient>
) {
  const auth = useAuth()
  const signInPasskey = useMutation(() => ({
    ...passkeyAutoFillOptions(authClient),
    ...(options?.mutation?.() ?? {})
  }))

  onMount(() => {
    if (options?.enabled === false || !isPasskeyAutoFillEnabled(auth.plugins)) {
      return
    }

    let cancelled = false

    void isConditionalMediationAvailable().then((available) => {
      if (!available || cancelled) return

      signInPasskey.mutate({
        autoFill: true,
        fetchOptions: options?.fetchOptions
      })
    })

    onCleanup(() => {
      cancelled = true
    })
  })
}
