// examples/start-solid-zaidan-example/src/components/auth/two-factor/enable-two-factor-dialog.tsx
import { createQrCodeSvgData } from "@better-auth-ui/core"
import {
  enableTwoFactorOptions,
  type TwoFactorAuthClient,
  type TwoFactorMethod,
  verifyTotpOptions
} from "@better-auth-ui/core/plugins/two-factor"
import {
  createCopyToClipboard,
  useAuth,
  useAuthPlugin
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { Check, Copy, ShieldCheck } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { OtpField } from "@/components/auth/otp-field"
import { BackupCodes } from "@/components/auth/two-factor/backup-codes"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "@/lib/auth/use-two-factor-password"

type EnrollmentStep = "password" | "verify" | "backupCodes"

/**
 * Two-factor enrollment with authenticator-app and delivered-code methods.
 *
 * TOTP continues through QR verification and backup-code capture. OTP becomes
 * active as soon as Better Auth accepts the enrollment request.
 */
export function EnableTwoFactorDialog(props: {
  onOpenChange: (open: boolean) => void
}) {
  const auth = useAuth()
  const {
    codeLength,
    enrollmentMethods,
    localization: twoFactorLocalization
  } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const [step, setStep] = createSignal<EnrollmentStep>("password")
  const [method, setMethod] = createSignal<TwoFactorMethod>(
    enrollmentMethods[0] ?? "totp"
  )
  const [totpUri, setTotpUri] = createSignal("")
  const [backupCodes, setBackupCodes] = createSignal<string[]>([])
  const [code, setCode] = createSignal("")
  const { copied: setupKeyCopied, copy: copySetupKey } = createCopyToClipboard({
    onError: () => toast.error(twoFactorLocalization.setupKeyCopyFailed)
  })

  const qrCode = () => (totpUri() ? createQrCodeSvgData(totpUri()) : null)

  // Manual entry fallback for authenticator apps that can't scan. The URI is
  // an `otpauth://` URL, so the secret is just a query parameter.
  const setupKey = () => {
    if (!totpUri()) return null

    try {
      return new URL(totpUri()).searchParams.get("secret")
    } catch {
      return null
    }
  }

  const twoFactorClient = () => auth.authClient as TwoFactorAuthClient

  const enableTwoFactor = createMutation(() => ({
    ...enableTwoFactorOptions(twoFactorClient()),
    onSuccess: (data) => {
      if (data.method === "otp") {
        toast.success(twoFactorLocalization.twoFactorEnabled)
        props.onOpenChange(false)
        return
      }

      setTotpUri(data.totpURI)
      setBackupCodes(data.backupCodes)
      setStep("verify")
    }
  }))

  const verifyTotp = createMutation(() => ({
    ...verifyTotpOptions(twoFactorClient()),
    onError: () => setCode(""),
    onSuccess: () => {
      toast.success(twoFactorLocalization.twoFactorEnabled)
      setStep("backupCodes")
    }
  }))

  const isPending = () =>
    enableTwoFactor.isPending ||
    verifyTotp.isPending ||
    isResolvingPasswordRequirement()

  const verifyCode = (completedCode: string) => {
    if (
      isPending() ||
      step() !== "verify" ||
      completedCode.length !== codeLength
    ) {
      return
    }

    verifyTotp.mutate({ code: completedCode } as Parameters<
      typeof verifyTotp.mutate
    >[0])
  }

  const submit = (event: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    event.preventDefault()

    if (step() === "backupCodes") {
      props.onOpenChange(false)
      return
    }

    if (step() === "verify") {
      verifyCode(code())
      return
    }

    const formData = new FormData(event.currentTarget)
    const password = String(formData.get("password") ?? "")

    enableTwoFactor.mutate(
      (requiresPassword()
        ? { method: method(), password }
        : { method: method() }) as Parameters<typeof enableTwoFactor.mutate>[0]
    )
  }

  const submitLabel = () => {
    if (step() === "backupCodes") return twoFactorLocalization.done
    if (step() === "verify") return twoFactorLocalization.verify

    return twoFactorLocalization.enableTwoFactor
  }

  const description = () => {
    if (step() === "verify") return twoFactorLocalization.scanQrCode
    if (step() === "password" && requiresPassword())
      return twoFactorLocalization.passwordConfirmation

    return twoFactorLocalization.twoFactorDescription
  }

  return (
    <DialogContent>
      <form class="flex flex-col gap-6" onSubmit={submit}>
        <DialogHeader>
          <div class="flex size-10 items-center justify-center rounded-md bg-muted">
            <ShieldCheck class="size-4.5" />
          </div>

          <DialogTitle>{twoFactorLocalization.twoFactor}</DialogTitle>
          <DialogDescription>{description()}</DialogDescription>
        </DialogHeader>

        <Show when={step() === "password"}>
          <div class="flex flex-col gap-4">
            <Show when={enrollmentMethods.length > 1}>
              <Tabs value={method()} onChange={setMethod}>
                <TabsList
                  aria-label={twoFactorLocalization.chooseEnrollmentMethod}
                  class="w-full"
                >
                  <Show when={enrollmentMethods.includes("totp")}>
                    <TabsTrigger value="totp">
                      {twoFactorLocalization.authenticatorApp}
                    </TabsTrigger>
                  </Show>
                  <Show when={enrollmentMethods.includes("otp")}>
                    <TabsTrigger value="otp">
                      {twoFactorLocalization.deliveredCode}
                    </TabsTrigger>
                  </Show>
                </TabsList>
              </Tabs>
            </Show>

            <p class="text-muted-foreground text-sm">
              {method() === "totp"
                ? twoFactorLocalization.authenticatorAppDescription
                : twoFactorLocalization.deliveredCodeDescription}
            </p>

            <Show when={requiresPassword()}>
              <Field>
                <FieldLabel for="enable-two-factor-password">
                  {auth.localization.auth.password}
                </FieldLabel>

                <Input
                  autocomplete="current-password"
                  autofocus
                  disabled={isPending()}
                  id="enable-two-factor-password"
                  name="password"
                  placeholder={auth.localization.auth.passwordPlaceholder}
                  required
                  type="password"
                />
              </Field>
            </Show>
          </div>
        </Show>

        <Show when={step() === "verify"}>
          <div class="flex flex-col items-center gap-4">
            <Show when={qrCode()}>
              {(data) => (
                <svg
                  aria-hidden="true"
                  class="size-44 rounded-md border"
                  viewBox={`0 0 ${data().size} ${data().size}`}
                >
                  <path
                    d={`M0 0h${data().size}v${data().size}H0z`}
                    fill="white"
                  />
                  <path
                    d={data().path}
                    fill="black"
                    shape-rendering="crispEdges"
                  />
                </svg>
              )}
            </Show>

            <Show when={setupKey()}>
              {(key) => (
                <Field class="w-full gap-1">
                  <FieldLabel
                    class="text-muted-foreground text-xs"
                    for="two-factor-setup-key"
                  >
                    {twoFactorLocalization.setupKey}
                  </FieldLabel>

                  <InputGroup>
                    <InputGroupInput
                      class="font-mono text-xs"
                      id="two-factor-setup-key"
                      readonly
                      value={key()}
                    />

                    <InputGroupAddon align="inline-end">
                      <InputGroupButton
                        aria-label={
                          setupKeyCopied()
                            ? twoFactorLocalization.setupKeyCopied
                            : auth.localization.settings.copyToClipboard
                        }
                        onClick={() => copySetupKey(key())}
                        size="icon-xs"
                        type="button"
                      >
                        <Show fallback={<Copy />} when={setupKeyCopied()}>
                          <Check />
                        </Show>
                      </InputGroupButton>
                    </InputGroupAddon>
                  </InputGroup>
                </Field>
              )}
            </Show>

            <OtpField
              autofocus
              class="w-full"
              disabled={isPending()}
              id="enable-two-factor-code"
              label={twoFactorLocalization.authenticatorCode}
              length={codeLength}
              name="code"
              onInput={setCode}
              onComplete={verifyCode}
              value={code()}
            />
          </div>
        </Show>

        <Show when={step() === "backupCodes"}>
          <BackupCodes codes={backupCodes()} />
        </Show>

        <DialogFooter>
          <Show when={step() !== "backupCodes"}>
            <DialogClose
              as={Button}
              disabled={isPending()}
              type="button"
              variant="outline"
            >
              {auth.localization.settings.cancel}
            </DialogClose>
          </Show>

          <Button
            disabled={
              isPending() ||
              (step() === "verify" && code().length !== codeLength)
            }
            type="submit"
          >
            <Show when={isPending()}>
              <Spinner />
            </Show>

            {submitLabel()}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  )
}

// examples/next-shadcn-example/src/components/auth/two-factor/enable-two-factor-dialog.tsx
"use client"

import { createQrCodeSvgData } from "@better-auth-ui/core"
import type {
  TwoFactorAuthClient,
  TwoFactorMethod
} from "@better-auth-ui/core/plugins/two-factor"
import {
  useAuth,
  useAuthPlugin,
  useCopyToClipboard
} from "@better-auth-ui/react"
import {
  useEnableTwoFactor,
  useVerifyTotp
} from "@better-auth-ui/react/plugins/two-factor"
import { Check, Copy, ShieldCheck } from "lucide-react"
import { type SyntheticEvent, useMemo, useState } from "react"
import { toast } from "sonner"
import { Button, buttonVariants } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "@/lib/auth/use-two-factor-password"
import { OtpField } from "../otp-field"
import { BackupCodes } from "./backup-codes"

type EnrollmentStep = "password" | "verify" | "backupCodes"

export type EnableTwoFactorDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Two-factor enrollment with authenticator-app and delivered-code methods.
 *
 * TOTP continues through QR verification and backup-code capture. OTP becomes
 * active as soon as Better Auth accepts the enrollment request.
 *
 * @param open - Whether the dialog is open.
 * @param onOpenChange - Called when the dialog requests an open state change.
 */
export function EnableTwoFactorDialog({
  open,
  onOpenChange
}: EnableTwoFactorDialogProps) {
  const { authClient, localization } = useAuth()
  const {
    codeLength,
    enrollmentMethods,
    localization: twoFactorLocalization
  } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const twoFactorClient = authClient as TwoFactorAuthClient

  const [step, setStep] = useState<EnrollmentStep>("password")
  const [method, setMethod] = useState<TwoFactorMethod>(
    enrollmentMethods[0] ?? "totp"
  )
  const [totpUri, setTotpUri] = useState("")
  const [backupCodes, setBackupCodes] = useState<string[]>([])
  const [code, setCode] = useState("")
  const {
    copied: setupKeyCopied,
    copy: copySetupKeyValue,
    reset: resetSetupKeyCopy
  } = useCopyToClipboard({
    onError: () => toast.error(twoFactorLocalization.setupKeyCopyFailed)
  })

  const qrCode = useMemo(
    () => (totpUri ? createQrCodeSvgData(totpUri) : null),
    [totpUri]
  )

  // Manual entry fallback for authenticator apps that can't scan. The URI is
  // an `otpauth://` URL, so the secret is just a query parameter.
  const setupKey = useMemo(() => {
    if (!totpUri) return null

    try {
      return new URL(totpUri).searchParams.get("secret")
    } catch {
      return null
    }
  }, [totpUri])

  const copySetupKey = async () => {
    if (!setupKey) return

    await copySetupKeyValue(setupKey)
  }

  const {
    mutate: enableTwoFactor,
    isPending: isEnabling,
    reset: resetEnrollment
  } = useEnableTwoFactor(twoFactorClient, {
    onSuccess: (data) => {
      if (data.method === "otp") {
        toast.success(twoFactorLocalization.twoFactorEnabled)
        handleOpenChange(false)
        return
      }

      setTotpUri(data.totpURI)
      setBackupCodes(data.backupCodes)
      setStep("verify")
    }
  })

  const { mutate: verifyTotp, isPending: isVerifying } = useVerifyTotp(
    twoFactorClient,
    {
      onError: () => setCode(""),
      onSuccess: () => {
        toast.success(twoFactorLocalization.twoFactorEnabled)
        setStep("backupCodes")
      }
    }
  )

  const isPending = isEnabling || isVerifying || isResolvingPasswordRequirement

  const verifyCode = (completedCode: string) => {
    if (isPending || step !== "verify" || completedCode.length !== codeLength) {
      return
    }

    verifyTotp({ code: completedCode })
  }

  const handleOpenChange = (nextOpen: boolean) => {
    onOpenChange(nextOpen)

    if (!nextOpen) {
      setStep("password")
      setMethod(enrollmentMethods[0] ?? "totp")
      setTotpUri("")
      setBackupCodes([])
      setCode("")
      resetSetupKeyCopy()
      // Clears the resolved TOTP URI and backup codes from the mutation cache.
      resetEnrollment()
    }
  }

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (step === "backupCodes") {
      handleOpenChange(false)
      return
    }

    if (step === "verify") {
      verifyCode(code)
      return
    }

    const formData = new FormData(e.currentTarget)
    const password = formData.get("password") as string

    enableTwoFactor(requiresPassword ? { method, password } : { method })
  }

  const submitLabel =
    step === "backupCodes"
      ? twoFactorLocalization.done
      : step === "verify"
        ? twoFactorLocalization.verify
        : twoFactorLocalization.enableTwoFactor

  return (
    <Dialog open={open} onOpenChange={handleOpenChange}>
      <DialogContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-6">
          <DialogHeader>
            <DialogTitle>
              <ShieldCheck />
              {twoFactorLocalization.twoFactor}
            </DialogTitle>

            <DialogDescription>
              {step === "password" && requiresPassword
                ? twoFactorLocalization.passwordConfirmation
                : step === "verify"
                  ? twoFactorLocalization.scanQrCode
                  : twoFactorLocalization.twoFactorDescription}
            </DialogDescription>
          </DialogHeader>

          {step === "password" && (
            <div className="flex flex-col gap-4">
              {enrollmentMethods.length > 1 && (
                <Tabs
                  value={method}
                  onValueChange={(value) => setMethod(value as TwoFactorMethod)}
                >
                  <TabsList
                    aria-label={twoFactorLocalization.chooseEnrollmentMethod}
                    className="w-full"
                  >
                    {enrollmentMethods.includes("totp") && (
                      <TabsTrigger value="totp">
                        {twoFactorLocalization.authenticatorApp}
                      </TabsTrigger>
                    )}
                    {enrollmentMethods.includes("otp") && (
                      <TabsTrigger value="otp">
                        {twoFactorLocalization.deliveredCode}
                      </TabsTrigger>
                    )}
                  </TabsList>
                </Tabs>
              )}

              <p className="text-muted-foreground text-sm">
                {method === "totp"
                  ? twoFactorLocalization.authenticatorAppDescription
                  : twoFactorLocalization.deliveredCodeDescription}
              </p>

              {requiresPassword && (
                <Field>
                  <FieldLabel htmlFor="two-factor-password">
                    {localization.auth.password}
                  </FieldLabel>

                  <Input
                    id="two-factor-password"
                    name="password"
                    type="password"
                    autoComplete="current-password"
                    autoFocus
                    required
                    placeholder={localization.auth.passwordPlaceholder}
                    disabled={isPending}
                  />

                  <FieldError />
                </Field>
              )}
            </div>
          )}

          {step === "verify" && (
            <div className="flex flex-col items-center gap-4">
              {qrCode && (
                <svg
                  aria-hidden="true"
                  className="size-44 rounded-md border"
                  viewBox={`0 0 ${qrCode.size} ${qrCode.size}`}
                >
                  <path
                    fill="white"
                    d={`M0 0h${qrCode.size}v${qrCode.size}H0z`}
                  />
                  <path
                    fill="black"
                    d={qrCode.path}
                    shapeRendering="crispEdges"
                  />
                </svg>
              )}

              {setupKey && (
                <Field className="w-full gap-1">
                  <FieldLabel
                    className="text-muted-foreground text-xs"
                    htmlFor="two-factor-setup-key"
                  >
                    {twoFactorLocalization.setupKey}
                  </FieldLabel>

                  <InputGroup>
                    <InputGroupInput
                      className="font-mono text-xs"
                      id="two-factor-setup-key"
                      readOnly
                      value={setupKey}
                    />

                    <InputGroupAddon align="inline-end">
                      <InputGroupButton
                        aria-label={
                          setupKeyCopied
                            ? twoFactorLocalization.setupKeyCopied
                            : localization.settings.copyToClipboard
                        }
                        onClick={copySetupKey}
                        size="icon-xs"
                      >
                        {setupKeyCopied ? <Check /> : <Copy />}
                      </InputGroupButton>
                    </InputGroupAddon>
                  </InputGroup>
                </Field>
              )}

              <OtpField
                autoFocus
                className="w-full"
                disabled={isPending}
                label={twoFactorLocalization.authenticatorCode}
                length={codeLength}
                name="code"
                value={code}
                onChange={setCode}
                onComplete={verifyCode}
              />
            </div>
          )}

          {step === "backupCodes" && <BackupCodes codes={backupCodes} />}

          <DialogFooter>
            {step !== "backupCodes" && (
              <DialogClose
                className={buttonVariants({ variant: "outline" })}
                disabled={isPending}
                type="button"
              >
                {localization.settings.cancel}
              </DialogClose>
            )}

            <Button
              type="submit"
              disabled={
                isPending || (step === "verify" && code.length !== codeLength)
              }
            >
              {isPending && <Spinner />}

              {submitLabel}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
