// packages/react-native/src/components/auth/admin/admin-users.tsx
import {
  validateEmailAddress,
  validateStringLength
} from "@better-auth-ui/core"
import {
  adminPermissionOptions,
  isAdminTarget,
  type AdminAuthClient,
  type AdminUser
} from "@better-auth-ui/core/plugins/admin"
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import {
  useAdminUsers,
  useAdminUser,
  useAdminUserSessions,
  useCreateAdminUser,
  useUpdateAdminUser,
  useSetAdminUserRole,
  useSetAdminUserPassword,
  useBanAdminUser,
  useUnbanAdminUser,
  useRemoveAdminUser,
  useImpersonateAdminUser,
  useRevokeAdminUserSession,
  useRevokeAdminUserSessions
} from "@better-auth-ui/react/plugins/admin"
import { useQueries, keepPreviousData } from "@tanstack/react-query"
import { useState } from "react"
import { adminPlugin } from "../../../lib/auth/admin-plugin"
import type { CardSlotProps } from "../../../lib/auth-plugin"
import { useNativeLocale } from "../../../lib/native-locale"
import { AlertDialog } from "../../../primitives/alert-dialog"
import { Button } from "../../../primitives/button"
import { Card } from "../../../primitives/card"
import { Checkbox } from "../../../primitives/checkbox"
import { CopyValue } from "../copy-value"
import { Description } from "../../../primitives/description"
import { SearchField } from "../../../primitives/inputs-extra"
import { Select } from "../../../primitives/menu"
import { Skeleton } from "../../../primitives/skeleton"
import { Box, Txt } from "../../../primitives/styled"
import { Tabs } from "../../../primitives/tabs"
import { useAuthForm } from "../auth-form"

const actions = {
  list: { user: ["list"] },
  create: { user: ["create"] },
  update: { user: ["update"] },
  role: { user: ["set-role"] },
  password: { user: ["set-password"] },
  ban: { user: ["ban"] },
  remove: { user: ["delete"] },
  impersonate: { user: ["impersonate"] },
  impersonateAdmin: { user: ["impersonate-admins"] },
  sessions: { session: ["list"] },
  revoke: { session: ["revoke"] }
} as const
function useAdminActions() {
  const { authClient } = useAuth()
  const { data } = useSession(authClient)
  const names = Object.keys(actions) as (keyof typeof actions)[]
  const queries = useQueries({
    queries: names.map((name) =>
      adminPermissionOptions(
        authClient as AdminAuthClient,
        data?.user.id,
        actions[name]
      )
    )
  })
  return {
    permissionPending: queries.some((query) => query.isPending),
    ...Object.fromEntries(
      names.map((name, position) => [
        name,
        queries[position]!.data?.success === true
      ])
    )
  } as Record<keyof typeof actions, boolean> & { permissionPending: boolean }
}

type Action =
  | { type: "create" }
  | {
      type:
        | "edit"
        | "role"
        | "password"
        | "ban"
        | "unban"
        | "remove"
        | "impersonate"
      user: AdminUser
    }
export function AdminUsers(props: CardSlotProps) {
  const { authClient, localization: common } = useAuth()
  const { localization, pageSize } = useAuthPlugin(adminPlugin)
  const allowed = useAdminActions()
  const [search, setSearch] = useState("")
  const [searchField, setSearchField] = useState<"email" | "name">("email")
  const [operator, setOperator] = useState<
    "contains" | "starts_with" | "ends_with"
  >("contains")
  const [sort, setSort] = useState("newest")
  const [status, setStatus] = useState("all")
  const [page, setPage] = useState(0)
  const [action, setAction] = useState<Action>()
  const [selected, setSelected] = useState<string>()
  const { languageTag } = useNativeLocale()
  const offset = page * pageSize
  const users = useAdminUsers(authClient as AdminAuthClient, {
    enabled: allowed.list,
    placeholderData: keepPreviousData,
    params: {
      limit: pageSize,
      offset,
      searchValue: search.trim() || undefined,
      searchField,
      searchOperator: operator,
      sortBy: sort.startsWith("name") ? "name" : "createdAt",
      sortDirection: sort === "oldest" || sort === "name-asc" ? "asc" : "desc",
      ...(status !== "all" && {
        filterField: "banned",
        filterValue: status === "banned",
        filterOperator: "eq" as const
      })
    }
  })
  const number = new Intl.NumberFormat(languageTag)
  return (
    <Box className={props.className ?? "gap-4"}>
      <Txt className="font-semibold">{localization.users}</Txt>
      <Description>{localization.usersDescription}</Description>
      <SearchField
        value={search}
        onChangeText={(value) => {
          setSearch(value)
          setPage(0)
        }}
        placeholder={localization.search}
        aria-label={localization.search}
      />
      <Select
        label={localization.search}
        selectedKey={searchField}
        options={[
          { key: "email", label: localization.searchByEmail },
          { key: "name", label: localization.searchByName }
        ]}
        onSelectionChange={(key) => {
          setSearchField(key as typeof searchField)
          setPage(0)
        }}
      />
      <Select
        label={localization.searchOperator}
        selectedKey={operator}
        options={[
          { key: "contains", label: localization.searchContains },
          { key: "starts_with", label: localization.startsWith },
          { key: "ends_with", label: localization.endsWith }
        ]}
        onSelectionChange={(key) => {
          setOperator(key as typeof operator)
          setPage(0)
        }}
      />
      <Select
        label={localization.sort}
        selectedKey={sort}
        options={[
          { key: "newest", label: localization.sortNewest },
          { key: "oldest", label: localization.sortOldest },
          { key: "name-asc", label: localization.sortNameAscending },
          { key: "name-desc", label: localization.sortNameDescending }
        ]}
        onSelectionChange={(key) => {
          setSort(key)
          setPage(0)
        }}
      />
      <Select
        label={localization.status}
        selectedKey={status}
        options={[
          { key: "all", label: localization.filterAllStatuses },
          { key: "active", label: localization.active },
          { key: "banned", label: localization.banned }
        ]}
        onSelectionChange={(key) => {
          setStatus(key)
          setPage(0)
        }}
      />
      {!allowed.permissionPending && !allowed.list ? (
        <Description>{common.errors.permissionDenied}</Description>
      ) : null}
      {allowed.create ? (
        <Button onPress={() => setAction({ type: "create" })}>
          {localization.createUser}
        </Button>
      ) : null}
      {allowed.permissionPending || (allowed.list && users.isPending) ? (
        <Skeleton className="h-20 w-full" />
      ) : null}
      {users.error ? (
        <>
          <Txt accessibilityRole="alert">{localization.loadUsersError}</Txt>
          <Button
            onPress={() => {
              void users.refetch()
            }}
          >
            {localization.retry}
          </Button>
        </>
      ) : null}
      {users.data?.users.length === 0 ? (
        <Description>{localization.noUsersDescription}</Description>
      ) : null}
      {users.data?.users.map((user) => (
        <Card key={user.id} variant={props.variant}>
          <Card.Content className="gap-2">
            <Txt className="font-medium">{user.name}</Txt>
            <Description>{user.email}</Description>
            <Description>{user.role}</Description>
            <Description>
              {user.banned ? localization.banned : localization.active}
            </Description>
            <Button onPress={() => setSelected(user.id)}>
              {localization.userDetails}
            </Button>
          </Card.Content>
        </Card>
      ))}
      {users.data ? (
        <Description>
          {localization.usersPaginationRange
            .replace(
              "{{from}}",
              number.format(users.data.total ? offset + 1 : 0)
            )
            .replace(
              "{{to}}",
              number.format(Math.min(offset + pageSize, users.data.total))
            )
            .replace("{{total}}", number.format(users.data.total))}
        </Description>
      ) : null}
      <Box className="flex-row gap-2">
        <Button
          isDisabled={users.isFetching || !page}
          onPress={() => setPage(page - 1)}
        >
          {localization.previousPage}
        </Button>
        <Button
          isDisabled={
            users.isFetching ||
            !users.data ||
            offset + pageSize >= users.data.total
          }
          onPress={() => setPage(page + 1)}
        >
          {localization.nextPage}
        </Button>
      </Box>
      {selected ? (
        <AdminUserInspector
          key={selected}
          userId={selected}
          onClose={() => setSelected(undefined)}
          onAction={setAction}
          variant={props.variant}
        />
      ) : null}
      {action ? (
        <AdminAction
          key={
            action.type === "create"
              ? "create"
              : `${action.user.id}:${action.type}`
          }
          action={action}
          onClose={() => setAction(undefined)}
        />
      ) : null}
    </Box>
  )
}

function AdminUserInspector({
  userId,
  onClose,
  onAction,
  variant
}: CardSlotProps & {
  userId: string
  onClose: () => void
  onAction: (action: Action) => void
}) {
  const { authClient, plugins } = useAuth()
  const { localization, adminRoles, adminUserIds, showIpAddress } =
    useAuthPlugin(adminPlugin)
  const allowed = useAdminActions()
  const user = useAdminUser(authClient as AdminAuthClient, userId, {
    enabled: allowed.list
  })
  const sessions = useAdminUserSessions(authClient as AdminAuthClient, userId, {
    enabled: allowed.sessions
  })
  const revoke = useRevokeAdminUserSession(
    authClient as AdminAuthClient,
    userId
  )
  const revokeAll = useRevokeAdminUserSessions(
    authClient as AdminAuthClient,
    userId
  )
  const [token, setToken] = useState<string>()
  const [tab, setTab] = useState("overview")
  const { languageTag } = useNativeLocale()
  const contributions = plugins.flatMap((plugin) => plugin.adminUserTabs ?? [])
  const target = user.data
  return (
    <AlertDialog
      isOpen
      onOpenChange={(open) => {
        if (!open) onClose()
      }}
    >
      <AlertDialog.Header>
        <AlertDialog.Heading>
          {target?.name ?? localization.userDetails}
        </AlertDialog.Heading>
      </AlertDialog.Header>
      <AlertDialog.Body>
        <Tabs selectedKey={tab} onSelectionChange={setTab}>
          <Tabs.List aria-label={localization.userDetails}>
            <Tabs.Tab id="overview">{localization.overview}</Tabs.Tab>
            <Tabs.Tab id="sessions">{localization.sessions}</Tabs.Tab>
            {contributions.map((item) => (
              <Tabs.Tab key={item.id} id={item.id}>
                {item.label}
              </Tabs.Tab>
            ))}
          </Tabs.List>
          <Tabs.Panel id="overview">
            <Box className="gap-3">
              {user.isPending ? <Skeleton className="h-10 w-full" /> : null}
              {user.error ? (
                <Txt accessibilityRole="alert">{user.error.message}</Txt>
              ) : null}
              {target ? (
                <>
                  <CopyValue
                    value={target.id}
                    label={localization.copyUserId}
                  />
                  <Txt>{target.email}</Txt>
                  <Description>
                    {localization.emailVerified}: {String(target.emailVerified)}
                  </Description>
                  <Description>{target.role}</Description>
                  <Description>
                    {new Intl.DateTimeFormat(languageTag, {
                      dateStyle: "medium"
                    }).format(new Date(target.createdAt))}
                  </Description>
                  {target.banReason ? (
                    <Description>{target.banReason}</Description>
                  ) : null}
                  {target.banExpires ? (
                    <Description>
                      {new Intl.DateTimeFormat(languageTag, {
                        dateStyle: "medium"
                      }).format(new Date(target.banExpires))}
                    </Description>
                  ) : null}
                  {allowed.update ? (
                    <Button
                      onPress={() => onAction({ type: "edit", user: target })}
                    >
                      {localization.saveUser}
                    </Button>
                  ) : null}
                  {allowed.role ? (
                    <Button
                      onPress={() => onAction({ type: "role", user: target })}
                    >
                      {localization.saveRole}
                    </Button>
                  ) : null}
                  {allowed.password ? (
                    <Button
                      onPress={() =>
                        onAction({ type: "password", user: target })
                      }
                    >
                      {localization.setPassword}
                    </Button>
                  ) : null}
                  {allowed.ban ? (
                    <Button
                      onPress={() =>
                        onAction({
                          type: target.banned ? "unban" : "ban",
                          user: target
                        })
                      }
                    >
                      {target.banned
                        ? localization.unbanUser
                        : localization.banUser}
                    </Button>
                  ) : null}
                  {allowed.impersonate &&
                  (!isAdminTarget(target, adminRoles, adminUserIds) ||
                    allowed.impersonateAdmin) ? (
                    <Button
                      onPress={() =>
                        onAction({ type: "impersonate", user: target })
                      }
                    >
                      {localization.impersonateUser}
                    </Button>
                  ) : null}
                  {allowed.remove ? (
                    <Button
                      variant="danger"
                      onPress={() => onAction({ type: "remove", user: target })}
                    >
                      {localization.deleteUser}
                    </Button>
                  ) : null}
                </>
              ) : null}
            </Box>
          </Tabs.Panel>
          <Tabs.Panel id="sessions">
            <Box className="gap-3">
              {sessions.isPending && allowed.sessions ? (
                <Skeleton className="h-10 w-full" />
              ) : null}
              {sessions.error ? (
                <Txt accessibilityRole="alert">{sessions.error.message}</Txt>
              ) : null}
              {sessions.data?.sessions.length === 0 ? (
                <Description>{localization.noSessions}</Description>
              ) : null}
              {sessions.data?.sessions.map((session) => (
                <Card key={session.id} variant={variant}>
                  <Card.Content className="gap-2">
                    <Description>{session.userAgent}</Description>
                    {showIpAddress && session.ipAddress ? (
                      <Description>{session.ipAddress}</Description>
                    ) : null}
                    <Description>
                      {new Intl.DateTimeFormat(languageTag, {
                        dateStyle: "medium",
                        timeStyle: "short"
                      }).format(new Date(session.createdAt))}
                    </Description>
                    {allowed.revoke ? (
                      <Button onPress={() => setToken(session.token)}>
                        {localization.revoke}
                      </Button>
                    ) : null}
                  </Card.Content>
                </Card>
              ))}
              {allowed.revoke ? (
                <Button
                  isDisabled={!sessions.data?.sessions.length}
                  onPress={() => setToken("all")}
                >
                  {localization.revokeAllSessions}
                </Button>
              ) : null}
            </Box>
          </Tabs.Panel>
          {contributions.map((item) => (
            <Tabs.Panel key={item.id} id={item.id}>
              <item.component userId={userId} />
            </Tabs.Panel>
          ))}
        </Tabs>
      </AlertDialog.Body>
      <AlertDialog.Footer>
        <Button onPress={onClose}>{localization.close}</Button>
      </AlertDialog.Footer>
      <AlertDialog
        isOpen={!!token}
        onOpenChange={(open) => {
          if (!open && !revoke.isPending && !revokeAll.isPending)
            setToken(undefined)
        }}
      >
        <AlertDialog.Header>
          <AlertDialog.Heading>
            {token === "all"
              ? localization.revokeAllSessions
              : localization.revoke}
          </AlertDialog.Heading>
        </AlertDialog.Header>
        <AlertDialog.Footer>
          <Button onPress={() => setToken(undefined)}>
            {localization.cancel}
          </Button>
          <Button
            variant="danger"
            isPending={revoke.isPending || revokeAll.isPending}
            onPress={() => {
              if (!token) return
              if (token === "all")
                revokeAll.mutate(
                  { userId },
                  { onSuccess: () => setToken(undefined) }
                )
              else
                revoke.mutate(
                  { sessionToken: token },
                  { onSuccess: () => setToken(undefined) }
                )
            }}
          >
            {localization.revoke}
          </Button>
        </AlertDialog.Footer>
      </AlertDialog>
    </AlertDialog>
  )
}

function AdminAction({
  action,
  onClose
}: {
  action: Action
  onClose: () => void
}) {
  const {
    authClient,
    localization: common,
    emailAndPassword,
    navigate,
    redirectTo
  } = useAuth()
  const {
    localization,
    roles,
    defaultRole,
    allowMultipleRoles,
    impersonationRedirectTo,
    adminRoles,
    adminUserIds
  } = useAuthPlugin(adminPlugin)
  const client = authClient as AdminAuthClient
  const allowed = useAdminActions()
  const create = useCreateAdminUser(client),
    update = useUpdateAdminUser(client),
    setRole = useSetAdminUserRole(client),
    password = useSetAdminUserPassword(client),
    ban = useBanAdminUser(client),
    unban = useUnbanAdminUser(client),
    remove = useRemoveAdminUser(client),
    impersonate = useImpersonateAdminUser(client)
  const pending = [
    create,
    update,
    setRole,
    password,
    ban,
    unban,
    remove,
    impersonate
  ].some((mutation) => mutation.isPending)
  const initial = action.type === "create" ? undefined : action.user
  const [selectedRoles, selectRoles] = useState(
    initial?.role?.split(",").filter(Boolean) ?? [defaultRole]
  )
  const form = useAuthForm({
    defaultValues: {
      name: initial?.name ?? "",
      email: initial?.email ?? "",
      password: "",
      banReason: "",
      banDuration: ""
    },
    onSubmit: async ({ value }) => {
      const userId = initial?.id ?? ""
      if (action.type === "create" && allowed.create)
        await create.mutateAsync({
          name: value.name.trim(),
          email: value.email.trim(),
          password: value.password,
          role: selectedRoles as Parameters<
            AdminAuthClient["admin"]["setRole"]
          >[0]["role"]
        })
      else if (action.type === "edit" && allowed.update)
        await update.mutateAsync({
          userId,
          data: { name: value.name.trim(), email: value.email.trim() }
        })
      else if (action.type === "role" && allowed.role)
        await setRole.mutateAsync({
          userId,
          role: selectedRoles as Parameters<
            AdminAuthClient["admin"]["setRole"]
          >[0]["role"]
        })
      else if (action.type === "password" && allowed.password) {
        try {
          await password.mutateAsync({ userId, newPassword: value.password })
        } finally {
          form.setFieldValue("password", "")
        }
      } else if (action.type === "ban" && allowed.ban)
        await ban.mutateAsync({
          userId,
          banReason: value.banReason.trim() || undefined,
          banExpiresIn: value.banDuration
            ? Number(value.banDuration) * 86400
            : undefined
        })
      else if (action.type === "unban" && allowed.ban)
        await unban.mutateAsync({ userId })
      else if (action.type === "remove" && allowed.remove)
        await remove.mutateAsync({ userId })
      else if (
        action.type === "impersonate" &&
        allowed.impersonate &&
        (!isAdminTarget(action.user, adminRoles, adminUserIds) ||
          allowed.impersonateAdmin)
      ) {
        await impersonate.mutateAsync({ userId })
        navigate({ to: impersonationRedirectTo ?? redirectTo })
      } else throw new Error(localization.accessDenied)
      onClose()
    }
  })
  const title = {
    create: localization.createUser,
    edit: localization.saveUser,
    role: localization.saveRole,
    password: localization.setPassword,
    ban: localization.banUser,
    unban: localization.unbanUser,
    remove: localization.deleteUser,
    impersonate: localization.impersonateUser
  }[action.type]
  return (
    <AlertDialog
      isOpen
      onOpenChange={(open) => {
        if (!open && !pending) onClose()
      }}
    >
      <AlertDialog.Header>
        <AlertDialog.Heading>{title}</AlertDialog.Heading>
      </AlertDialog.Header>
      <form.AppForm>
        <form.AuthFormRoot className="gap-4">
          <AlertDialog.Body>
            {action.type === "create" || action.type === "edit" ? (
              <>
                {(["name", "email"] as const).map((name) => (
                  <form.AppField
                    key={name}
                    name={name}
                    validators={{
                      onChange: ({ value }) =>
                        name === "email"
                          ? validateEmailAddress(value, {
                              requiredMessage: common.auth.fieldRequired,
                              invalidMessage: common.auth.invalidEmail
                            })
                          : validateStringLength(value, {
                              trim: true,
                              requiredMessage: common.auth.fieldRequired
                            })
                    }}
                  >
                    {(field) => (
                      <field.AuthFormTextField
                        label={localization[name]}
                        type={name === "email" ? "email" : "text"}
                        isDisabled={pending}
                      />
                    )}
                  </form.AppField>
                ))}
              </>
            ) : null}
            {action.type === "create" || action.type === "role" ? (
              <Box className="gap-2">
                <Txt>{localization.role}</Txt>
                {roles.map((role) => (
                  <Checkbox
                    key={role}
                    isSelected={selectedRoles.includes(role)}
                    isDisabled={pending}
                    onChange={(checked) =>
                      selectRoles(
                        allowMultipleRoles
                          ? checked
                            ? [...selectedRoles, role]
                            : selectedRoles.filter((value) => value !== role)
                          : [role]
                      )
                    }
                  >
                    {role}
                  </Checkbox>
                ))}
              </Box>
            ) : null}
            {action.type === "create" || action.type === "password" ? (
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: common.auth.fieldRequired,
                      minLength: emailAndPassword.minPasswordLength,
                      minLengthMessage: common.auth.tooShort.replace(
                        "{{min}}",
                        String(emailAndPassword.minPasswordLength)
                      ),
                      maxLength: emailAndPassword.maxPasswordLength,
                      maxLengthMessage: common.auth.tooLong.replace(
                        "{{max}}",
                        String(emailAndPassword.maxPasswordLength)
                      )
                    })
                }}
              >
                {(field) => (
                  <field.AuthFormPasswordField
                    label={localization.password}
                    strengthMeter
                    isPending={pending}
                  />
                )}
              </form.AppField>
            ) : null}
            {action.type === "ban" ? (
              <>
                <form.AppField name="banReason">
                  {(field) => (
                    <field.AuthFormTextField
                      label={localization.banReason}
                      isDisabled={pending}
                    />
                  )}
                </form.AppField>
                <form.AppField
                  name="banDuration"
                  validators={{
                    onChange: ({ value }) =>
                      value &&
                      (!Number.isFinite(Number(value)) || Number(value) <= 0)
                        ? common.auth.fieldRequired
                        : undefined
                  }}
                >
                  {(field) => (
                    <field.AuthFormTextField
                      label={localization.banDuration}
                      isDisabled={pending}
                    />
                  )}
                </form.AppField>
                <Description>{localization.banDurationDescription}</Description>
              </>
            ) : null}
            {initial ? <Description>{initial.email}</Description> : null}
          </AlertDialog.Body>
          <AlertDialog.Footer>
            <Button isDisabled={pending} onPress={onClose}>
              {localization.cancel}
            </Button>
            <form.AuthFormSubmitButton
              isPending={pending}
              isDisabled={
                (action.type === "create" || action.type === "role") &&
                !selectedRoles.length
              }
              variant={
                action.type === "remove" || action.type === "ban"
                  ? "danger"
                  : "primary"
              }
            >
              {title}
            </form.AuthFormSubmitButton>
          </AlertDialog.Footer>
        </form.AuthFormRoot>
      </form.AppForm>
    </AlertDialog>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/admin/admin-users.tsx
import {
  type AdminAuthClient,
  type AdminListUsersParams,
  adminPlugin
} from "@better-auth-ui/core/plugins/admin"
import { useAuth } from "@better-auth-ui/solid"
import {
  useAdminPermission,
  useAdminUser,
  useAdminUserSessions,
  useAdminUsers
} from "@better-auth-ui/solid/plugins/admin"
import { createDebounce } from "@solid-primitives/debounce"
import { Search } from "lucide-solid"
import { createMemo, createSignal, For, Show } from "solid-js"
import { Dynamic } from "solid-js/web"

import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import {
  Empty,
  EmptyDescription,
  EmptyHeader,
  EmptyTitle
} from "@/components/ui/empty"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import { Skeleton } from "@/components/ui/skeleton"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { cn } from "@/lib/utils"

import { UserAvatar } from "../user/user-avatar"

export type AdminUsersProps = {
  class?: string
  onSelectedUserIdChange?: (userId: string | undefined) => void
  selectedUserId?: string
}

const skeletonIds = ["solid-admin-1", "solid-admin-2", "solid-admin-3"]

const formatDate = (value: Date | string | undefined | null) =>
  value
    ? new Intl.DateTimeFormat(undefined, { dateStyle: "medium" }).format(
        new Date(value)
      )
    : "–"

/** Zaidan presentation for the static Admin users view. */
export function AdminUsers(props: AdminUsersProps) {
  const auth = useAuth()
  const authClient = auth.authClient as AdminAuthClient
  const defaults = adminPlugin()
  const config = () =>
    (auth.plugins.find((plugin) => plugin.id === adminPlugin.id) ??
      defaults) as typeof defaults
  const [localSelectedUserId, setLocalSelectedUserId] = createSignal<string>()
  const [page, setPage] = createSignal(0)
  const [search, setSearch] = createSignal("")
  const [debouncedSearch, setDebouncedSearch] = createSignal("")
  const [searchField, setSearchField] = createSignal<"email" | "name">("email")
  const updateDebouncedSearch = createDebounce(setDebouncedSearch, 300)
  const selectedUserId = () =>
    props.onSelectedUserIdChange ? props.selectedUserId : localSelectedUserId()
  const permission = useAdminPermission(authClient, () => ({ user: ["list"] }))
  const params = createMemo<AdminListUsersParams>(() => ({
    limit: config().pageSize,
    offset: page() * config().pageSize,
    searchField: searchField(),
    searchOperator: "contains",
    searchValue: debouncedSearch() || undefined,
    sortBy: "createdAt",
    sortDirection: "desc"
  }))
  const users = useAdminUsers(authClient, () => ({
    enabled: permission.data?.success === true,
    params: params()
  }))

  const selectUser = (userId: string | undefined) => {
    if (!props.onSelectedUserIdChange) setLocalSelectedUserId(userId)
    props.onSelectedUserIdChange?.(userId)
  }
  const total = () => users.data?.total ?? 0

  return (
    <section class={cn("flex flex-col gap-4", props.class)}>
      <header class="flex flex-col gap-1">
        <h1 class="text-xl font-semibold">{config().localization.users}</h1>
        <p class="text-sm text-muted-foreground">
          {config().localization.usersDescription}
        </p>
      </header>

      <div class="flex flex-col gap-2 sm:flex-row">
        <select
          aria-label={config().localization.search}
          class="h-8 rounded-lg border bg-transparent px-2 text-sm sm:w-36"
          onChange={(event) => {
            setSearchField(event.currentTarget.value as "email" | "name")
            setPage(0)
          }}
          value={searchField()}
        >
          <option value="email">{config().localization.email}</option>
          <option value="name">{config().localization.name}</option>
        </select>
        <InputGroup class="sm:max-w-md">
          <InputGroupAddon>
            <Search />
          </InputGroupAddon>
          <InputGroupInput
            aria-label={config().localization.search}
            onInput={(event) => {
              const value = event.currentTarget.value
              setSearch(value)
              setPage(0)
              updateDebouncedSearch(value.trim())
            }}
            placeholder={
              searchField() === "email"
                ? config().localization.searchByEmail
                : config().localization.searchByName
            }
            value={search()}
          />
        </InputGroup>
      </div>

      <Show
        fallback={
          <AdminMessage
            title={config().localization.accessDenied}
            description={config().localization.accessDeniedDescription}
          />
        }
        when={permission.isPending || permission.data?.success}
      >
        <Show
          fallback={
            <AdminMessage
              title={config().localization.loadUsersError}
              description={config().localization.loadUsersErrorDescription}
            />
          }
          when={!users.isError}
        >
          <div class="overflow-hidden rounded-lg border">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>{config().localization.name}</TableHead>
                  <TableHead>{config().localization.role}</TableHead>
                  <TableHead>{config().localization.status}</TableHead>
                  <TableHead>{config().localization.created}</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <Show
                  fallback={
                    <Show
                      fallback={
                        <TableRow>
                          <TableCell colspan="4">
                            <Empty class="min-h-48 gap-2 p-4">
                              <EmptyHeader class="gap-1">
                                <EmptyTitle>
                                  {config().localization.noUsers}
                                </EmptyTitle>
                                <EmptyDescription>
                                  {config().localization.noUsersDescription}
                                </EmptyDescription>
                              </EmptyHeader>
                            </Empty>
                          </TableCell>
                        </TableRow>
                      }
                      when={users.data?.users.length}
                    >
                      <For each={users.data?.users}>
                        {(user) => (
                          <TableRow
                            aria-selected={selectedUserId() === user.id}
                            class="cursor-pointer"
                            onClick={() => selectUser(user.id)}
                          >
                            <TableCell>
                              <div class="flex items-center gap-3">
                                <UserAvatar user={user} />
                                <div class="min-w-0">
                                  <Button
                                    class="h-auto min-w-0 justify-start p-0 font-medium"
                                    onClick={(event) => {
                                      event.stopPropagation()
                                      selectUser(user.id)
                                    }}
                                    variant="link"
                                  >
                                    <span class="truncate">{user.name}</span>
                                  </Button>
                                  <div class="truncate text-xs text-muted-foreground">
                                    {user.email}
                                  </div>
                                </div>
                              </div>
                            </TableCell>
                            <TableCell>
                              <Badge variant="outline">
                                {user.role ?? config().defaultRole}
                              </Badge>
                            </TableCell>
                            <TableCell>
                              <Badge
                                variant={
                                  user.banned ? "destructive" : "secondary"
                                }
                              >
                                {user.banned
                                  ? config().localization.banned
                                  : config().localization.active}
                              </Badge>
                            </TableCell>
                            <TableCell>{formatDate(user.createdAt)}</TableCell>
                          </TableRow>
                        )}
                      </For>
                    </Show>
                  }
                  when={permission.isPending || users.isPending}
                >
                  <For each={skeletonIds}>
                    {(id) => (
                      <TableRow>
                        <TableCell colspan="4">
                          <Skeleton class="h-10 w-full" data-id={id} />
                        </TableCell>
                      </TableRow>
                    )}
                  </For>
                </Show>
              </TableBody>
            </Table>
          </div>
        </Show>
      </Show>

      <footer class="flex items-center justify-between gap-2 text-sm text-muted-foreground">
        <span>
          {config()
            .localization.usersPaginationRange.replace(
              "{{from}}",
              String(total() ? page() * config().pageSize + 1 : 0)
            )
            .replace(
              "{{to}}",
              String(Math.min(total(), (page() + 1) * config().pageSize))
            )
            .replace("{{total}}", String(total()))}
        </span>
        <div class="flex gap-2">
          <Button
            disabled={page() === 0}
            onClick={() => setPage((value) => Math.max(0, value - 1))}
            variant="outline"
          >
            {config().localization.previousPage}
          </Button>
          <Button
            disabled={(page() + 1) * config().pageSize >= total()}
            onClick={() => setPage((value) => value + 1)}
            variant="outline"
          >
            {config().localization.nextPage}
          </Button>
        </div>
      </footer>

      <UserDialog
        open={Boolean(selectedUserId())}
        onOpenChange={(open) => !open && selectUser(undefined)}
        userId={selectedUserId}
      />
    </section>
  )
}

function AdminMessage(props: { description: string; title: string }) {
  return (
    <div class="flex min-h-64 flex-col items-center justify-center gap-1 rounded-lg border border-dashed p-8 text-center">
      <h2 class="font-medium">{props.title}</h2>
      <p class="text-sm text-muted-foreground">{props.description}</p>
    </div>
  )
}

function SessionRowsSkeleton() {
  return (
    <For each={skeletonIds}>
      {(id) => <Skeleton class="h-20 w-full" data-id={`session-${id}`} />}
    </For>
  )
}

function UserDialog(props: {
  open: boolean
  onOpenChange: (open: boolean) => void
  userId: () => string | undefined
}) {
  const auth = useAuth()
  const authClient = auth.authClient as AdminAuthClient
  const config = () =>
    (auth.plugins.find((plugin) => plugin.id === adminPlugin.id) ??
      adminPlugin()) as ReturnType<typeof adminPlugin>
  const contributedTabs = createMemo(() =>
    auth.plugins.flatMap((plugin) =>
      (plugin.adminUserTabs ?? []).map((tab) => ({
        ...tab,
        value: `${plugin.id}:${tab.id}`
      }))
    )
  )
  const user = useAdminUser(authClient, props.userId)
  const sessionsPermission = useAdminPermission(authClient, () => ({
    session: ["list"]
  }))
  const sessions = useAdminUserSessions(authClient, props.userId, () => ({
    enabled: sessionsPermission.data?.success === true
  }))

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent class="max-h-[90vh] max-w-lg overflow-y-auto rounded-xl border bg-popover p-4">
        <DialogHeader>
          <DialogTitle>{config().localization.userDetails}</DialogTitle>
          <DialogDescription>
            {user.data?.email ?? config().localization.usersDescription}
          </DialogDescription>
        </DialogHeader>
        <Show
          fallback={
            <AdminMessage
              title={config().localization.loadUsersError}
              description={config().localization.loadUsersErrorDescription}
            />
          }
          when={!user.isError}
        >
          <Show
            fallback={<Skeleton class="mt-4 h-40 w-full" />}
            when={user.data}
          >
            {(detail) => (
              <Tabs class="mt-4" defaultValue="overview">
                <TabsList>
                  <TabsTrigger value="overview">
                    {config().localization.overview}
                  </TabsTrigger>
                  <TabsTrigger value="sessions">
                    {config().localization.sessions}
                  </TabsTrigger>
                  <For each={contributedTabs()}>
                    {(tab) => (
                      <TabsTrigger value={tab.value}>
                        <Dynamic component={tab.label} />
                      </TabsTrigger>
                    )}
                  </For>
                </TabsList>
                <TabsContent class="flex flex-col gap-4 pt-4" value="overview">
                  <div class="flex items-center gap-3">
                    <UserAvatar class="size-12" user={detail()} />
                    <div>
                      <div class="font-medium">{detail().name}</div>
                      <div class="text-sm text-muted-foreground">
                        {detail().email}
                      </div>
                    </div>
                  </div>
                  <dl class="grid grid-cols-[auto_1fr] gap-3 text-sm">
                    <dt class="text-muted-foreground">
                      {config().localization.userId}
                    </dt>
                    <dd class="font-mono text-xs">{detail().id}</dd>
                    <dt class="text-muted-foreground">
                      {config().localization.role}
                    </dt>
                    <dd>{detail().role ?? config().defaultRole}</dd>
                    <dt class="text-muted-foreground">
                      {config().localization.created}
                    </dt>
                    <dd>{formatDate(detail().createdAt)}</dd>
                  </dl>
                </TabsContent>
                <TabsContent class="flex flex-col gap-2 pt-4" value="sessions">
                  <Show
                    fallback={<SessionRowsSkeleton />}
                    when={!sessionsPermission.isPending}
                  >
                    <Show
                      fallback={
                        <p class="py-8 text-center text-sm text-muted-foreground">
                          {config().localization.accessDeniedDescription}
                        </p>
                      }
                      when={sessionsPermission.data?.success}
                    >
                      <Show
                        fallback={<SessionRowsSkeleton />}
                        when={!sessions.isPending}
                      >
                        <Show
                          fallback={
                            <p class="py-8 text-center text-sm text-muted-foreground">
                              {config().localization.noSessions}
                            </p>
                          }
                          when={sessions.data?.sessions.length}
                        >
                          <For each={sessions.data?.sessions}>
                            {(session) => (
                              <div class="rounded-lg border p-3">
                                <div class="truncate text-sm font-medium">
                                  {session.userAgent ||
                                    config().localization.sessions}
                                </div>
                                <div class="text-xs text-muted-foreground">
                                  {formatDate(session.createdAt)} ·{" "}
                                  {formatDate(session.expiresAt)}
                                </div>
                                <Show
                                  when={
                                    config().showIpAddress && session.ipAddress
                                  }
                                >
                                  <div class="mt-1 font-mono text-xs text-muted-foreground">
                                    {session.ipAddress}
                                  </div>
                                </Show>
                              </div>
                            )}
                          </For>
                        </Show>
                      </Show>
                    </Show>
                  </Show>
                </TabsContent>
                <For each={contributedTabs()}>
                  {(tab) => (
                    <TabsContent class="pt-4" value={tab.value}>
                      <Dynamic component={tab.component} userId={detail().id} />
                    </TabsContent>
                  )}
                </For>
              </Tabs>
            )}
          </Show>
        </Show>
        <DialogFooter showCloseButton />
      </DialogContent>
    </Dialog>
  )
}
