// examples/start-solid-zaidan-example/src/components/auth/additional-field.tsx
import {
  type AdditionalField as AdditionalFieldConfig,
  resolveInputType
} from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import { CalendarIcon, Check, Copy } from "lucide-solid"
import { createEffect, createMemo, createSignal, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Combobox,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem
} from "@/components/ui/combobox"
import {
  Field,
  FieldContent,
  FieldError,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select"
import {
  Popover,
  PopoverContent,
  PopoverTrigger
} from "@/components/ui/popover"
import { Slider } from "@/components/ui/slider"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"

export type AdditionalFieldProps = {
  field: AdditionalFieldConfig
  isPending?: boolean
  name: string
  /** Complete suffix appended to labels for fields that are not required. */
  optionalLabel?: string
}

const valueToString = (value: AdditionalFieldConfig["defaultValue"]) =>
  value == null
    ? ""
    : value instanceof Date
      ? value.toISOString()
      : String(value)

const toDate = (value: AdditionalFieldConfig["defaultValue"]) => {
  if (value instanceof Date) return value
  if (typeof value !== "string") return undefined

  const parsed = new Date(value)
  return Number.isNaN(parsed.getTime()) ? undefined : parsed
}

const formatTime = (date: Date) => {
  const pad = (value: number) => value.toString().padStart(2, "0")
  return `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`
}

export function AdditionalField(props: AdditionalFieldProps) {
  const inputType = () => resolveInputType(props.field)
  const label = () =>
    props.optionalLabel && !props.field.required
      ? `${String(props.field.label)}${props.optionalLabel}`
      : props.field.label

  if (props.field.render) {
    return (
      <>
        {props.field.render({
          ...props,
          field:
            label() === props.field.label
              ? props.field
              : { ...props.field, label: label() }
        })}
      </>
    )
  }

  if (inputType() === "hidden") {
    return (
      <input
        name={props.name}
        type="hidden"
        value={valueToString(props.field.defaultValue)}
      />
    )
  }

  if (inputType() === "textarea") {
    return (
      <Field>
        <FieldLabel for={props.name}>{label()}</FieldLabel>
        <Textarea
          disabled={props.isPending}
          id={props.name}
          name={props.name}
          placeholder={props.field.placeholder}
          readonly={props.field.readOnly}
          required={props.field.required}
          value={valueToString(props.field.defaultValue)}
        />
        <FieldError />
      </Field>
    )
  }

  if (inputType() === "number") {
    const maxFractionDigits = props.field.formatOptions?.maximumFractionDigits

    return (
      <Field>
        <FieldLabel for={props.name}>{label()}</FieldLabel>
        <Input
          disabled={props.isPending}
          id={props.name}
          inputmode={maxFractionDigits ? "decimal" : "numeric"}
          max={props.field.max}
          min={props.field.min}
          name={props.name}
          placeholder={props.field.placeholder}
          readonly={props.field.readOnly}
          required={props.field.required}
          step={
            props.field.step ??
            (maxFractionDigits ? 1 / 10 ** maxFractionDigits : undefined)
          }
          type="number"
          value={valueToString(props.field.defaultValue)}
        />
        <FieldError />
      </Field>
    )
  }

  if (inputType() === "slider") {
    return <SliderField {...props} label={label()} />
  }

  if (inputType() === "switch") {
    return (
      <Field orientation="horizontal">
        <Switch
          defaultChecked={
            props.field.defaultValue === true ||
            valueToString(props.field.defaultValue) === "true"
          }
          disabled={props.isPending || props.field.readOnly}
          id={props.name}
          name={props.name}
          required={props.field.required}
        />
        <FieldContent>
          <FieldLabel for={props.name}>{label()}</FieldLabel>
        </FieldContent>
      </Field>
    )
  }

  if (inputType() === "checkbox") {
    return (
      <Field orientation="horizontal">
        <Checkbox
          defaultChecked={
            props.field.defaultValue === true ||
            valueToString(props.field.defaultValue) === "true"
          }
          disabled={props.isPending || props.field.readOnly}
          id={props.name}
          name={props.name}
          required={props.field.required}
        />
        <FieldContent>
          <FieldLabel for={props.name}>{label()}</FieldLabel>
        </FieldContent>
      </Field>
    )
  }

  if (inputType() === "select") {
    return (
      <Field>
        <FieldLabel for={props.name}>{label()}</FieldLabel>
        <NativeSelect
          class="w-full"
          disabled={props.isPending || props.field.readOnly}
          id={props.name}
          name={props.name}
          required={props.field.required}
          value={valueToString(props.field.defaultValue)}
        >
          <Show when={props.field.placeholder}>
            <NativeSelectOption disabled value="">
              {props.field.placeholder}
            </NativeSelectOption>
          </Show>
          <For each={props.field.options ?? []}>
            {(option) => (
              <NativeSelectOption value={option.value}>
                {option.label}
              </NativeSelectOption>
            )}
          </For>
        </NativeSelect>
        <FieldError />
      </Field>
    )
  }

  if (inputType() === "combobox") {
    const options = props.field.options ?? []
    const initialValue = options.find(
      (option) => option.value === valueToString(props.field.defaultValue)
    )

    return (
      <Field>
        <FieldLabel for={props.name}>{label()}</FieldLabel>
        <Combobox
          defaultValue={initialValue}
          disabled={props.isPending || props.field.readOnly}
          itemComponent={(itemProps) => (
            <ComboboxItem item={itemProps.item}>
              {itemProps.item.rawValue.label}
            </ComboboxItem>
          )}
          name={props.name}
          optionLabel="label"
          optionTextValue="label"
          optionValue="value"
          options={options}
          placeholder={props.field.placeholder}
          required={props.field.required}
        >
          <ComboboxInput
            class="w-full"
            id={props.name}
            placeholder={props.field.placeholder}
          />
          <ComboboxContent>
            <ComboboxEmpty>No items found.</ComboboxEmpty>
          </ComboboxContent>
        </Combobox>
        <FieldError />
      </Field>
    )
  }

  if (inputType() === "date" || inputType() === "datetime") {
    return <DateInput {...props} label={label()} />
  }

  return <InputField {...props} label={label()} />
}

type LabeledAdditionalFieldProps = AdditionalFieldProps & {
  label: AdditionalFieldConfig["label"]
}

function InputField(props: LabeledAdditionalFieldProps) {
  const auth = useAuth()
  const [copied, setCopied] = createSignal(false)
  let inputRef: HTMLInputElement | undefined
  const hasPrefix = () => props.field.prefix != null
  const hasSuffix = () =>
    props.field.suffix != null || props.field.copyable === true

  const copyValue = async () => {
    if (!inputRef?.value) return

    try {
      await navigator.clipboard.writeText(inputRef.value)
      setCopied(true)
      window.setTimeout(() => setCopied(false), 1500)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
    }
  }

  if (hasPrefix() || hasSuffix()) {
    return (
      <Field>
        <FieldLabel for={props.name}>{props.label}</FieldLabel>
        <InputGroup>
          <Show when={props.field.prefix}>
            <InputGroupAddon align="inline-start">
              {props.field.prefix}
            </InputGroupAddon>
          </Show>
          <InputGroupInput
            disabled={props.isPending}
            id={props.name}
            name={props.name}
            placeholder={props.field.placeholder}
            readonly={props.field.readOnly}
            ref={inputRef}
            required={props.field.required}
            value={valueToString(props.field.defaultValue)}
          />
          <Show
            when={props.field.copyable}
            fallback={
              <Show when={props.field.suffix}>
                <InputGroupAddon align="inline-end">
                  {props.field.suffix}
                </InputGroupAddon>
              </Show>
            }
          >
            <InputGroupAddon align="inline-end">
              <InputGroupButton
                aria-label={auth.localization.settings.copyToClipboard}
                disabled={props.isPending}
                onClick={copyValue}
                title={auth.localization.settings.copyToClipboard}
              >
                <Show when={copied()} fallback={<Copy />}>
                  <Check />
                </Show>
              </InputGroupButton>
            </InputGroupAddon>
          </Show>
        </InputGroup>
        <FieldError />
      </Field>
    )
  }

  return (
    <Field>
      <FieldLabel for={props.name}>{props.label}</FieldLabel>
      <Input
        disabled={props.isPending}
        id={props.name}
        name={props.name}
        placeholder={props.field.placeholder}
        readonly={props.field.readOnly}
        required={props.field.required}
        value={valueToString(props.field.defaultValue)}
      />
      <FieldError />
    </Field>
  )
}

function SliderField(props: LabeledAdditionalFieldProps) {
  const maxFractionDigits = props.field.formatOptions?.maximumFractionDigits
  const min = props.field.min ?? 0
  const max = props.field.max ?? 100
  const step =
    props.field.step ?? (maxFractionDigits ? 1 / 10 ** maxFractionDigits : 1)
  const defaultValue = () =>
    typeof props.field.defaultValue === "number"
      ? props.field.defaultValue
      : props.field.defaultValue != null &&
          !Number.isNaN(Number(props.field.defaultValue))
        ? Number(props.field.defaultValue)
        : min
  const [value, setValue] = createSignal(defaultValue())
  const [isDirty, setIsDirty] = createSignal(false)
  const formatter = new Intl.NumberFormat(undefined, props.field.formatOptions)

  createEffect(() => {
    const nextValue = defaultValue()
    if (!isDirty()) setValue(nextValue)
  })

  return (
    <Field>
      <div class="flex items-center justify-between gap-2">
        <FieldLabel for={props.name}>{props.label}</FieldLabel>
        <span class="text-muted-foreground text-sm tabular-nums">
          {formatter.format(value())}
        </span>
      </div>
      <Slider
        disabled={props.isPending || props.field.readOnly}
        id={props.name}
        maxValue={max}
        minValue={min}
        name={props.name}
        onChange={(values) => {
          setIsDirty(true)
          setValue(values[0] ?? min)
        }}
        step={step}
        value={[value()]}
      />
      <FieldError />
    </Field>
  )
}

function DateInput(props: LabeledAdditionalFieldProps) {
  const auth = useAuth()
  const isDateTime = () => resolveInputType(props.field) === "datetime"
  const defaultDate = () => toDate(props.field.defaultValue)
  const initialDate = defaultDate()
  const [date, setDate] = createSignal<Date | undefined>(initialDate)
  const [time, setTime] = createSignal(
    initialDate && isDateTime() ? formatTime(initialDate) : ""
  )
  const [isDirty, setIsDirty] = createSignal(false)
  const [open, setOpen] = createSignal(false)
  const [error, setError] = createSignal<string>()

  createEffect(() => {
    const nextDate = defaultDate()
    if (isDirty()) return

    setDate(nextDate)
    setTime(nextDate && isDateTime() ? formatTime(nextDate) : "")
    if (nextDate) setError(undefined)
  })

  const formValue = createMemo(() => {
    const selectedDate = date()
    if (!selectedDate) return ""

    const value = new Date(selectedDate)
    if (isDateTime() && time().trim()) {
      const [hours = "0", minutes = "0", seconds = "0"] = time().split(":")
      value.setHours(Number(hours), Number(minutes), Number(seconds), 0)
    } else {
      value.setHours(0, 0, 0, 0)
    }
    return value.toISOString()
  })

  return (
    <Field data-invalid={Boolean(error())}>
      <FieldLabel for={`${props.name}-date`}>{props.label}</FieldLabel>
      <div class="relative flex gap-2">
        <input
          aria-label={props.label}
          class="sr-only"
          name={props.name}
          onInvalid={(event) => {
            event.preventDefault()
            setError(event.currentTarget.validationMessage)
          }}
          required={props.field.required}
          tabindex={-1}
          type="text"
          value={formValue()}
        />
        <Popover onOpenChange={setOpen} open={open()}>
          <PopoverTrigger
            aria-invalid={Boolean(error())}
            as={Button}
            class="flex-1 justify-between font-normal data-[empty=true]:text-muted-foreground"
            data-empty={!date()}
            disabled={props.isPending || props.field.readOnly}
            id={`${props.name}-date`}
            type="button"
            variant="outline"
          >
            <Show when={date()} fallback={props.field.placeholder}>
              {(selectedDate) => selectedDate().toLocaleDateString()}
            </Show>
            <CalendarIcon />
          </PopoverTrigger>
          <PopoverContent class="w-auto overflow-hidden p-0">
            <Calendar
              defaultMonth={date()}
              mode="single"
              monthYearSelection
              onValueChange={(value) => {
                setIsDirty(true)
                setDate(value ?? undefined)
                if (value) setError(undefined)
                if (!isDateTime()) setOpen(false)
              }}
              value={date() ?? null}
            />
          </PopoverContent>
        </Popover>
        <Show when={isDateTime()}>
          <Field class="w-32">
            <FieldLabel class="sr-only" for={`${props.name}-time`}>
              {auth.localization.settings.time}
            </FieldLabel>
            <Input
              class="appearance-none bg-background [&::-webkit-calendar-picker-indicator]:hidden"
              disabled={props.isPending || props.field.readOnly}
              id={`${props.name}-time`}
              onInput={(event) => {
                setIsDirty(true)
                setTime(event.currentTarget.value)
              }}
              step="1"
              type="time"
              value={time()}
            />
          </Field>
        </Show>
      </div>
      <FieldError>{error()}</FieldError>
    </Field>
  )
}

// examples/start-shadcn-baseui-example/src/components/auth/additional-field.tsx
"use client"

import {
  type AdditionalField as AdditionalFieldConfig,
  resolveInputType
} from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/react"
import { format } from "date-fns"
import { CalendarIcon, Check, ChevronDownIcon, Copy } from "lucide-react"
import { type ComponentType, useRef, useState } from "react"
import { toast } from "sonner"

import { buttonVariants } from "@/components/ui/button"
import { Calendar } from "@/components/ui/calendar"
import { Checkbox } from "@/components/ui/checkbox"
import {
  Combobox,
  ComboboxContent,
  ComboboxEmpty,
  ComboboxInput,
  ComboboxItem,
  ComboboxList
} from "@/components/ui/combobox"
import {
  Field,
  FieldContent,
  FieldError,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Popover,
  PopoverContent,
  PopoverTrigger
} from "@/components/ui/popover"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"
import { Slider } from "@/components/ui/slider"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { cn } from "@/lib/utils"

export type AdditionalFieldProps = {
  name: string
  field: AdditionalFieldConfig
  isPending?: boolean
  /** Complete suffix appended to labels for fields that are not required. */
  optionalLabel?: string
}

/** Convert a `defaultValue` into a `Date` for the calendar. */
function toDate(value: unknown): Date | undefined {
  if (value instanceof Date) return value
  if (typeof value === "string") {
    const parsed = new Date(value)
    return Number.isNaN(parsed.getTime()) ? undefined : parsed
  }
  return undefined
}

/** Format a Date as `HH:mm:ss` for an `<input type="time">`. */
function formatTime(date: Date) {
  const pad = (n: number) => n.toString().padStart(2, "0")
  return `${pad(date.getHours())}:${pad(date.getMinutes())}:${pad(date.getSeconds())}`
}

/**
 * Icon-only copy button used as an `InputGroupAddon`. `getValue` is invoked
 * lazily on click so the button copies the input's *live* value rather than a
 * stale snapshot — important when paired with editable inputs.
 */
function CopyButton({
  getValue,
  isDisabled
}: {
  getValue: () => string | undefined
  isDisabled?: boolean
}) {
  const { localization } = useAuth()
  const [copied, setCopied] = useState(false)

  async function handleCopy() {
    const value = getValue()
    if (!value) return

    try {
      await navigator.clipboard.writeText(value)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
    }
  }

  return (
    <InputGroupButton
      aria-label={localization.settings.copyToClipboard}
      title={localization.settings.copyToClipboard}
      onClick={handleCopy}
      disabled={isDisabled}
    >
      {copied ? <Check /> : <Copy />}
    </InputGroupButton>
  )
}

/** Renders a single additional user field via shadcn primitives. */
export function AdditionalField({
  name,
  field: configuredField,
  isPending,
  optionalLabel
}: AdditionalFieldProps) {
  const field =
    optionalLabel && !configuredField.required
      ? {
          ...configuredField,
          label: (
            <>
              {configuredField.label}
              {optionalLabel}
            </>
          )
        }
      : configuredField
  const inputType = resolveInputType(field)

  if (field.render) {
    const FieldRenderer = field.render as ComponentType<AdditionalFieldProps>
    return (
      <FieldRenderer
        name={name}
        field={field}
        isPending={isPending}
        optionalLabel={optionalLabel}
      />
    )
  }

  if (inputType === "hidden") {
    return (
      <input
        type="hidden"
        name={name}
        value={
          field.defaultValue == null
            ? ""
            : field.defaultValue instanceof Date
              ? field.defaultValue.toISOString()
              : String(field.defaultValue)
        }
      />
    )
  }

  if (inputType === "textarea") {
    return (
      <Field>
        <FieldLabel htmlFor={name}>{field.label}</FieldLabel>

        <Textarea
          id={name}
          name={name}
          defaultValue={
            field.defaultValue == null ? undefined : String(field.defaultValue)
          }
          placeholder={field.placeholder}
          required={field.required}
          readOnly={field.readOnly}
          disabled={isPending}
        />

        <FieldError />
      </Field>
    )
  }

  if (inputType === "number") {
    const maxFractionDigits = field.formatOptions?.maximumFractionDigits

    return (
      <Field>
        <FieldLabel htmlFor={name}>{field.label}</FieldLabel>

        <Input
          id={name}
          name={name}
          type="number"
          inputMode={maxFractionDigits ? "decimal" : "numeric"}
          min={field.min}
          max={field.max}
          step={
            field.step ??
            (maxFractionDigits ? 1 / 10 ** maxFractionDigits : undefined)
          }
          defaultValue={
            field.defaultValue == null
              ? undefined
              : typeof field.defaultValue === "number"
                ? field.defaultValue
                : String(field.defaultValue)
          }
          placeholder={field.placeholder}
          required={field.required}
          readOnly={field.readOnly}
          disabled={isPending}
        />

        <FieldError />
      </Field>
    )
  }

  if (inputType === "slider") {
    return <SliderField name={name} field={field} isPending={isPending} />
  }

  if (inputType === "switch") {
    return (
      <Field orientation="horizontal">
        <Switch
          id={name}
          name={name}
          defaultChecked={
            field.defaultValue === true || field.defaultValue === "true"
          }
          disabled={isPending || field.readOnly}
        />

        <FieldContent>
          <FieldLabel htmlFor={name}>{field.label}</FieldLabel>
        </FieldContent>
      </Field>
    )
  }

  if (inputType === "checkbox") {
    return (
      <Field orientation="horizontal">
        <Checkbox
          id={name}
          name={name}
          defaultChecked={
            field.defaultValue === true || field.defaultValue === "true"
          }
          required={field.required}
          disabled={isPending || field.readOnly}
        />

        <FieldContent>
          <FieldLabel htmlFor={name}>{field.label}</FieldLabel>
        </FieldContent>
      </Field>
    )
  }

  if (inputType === "select") {
    return (
      <Field>
        <FieldLabel htmlFor={name}>{field.label}</FieldLabel>

        <Select
          name={name}
          defaultValue={
            field.defaultValue != null ? String(field.defaultValue) : undefined
          }
          required={field.required}
          disabled={isPending || field.readOnly}
        >
          <SelectTrigger id={name} className="w-full">
            <SelectValue placeholder={field.placeholder} />
          </SelectTrigger>

          <SelectContent>
            {field.options?.map((option) => (
              <SelectItem key={option.value} value={option.value}>
                {option.label}
              </SelectItem>
            ))}
          </SelectContent>
        </Select>

        <FieldError />
      </Field>
    )
  }

  if (inputType === "combobox") {
    return (
      <Field>
        <FieldLabel htmlFor={name}>{field.label}</FieldLabel>

        <Combobox
          items={field.options ?? []}
          name={name}
          defaultValue={
            field.defaultValue != null ? String(field.defaultValue) : undefined
          }
          required={field.required}
          disabled={isPending || field.readOnly}
        >
          <ComboboxInput placeholder={field.placeholder} id={name} />

          <ComboboxContent>
            <ComboboxEmpty>No items found.</ComboboxEmpty>

            <ComboboxList>
              {(option) => (
                <ComboboxItem key={option.value} value={option}>
                  {option.label}
                </ComboboxItem>
              )}
            </ComboboxList>
          </ComboboxContent>
        </Combobox>

        <FieldError />
      </Field>
    )
  }

  if (inputType === "date" || inputType === "datetime") {
    return <DateInput name={name} field={field} isPending={isPending} />
  }

  return <InputField name={name} field={field} isPending={isPending} />
}

function InputField({ name, field, isPending }: AdditionalFieldProps) {
  const inputRef = useRef<HTMLInputElement>(null)

  const hasPrefix = field.prefix != null
  const hasSuffix = field.suffix != null || field.copyable

  const isNumeric = field.type === "number"
  const maxFractionDigits = field.formatOptions?.maximumFractionDigits
  const nativeInputType = isNumeric ? "number" : undefined
  const nativeInputMode = isNumeric
    ? maxFractionDigits
      ? "decimal"
      : "numeric"
    : undefined
  const nativeStep = maxFractionDigits ? 1 / 10 ** maxFractionDigits : undefined

  if (hasPrefix || hasSuffix) {
    return (
      <Field>
        <FieldLabel htmlFor={name}>{field.label}</FieldLabel>

        <InputGroup>
          {hasPrefix && (
            <InputGroupAddon align="inline-start">
              {field.prefix}
            </InputGroupAddon>
          )}

          <InputGroupInput
            ref={inputRef}
            id={name}
            name={name}
            type={nativeInputType}
            inputMode={nativeInputMode}
            step={nativeStep}
            defaultValue={
              field.defaultValue == null
                ? undefined
                : String(field.defaultValue)
            }
            placeholder={field.placeholder}
            required={field.required}
            readOnly={field.readOnly}
            disabled={isPending}
          />

          {field.copyable ? (
            <InputGroupAddon align="inline-end">
              <CopyButton
                getValue={() => inputRef.current?.value}
                isDisabled={isPending}
              />
            </InputGroupAddon>
          ) : (
            field.suffix != null && (
              <InputGroupAddon align="inline-end">
                {field.suffix}
              </InputGroupAddon>
            )
          )}
        </InputGroup>

        <FieldError />
      </Field>
    )
  }

  return (
    <Field>
      <FieldLabel htmlFor={name}>{field.label}</FieldLabel>

      <Input
        id={name}
        name={name}
        type={nativeInputType}
        inputMode={nativeInputMode}
        step={nativeStep}
        defaultValue={
          field.defaultValue == null ? undefined : String(field.defaultValue)
        }
        placeholder={field.placeholder}
        required={field.required}
        readOnly={field.readOnly}
        disabled={isPending}
      />

      <FieldError />
    </Field>
  )
}

/**
 * Slider field. Radix Slider doesn't render the current value, so we render
 * it next to the label and control the state to keep the displayed value in
 * sync. The selected value is submitted via the underlying Radix `name` prop.
 */
function SliderField({ name, field, isPending }: AdditionalFieldProps) {
  const maxFractionDigits = field.formatOptions?.maximumFractionDigits
  const min = field.min ?? 0
  const max = field.max ?? 100
  const step =
    field.step ?? (maxFractionDigits ? 1 / 10 ** maxFractionDigits : 1)
  const initial =
    typeof field.defaultValue === "number"
      ? field.defaultValue
      : field.defaultValue != null && !Number.isNaN(Number(field.defaultValue))
        ? Number(field.defaultValue)
        : min

  const [value, setValue] = useState<number>(initial)

  const formatter = new Intl.NumberFormat(undefined, field.formatOptions)

  return (
    <Field>
      <div className="flex items-center justify-between gap-2">
        <FieldLabel htmlFor={name}>{field.label}</FieldLabel>
        <span className="text-sm text-muted-foreground tabular-nums">
          {formatter.format(value)}
        </span>
      </div>

      <Slider
        id={name}
        name={name}
        value={[value]}
        onValueChange={(v) => setValue((Array.isArray(v) ? v[0] : v) ?? min)}
        min={min}
        max={max}
        step={step}
        disabled={isPending || field.readOnly}
      />

      <FieldError />
    </Field>
  )
}

/**
 * Date / datetime input. Composes `Popover` + `Calendar` for the date and
 * (optionally) `<input type="time">` for the time. Submits the combined ISO
 * value via a hidden `<input>` so it shows up in `FormData`.
 */
function DateInput({ name, field, isPending }: AdditionalFieldProps) {
  const { localization } = useAuth()
  const inputType = resolveInputType(field)
  const isDateTime = inputType === "datetime"

  const [date, setDate] = useState<Date | undefined>(toDate(field.defaultValue))
  const [time, setTime] = useState<string>(
    isDateTime && date ? formatTime(date) : ""
  )
  const [open, setOpen] = useState(false)
  const [error, setError] = useState<string>()

  // Compose the hidden form value: ISO date for "date", ISO datetime for
  // "datetime" (date + time).
  let formValue = ""
  if (date) {
    if (isDateTime && time && time.trim() !== "") {
      const [h = "0", m = "0", s = "0"] = time.split(":")
      const combined = new Date(date)
      combined.setHours(Number(h), Number(m), Number(s), 0)
      formValue = combined.toISOString()
    } else {
      // Anchor to local midnight then serialize as ISO so the downstream
      // `parseAdditionalFieldValue` parses the same calendar day regardless
      // of timezone (a bare "YYYY-MM-DD" would be parsed as UTC midnight).
      // Datetime fields with a blank time also fall through here, defaulting
      // the time to local midnight since the parsed value is always a `Date`.
      const localMidnight = new Date(date)
      localMidnight.setHours(0, 0, 0, 0)
      formValue = localMidnight.toISOString()
    }
  }

  return (
    <Field data-invalid={!!error}>
      <FieldLabel htmlFor={`${name}-date`}>{field.label}</FieldLabel>

      <div className="relative flex gap-2">
        {/* Visually-hidden input so required constraint validation fires on submit.
            onInvalid suppresses the native browser balloon and routes the message
            through the styled <FieldError> below — matching the pattern used by
            the Name / Email / Password fields in the sign-up form. */}
        <input
          type="text"
          name={name}
          value={formValue}
          onChange={() => {}}
          required={field.required}
          tabIndex={-1}
          aria-hidden="true"
          className="pointer-events-none absolute inset-0 h-full w-full opacity-0"
          onInvalid={(e) => {
            e.preventDefault()
            setError((e.target as HTMLInputElement).validationMessage)
          }}
        />
        <Popover open={open} onOpenChange={setOpen}>
          <PopoverTrigger
            type="button"
            id={`${name}-date`}
            data-empty={!date}
            aria-invalid={!!error}
            disabled={isPending || field.readOnly}
            className={cn(
              buttonVariants({ variant: "outline" }),
              "flex-1 justify-between font-normal",
              "data-[empty=true]:text-muted-foreground"
            )}
          >
            {date ? format(date, "PPP") : <span>{field.placeholder}</span>}

            {isDateTime ? <ChevronDownIcon /> : <CalendarIcon />}
          </PopoverTrigger>

          <PopoverContent className="w-auto overflow-hidden p-0" align="start">
            <Calendar
              mode="single"
              selected={date}
              defaultMonth={date}
              captionLayout="dropdown"
              onSelect={(value) => {
                setDate(value)
                if (value) setError(undefined)
                if (!isDateTime) setOpen(false)
              }}
            />
          </PopoverContent>
        </Popover>

        {isDateTime && (
          <Field className="w-32">
            <FieldLabel htmlFor={`${name}-time`} className="sr-only">
              {localization.settings.time}
            </FieldLabel>

            <Input
              type="time"
              id={`${name}-time`}
              step="1"
              value={time}
              onChange={(e) => setTime(e.target.value)}
              disabled={isPending || field.readOnly}
              className="appearance-none bg-background [&::-webkit-calendar-picker-indicator]:hidden [&::-webkit-calendar-picker-indicator]:appearance-none"
            />
          </Field>
        )}
      </div>

      <FieldError>{error}</FieldError>
    </Field>
  )
}
