// examples/start-solid-zaidan-example/src/components/auth/open-email-button.tsx
import { createQrCodeSvgData, getEmailProviderLink } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import { QrCode } from "lucide-solid"
import { Show } from "solid-js"
import { buttonVariants } from "@/components/ui/button"
import {
  Tooltip,
  TooltipContent,
  TooltipTrigger
} from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"

export type OpenEmailButtonProps = {
  email: string
  class?: string
}

/**
 * Button that opens the user's email provider login page in a new tab.
 * Hovering or focusing the button reveals a QR code for opening the same
 * provider on another device. The provider is resolved from the email domain
 * via the curated `@mikkelscheike/email-provider-links` dataset (Gmail,
 * Outlook, GMX, etc.) and nothing is rendered when the domain is empty or not
 * a known provider.
 */
export function OpenEmailButton(props: OpenEmailButtonProps) {
  const auth = useAuth()
  const provider = () => getEmailProviderLink(props.email)

  return (
    <Show when={provider()} keyed>
      {(emailProvider) => {
        const scanLabel =
          auth.localization.auth.scanToOpenEmailProvider.replace(
            "{{provider}}",
            emailProvider.companyProvider
          )
        const qrCode = createQrCodeSvgData(emailProvider.loginUrl)

        return (
          <Tooltip>
            <TooltipTrigger
              type="button"
              class={cn(buttonVariants(), "w-full", props.class)}
              onClick={() =>
                window.open(
                  emailProvider.loginUrl,
                  "_blank",
                  "noopener,noreferrer"
                )
              }
            >
              {auth.localization.auth.openEmailProvider.replace(
                "{{provider}}",
                emailProvider.companyProvider
              )}
              <QrCode />
            </TooltipTrigger>
            <TooltipContent class="flex flex-col items-center gap-2 p-3">
              <svg
                viewBox={`0 0 ${qrCode.size} ${qrCode.size}`}
                aria-hidden="true"
                class="size-40"
              >
                <path
                  fill="white"
                  d={`M0 0h${qrCode.size}v${qrCode.size}H0z`}
                />
                <path
                  fill="black"
                  d={qrCode.path}
                  shape-rendering="crispEdges"
                />
              </svg>
              <p class="max-w-40 text-center leading-snug">{scanLabel}</p>
            </TooltipContent>
          </Tooltip>
        )
      }}
    </Show>
  )
}

// examples/start-shadcn-baseui-example/src/components/auth/open-email-button.tsx
"use client"

import { createQrCodeSvgData, getEmailProviderLink } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/react"
import { QrCode } from "lucide-react"
import { useMemo } from "react"

import { buttonVariants } from "@/components/ui/button"
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger
} from "@/components/ui/tooltip"
import { cn } from "@/lib/utils"

export type OpenEmailButtonProps = {
  /** Email address used to detect the provider, e.g. from the verify-email flow. */
  email: string
  className?: string
}

/**
 * Render a button that opens the user's email provider login page in a new
 * tab. Hovering or focusing the button reveals a QR code for opening the same
 * provider on another device.
 *
 * The provider is resolved from the email domain via the curated
 * `@mikkelscheike/email-provider-links` dataset (Gmail, Outlook, GMX, etc.).
 * Renders nothing when the domain is empty or not a known provider.
 *
 * @param email - Email address to resolve the provider from.
 * @param className - Additional CSS classes applied to the button.
 * @returns The open-email button, or `null` when no provider matches.
 */
export function OpenEmailButton({ email, className }: OpenEmailButtonProps) {
  const { localization } = useAuth()

  const provider = getEmailProviderLink(email)
  const loginUrl = provider?.loginUrl
  const qrCode = useMemo(
    () => (loginUrl ? createQrCodeSvgData(loginUrl) : null),
    [loginUrl]
  )

  if (!provider || !qrCode) return null

  const scanLabel = localization.auth.scanToOpenEmailProvider.replace(
    "{{provider}}",
    provider.companyProvider
  )

  return (
    <TooltipProvider>
      <Tooltip>
        <TooltipTrigger
          type="button"
          className={cn(buttonVariants(), "w-full", className)}
          onClick={() =>
            window.open(provider.loginUrl, "_blank", "noopener,noreferrer")
          }
        >
          {localization.auth.openEmailProvider.replace(
            "{{provider}}",
            provider.companyProvider
          )}
          <QrCode />
        </TooltipTrigger>
        <TooltipContent
          sideOffset={8}
          className="flex-col items-center gap-2 p-3"
        >
          <svg
            viewBox={`0 0 ${qrCode.size} ${qrCode.size}`}
            aria-hidden="true"
            focusable="false"
            className="size-40"
          >
            <path fill="white" d={`M0 0h${qrCode.size}v${qrCode.size}H0z`} />
            <path fill="black" d={qrCode.path} shapeRendering="crispEdges" />
          </svg>
          <p className="max-w-40 text-center leading-snug">{scanLabel}</p>
        </TooltipContent>
      </Tooltip>
    </TooltipProvider>
  )
}
