// packages/react-native/src/components/auth/auth.tsx
import type { AuthView } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/react"
import { type ComponentType, useEffect } from "react"
import { useAuthNavigation } from "../../navigation/navigation-context"
import type { CardVariant } from "../../primitives/card"
import { AuthCallback, AuthError } from "./auth-result"
import { AuthRedirect } from "./auth-redirect"
import { ResetLinkSent } from "./email-link-sent"
import { ForgotPassword } from "./forgot-password"
import type { SocialLayout } from "./provider-buttons"
import { ResetPassword } from "./reset-password"
import { SignIn } from "./sign-in"
import { SignOut } from "./sign-out"
import { SignUp } from "./sign-up"
import { VerifyEmail } from "./verify-email"

export type AuthProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardVariant
  /** Explicit view. Omit under the state adapter to use the adapter's view. */
  view?: AuthView
  /** Deep-link token for token-bearing views (reset-password). */
  token?: string
}

/**
 * Built-in views that only make sense when email + password auth is enabled.
 * When it's disabled, these redirect to `signIn`.
 */
const PASSWORD_ONLY_VIEWS: AuthView[] = [
  "signUp",
  "forgotPassword",
  "resetPassword",
  "resetLinkSent"
]

const AUTH_VIEWS: Partial<Record<AuthView, ComponentType<AuthProps>>> = {
  signIn: SignIn,
  signOut: SignOut,
  signUp: SignUp,
  forgotPassword: ForgotPassword,
  resetPassword: ResetPassword,
  verifyEmail: VerifyEmail,
  resetLinkSent: ResetLinkSent,
  callback: AuthCallback,
  error: AuthError,
  redirect: AuthRedirect
}

/**
 * Card switcher: renders the auth view resolved from the `view` prop or, under
 * the state adapter, the navigation adapter's current view. Mirrors the heroui
 * `Auth` switcher; plugin views (e.g. magic-link) arrive in a follow-up.
 */
export function Auth({
  className,
  socialLayout,
  socialPosition,
  variant,
  view,
  token
}: AuthProps) {
  const { emailAndPassword, plugins } = useAuth()
  const navigation = useAuthNavigation()

  const current = navigation.current()
  const authView =
    view ?? (current?.section === "auth" ? current.view : undefined) ?? "signIn"

  const shouldRedirectToSignIn =
    !emailAndPassword?.enabled && PASSWORD_ONLY_VIEWS.includes(authView)

  useEffect(() => {
    if (shouldRedirectToSignIn) {
      navigation.push("signIn", { replace: true })
    }
  }, [shouldRedirectToSignIn, navigation])

  if (shouldRedirectToSignIn) return null

  const viewProps = { className, socialLayout, socialPosition, variant, token }

  // 1. Plugin view overrides (first plugin wins, even over built-ins) — this is
  //    how e.g. magic-link / username sign-in replace a view.
  for (const plugin of plugins) {
    const PluginView = plugin.views?.auth?.[authView]
    if (PluginView) return <PluginView {...viewProps} />
  }

  // 2. Plugin fallback for signIn when email+password is disabled (e.g. magic
  //    link becomes the primary passwordless sign-in surface).
  if (authView === "signIn" && !emailAndPassword?.enabled) {
    const Fallback = plugins.find(
      (plugin) => plugin.fallbackViews?.auth?.signIn
    )?.fallbackViews?.auth?.signIn
    if (Fallback) return <Fallback {...viewProps} />
  }

  const ViewComponent = AUTH_VIEWS[authView]

  if (!ViewComponent) {
    throw new Error(
      `[Better Auth UI] Unknown view "${authView}". Valid views are: ${Object.keys(
        AUTH_VIEWS
      ).join(", ")}`
    )
  }

  return <ViewComponent {...viewProps} />
}

// examples/start-solid-zaidan-example/src/components/auth/auth.tsx
import { type AuthView, viewPaths } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import type { Component } from "solid-js"
import { createEffect } from "solid-js"
import { Dynamic } from "solid-js/web"

import { AuthRedirect } from "./auth-redirect"
import { AuthCallback, AuthError } from "./auth-result"
import { ForgotPassword } from "./forgot-password"
import type { SocialLayout } from "./provider-buttons"
import { ResetLinkSent } from "./reset-link-sent"
import { ResetPassword } from "./reset-password"
import { SignIn } from "./sign-in"
import { SignOut } from "./sign-out"
import { SignUp } from "./sign-up"
import { VerifyEmail } from "./verify-email"

type SupportedAuthRoute = {
  component: Component
  title: string
}

type UnsupportedAuthRoute = {
  redirectTo: "/"
}

export type AuthProps = {
  class?: string
  path?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  view?: AuthView
}

type AuthPluginView = Component<AuthProps>

type AuthPluginWithViews = {
  fallbackViews?: { auth?: Partial<Record<AuthView, AuthPluginView>> }
  viewPaths?: { auth?: Partial<Record<AuthView, string>> }
  views?: { auth?: Partial<Record<AuthView, AuthPluginView>> }
}

const passwordOnlyViews: AuthView[] = [
  "signUp",
  "forgotPassword",
  "resetPassword",
  "resetLinkSent"
]

const authRouteComponents: Partial<Record<string, SupportedAuthRoute>> = {
  [viewPaths.auth.callback]: {
    component: AuthCallback,
    title: "Authentication complete"
  },
  [viewPaths.auth.error]: {
    component: AuthError,
    title: "Authentication error"
  },
  [viewPaths.auth.redirect]: {
    component: AuthRedirect,
    title: "Redirecting"
  },
  [viewPaths.auth.signIn]: { component: SignIn, title: "Sign in" },
  [viewPaths.auth.signUp]: {
    component: SignUp,
    title: "Sign up"
  },
  [viewPaths.auth.signOut]: {
    component: SignOut,
    title: "Sign out"
  },
  [viewPaths.auth.forgotPassword]: {
    component: ForgotPassword,
    title: "Forgot password"
  },
  [viewPaths.auth.resetPassword]: {
    component: ResetPassword,
    title: "Reset password"
  },
  [viewPaths.auth.resetLinkSent]: {
    component: ResetLinkSent,
    title: "Reset link sent"
  },
  [viewPaths.auth.verifyEmail]: {
    component: VerifyEmail,
    title: "Verify email"
  }
}

const EmptyAuthView: Component<AuthProps> = () => null

export function resolveAuthRoute(
  path: string
): SupportedAuthRoute | UnsupportedAuthRoute {
  const route = authRouteComponents[path]

  return route ?? { redirectTo: "/" }
}

export function Auth(props: AuthProps) {
  const auth = useAuth()
  const currentView = () =>
    props.view ??
    (Object.keys(auth.viewPaths.auth) as AuthView[]).find(
      (key) => auth.viewPaths.auth[key] === props.path
    )
  const authView = () => currentView()
  const shouldRedirectToSignIn = () =>
    !auth.emailAndPassword?.enabled &&
    authView() &&
    passwordOnlyViews.includes(authView() as AuthView)

  const PluginComponent = () => {
    for (const plugin of auth.plugins as AuthPluginWithViews[]) {
      const pluginView =
        props.view ??
        authView() ??
        (Object.keys(plugin.viewPaths?.auth ?? {}) as AuthView[]).find(
          (key) => plugin.viewPaths?.auth?.[key] === props.path
        )
      const PluginView = pluginView
        ? plugin.views?.auth?.[pluginView]
        : undefined

      if (PluginView) return PluginView
    }
  }

  const FallbackComponent = () => {
    if (authView() !== "signIn" || auth.emailAndPassword?.enabled) return

    return (auth.plugins as AuthPluginWithViews[]).find(
      (plugin) => plugin.fallbackViews?.auth?.signIn
    )?.fallbackViews?.auth?.signIn
  }

  const RouteComponent = () => {
    const view = authView()
    if (!view) return

    const authPath = auth.viewPaths.auth[view]
    if (!authPath) return

    const route = resolveAuthRoute(authPath)

    return "redirectTo" in route
      ? undefined
      : (route.component as Component<AuthProps>)
  }

  const AuthComponent = () =>
    shouldRedirectToSignIn()
      ? EmptyAuthView
      : (PluginComponent() ??
        FallbackComponent() ??
        RouteComponent() ??
        EmptyAuthView)

  createEffect(() => {
    if (shouldRedirectToSignIn()) {
      auth.navigate({
        replace: true,
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
    }
  })

  return (
    <Dynamic
      component={AuthComponent()}
      class={props.class}
      socialLayout={props.socialLayout}
      socialPosition={props.socialPosition}
    />
  )
}
