// packages/react-native/src/components/auth/auth-result.tsx
import { getAuthResultMessage, parseAuthResult } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/react"
import { useAuthNavigation } from "../../navigation/navigation-context"
import { Button } from "../../primitives/button"
import { Description } from "../../primitives/description"
import { Card } from "../../primitives/card"
import type { AuthViewProps } from "../../lib/auth-plugin"
import { cn } from "../../lib/cn"

function AuthResultView({
  fallbackIntent,
  className,
  variant
}: AuthViewProps & { fallbackIntent: "success" | "danger" }) {
  const { localization } = useAuth()
  const navigation = useAuthNavigation()
  const params = new URLSearchParams()
  for (const key of [
    "error",
    "code",
    "result",
    "status",
    "flow",
    "source",
    "redirectTo",
    "returnTo"
  ]) {
    const value = navigation.getParam(key)
    if (value) params.set(key, value)
  }
  const result = parseAuthResult(params, fallbackIntent)
  const message = getAuthResultMessage(result, localization)
  const label =
    result.action === "accountSettings"
      ? localization.auth.callbackViewAccountSettings
      : result.action === "continue"
        ? localization.auth.callbackContinue
        : localization.auth[result.action]
  return (
    <Card className={cn("w-full max-w-sm gap-4", className)} variant={variant}>
      <Card.Header>
        <Card.Title>{message.title}</Card.Title>
        <Description>{message.description}</Description>
      </Card.Header>
      <Card.Footer>
        <Button
          variant={result.intent === "danger" ? "danger" : "primary"}
          onPress={() => {
            if (result.action === "continue")
              navigation.navigate({ to: result.redirectTo ?? "/" })
            else if (result.action === "accountSettings")
              navigation.push({ section: "settings", view: "security" })
            else navigation.push(result.action)
          }}
        >
          {label}
        </Button>
      </Card.Footer>
    </Card>
  )
}

export function AuthCallback(props: AuthViewProps) {
  return <AuthResultView {...props} fallbackIntent="success" />
}
export function AuthError(props: AuthViewProps) {
  return <AuthResultView {...props} fallbackIntent="danger" />
}

// examples/start-solid-zaidan-example/src/components/auth/auth-result.tsx
import {
  type AuthResult,
  getAuthResultMessage,
  parseAuthResult
} from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import { CircleCheck, CircleX, TriangleAlert } from "lucide-solid"
import { createSignal, onMount, Show } from "solid-js"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { cn } from "@/lib/utils"

type AuthResultProps = {
  class?: string
  fallbackIntent: "danger" | "success"
}

function AuthResultView(props: AuthResultProps) {
  const auth = useAuth()
  const [result, setResult] = createSignal<AuthResult>(
    parseAuthResult("", props.fallbackIntent)
  )

  onMount(() => {
    setResult(parseAuthResult(window.location.search, props.fallbackIntent))
  })

  const message = () => getAuthResultMessage(result(), auth.localization)
  const action = () => {
    switch (result().action) {
      case "accountSettings":
        return {
          label: auth.localization.auth.callbackViewAccountSettings,
          to: `${auth.basePaths.settings}/${auth.viewPaths.settings.security}`
        }
      case "continue":
        return {
          label: auth.localization.auth.callbackContinue,
          to: result().redirectTo ?? "/"
        }
      case "forgotPassword":
        return {
          label: auth.localization.auth.forgotPassword,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.forgotPassword}`
        }
      case "signUp":
        return {
          label: auth.localization.auth.signUp,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signUp}`
        }
      case "verifyEmail":
        return {
          label: auth.localization.auth.verifyEmail,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.verifyEmail}`
        }
      default:
        return {
          label: auth.localization.auth.signIn,
          to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
        }
    }
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader class="justify-items-center text-center">
        <Show
          when={result().intent === "success"}
          fallback={
            <Show
              when={result().intent === "warning"}
              fallback={
                <CircleX
                  aria-hidden="true"
                  class="mb-1 size-10 text-destructive"
                />
              }
            >
              <TriangleAlert
                aria-hidden="true"
                class="mb-1 size-10 text-warning"
              />
            </Show>
          }
        >
          <CircleCheck aria-hidden="true" class="mb-1 size-10 text-primary" />
        </Show>
        <CardTitle class="text-xl">{message().title}</CardTitle>
        <CardDescription>{message().description}</CardDescription>
      </CardHeader>
      <CardContent>
        <Button
          class="w-full"
          onClick={() => auth.navigate({ to: action().to })}
        >
          {action().label}
        </Button>
      </CardContent>
    </Card>
  )
}

export function AuthCallback(props: Omit<AuthResultProps, "fallbackIntent">) {
  return <AuthResultView {...props} fallbackIntent="success" />
}

export function AuthError(props: Omit<AuthResultProps, "fallbackIntent">) {
  return <AuthResultView {...props} fallbackIntent="danger" />
}
