// packages/heroui/src/components/auth/magic-link/magic-link-sent.tsx
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  Card,
  type CardProps,
  cn,
  Description,
  Link,
  useIsHydrated
} from "@heroui/react"
import { useEffect, useState } from "react"

import { magicLinkPlugin } from "../../../lib/auth/magic-link-plugin"
import { OpenEmailButton } from "../open-email-button"

/** `sessionStorage` key the magic-link form stores the submitted email under. */
export const MAGIC_LINK_SENT_STORAGE_KEY = "better-auth-ui.magic-link-sent"

export type MagicLinkSentProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Render a card confirming that a magic-link email was sent, with a button
 * to open the user's email provider.
 *
 * The target email is read from `sessionStorage` (set when the magic-link
 * form redirects here); the OpenEmail button is only shown when an email is
 * stored and resolves to a known provider.
 *
 * @param className - Additional CSS classes applied to the outer card container
 * @param variant - Variant to apply to the card
 * @returns The magic-link-sent card React element
 */
export function MagicLinkSent({ className, variant }: MagicLinkSentProps) {
  const { basePaths, emailAndPassword, localization, viewPaths } = useAuth()
  const { localization: magicLinkLocalization } = useAuthPlugin(magicLinkPlugin)

  const isHydrated = useIsHydrated()
  const [email, setEmail] = useState(
    (isHydrated && sessionStorage.getItem(MAGIC_LINK_SENT_STORAGE_KEY)) || ""
  )

  useEffect(() => {
    setEmail(sessionStorage.getItem(MAGIC_LINK_SENT_STORAGE_KEY) ?? "")
  }, [])

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.checkYourEmailTitle}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        <Description className="text-sm">
          {email
            ? magicLinkLocalization.magicLinkSentTo.replace("{{email}}", email)
            : magicLinkLocalization.magicLinkSent}
        </Description>

        {email && <OpenEmailButton email={email} />}
      </Card.Content>

      {emailAndPassword?.enabled && (
        <Card.Footer className="flex-col gap-3">
          <Description className="text-sm">
            {localization.auth.needToCreateAnAccount}{" "}
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
              className="text-accent no-underline hover:underline decoration-accent-hover"
            >
              {localization.auth.signUp}
            </Link>
          </Description>
        </Card.Footer>
      )}
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/magic-link-sent.tsx
import {
  magicLinkPlugin as coreMagicLinkPlugin,
  type MagicLinkLocalization,
  magicLinkLocalization
} from "@better-auth-ui/core/plugins/magic-link"
import { AuthLink, useAuth } from "@better-auth-ui/solid"
import { createSignal, onMount, Show } from "solid-js"
import { isServer } from "solid-js/web"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { OpenEmailButton } from "./open-email-button"

/** `sessionStorage` key the magic-link form stores the submitted email under. */
export const MAGIC_LINK_SENT_STORAGE_KEY = "better-auth-ui.magic-link-sent"

export type MagicLinkSentProps = {
  class?: string
}

/**
 * Magic-link-sent view. The target email is read from `sessionStorage` (set
 * when the magic-link form redirects here); if none is stored the user is
 * redirected back to the magic-link form. Offers a button to open the user's
 * email provider.
 */
export function MagicLinkSent(props: MagicLinkSentProps) {
  const auth = useAuth()
  const magicLinkPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMagicLinkPlugin.id)
  const magicLinkLabels = (): MagicLinkLocalization => ({
    ...magicLinkLocalization,
    ...(magicLinkPluginConfig()?.localization as
      | Partial<MagicLinkLocalization>
      | undefined)
  })
  const magicLinkPath = () =>
    magicLinkPluginConfig()?.viewPaths?.auth?.magicLink ?? "magic-link"

  const [email, setEmail] = createSignal(
    (!isServer && sessionStorage.getItem(MAGIC_LINK_SENT_STORAGE_KEY)) || ""
  )

  onMount(() => {
    const storedEmail = sessionStorage.getItem(MAGIC_LINK_SENT_STORAGE_KEY)

    if (!storedEmail) {
      auth.navigate({
        to: `${auth.basePaths.auth}/${magicLinkPath()}`
      })
      return
    }

    setEmail(storedEmail)
  })

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.checkYourEmailTitle}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <div class="flex flex-col gap-4">
          <p class="text-sm text-muted-foreground" role="status">
            {email()
              ? magicLinkLabels().magicLinkSentTo.replace("{{email}}", email())
              : magicLinkLabels().magicLinkSent}
          </p>

          <Show when={email()}>
            <OpenEmailButton email={email()} />
          </Show>
        </div>

        <Show when={auth.emailAndPassword?.enabled}>
          <p class="mt-4 text-center text-muted-foreground text-sm">
            {auth.localization.auth.needToCreateAnAccount}{" "}
            <AuthLink
              href={`${auth.basePaths.auth}/${auth.viewPaths.auth.signUp}`}
            >
              {auth.localization.auth.signUp}
            </AuthLink>
          </p>
        </Show>
      </CardContent>
    </Card>
  )
}
