// packages/heroui/src/components/auth/magic-link/magic-link.tsx
import { authMutationKeys, validateEmailAddress } from "@better-auth-ui/core"
import type { MagicLinkAuthClient } from "@better-auth-ui/core/plugins/magic-link"
import { getSsoFallbackEmail } from "@better-auth-ui/core/plugins/sso"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useSignInMagicLink } from "@better-auth-ui/react/plugins/magic-link"
import {
  Card,
  type CardProps,
  cn,
  Description,
  Input,
  Label,
  Link,
  TextField
} from "@heroui/react"
import { useIsMutating } from "@tanstack/react-query"

import { magicLinkPlugin } from "../../../lib/auth/magic-link-plugin"
import { useAuthForm } from "../auth-form"
import { FieldSeparator } from "../field-separator"
import { ProviderButtons, type SocialLayout } from "../provider-buttons"
import { ReauthenticationNotice } from "../reauthentication"
import { MAGIC_LINK_SENT_STORAGE_KEY } from "./magic-link-sent"

export type MagicLinkProps = {
  className?: string
  socialLayout?: SocialLayout
  socialPosition?: "top" | "bottom"
  variant?: CardProps["variant"]
}

/**
 * Magic-link sign-in form.
 *
 * @param socialLayout - Provider button layout.
 * @param socialPosition - `"top"` or `"bottom"`. Defaults to `"bottom"`.
 * @param variant - Card variant.
 */
export function MagicLink({
  className,
  socialLayout,
  socialPosition = "bottom",
  variant
}: MagicLinkProps) {
  const {
    authClient,
    basePaths,
    baseURL,
    emailAndPassword,
    localization,
    navigate,
    plugins,
    redirectTo,
    socialProviders,
    viewPaths
  } = useAuth()
  const { localization: magicLinkLocalization, viewPaths: magicLinkViewPaths } =
    useAuthPlugin(magicLinkPlugin)

  const { mutateAsync: signInMagicLink, isPending: signInMagicLinkPending } =
    useSignInMagicLink(authClient as MagicLinkAuthClient, {
      onSuccess: (_data, variables) => {
        sessionStorage.setItem(MAGIC_LINK_SENT_STORAGE_KEY, variables.email)
        navigate({
          to: `${basePaths.auth}/${magicLinkViewPaths.auth.magicLinkSent}`
        })
      }
    })

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0

  const form = useAuthForm({
    defaultValues: { email: getSsoFallbackEmail() },
    onSubmit: async ({ value }) =>
      await signInMagicLink({
        email: value.email,
        callbackURL: `${baseURL}${redirectTo}`
      })
  })

  const showSeparator = !!socialProviders?.length

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <ReauthenticationNotice />
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.signIn}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        {socialPosition === "top" && (
          <>
            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="magicLink" />
            )}

            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}
          </>
        )}

        <form.AppForm>
          <form.AuthFormRoot className="flex flex-col gap-4">
            <form.AppField
              name="email"
              validators={{
                onChange: ({ value }) =>
                  validateEmailAddress(value, {
                    invalidMessage: localization.auth.invalidEmail,
                    requiredMessage: localization.auth.fieldRequired
                  })
              }}
            >
              {(field) => (
                <TextField
                  name={field.name}
                  type="email"
                  autoComplete="email"
                  isDisabled={isPending}
                  value={field.state.value}
                  onBlur={field.handleBlur}
                  onChange={field.handleChange}
                >
                  <Label>{localization.auth.email}</Label>

                  <Input
                    placeholder={localization.auth.emailPlaceholder}
                    required
                    variant={
                      variant === "transparent" ? "primary" : "secondary"
                    }
                  />

                  <field.AuthFormFieldError />
                </TextField>
              )}
            </form.AppField>

            <form.AuthFormServerError />

            <div className="flex flex-col gap-3">
              <form.AuthFormSubmitButton
                isPending={signInMagicLinkPending}
                className="w-full"
                isDisabled={isPending}
              >
                {magicLinkLocalization.sendMagicLink}
              </form.AuthFormSubmitButton>

              {plugins.flatMap((plugin) =>
                (plugin.authButtons ?? []).map((AuthButton, index) => (
                  <AuthButton
                    key={`${plugin.id}-${index.toString()}`}
                    view="magicLink"
                  />
                ))
              )}
            </div>
          </form.AuthFormRoot>
        </form.AppForm>

        {socialPosition === "bottom" && (
          <>
            {showSeparator && (
              <FieldSeparator>{localization.auth.or}</FieldSeparator>
            )}

            {!!socialProviders?.length && (
              <ProviderButtons socialLayout={socialLayout} view="magicLink" />
            )}
          </>
        )}
      </Card.Content>

      {emailAndPassword?.enabled && (
        <Card.Footer className="flex-col gap-3">
          <Description className="text-sm">
            {localization.auth.needToCreateAnAccount}{" "}
            <Link
              href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
              className="text-accent no-underline hover:underline decoration-accent-hover"
            >
              {localization.auth.signUp}
            </Link>
          </Description>
        </Card.Footer>
      )}
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/magic-link.tsx
import { validateEmailAddress } from "@better-auth-ui/core"
import type { MagicLinkAuthClient } from "@better-auth-ui/core/plugins/magic-link"
import {
  magicLinkPlugin as coreMagicLinkPlugin,
  type MagicLinkLocalization,
  magicLinkLocalization
} from "@better-auth-ui/core/plugins/magic-link"
import { AuthLink, type AuthPlugin, useAuth } from "@better-auth-ui/solid"
import { useSignInMagicLink } from "@better-auth-ui/solid/plugins/magic-link"
import { type Component, For, Show } from "solid-js"
import { MAGIC_LINK_SENT_STORAGE_KEY } from "@/components/auth/magic-link-sent"
import {
  ProviderButtons,
  type SocialLayout
} from "@/components/auth/provider-buttons"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import { createAuthForm, isAuthFormFieldInvalid } from "./auth-form"
import { ReauthenticationNotice } from "./reauthentication"

export type MagicLinkProps = {
  class?: string
  socialLayout?: SocialLayout
  socialPosition?: "bottom" | "top"
}

type AuthButtonComponent = Component<{ view?: string }>

type AuthPluginWithButtons = AuthPlugin & {
  authButtons?: AuthButtonComponent[]
}

export function MagicLink(props: MagicLinkProps) {
  const auth = useAuth<MagicLinkAuthClient>()
  const magicLinkPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMagicLinkPlugin.id)
  const magicLinkLabels = (): MagicLinkLocalization => ({
    ...magicLinkLocalization,
    ...(magicLinkPluginConfig()?.localization as
      | Partial<MagicLinkLocalization>
      | undefined)
  })
  const magicLinkSentPath = () =>
    magicLinkPluginConfig()?.viewPaths?.auth?.magicLinkSent ?? "magic-link-sent"
  const signInMagicLink = useSignInMagicLink(auth.authClient, () => ({
    onSuccess: (_data, variables) => {
      sessionStorage.setItem(MAGIC_LINK_SENT_STORAGE_KEY, variables.email)
      auth.navigate({
        to: `${auth.basePaths.auth}/${magicLinkSentPath()}`
      })
    }
  }))
  const showSeparator = () => Boolean(auth.socialProviders?.length)
  const socialPosition = () => props.socialPosition ?? "bottom"

  const form = createAuthForm(() => ({
    defaultValues: { email: "" },
    onSubmit: async ({ value }) => {
      await signInMagicLink.mutateAsync({
        callbackURL: `${auth.baseURL}${auth.redirectTo}`,
        email: value.email
      } as Parameters<typeof signInMagicLink.mutateAsync>[0])
    }
  }))

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <ReauthenticationNotice />
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.signIn}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <div class="flex flex-col gap-6">
          <Show
            when={socialPosition() === "top" && auth.socialProviders?.length}
          >
            <ProviderButtons socialLayout={props.socialLayout} />
            <Show when={showSeparator()}>
              <div class="text-center text-muted-foreground text-xs">
                {auth.localization.auth.or}
              </div>
            </Show>
          </Show>
          <form.AppForm>
            <form.AuthFormRoot aria-label="Magic link">
              <FieldGroup>
                <form.AppField
                  name="email"
                  validators={{
                    onChange: ({ value }) =>
                      validateEmailAddress(value, {
                        invalidMessage: auth.localization.auth.invalidEmail,
                        requiredMessage: auth.localization.auth.fieldRequired
                      })
                  }}
                >
                  {(field) => (
                    <Field
                      data-invalid={isAuthFormFieldInvalid(field().state.meta)}
                    >
                      <FieldLabel for="magic-link-email">
                        {auth.localization.auth.email}
                      </FieldLabel>
                      <Input
                        aria-invalid={isAuthFormFieldInvalid(
                          field().state.meta
                        )}
                        autocomplete="email"
                        disabled={signInMagicLink.isPending}
                        id="magic-link-email"
                        name={field().name}
                        onBlur={field().handleBlur}
                        onInput={(event) =>
                          field().handleChange(event.currentTarget.value)
                        }
                        placeholder={auth.localization.auth.emailPlaceholder}
                        type="email"
                        value={field().state.value}
                      />
                      <field.AuthFormFieldError />
                    </Field>
                  )}
                </form.AppField>
                <div class="flex flex-col gap-3">
                  <form.AuthFormSubmitButton
                    disabled={signInMagicLink.isPending}
                  >
                    {magicLinkLabels().sendMagicLink}
                  </form.AuthFormSubmitButton>

                  <For
                    each={(auth.plugins as AuthPluginWithButtons[]).flatMap(
                      (plugin) =>
                        (plugin.authButtons ?? []).map((AuthButton) => ({
                          AuthButton
                        }))
                    )}
                  >
                    {({ AuthButton }) => <AuthButton view="magicLink" />}
                  </For>
                </div>
              </FieldGroup>
              <form.AuthFormServerError />
            </form.AuthFormRoot>
          </form.AppForm>
          <Show
            when={socialPosition() === "bottom" && auth.socialProviders?.length}
          >
            <Show when={showSeparator()}>
              <div class="text-center text-muted-foreground text-xs">
                {auth.localization.auth.or}
              </div>
            </Show>
            <ProviderButtons socialLayout={props.socialLayout} />
          </Show>
        </div>
        <Show when={auth.emailAndPassword?.enabled}>
          <p class="mt-4 text-center text-muted-foreground text-sm">
            {auth.localization.auth.needToCreateAnAccount}{" "}
            <AuthLink
              href={`${auth.basePaths.auth}/${auth.viewPaths.auth.signUp}`}
            >
              {auth.localization.auth.signUp}
            </AuthLink>
          </p>
        </Show>
      </CardContent>
    </Card>
  )
}
