// apps/docs/src/components/auth/otp-field.tsx
"use client"

import { REGEXP_ONLY_DIGITS } from "input-otp"
import { useId } from "react"

import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot
} from "@/components/ui/input-otp"
import { cn } from "@/lib/utils"

export type OtpFieldProps = {
  /** Visible label rendered above the slots. */
  label: string
  /** Number of slots — keep in sync with the server's code length. */
  length: number
  value: string
  onChange: (value: string) => void
  autoFocus?: boolean
  className?: string
  errorMessage?: string
  disabled?: boolean
  name?: string
}

/** Strip everything the numeric slots can't hold — pasted codes often carry spaces or dashes. */
function normalizeCode(value: string) {
  return value.replace(/\D/g, "")
}

/**
 * Labelled one-time-code input.
 *
 * Shared by every code-based flow (email OTP, two-factor challenge,
 * two-factor enrollment) so slot sizing, pasting, and error wiring behave the
 * same everywhere.
 *
 * @param label - Visible label, also used as the accessible name.
 * @param length - Number of code characters.
 * @param errorMessage - Rendered below the slots when set.
 */
export function OtpField({
  autoFocus,
  className,
  disabled,
  errorMessage,
  label,
  length,
  name,
  onChange,
  value
}: OtpFieldProps) {
  const inputId = useId()

  return (
    <Field className={cn(className)} data-invalid={!!errorMessage}>
      <FieldLabel htmlFor={inputId}>{label}</FieldLabel>

      <InputOTP
        aria-invalid={!!errorMessage}
        aria-label={label}
        autoComplete="one-time-code"
        autoFocus={autoFocus}
        containerClassName="w-full justify-center"
        disabled={disabled}
        id={inputId}
        inputMode="numeric"
        maxLength={length}
        name={name}
        pasteTransformer={normalizeCode}
        pattern={REGEXP_ONLY_DIGITS}
        value={value}
        onChange={(next) => onChange(normalizeCode(next))}
      >
        <InputOTPGroup>
          {Array.from({ length }, (_, slotIndex) => (
            <InputOTPSlot
              index={slotIndex}
              key={`otp-slot-${String(slotIndex + 1)}`}
            />
          ))}
        </InputOTPGroup>
      </InputOTP>

      <FieldError>{errorMessage}</FieldError>
    </Field>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/otp-field.tsx
import { createMemo, For, Show } from "solid-js"

import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import {
  InputOTP,
  InputOTPGroup,
  InputOTPSlot
} from "@/components/ui/input-otp"
import { cn } from "@/lib/utils"

export type OtpFieldProps = {
  /** Visible label rendered above the input. */
  label: string
  /** Number of digits — keep in sync with the server's code length. */
  length: number
  value: string
  onInput: (value: string) => void
  onComplete?: (value: string) => void
  autofocus?: boolean
  class?: string
  disabled?: boolean
  errorMessage?: string
  id?: string
  name?: string
}

/** Strip everything the numeric field can't hold — pasted codes often carry spaces or dashes. */
function normalizeCode(value: string) {
  return value.replace(/\D/g, "")
}

function createOtpSlots(length: number) {
  return Array.from({ length }, (_, slotIndex) => ({
    id: `otp-slot-${String(slotIndex + 1)}`,
    index: slotIndex
  }))
}

/**
 * Labelled one-time-code input.
 *
 * Shared by every code-based flow (email OTP, two-factor challenge,
 * two-factor enrollment) so spacing, pasting, and error wiring behave the
 * same everywhere.
 */
export function OtpField(props: OtpFieldProps) {
  const inputId = () => props.id ?? "otp-code"
  const errorId = () => `${inputId()}-error`
  const slots = createMemo(() => createOtpSlots(props.length))

  return (
    <Field class={cn(props.class)} data-invalid={Boolean(props.errorMessage)}>
      <FieldLabel for={inputId()}>{props.label}</FieldLabel>

      <InputOTP
        maxLength={props.length}
        aria-describedby={props.errorMessage ? errorId() : undefined}
        aria-invalid={Boolean(props.errorMessage)}
        aria-label={props.label}
        autocomplete="one-time-code"
        autofocus={props.autofocus}
        containerClass="w-full justify-center"
        disabled={props.disabled}
        id={inputId()}
        inputmode="numeric"
        name={props.name}
        pattern="^\\d*$"
        value={props.value}
        onValueChange={(next) => props.onInput(normalizeCode(next))}
        onComplete={(completedCode) =>
          props.onComplete?.(normalizeCode(completedCode))
        }
      >
        <InputOTPGroup>
          <For each={slots()}>
            {(slot) => <InputOTPSlot index={slot.index} />}
          </For>
        </InputOTPGroup>
      </InputOTP>

      <Show when={props.errorMessage}>
        {(message) => <FieldError id={errorId()}>{message()}</FieldError>}
      </Show>
    </Field>
  )
}
