// packages/react-native/src/components/auth/provider-button.tsx
import { authMutationKeys, getProviderName } from "@better-auth-ui/core"
import { useAuth, useSignInSocial } from "@better-auth-ui/react"
import { useIsMutating } from "@tanstack/react-query"
import type { SocialProvider } from "better-auth/social-providers"
import { providerIcons } from "../../lib/provider-icons"
import { Button, type ButtonProps } from "../../primitives/button"

export type ProviderButtonProps = {
  provider: SocialProvider
  display?: "full" | "name" | "icon"
} & Omit<ButtonProps, "children" | "onPress" | "isPending" | "isDisabled">

/**
 * Social provider sign-in button. `display`: `"full"` (e.g. "Continue with
 * Google"), `"name"` (provider name), or `"icon"` (icon only).
 */
export function ProviderButton({
  provider,
  display = "full",
  variant = "tertiary",
  ...props
}: ProviderButtonProps) {
  const { authClient, baseURL, localization, redirectTo } = useAuth()

  const callbackURL = `${baseURL}${redirectTo}`

  const { mutate: signInSocial } = useSignInSocial(authClient)

  const ProviderIcon = providerIcons[provider]

  const signInMutating = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpMutating = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  const isPending = signInMutating + signUpMutating > 0

  return (
    <Button
      variant={variant}
      isPending={isPending}
      onPress={() => signInSocial({ provider, callbackURL })}
      aria-label={getProviderName(provider)}
      {...props}
    >
      {ProviderIcon ? (
        <ProviderIcon width={20} height={20} color="#171717" />
      ) : null}

      {display === "full"
        ? localization.auth.continueWith.replace(
            "{{provider}}",
            getProviderName(provider)
          )
        : display === "name"
          ? getProviderName(provider)
          : null}
    </Button>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/provider-button.tsx
import { getProviderName } from "@better-auth-ui/core"
import { useAuth } from "@better-auth-ui/solid"
import type { SocialProvider } from "better-auth/social-providers"
import type { ComponentProps } from "solid-js"
import { createSignal } from "solid-js"
import { Button } from "@/components/ui/button"
import { resolveSocialAuthParams, type SocialAuthView } from "./sign-in-path"

export type ProviderButtonProps = {
  display?: "full" | "icon" | "name"
  provider: SocialProvider
  view?: SocialAuthView
} & Omit<ComponentProps<typeof Button>, "children" | "disabled" | "onClick">

export function ProviderButton(props: ProviderButtonProps) {
  const auth = useAuth()
  const [isPending, setIsPending] = createSignal(false)
  const display = () => props.display ?? "full"
  const providerName = () => getProviderName(props.provider)
  const label = () =>
    auth.localization.auth.continueWith.replace("{{provider}}", providerName())
  const signInSocial = async () => {
    if (isPending()) return

    setIsPending(true)

    try {
      await auth.authClient.signIn.social(
        resolveSocialAuthParams({
          provider: props.provider,
          basePaths: auth.basePaths,
          baseURL: auth.baseURL,
          redirectTo: auth.redirectTo,
          view: props.view ?? "signIn",
          viewPaths: auth.viewPaths
        }) as Parameters<typeof auth.authClient.signIn.social>[0]
      )
    } finally {
      setIsPending(false)
    }
  }

  return (
    <Button
      aria-label={providerName()}
      class={props.class}
      disabled={isPending()}
      onClick={signInSocial}
      type="button"
      variant={props.variant ?? "outline"}
    >
      <span aria-hidden>{providerName().slice(0, 1)}</span>
      {isPending()
        ? `${providerName()}…`
        : display() === "full"
          ? label()
          : display() === "name"
            ? providerName()
            : null}
    </Button>
  )
}
