// packages/react-native/src/components/auth/provider-buttons.tsx
import { useAuth } from "@better-auth-ui/react"
import { useMemo } from "react"
import { View } from "react-native"
import { cn } from "../../lib/cn"
import { ProviderButton } from "./provider-button"

export type SocialLayout = "auto" | "horizontal" | "vertical" | "grid"

export type ProviderButtonsProps = {
  socialLayout?: SocialLayout
}

/**
 * Social provider sign-in buttons. Each button owns its own sign-in mutation
 * and reads shared pending state from React Query. `"auto"` picks horizontal
 * when there are four or more providers, otherwise vertical.
 */
export function ProviderButtons({
  socialLayout = "auto"
}: ProviderButtonsProps) {
  const { socialProviders } = useAuth()

  const resolvedSocialLayout = useMemo<Exclude<SocialLayout, "auto">>(() => {
    if (socialLayout === "auto") {
      return socialProviders?.length && socialProviders.length >= 4
        ? "horizontal"
        : "vertical"
    }
    return socialLayout
  }, [socialLayout, socialProviders?.length])

  return (
    <View
      className={cn(
        "gap-3",
        resolvedSocialLayout === "grid" && "flex-row flex-wrap",
        resolvedSocialLayout === "vertical" && "flex-col",
        resolvedSocialLayout === "horizontal" && "flex-row flex-wrap"
      )}
    >
      {socialProviders?.map((provider) => (
        <ProviderButton
          key={provider}
          provider={provider}
          display={
            resolvedSocialLayout === "vertical"
              ? "full"
              : resolvedSocialLayout === "grid"
                ? "name"
                : "icon"
          }
          className={cn(
            resolvedSocialLayout === "grid" ? "w-[48%]" : "w-full",
            resolvedSocialLayout === "horizontal" && "flex-1"
          )}
        />
      ))}
    </View>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/provider-buttons.tsx
import { useAuth } from "@better-auth-ui/solid"
import { For } from "solid-js"
import { cn } from "@/lib/utils"
import { ProviderButton } from "./provider-button"
import type { SocialAuthView } from "./sign-in-path"

export type SocialLayout = "auto" | "grid" | "horizontal" | "vertical"

export type ProviderButtonsProps = {
  socialLayout?: SocialLayout
  view?: SocialAuthView
}

export function ProviderButtons(props: ProviderButtonsProps) {
  const auth = useAuth()
  const resolvedSocialLayout = () => {
    const socialLayout = props.socialLayout ?? "auto"
    if (socialLayout !== "auto") return socialLayout

    return auth.socialProviders?.length && auth.socialProviders.length >= 4
      ? "horizontal"
      : "vertical"
  }

  return (
    <div
      class={cn(
        "gap-3",
        resolvedSocialLayout() === "grid" && "grid grid-cols-2",
        resolvedSocialLayout() === "vertical" && "flex flex-col",
        resolvedSocialLayout() === "horizontal" && "flex flex-row flex-wrap"
      )}
    >
      <For each={auth.socialProviders ?? []}>
        {(provider) => (
          <ProviderButton
            class={cn(resolvedSocialLayout() === "horizontal" && "flex-1")}
            display={
              resolvedSocialLayout() === "vertical"
                ? "full"
                : resolvedSocialLayout() === "grid"
                  ? "name"
                  : "icon"
            }
            provider={provider}
            view={props.view}
          />
        )}
      </For>
    </div>
  )
}
