// packages/shadcn/src/components/auth/provider-buttons.tsx
"use client"

import { providerIcons, useAuth } from "@better-auth-ui/react"
import { getProviderName } from "@better-auth-ui/react/core"
import { useMemo } from "react"

import { Button } from "@/components/ui/button"
import { Field } from "@/components/ui/field"
import { cn } from "@/lib/utils"

export type ProviderButtonsProps = {
  isPending: boolean
  socialLayout?: SocialLayout
  signInSocial: (formData: FormData) => void
}

export type SocialLayout = "auto" | "horizontal" | "vertical" | "grid"

/**
 * Render social provider sign-in buttons and handle sign-in initiation and pending state.
 *
 * @param isPending - When true, disables all provider buttons.
 * @param socialLayout - Preferred layout for the provider buttons; when set to `"auto"` the layout is chosen based on the number of available providers.
 * @param signInSocial - The function to call when a social provider button is clicked.
 */
export function ProviderButtons({
  isPending,
  socialLayout = "auto",
  signInSocial
}: ProviderButtonsProps) {
  const { localization, socialProviders } = useAuth()

  const resolvedSocialLayout = useMemo(() => {
    if (socialLayout === "auto") {
      if (socialProviders?.length && socialProviders.length >= 4) {
        return "horizontal"
      }

      return "vertical"
    }

    return socialLayout
  }, [socialLayout, socialProviders?.length])

  return (
    <form action={signInSocial}>
      <Field
        className={cn(
          "gap-3",
          resolvedSocialLayout === "grid" && "grid grid-cols-2",
          resolvedSocialLayout === "vertical" && "flex-col",
          resolvedSocialLayout === "horizontal" && "flex-row flex-wrap"
        )}
      >
        {socialProviders?.map((provider) => {
          const ProviderIcon = providerIcons[provider]

          return (
            <Button
              key={provider}
              name="provider"
              value={provider}
              className={cn(
                "flex-1",
                resolvedSocialLayout === "horizontal" && "flex-1"
              )}
              variant="outline"
              type="submit"
              disabled={isPending}
            >
              <ProviderIcon />

              {resolvedSocialLayout === "vertical"
                ? localization.auth.continueWith.replace(
                    "{{provider}}",
                    getProviderName(provider)
                  )
                : resolvedSocialLayout === "grid"
                  ? getProviderName(provider)
                  : null}
            </Button>
          )
        })}
      </Field>
    </form>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/provider-buttons.tsx
import { useAuth } from "@better-auth-ui/solid"
import { For } from "solid-js"
import { cn } from "@/lib/utils"
import { ProviderButton } from "./provider-button"
import type { SocialAuthView } from "./sign-in-path"

export type SocialLayout = "auto" | "grid" | "horizontal" | "vertical"

export type ProviderButtonsProps = {
  socialLayout?: SocialLayout
  view?: SocialAuthView
}

export function ProviderButtons(props: ProviderButtonsProps) {
  const auth = useAuth()
  const resolvedSocialLayout = () => {
    const socialLayout = props.socialLayout ?? "auto"
    if (socialLayout !== "auto") return socialLayout

    return auth.socialProviders?.length && auth.socialProviders.length >= 4
      ? "horizontal"
      : "vertical"
  }

  return (
    <div
      class={cn(
        "gap-3",
        resolvedSocialLayout() === "grid" && "grid grid-cols-2",
        resolvedSocialLayout() === "vertical" && "flex flex-col",
        resolvedSocialLayout() === "horizontal" && "flex flex-row flex-wrap"
      )}
    >
      <For each={auth.socialProviders ?? []}>
        {(provider) => (
          <ProviderButton
            class={cn(resolvedSocialLayout() === "horizontal" && "flex-1")}
            display={
              resolvedSocialLayout() === "vertical"
                ? "full"
                : resolvedSocialLayout() === "grid"
                  ? "name"
                  : "icon"
            }
            provider={provider}
            view={props.view}
          />
        )}
      </For>
    </div>
  )
}
