// examples/start-shadcn-example/src/components/auth/reset-password.tsx
"use client"

import {
  getAuthLinkURL,
  isPasswordCompromisedError
} from "@better-auth-ui/core"
import { useAuth, useResetPassword } from "@better-auth-ui/react"
import { useForm } from "@tanstack/react-form"
import { Eye, EyeOff } from "lucide-react"
import { useEffect, useState } from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"
import { PasswordStrengthMeter } from "./password-strength-meter"

export type ResetPasswordProps = {
  className?: string
}

/**
 * Render a password reset form that validates the reset token from the URL, accepts a new password (and optional confirmation), and submits it to the auth client.
 *
 * The component checks for a `token` query parameter on mount and, if missing, shows an error toast and navigates to the sign-in page. It exposes per-field validation messages, toggles for password visibility, and disables inputs while the reset request is pending.
 *
 * @returns The password reset form UI ready to be mounted in the app layout.
 */
export function ResetPassword({ className }: ResetPasswordProps) {
  const {
    authClient,
    basePaths,
    emailAndPassword,
    localization,
    navigate,
    redirectTo,
    viewPaths,
    Link
  } = useAuth()
  const signInURL = getAuthLinkURL(
    `${basePaths.auth}/${viewPaths.auth.signIn}`,
    redirectTo
  )

  const { mutate: resetPassword, isPending } = useResetPassword(authClient, {
    onError: (error) => {
      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setFieldErrors((prev) => ({
          ...prev,
          password: localization.auth.passwordCompromised
        }))
      }
    },
    onSuccess: () => {
      toast.success(localization.auth.passwordResetSuccess)
      navigate({ to: signInURL })
    }
  })

  const [isPasswordVisible, setIsPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  const [fieldErrors, setFieldErrors] = useState<{
    password?: string
    confirmPassword?: string
  }>({})

  useEffect(() => {
    const searchParams = new URLSearchParams(window.location.search)
    const token = searchParams.get("token") as string

    if (!token) {
      toast.error(localization.auth.invalidResetPasswordToken)
      navigate({ to: signInURL })
    }
  }, [localization.auth.invalidResetPasswordToken, navigate, signInURL])

  const form = useForm({
    defaultValues: { confirmPassword: "", password: "" },
    onSubmit: ({ value }) => {
      const searchParams = new URLSearchParams(window.location.search)
      const token = searchParams.get("token") as string

      if (!token) {
        toast.error(localization.auth.invalidResetPasswordToken)
        navigate({ to: signInURL })
        return
      }

      if (
        emailAndPassword?.confirmPassword &&
        value.password !== value.confirmPassword
      ) {
        setFieldErrors((current) => ({
          ...current,
          confirmPassword: localization.auth.passwordsDoNotMatch
        }))
        return
      }

      resetPassword({ token, newPassword: value.password })
    }
  })

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl font-semibold">
          {localization.auth.resetPassword}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <form
          onSubmit={(event) => {
            event.preventDefault()
            void form.handleSubmit()
          }}
        >
          <FieldGroup>
            <form.Field name="password">
              {(field) => (
                <Field data-invalid={!!fieldErrors.password}>
                  <FieldLabel htmlFor="password">
                    {localization.auth.password}
                  </FieldLabel>

                  <InputGroup>
                    <InputGroupInput
                      id="password"
                      type={isPasswordVisible ? "text" : "password"}
                      autoComplete="new-password"
                      placeholder={localization.auth.newPasswordPlaceholder}
                      required
                      minLength={emailAndPassword?.minPasswordLength}
                      maxLength={emailAndPassword?.maxPasswordLength}
                      disabled={isPending}
                      name={field.name}
                      onBlur={field.handleBlur}
                      onChange={(e) => {
                        field.handleChange(e.target.value)
                        setFieldErrors((prev) => ({
                          ...prev,
                          password: undefined
                        }))
                      }}
                      onInvalid={(e) => {
                        e.preventDefault()
                        const el = e.target as HTMLInputElement
                        const min = emailAndPassword?.minPasswordLength
                        const max = emailAndPassword?.maxPasswordLength
                        const msg = el.validity.valueMissing
                          ? localization.auth.fieldRequired
                          : el.validity.tooShort
                            ? localization.auth.tooShort.replace(
                                "{{min}}",
                                String(min)
                              )
                            : localization.auth.tooLong.replace(
                                "{{max}}",
                                String(max)
                              )

                        setFieldErrors((prev) => ({
                          ...prev,
                          password: msg
                        }))
                      }}
                      aria-invalid={!!fieldErrors.password}
                      value={field.state.value}
                    />

                    <InputGroupAddon align="inline-end">
                      <InputGroupButton
                        size="icon-xs"
                        aria-label={
                          isPasswordVisible
                            ? localization.auth.hidePassword
                            : localization.auth.showPassword
                        }
                        title={
                          isPasswordVisible
                            ? localization.auth.hidePassword
                            : localization.auth.showPassword
                        }
                        onClick={() => {
                          setIsPasswordVisible((visible) => !visible)
                        }}
                      >
                        {isPasswordVisible ? <EyeOff /> : <Eye />}
                      </InputGroupButton>
                    </InputGroupAddon>
                  </InputGroup>

                  <FieldError>{fieldErrors.password}</FieldError>

                  <PasswordStrengthMeter password={field.state.value} />
                </Field>
              )}
            </form.Field>

            {emailAndPassword?.confirmPassword && (
              <form.Field name="confirmPassword">
                {(field) => (
                  <Field data-invalid={!!fieldErrors.confirmPassword}>
                    <FieldLabel htmlFor="confirmPassword">
                      {localization.auth.confirmPassword}
                    </FieldLabel>

                    <InputGroup>
                      <InputGroupInput
                        id="confirmPassword"
                        name={field.name}
                        type={isConfirmPasswordVisible ? "text" : "password"}
                        autoComplete="new-password"
                        placeholder={
                          localization.auth.confirmPasswordPlaceholder
                        }
                        required
                        minLength={emailAndPassword?.minPasswordLength}
                        maxLength={emailAndPassword?.maxPasswordLength}
                        disabled={isPending}
                        onBlur={field.handleBlur}
                        onChange={(event) => {
                          field.handleChange(event.target.value)
                          setFieldErrors((prev) => ({
                            ...prev,
                            confirmPassword: undefined
                          }))
                        }}
                        onInvalid={(e) => {
                          e.preventDefault()
                          const el = e.target as HTMLInputElement
                          const min = emailAndPassword?.minPasswordLength
                          const max = emailAndPassword?.maxPasswordLength
                          const msg = el.validity.valueMissing
                            ? localization.auth.fieldRequired
                            : el.validity.tooShort
                              ? localization.auth.tooShort.replace(
                                  "{{min}}",
                                  String(min)
                                )
                              : localization.auth.tooLong.replace(
                                  "{{max}}",
                                  String(max)
                                )

                          setFieldErrors((prev) => ({
                            ...prev,
                            confirmPassword: msg
                          }))
                        }}
                        aria-invalid={!!fieldErrors.confirmPassword}
                        value={field.state.value}
                      />

                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          size="icon-xs"
                          aria-label={
                            isConfirmPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          title={
                            isConfirmPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          onClick={() => {
                            setIsConfirmPasswordVisible((visible) => !visible)
                          }}
                        >
                          {isConfirmPasswordVisible ? <EyeOff /> : <Eye />}
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>

                    <FieldError>{fieldErrors.confirmPassword}</FieldError>
                  </Field>
                )}
              </form.Field>
            )}

            <div className="flex flex-col gap-3">
              <Button type="submit" disabled={isPending}>
                {isPending && <Spinner />}

                {localization.auth.resetPassword}
              </Button>
            </div>
          </FieldGroup>
        </form>

        <div className="flex flex-col gap-3 items-center w-full mt-4">
          <FieldDescription className="text-center">
            {localization.auth.rememberYourPassword}{" "}
            <Link
              href={getAuthLinkURL(
                `${basePaths.auth}/${viewPaths.auth.signIn}`,
                redirectTo
              )}
              className="underline underline-offset-4"
            >
              {localization.auth.signIn}
            </Link>
          </FieldDescription>
        </div>
      </CardContent>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/reset-password.tsx
import {
  getAuthLinkURL,
  getFormFieldErrors,
  isPasswordCompromisedError,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import { AuthLink, useAuth, useResetPassword } from "@better-auth-ui/solid"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"
import { createAuthForm, isAuthFormFieldInvalid } from "./auth-form"
import { PasswordStrengthMeter } from "./password-strength-meter"

export type ResetPasswordProps = {
  class?: string
  token?: string
}

const tokenFromLocation = () => {
  if (typeof window === "undefined") return undefined

  return new URLSearchParams(window.location.search).get("token")
}

export function ResetPassword(props: ResetPasswordProps) {
  const auth = useAuth()
  const [isCompromised, setIsCompromised] = createSignal(false)
  const [tokenError, setTokenError] = createSignal<string>()
  const [isPasswordVisible, setIsPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const resetPassword = useResetPassword(auth.authClient, () => ({
    onError: (error) => {
      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setIsCompromised(true)
      }
    }
  }))
  const form = createAuthForm(() => ({
    defaultValues: { confirmPassword: "", password: "" },
    onSubmit: async ({ value }) => {
      const token = props.token ?? tokenFromLocation()

      setTokenError(
        token ? undefined : auth.localization.auth.invalidResetPasswordToken
      )
      if (!token) return
      try {
        await resetPassword.mutateAsync({ token, newPassword: value.password })
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  }))

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.resetPassword}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot aria-label="Reset password">
            <div class="flex flex-col gap-6">
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      maxLength: auth.emailAndPassword.maxPasswordLength,
                      maxLengthMessage: auth.localization.auth.tooLong.replace(
                        "{{max}}",
                        String(auth.emailAndPassword.maxPasswordLength)
                      ),
                      minLength: auth.emailAndPassword.minPasswordLength,
                      minLengthMessage: auth.localization.auth.tooShort.replace(
                        "{{min}}",
                        String(auth.emailAndPassword.minPasswordLength)
                      ),
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta) ||
                    isCompromised()

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="reset-password-new">
                        {auth.localization.auth.newPassword}
                      </FieldLabel>
                      <div class="relative">
                        <Input
                          aria-invalid={isInvalid()}
                          autocomplete="new-password"
                          class="pr-12"
                          id="reset-password-new"
                          maxLength={auth.emailAndPassword.maxPasswordLength}
                          minLength={auth.emailAndPassword.minPasswordLength}
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) => {
                            field().handleChange(event.currentTarget.value)
                            setIsCompromised(false)
                          }}
                          placeholder={
                            auth.localization.auth.newPasswordPlaceholder
                          }
                          required
                          type={isPasswordVisible() ? "text" : "password"}
                          value={field().state.value}
                        />

                        <Button
                          aria-label={
                            isPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          class="absolute right-1 top-1/2 -translate-y-1/2"
                          onClick={() =>
                            setIsPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          type="button"
                          variant="ghost"
                        >
                          {isPasswordVisible() ? (
                            <EyeOff aria-hidden class="size-4" />
                          ) : (
                            <Eye aria-hidden class="size-4" />
                          )}
                        </Button>
                      </div>

                      <Show
                        when={
                          isCompromised()
                            ? auth.localization.auth.passwordCompromised
                            : undefined
                        }
                        fallback={
                          <FieldError
                            errors={getFormFieldErrors(
                              field().state.meta.errors
                            )}
                          />
                        }
                      >
                        {(message) => <FieldError>{message()}</FieldError>}
                      </Show>

                      <PasswordStrengthMeter password={field().state.value} />
                    </Field>
                  )
                }}
              </form.AppField>
              <form.AppField
                name="confirmPassword"
                validators={{
                  onChangeListenTo: ["password"],
                  onChange: ({ fieldApi, value }) =>
                    validateStringLength(value, {
                      maxLength: auth.emailAndPassword.maxPasswordLength,
                      maxLengthMessage: auth.localization.auth.tooLong.replace(
                        "{{max}}",
                        String(auth.emailAndPassword.maxPasswordLength)
                      ),
                      minLength: auth.emailAndPassword.minPasswordLength,
                      minLengthMessage: auth.localization.auth.tooShort.replace(
                        "{{min}}",
                        String(auth.emailAndPassword.minPasswordLength)
                      ),
                      requiredMessage: auth.localization.auth.fieldRequired
                    }) ??
                    validateMatchingValue(
                      value,
                      fieldApi.form.getFieldValue("password"),
                      auth.localization.auth.passwordsDoNotMatch
                    )
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta)

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="reset-password-confirm">
                        {auth.localization.auth.confirmPassword}
                      </FieldLabel>
                      <div class="relative">
                        <Input
                          aria-invalid={isInvalid()}
                          autocomplete="new-password"
                          class="pr-12"
                          id="reset-password-confirm"
                          maxLength={auth.emailAndPassword.maxPasswordLength}
                          minLength={auth.emailAndPassword.minPasswordLength}
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) =>
                            field().handleChange(event.currentTarget.value)
                          }
                          placeholder={
                            auth.localization.auth.confirmPasswordPlaceholder
                          }
                          required
                          type={
                            isConfirmPasswordVisible() ? "text" : "password"
                          }
                          value={field().state.value}
                        />

                        <Button
                          aria-label={
                            isConfirmPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          class="absolute right-1 top-1/2 -translate-y-1/2"
                          onClick={() =>
                            setIsConfirmPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isConfirmPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          type="button"
                          variant="ghost"
                        >
                          {isConfirmPasswordVisible() ? (
                            <EyeOff aria-hidden class="size-4" />
                          ) : (
                            <Eye aria-hidden class="size-4" />
                          )}
                        </Button>
                      </div>

                      <FieldError
                        errors={getFormFieldErrors(field().state.meta.errors)}
                      />
                    </Field>
                  )
                }}
              </form.AppField>
              <form.AuthFormSubmitButton disabled={resetPassword.isPending}>
                {auth.localization.auth.resetPassword}
              </form.AuthFormSubmitButton>
              <Show when={tokenError()}>
                {(message) => (
                  <Alert variant="destructive">
                    <AlertDescription>{message()}</AlertDescription>
                  </Alert>
                )}
              </Show>
              <Show when={resetPassword.isSuccess}>
                <Alert>
                  <AlertDescription role="status">
                    {auth.localization.auth.passwordResetSuccessDescription}
                  </AlertDescription>
                </Alert>
              </Show>
              <Show
                when={
                  resetPassword.isError &&
                  !isPasswordCompromisedError(resetPassword.error)
                }
              >
                <Alert variant="destructive">
                  <AlertDescription>
                    {auth.localization.auth.passwordResetErrorDescription}
                  </AlertDescription>
                </Alert>
              </Show>
            </div>
          </form.AuthFormRoot>
        </form.AppForm>

        <div class="mt-4 flex w-full flex-col items-center gap-3">
          <p class="text-center text-sm text-muted-foreground">
            {auth.localization.auth.rememberYourPassword}{" "}
            <AuthLink
              class="underline underline-offset-4"
              href={getAuthLinkURL(
                `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`,
                auth.redirectTo
              )}
            >
              {auth.localization.auth.signIn}
            </AuthLink>
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
