// packages/heroui/src/components/auth/reset-password.tsx
import {
  getAuthLinkURL,
  isPasswordCompromisedError,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import { useAuth, useResetPassword } from "@better-auth-ui/react"
import { Eye, EyeSlash } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Description,
  FieldError,
  InputGroup,
  Label,
  Link,
  TextField,
  toast
} from "@heroui/react"
import { useEffect, useState } from "react"
import { isAuthFormFieldInvalid, useAuthForm } from "./auth-form"
import { PasswordStrengthMeter } from "./password-strength-meter"

export type ResetPasswordProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Renders a reset password form that verifies a "token" URL parameter on mount and redirects to sign-in if absent.
 *
 * Renders password (and optional confirm-password) inputs with visibility toggles, applies min/max length constraints from the auth configuration, shows field errors, and submits the new password to the auth client.
 */
export function ResetPassword({ className, variant }: ResetPasswordProps) {
  const {
    authClient,
    basePaths,
    emailAndPassword,
    localization,
    navigate,
    redirectTo,
    viewPaths
  } = useAuth()
  const signInURL = getAuthLinkURL(
    `${basePaths.auth}/${viewPaths.auth.signIn}`,
    redirectTo
  )

  const { mutateAsync: resetPassword, isPending } = useResetPassword(
    authClient,
    {
      onError: (error) => {
        // The haveIBeenPwned plugin rejects on the password itself, so it
        // belongs against the field rather than in a toast.
        setIsCompromised(isPasswordCompromisedError(error))
      },
      onSuccess: () => {
        toast.success(localization.auth.passwordResetSuccess)
        navigate({ to: signInURL })
      }
    }
  )

  const [isCompromised, setIsCompromised] = useState(false)
  const [isPasswordVisible, setIsPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  useEffect(() => {
    const searchParams = new URLSearchParams(window.location.search)
    const token = searchParams.get("token") as string

    if (!token) {
      toast.danger(localization.auth.invalidResetPasswordToken)
      navigate({ to: signInURL })
    }
  }, [localization.auth.invalidResetPasswordToken, navigate, signInURL])

  const form = useAuthForm({
    defaultValues: { confirmPassword: "", password: "" },
    onSubmit: async ({ value }) => {
      const searchParams = new URLSearchParams(window.location.search)
      const token = searchParams.get("token") as string

      if (!token) {
        toast.danger(localization.auth.invalidResetPasswordToken)
        navigate({ to: signInURL })
        return
      }

      try {
        await resetPassword({ token, newPassword: value.password })
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  })

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header>
        <Card.Title className="text-xl font-semibold mb-1">
          {localization.auth.resetPassword}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        <form.AppForm>
          <form.AuthFormRoot className="flex flex-col gap-4">
            <form.AppField
              name="password"
              validators={{
                onChange: ({ value }) =>
                  validateStringLength(value, {
                    maxLength: emailAndPassword?.maxPasswordLength,
                    maxLengthMessage: localization.auth.tooLong.replace(
                      "{{max}}",
                      String(emailAndPassword?.maxPasswordLength)
                    ),
                    minLength: emailAndPassword?.minPasswordLength,
                    minLengthMessage: localization.auth.tooShort.replace(
                      "{{min}}",
                      String(emailAndPassword?.minPasswordLength)
                    ),
                    requiredMessage: localization.auth.fieldRequired
                  })
              }}
            >
              {(field) => {
                const isInvalid =
                  isAuthFormFieldInvalid(field.state.meta) || isCompromised

                return (
                  <TextField
                    minLength={emailAndPassword?.minPasswordLength}
                    maxLength={emailAndPassword?.maxPasswordLength}
                    name={field.name}
                    autoComplete="new-password"
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(value) => {
                      field.handleChange(value)
                      setIsCompromised(false)
                    }}
                    isInvalid={isInvalid || undefined}
                    isDisabled={isPending}
                    validationBehavior="aria"
                  >
                    <Label>{localization.auth.password}</Label>

                    <InputGroup
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    >
                      <InputGroup.Input
                        name="password"
                        placeholder={localization.auth.newPasswordPlaceholder}
                        type={isPasswordVisible ? "text" : "password"}
                        required
                      />

                      <InputGroup.Suffix className="px-0">
                        <Button
                          isIconOnly
                          aria-label={
                            isPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          size="sm"
                          variant="ghost"
                          onPress={() =>
                            setIsPasswordVisible(!isPasswordVisible)
                          }
                          isDisabled={isPending}
                        >
                          {isPasswordVisible ? <EyeSlash /> : <Eye />}
                        </Button>
                      </InputGroup.Suffix>
                    </InputGroup>

                    {isCompromised ? (
                      <FieldError>
                        {localization.auth.passwordCompromised}
                      </FieldError>
                    ) : (
                      <field.AuthFormFieldError />
                    )}

                    <PasswordStrengthMeter password={field.state.value} />
                  </TextField>
                )
              }}
            </form.AppField>

            {emailAndPassword?.confirmPassword && (
              <form.AppField
                name="confirmPassword"
                validators={{
                  onChangeListenTo: ["password"],
                  onChange: ({ fieldApi, value }) =>
                    validateStringLength(value, {
                      maxLength: emailAndPassword?.maxPasswordLength,
                      maxLengthMessage: localization.auth.tooLong.replace(
                        "{{max}}",
                        String(emailAndPassword?.maxPasswordLength)
                      ),
                      minLength: emailAndPassword?.minPasswordLength,
                      minLengthMessage: localization.auth.tooShort.replace(
                        "{{min}}",
                        String(emailAndPassword?.minPasswordLength)
                      ),
                      requiredMessage: localization.auth.fieldRequired
                    }) ??
                    validateMatchingValue(
                      value,
                      fieldApi.form.getFieldValue("password"),
                      localization.auth.passwordsDoNotMatch
                    )
                }}
              >
                {(field) => (
                  <TextField
                    minLength={emailAndPassword?.minPasswordLength}
                    maxLength={emailAndPassword?.maxPasswordLength}
                    name={field.name}
                    autoComplete="new-password"
                    isDisabled={isPending}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                    value={field.state.value}
                    isInvalid={
                      isAuthFormFieldInvalid(field.state.meta) || undefined
                    }
                    validationBehavior="aria"
                  >
                    <Label>{localization.auth.confirmPassword}</Label>

                    <InputGroup
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    >
                      <InputGroup.Input
                        placeholder={
                          localization.auth.confirmPasswordPlaceholder
                        }
                        type={isConfirmPasswordVisible ? "text" : "password"}
                        required
                        name="confirmPassword"
                      />

                      <InputGroup.Suffix className="px-0">
                        <Button
                          isIconOnly
                          aria-label={
                            isConfirmPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          size="sm"
                          variant="ghost"
                          onPress={() =>
                            setIsConfirmPasswordVisible(
                              !isConfirmPasswordVisible
                            )
                          }
                          isDisabled={isPending}
                        >
                          {isConfirmPasswordVisible ? <EyeSlash /> : <Eye />}
                        </Button>
                      </InputGroup.Suffix>
                    </InputGroup>

                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>
            )}

            <div className="flex flex-col gap-3">
              <form.AuthFormSubmitButton
                className="w-full"
                isDisabled={isPending}
              >
                {localization.auth.resetPassword}
              </form.AuthFormSubmitButton>
            </div>
          </form.AuthFormRoot>
        </form.AppForm>
      </Card.Content>

      <Card.Footer className="flex-col gap-3">
        <Description className="text-sm">
          {localization.auth.rememberYourPassword}{" "}
          <Link
            href={getAuthLinkURL(
              `${basePaths.auth}/${viewPaths.auth.signIn}`,
              redirectTo
            )}
            className="text-accent no-underline hover:underline decoration-accent-hover"
          >
            {localization.auth.signIn}
          </Link>
        </Description>
      </Card.Footer>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/reset-password.tsx
import {
  getAuthLinkURL,
  getFormFieldErrors,
  isPasswordCompromisedError,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import { AuthLink, useAuth, useResetPassword } from "@better-auth-ui/solid"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { Alert, AlertDescription } from "@/components/ui/alert"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { cn } from "cn"
import { createAuthForm, isAuthFormFieldInvalid } from "./auth-form"
import { PasswordStrengthMeter } from "./password-strength-meter"

export type ResetPasswordProps = {
  class?: string
  token?: string
}

const tokenFromLocation = () => {
  if (typeof window === "undefined") return undefined

  return new URLSearchParams(window.location.search).get("token")
}

export function ResetPassword(props: ResetPasswordProps) {
  const auth = useAuth()
  const [isCompromised, setIsCompromised] = createSignal(false)
  const [tokenError, setTokenError] = createSignal<string>()
  const [isPasswordVisible, setIsPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const resetPassword = useResetPassword(auth.authClient, () => ({
    onError: (error) => {
      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setIsCompromised(true)
      }
    }
  }))
  const form = createAuthForm(() => ({
    defaultValues: { confirmPassword: "", password: "" },
    onSubmit: async ({ value }) => {
      const token = props.token ?? tokenFromLocation()

      setTokenError(
        token ? undefined : auth.localization.auth.invalidResetPasswordToken
      )
      if (!token) return
      try {
        await resetPassword.mutateAsync({ token, newPassword: value.password })
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  }))

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.resetPassword}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot aria-label="Reset password">
            <div class="flex flex-col gap-6">
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      maxLength: auth.emailAndPassword.maxPasswordLength,
                      maxLengthMessage: auth.localization.auth.tooLong.replace(
                        "{{max}}",
                        String(auth.emailAndPassword.maxPasswordLength)
                      ),
                      minLength: auth.emailAndPassword.minPasswordLength,
                      minLengthMessage: auth.localization.auth.tooShort.replace(
                        "{{min}}",
                        String(auth.emailAndPassword.minPasswordLength)
                      ),
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta) ||
                    isCompromised()

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="reset-password-new">
                        {auth.localization.auth.newPassword}
                      </FieldLabel>
                      <div class="relative">
                        <Input
                          aria-invalid={isInvalid()}
                          autocomplete="new-password"
                          class="pr-12"
                          id="reset-password-new"
                          maxLength={auth.emailAndPassword.maxPasswordLength}
                          minLength={auth.emailAndPassword.minPasswordLength}
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) => {
                            field().handleChange(event.currentTarget.value)
                            setIsCompromised(false)
                          }}
                          placeholder={
                            auth.localization.auth.newPasswordPlaceholder
                          }
                          required
                          type={isPasswordVisible() ? "text" : "password"}
                          value={field().state.value}
                        />

                        <Button
                          aria-label={
                            isPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          class="absolute right-1 top-1/2 -translate-y-1/2"
                          onClick={() =>
                            setIsPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          type="button"
                          variant="ghost"
                        >
                          {isPasswordVisible() ? (
                            <EyeOff aria-hidden class="size-4" />
                          ) : (
                            <Eye aria-hidden class="size-4" />
                          )}
                        </Button>
                      </div>

                      <Show
                        when={
                          isCompromised()
                            ? auth.localization.auth.passwordCompromised
                            : undefined
                        }
                        fallback={
                          <FieldError
                            errors={getFormFieldErrors(
                              field().state.meta.errors
                            )}
                          />
                        }
                      >
                        {(message) => <FieldError>{message()}</FieldError>}
                      </Show>

                      <PasswordStrengthMeter password={field().state.value} />
                    </Field>
                  )
                }}
              </form.AppField>
              <form.AppField
                name="confirmPassword"
                validators={{
                  onChangeListenTo: ["password"],
                  onChange: ({ fieldApi, value }) =>
                    validateStringLength(value, {
                      maxLength: auth.emailAndPassword.maxPasswordLength,
                      maxLengthMessage: auth.localization.auth.tooLong.replace(
                        "{{max}}",
                        String(auth.emailAndPassword.maxPasswordLength)
                      ),
                      minLength: auth.emailAndPassword.minPasswordLength,
                      minLengthMessage: auth.localization.auth.tooShort.replace(
                        "{{min}}",
                        String(auth.emailAndPassword.minPasswordLength)
                      ),
                      requiredMessage: auth.localization.auth.fieldRequired
                    }) ??
                    validateMatchingValue(
                      value,
                      fieldApi.form.getFieldValue("password"),
                      auth.localization.auth.passwordsDoNotMatch
                    )
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta)

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="reset-password-confirm">
                        {auth.localization.auth.confirmPassword}
                      </FieldLabel>
                      <div class="relative">
                        <Input
                          aria-invalid={isInvalid()}
                          autocomplete="new-password"
                          class="pr-12"
                          id="reset-password-confirm"
                          maxLength={auth.emailAndPassword.maxPasswordLength}
                          minLength={auth.emailAndPassword.minPasswordLength}
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) =>
                            field().handleChange(event.currentTarget.value)
                          }
                          placeholder={
                            auth.localization.auth.confirmPasswordPlaceholder
                          }
                          required
                          type={
                            isConfirmPasswordVisible() ? "text" : "password"
                          }
                          value={field().state.value}
                        />

                        <Button
                          aria-label={
                            isConfirmPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          class="absolute right-1 top-1/2 -translate-y-1/2"
                          onClick={() =>
                            setIsConfirmPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isConfirmPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          type="button"
                          variant="ghost"
                        >
                          {isConfirmPasswordVisible() ? (
                            <EyeOff aria-hidden class="size-4" />
                          ) : (
                            <Eye aria-hidden class="size-4" />
                          )}
                        </Button>
                      </div>

                      <FieldError
                        errors={getFormFieldErrors(field().state.meta.errors)}
                      />
                    </Field>
                  )
                }}
              </form.AppField>
              <form.AuthFormSubmitButton disabled={resetPassword.isPending}>
                {auth.localization.auth.resetPassword}
              </form.AuthFormSubmitButton>
              <Show when={tokenError()}>
                {(message) => (
                  <Alert variant="destructive">
                    <AlertDescription>{message()}</AlertDescription>
                  </Alert>
                )}
              </Show>
              <Show when={resetPassword.isSuccess}>
                <Alert>
                  <AlertDescription role="status">
                    {auth.localization.auth.passwordResetSuccessDescription}
                  </AlertDescription>
                </Alert>
              </Show>
              <Show
                when={
                  resetPassword.isError &&
                  !isPasswordCompromisedError(resetPassword.error)
                }
              >
                <Alert variant="destructive">
                  <AlertDescription>
                    {auth.localization.auth.passwordResetErrorDescription}
                  </AlertDescription>
                </Alert>
              </Show>
            </div>
          </form.AuthFormRoot>
        </form.AppForm>

        <div class="mt-4 flex w-full flex-col items-center gap-3">
          <p class="text-center text-sm text-muted-foreground">
            {auth.localization.auth.rememberYourPassword}{" "}
            <AuthLink
              class="underline underline-offset-4"
              href={getAuthLinkURL(
                `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`,
                auth.redirectTo
              )}
            >
              {auth.localization.auth.signIn}
            </AuthLink>
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
