// packages/react-native/src/components/auth/verify-email.tsx
import { useAuth, useSendVerificationEmail } from "@better-auth-ui/react"
import { useEffect, useState } from "react"
import { View } from "react-native"
import { cn } from "../../lib/cn"
import { getPendingEmail } from "../../lib/pending-email"
import { Button } from "../../primitives/button"
import { Card, type CardVariant } from "../../primitives/card"
import { Description } from "../../primitives/description"
import { Link } from "../../primitives/link"
import { toast } from "../../primitives/toast"
import { OpenEmailButton } from "./open-email-button"

export type VerifyEmailProps = {
  className?: string
  variant?: CardVariant
}

/** Seconds the resend button stays disabled to prevent spamming the endpoint. */
const RESEND_COOLDOWN_SECONDS = 60

/**
 * Render a card prompting the user to verify their email, with a resend button
 * that is rate-limited by a cooldown timer.
 *
 * The target email is read from the in-memory pending-email store (set when
 * sign-up or sign-in redirects here); the OpenEmail/Resend controls are only
 * shown when an email is stored. The resend button is disabled while a
 * cooldown is active and shows the remaining seconds.
 *
 * @param className - Additional CSS classes applied to the outer card container
 * @param variant - Variant to apply to the card
 * @returns The verify-email card React element
 */
export function VerifyEmail({ className, variant }: VerifyEmailProps) {
  const { authClient, baseURL, localization, redirectTo } = useAuth()

  const [email, setEmail] = useState(() => getPendingEmail() ?? "")
  const [cooldown, setCooldown] = useState(RESEND_COOLDOWN_SECONDS)

  useEffect(() => {
    setEmail(getPendingEmail() ?? "")
  }, [])

  useEffect(() => {
    if (cooldown <= 0 || !email) return

    const interval = setInterval(() => {
      setCooldown((current) => (current > 0 ? current - 1 : 0))
    }, 1000)

    return () => clearInterval(interval)
  }, [cooldown, email])

  const { mutate: sendVerificationEmail, isPending } = useSendVerificationEmail(
    authClient,
    {
      onSuccess: () => {
        toast.success(localization.auth.verificationEmailSent)
        setCooldown(RESEND_COOLDOWN_SECONDS)
      }
    }
  )

  const isCoolingDown = cooldown > 0

  return (
    <Card className={cn("w-full max-w-sm gap-4", className)} variant={variant}>
      <Card.Header>
        <Card.Title className="mb-1">
          {localization.auth.verifyEmail}
        </Card.Title>
      </Card.Header>

      <Card.Content className="gap-4">
        <Description className="text-sm">
          {localization.auth.checkYourEmail}
        </Description>

        {email && (
          <View className="flex-col gap-3">
            <OpenEmailButton email={email} />

            <Button
              className="w-full"
              variant="tertiary"
              isDisabled={!email || isCoolingDown || isPending}
              isPending={isPending}
              onPress={() =>
                sendVerificationEmail({
                  email,
                  callbackURL: `${baseURL}${redirectTo}`
                })
              }
            >
              {isCoolingDown
                ? localization.auth.resendIn.replace(
                    "{{seconds}}",
                    String(cooldown)
                  )
                : localization.auth.resend}
            </Button>
          </View>
        )}
      </Card.Content>

      <Card.Footer className="flex-col gap-3">
        <Description className="text-sm">
          {localization.auth.alreadyVerifiedYourEmail}{" "}
          <Link view="signIn" className="text-sm">
            {localization.auth.signIn}
          </Link>
        </Description>
      </Card.Footer>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/verify-email.tsx
import { useAuth, useSendVerificationEmail } from "@better-auth-ui/solid"
import { Link } from "@tanstack/solid-router"
import { createSignal, onCleanup, onMount } from "solid-js"
import { isServer } from "solid-js/web"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { OpenEmailButton } from "./open-email-button"

export type VerifyEmailProps = {
  class?: string
}

/** Seconds the resend button stays disabled to prevent spamming the endpoint. */
const RESEND_COOLDOWN_SECONDS = 60

/**
 * Verify-email view. The target email is read from `sessionStorage` (set when
 * sign-up or sign-in redirects here); if none is stored the user is redirected
 * back to sign-in. Offers a button to open the user's email provider plus a
 * resend button rate-limited by a cooldown timer.
 */
export function VerifyEmail(props: VerifyEmailProps) {
  const auth = useAuth()

  const [email, setEmail] = createSignal(
    (!isServer && sessionStorage.getItem("better-auth-ui.verify-email")) || ""
  )
  const [cooldown, setCooldown] = createSignal(RESEND_COOLDOWN_SECONDS)

  const sendVerificationEmail = useSendVerificationEmail(auth.authClient, {
    onSuccess: () => {
      toast.success(auth.localization.auth.verificationEmailSent)
      setCooldown(RESEND_COOLDOWN_SECONDS)
    }
  })

  onMount(() => {
    const storedEmail = sessionStorage.getItem("better-auth-ui.verify-email")

    if (!storedEmail) {
      auth.navigate({
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
      return
    }

    setEmail(storedEmail)

    const interval = setInterval(() => {
      setCooldown((current) => (current > 0 ? current - 1 : 0))
    }, 1000)

    onCleanup(() => clearInterval(interval))
  })

  const isCoolingDown = () => cooldown() > 0

  const resend = () => {
    sendVerificationEmail.mutate({
      callbackURL: `${auth.baseURL}${auth.redirectTo}`,
      email: email()
    } as Parameters<typeof sendVerificationEmail.mutate>[0])
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.verifyEmail}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <div class="flex flex-col gap-4">
          <p class="text-sm text-muted-foreground">
            {auth.localization.auth.checkYourEmail}
          </p>

          <div class="flex flex-col gap-3">
            <OpenEmailButton email={email()} />

            <Button
              disabled={
                !email() || isCoolingDown() || sendVerificationEmail.isPending
              }
              onClick={resend}
              type="button"
              variant="outline"
            >
              {isCoolingDown()
                ? auth.localization.auth.resendIn.replace(
                    "{{seconds}}",
                    String(cooldown())
                  )
                : auth.localization.auth.resend}
            </Button>
          </div>
        </div>

        <div class="mt-4 flex w-full flex-col items-center gap-3">
          <p class="text-center text-sm text-muted-foreground">
            {auth.localization.auth.alreadyVerifiedYourEmail}{" "}
            <Link
              class="underline underline-offset-4"
              params={{ path: auth.viewPaths.auth.signIn }}
              to="/auth/$path"
            >
              {auth.localization.auth.signIn}
            </Link>
          </p>
        </div>
      </CardContent>
    </Card>
  )
}
