// examples/start-shadcn-baseui-example/src/components/auth/organization/delete-organization.tsx
"use client"

import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useAuth,
  useAuthPlugin,
  useHasPermission
} from "@better-auth-ui/react"
import { useState } from "react"

import { Button } from "@/components/ui/button"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { DeleteOrganizationDialog } from "./delete-organization-dialog"
import { DeleteOrganizationSkeleton } from "./delete-organization-skeleton"

/**
 * Danger-zone row to delete the active organization. Hidden for members without
 * the `organization:delete` permission.
 */
export function DeleteOrganization() {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { localization: organizationLocalization } =
    useAuthPlugin(organizationPlugin)

  const { data: activeOrganization } = useActiveOrganization(authClient)

  const { data: permission, isPending: permissionPending } = useHasPermission(
    authClient,
    {
      permissions: { organization: ["delete"] }
    }
  )

  const [confirmOpen, setConfirmOpen] = useState(false)

  if (permissionPending) {
    return <DeleteOrganizationSkeleton />
  }

  if (!permission?.success) {
    return null
  }

  return (
    <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <p className="text-sm font-medium leading-tight">
          {organizationLocalization.deleteOrganization}
        </p>

        <p className="text-muted-foreground mt-0.5 text-xs">
          {organizationLocalization.deleteOrganizationDescription}
        </p>
      </div>

      <Button
        disabled={!activeOrganization}
        size="sm"
        variant="outline"
        className="text-destructive"
        onClick={() => setConfirmOpen(true)}
      >
        {organizationLocalization.deleteOrganization}
      </Button>

      {activeOrganization && (
        <DeleteOrganizationDialog
          open={confirmOpen}
          onOpenChange={setConfirmOpen}
          organization={activeOrganization}
        />
      )}
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/delete-organization.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins/organization"
import type { OrganizationAuthClient } from "@better-auth-ui/solid"
import { useActiveOrganization, useAuth } from "@better-auth-ui/solid"
import { createSignal, Show } from "solid-js"
import { Button } from "@/components/ui/button"
import { DeleteOrganizationDialog } from "./delete-organization-dialog"

export type DeleteOrganizationProps = {
  localization: Pick<
    OrganizationLocalization,
    | "deleteOrganization"
    | "deleteOrganizationDescription"
    | "organizationDeleted"
  >
}

export function DeleteOrganization(props: DeleteOrganizationProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const [confirmOpen, setConfirmOpen] = createSignal(false)
  const activeOrganization = useActiveOrganization(auth.authClient)
  return (
    <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div>
        <p class="font-medium text-sm leading-tight">
          {props.localization.deleteOrganization}
        </p>
        <p class="mt-0.5 text-muted-foreground text-xs">
          {props.localization.deleteOrganizationDescription}
        </p>
      </div>

      <Button
        class="text-destructive"
        disabled={!activeOrganization.data}
        onClick={() => setConfirmOpen(true)}
        size="sm"
        type="button"
        variant="outline"
      >
        {props.localization.deleteOrganization}
      </Button>

      <Show when={activeOrganization.data}>
        {(organization) => (
          <DeleteOrganizationDialog
            localization={props.localization}
            onOpenChange={setConfirmOpen}
            open={confirmOpen()}
            organization={organization()}
          />
        )}
      </Show>
    </div>
  )
}
