// packages/heroui/src/components/auth/organization/organization-profile.tsx
import {
  fieldsWithModelValues,
  getAdditionalFieldDefaultValues,
  getAdditionalFieldSubmitValues,
  validateStringLength
} from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useActiveOrganization,
  useHasPermission,
  useUpdateOrganization
} from "@better-auth-ui/react/plugins/organization"
import {
  Card,
  type CardProps,
  cn,
  Input,
  Label,
  Skeleton,
  TextField,
  toast
} from "@heroui/react"
import { useEffect } from "react"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import {
  getAuthAdditionalFieldValidators,
  isAuthFormFieldInvalid,
  useAuthForm
} from "../auth-form"
import { ChangeOrganizationLogo } from "./change-organization-logo"
import { SlugField } from "./slug-field"

export type OrganizationProfileProps = {
  className?: string
  hideSlug?: boolean
  variant?: CardProps["variant"]
}

/**
 * Profile card for the active organization: logo (when enabled), display name, and slug.
 */
export function OrganizationProfile({
  className,
  variant,
  hideSlug: hideSlugProp,
  ...props
}: OrganizationProfileProps & Omit<CardProps, "children">) {
  const { authClient, localization } = useAuth()
  const {
    additionalFields,
    localization: organizationLocalization,
    hideSlug: pluginHideSlug
  } = useAuthPlugin(organizationPlugin)
  const hideSlug = hideSlugProp ?? pluginHideSlug ?? false

  const { data: activeOrganization } = useActiveOrganization(
    authClient as OrganizationAuthClient
  )
  const canUpdate = useHasPermission(authClient as OrganizationAuthClient, {
    permissions: { organization: ["update"] }
  })

  const { mutateAsync: commitOrganizationUpdate, isPending } =
    useUpdateOrganization(authClient as OrganizationAuthClient, {
      onSuccess: () =>
        toast.success(organizationLocalization.organizationUpdatedSuccess)
    })

  const form = useAuthForm({
    defaultValues: {
      additionalFields: getAdditionalFieldDefaultValues(additionalFields),
      name: "",
      slug: ""
    },
    onSubmit: async ({ value }) => {
      if (!activeOrganization || !canUpdate.data?.success) return
      await commitOrganizationUpdate({
        data: {
          ...getAdditionalFieldSubmitValues(
            additionalFields,
            value.additionalFields
          ),
          name: value.name,
          ...(!hideSlug && { slug: value.slug })
        }
      })
    }
  })

  useEffect(() => {
    if (!activeOrganization) return
    form.reset({
      additionalFields: getAdditionalFieldDefaultValues(
        fieldsWithModelValues(
          additionalFields,
          activeOrganization as Record<string, unknown>
        )
      ),
      name: activeOrganization.name,
      slug: activeOrganization.slug
    })
  }, [activeOrganization, additionalFields, form])

  const inputVariant = variant === "transparent" ? "primary" : "secondary"
  const formDisabled =
    isPending || canUpdate.isPending || !canUpdate.data?.success

  return (
    <div>
      <h2 className={cn("mb-3 text-sm font-semibold")}>
        {organizationLocalization.organizationProfile}
      </h2>

      <Card className={cn(className)} variant={variant} {...props}>
        <Card.Content>
          <form.AppForm>
            <form.AuthFormRoot className="flex flex-col gap-4">
              <ChangeOrganizationLogo />

              <form.AppField
                name="name"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: localization.auth.fieldRequired,
                      trim: true
                    })
                }}
              >
                {(field) => {
                  const isInvalid = isAuthFormFieldInvalid(field.state.meta)

                  return (
                    <TextField
                      name={field.name}
                      isDisabled={formDisabled || !activeOrganization}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={field.handleChange}
                      isInvalid={isInvalid || undefined}
                      validationBehavior="aria"
                    >
                      <Label>{organizationLocalization.name}</Label>

                      <Input
                        className={cn(!activeOrganization && "hidden")}
                        autoComplete="organization"
                        placeholder={organizationLocalization.namePlaceholder}
                        variant={inputVariant}
                      />

                      {!activeOrganization && (
                        <Skeleton className="h-10 w-full rounded-xl md:h-9" />
                      )}

                      <field.AuthFormFieldError />
                    </TextField>
                  )
                }}
              </form.AppField>

              {!hideSlug &&
                (activeOrganization ? (
                  <form.AppField name="slug">
                    {(field) => (
                      <SlugField
                        value={field.state.value}
                        onChange={field.handleChange}
                        currentSlug={activeOrganization.slug}
                        isDisabled={formDisabled}
                        variant={inputVariant}
                      />
                    )}
                  </form.AppField>
                ) : (
                  <TextField isDisabled>
                    <Label>{organizationLocalization.slug}</Label>
                    <Skeleton className="h-10 w-full rounded-xl md:h-9" />
                  </TextField>
                ))}
              {activeOrganization &&
                additionalFields.map((configuredField) => (
                  <form.AppField
                    key={configuredField.name}
                    name={`additionalFields.${configuredField.name}`}
                    validators={getAuthAdditionalFieldValidators(
                      configuredField,
                      localization.auth.fieldRequired
                    )}
                  >
                    {(field) => (
                      <field.AuthFormAdditionalField
                        field={configuredField}
                        isPending={formDisabled}
                        optionalLabel={localization.settings.optional}
                        variant={variant}
                      />
                    )}
                  </form.AppField>
                ))}

              {(canUpdate.isPending || canUpdate.data?.success) && (
                <form.AuthFormSubmitButton
                  isDisabled={formDisabled || !activeOrganization}
                  size="sm"
                  className="mt-1"
                >
                  {localization.settings.saveChanges}
                </form.AuthFormSubmitButton>
              )}
            </form.AuthFormRoot>
          </form.AppForm>
        </Card.Content>
      </Card>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-profile.tsx
import {
  fieldsWithModelValues,
  getAdditionalFieldDefaultValues,
  getAdditionalFieldSubmitValues,
  getFormFieldErrors,
  validateStringLength
} from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useHasPermission,
  useUpdateOrganization
} from "@better-auth-ui/solid/plugins/organization"
import { createEffect, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Card, CardContent } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import {
  createAuthForm,
  getAuthAdditionalFieldValidators,
  isAuthFormFieldInvalid
} from "../auth-form"
import { ChangeOrganizationLogo } from "./change-organization-logo"
import { SlugField } from "./slug-field"

export type OrganizationProfileProps = {
  class?: string
  hideSlug?: boolean
}

export function OrganizationProfile(props: OrganizationProfileProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const activeOrganization = useActiveOrganization(auth.authClient)
  const canUpdate = useHasPermission(auth.authClient, () => ({
    permissions: { organization: ["update"] }
  }))
  const config = useAuthPlugin(organizationPlugin)
  const hideSlug = () => props.hideSlug ?? config.hideSlug ?? false
  const updateOrganization = useUpdateOrganization(auth.authClient, () => ({
    onSuccess: () =>
      toast.success(config.localization.organizationUpdatedSuccess)
  }))
  const form = createAuthForm(() => ({
    defaultValues: {
      additionalFields: getAdditionalFieldDefaultValues(
        config.additionalFields
      ),
      name: "",
      slug: ""
    },
    onSubmit: async ({ value }) => {
      if (!activeOrganization.data || !canUpdate.data?.success) return
      await updateOrganization.mutateAsync({
        data: {
          ...getAdditionalFieldSubmitValues(
            config.additionalFields,
            value.additionalFields
          ),
          name: value.name,
          ...(!hideSlug() && { slug: value.slug })
        }
      })
    }
  }))
  createEffect(() => {
    const organization = activeOrganization.data
    if (!organization) return
    form.reset({
      additionalFields: getAdditionalFieldDefaultValues(
        fieldsWithModelValues(
          config.additionalFields,
          organization as Record<string, unknown>
        )
      ),
      name: organization.name,
      slug: organization.slug
    })
  })
  const formDisabled = () =>
    updateOrganization.isPending ||
    canUpdate.isPending ||
    !canUpdate.data?.success

  return (
    <div class={props.class}>
      <h2 class="mb-3 font-semibold text-sm">
        {config.localization.organizationProfile}
      </h2>
      <Card>
        <CardContent>
          <form.AppForm>
            <form.AuthFormRoot class="flex flex-col gap-4">
              <ChangeOrganizationLogo class="-ml-1" />

              <form.AppField
                name="name"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: auth.localization.auth.fieldRequired,
                      trim: true
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta)

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="organization-profile-name">
                        {config.localization.name}
                      </FieldLabel>
                      <Show when={activeOrganization.data}>
                        <Input
                          aria-invalid={isInvalid()}
                          disabled={formDisabled()}
                          id="organization-profile-name"
                          name={field().name}
                          onBlur={field().handleBlur}
                          onInput={(event) =>
                            field().handleChange(event.currentTarget.value)
                          }
                          placeholder={config.localization.namePlaceholder}
                          value={field().state.value}
                        />
                      </Show>
                      <FieldError
                        errors={getFormFieldErrors(field().state.meta.errors)}
                      />
                    </Field>
                  )
                }}
              </form.AppField>

              <Show when={!hideSlug() && activeOrganization.data}>
                {(organization) => (
                  <form.AppField name="slug">
                    {(field) => (
                      <SlugField
                        currentSlug={organization().slug}
                        disabled={formDisabled()}
                        id="organization-profile-slug"
                        onChange={field().handleChange}
                        value={field().state.value}
                      />
                    )}
                  </form.AppField>
                )}
              </Show>

              <Show when={activeOrganization.data}>
                <For each={config.additionalFields}>
                  {(configuredField) => (
                    <form.AppField
                      name={`additionalFields.${configuredField.name}`}
                      validators={getAuthAdditionalFieldValidators(
                        configuredField,
                        auth.localization.auth.fieldRequired
                      )}
                    >
                      {(field) => (
                        <field.AuthFormAdditionalField
                          field={configuredField}
                          isPending={formDisabled()}
                          optionalLabel={auth.localization.settings.optional}
                        />
                      )}
                    </form.AppField>
                  )}
                </For>
              </Show>

              <Show when={canUpdate.isPending || canUpdate.data?.success}>
                <form.AuthFormSubmitButton
                  class="mt-1 w-fit"
                  disabled={!activeOrganization.data || formDisabled()}
                  size="sm"
                >
                  {auth.localization.settings.saveChanges}
                </form.AuthFormSubmitButton>
              </Show>
            </form.AuthFormRoot>
          </form.AppForm>
        </CardContent>
      </Card>
    </div>
  )
}
