// examples/start-shadcn-baseui-example/src/components/auth/organization/organization-teams.tsx
"use client"

import {
  type AdditionalFields,
  fieldsWithModelValues,
  parseAdditionalFieldValues
} from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useActiveOrganization,
  useAddTeamMember,
  useCreateTeam,
  useHasPermission,
  useListOrganizationMembers,
  useListTeamMembers,
  useListTeams,
  useRemoveTeam,
  useRemoveTeamMember,
  useUpdateTeam
} from "@better-auth-ui/react/plugins/organization"
import { type FormEvent, useState } from "react"
import { toast } from "sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectGroup,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { AdditionalField } from "../additional-field"

export function OrganizationTeams() {
  const { authClient, localization: authLocalization } =
    useAuth<OrganizationAuthClient>()
  const { data: activeOrganization } = useActiveOrganization(authClient)
  const { localization, modelFields, teamPolicy } =
    useAuthPlugin(organizationPlugin)
  const teams = useListTeams(authClient, {
    query: { organizationId: activeOrganization?.id }
  })
  const members = useListOrganizationMembers(authClient)
  const createTeam = useCreateTeam(authClient, {
    onSuccess: () => toast.success(localization.teamCreated)
  })
  const canCreate = useHasPermission(authClient, {
    organizationId: activeOrganization?.id,
    permissions: { team: ["create"] }
  })

  const [isCreatingFields, setIsCreatingFields] = useState(false)
  const teamLimitReached =
    teamPolicy.maximumTeams !== undefined &&
    (teams.data?.length ?? 0) >= teamPolicy.maximumTeams

  async function handleCreate(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    const form = event.currentTarget
    const name = String(new FormData(form).get("name") ?? "").trim()
    if (
      !name ||
      !activeOrganization ||
      !canCreate.data?.success ||
      teamLimitReached
    )
      return

    setIsCreatingFields(true)
    try {
      const values = await parseAdditionalFieldValues(
        modelFields.team,
        new FormData(form)
      )
      createTeam.mutate(
        { ...values, name, organizationId: activeOrganization.id },
        {
          onSuccess: () => form.reset(),
          onSettled: () => setIsCreatingFields(false)
        }
      )
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
      setIsCreatingFields(false)
    }
  }

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
        <div>
          <h2 className="text-sm font-semibold">{localization.teams}</h2>
          <p className="text-sm text-muted-foreground">
            {localization.teamsDescription}
          </p>
        </div>
        {(canCreate.isPending || canCreate.data?.success) && (
          <form
            className="grid w-full gap-3 sm:max-w-xl sm:grid-cols-2"
            onSubmit={handleCreate}
          >
            <Field>
              <FieldLabel htmlFor="new-team-name">
                {localization.name}
              </FieldLabel>
              <Input
                id="new-team-name"
                name="name"
                required
                disabled={canCreate.isPending || teamLimitReached}
              />
            </Field>
            {modelFields.team.map((field) => (
              <AdditionalField
                key={field.name}
                field={field}
                name={field.name}
                isPending={
                  canCreate.isPending ||
                  createTeam.isPending ||
                  isCreatingFields
                }
                optionalLabel={authLocalization.settings.optional}
              />
            ))}
            <Button
              className="self-end"
              type="submit"
              disabled={
                canCreate.isPending ||
                createTeam.isPending ||
                isCreatingFields ||
                teamLimitReached
              }
            >
              {createTeam.isPending && <Spinner />}
              {localization.createTeam}
            </Button>
            {teamLimitReached && (
              <p
                className="text-sm text-destructive sm:col-span-2"
                role="alert"
              >
                {localization.teamLimitReached}
              </p>
            )}
          </form>
        )}
      </div>
      {teams.isPending ? (
        <Spinner />
      ) : teams.data?.length ? (
        teams.data.map((team) => (
          <TeamCard
            key={team.id}
            organizationId={activeOrganization?.id ?? ""}
            organizationMembers={members.data?.members ?? []}
            team={team}
            teamFields={modelFields.team}
            teamCount={teams.data?.length ?? 0}
            maximumMembersPerTeam={teamPolicy.maximumMembersPerTeam}
            allowRemovingAllTeams={teamPolicy.allowRemovingAllTeams}
          />
        ))
      ) : (
        <Card>
          <CardHeader>
            <CardTitle>{localization.noTeams}</CardTitle>
          </CardHeader>
          <CardContent className="text-sm text-muted-foreground">
            {localization.noTeamsDescription}
          </CardContent>
        </Card>
      )}
    </div>
  )
}

function TeamCard({
  organizationId,
  organizationMembers,
  team,
  teamFields,
  teamCount,
  maximumMembersPerTeam,
  allowRemovingAllTeams
}: {
  organizationId: string
  organizationMembers: Array<{
    userId: string
    user: { name: string; email: string }
  }>
  team: { id: string; name: string; [key: string]: unknown }
  teamFields: AdditionalFields
  teamCount: number
  maximumMembersPerTeam?: number
  allowRemovingAllTeams: boolean
}) {
  const { authClient, localization: authLocalization } =
    useAuth<OrganizationAuthClient>()
  const { localization } = useAuthPlugin(organizationPlugin)
  const teamMembers = useListTeamMembers(authClient, {
    query: { teamId: team.id }
  })
  const canUpdate = useHasPermission(authClient, {
    organizationId,
    permissions: { team: ["update"] }
  })
  const canDelete = useHasPermission(authClient, {
    organizationId,
    permissions: { team: ["delete"] }
  })
  const canAddMember = useHasPermission(authClient, {
    organizationId,
    permissions: { member: ["update"] }
  })
  const canRemoveMember = useHasPermission(authClient, {
    organizationId,
    permissions: { member: ["delete"] }
  })
  const updateTeam = useUpdateTeam(authClient)
  const removeTeam = useRemoveTeam(authClient)
  const [name, setName] = useState(team.name)
  const [isUpdatingFields, setIsUpdatingFields] = useState(false)
  const [userId, setUserId] = useState("")
  const addMember = useAddTeamMember(authClient, {
    onSuccess: () => setUserId("")
  })
  const removeMember = useRemoveTeamMember(authClient)
  const memberIds = new Set(teamMembers.data?.map((member) => member.userId))
  const availableMembers = organizationMembers
    .filter((member) => !memberIds.has(member.userId))
    .map((member) => ({
      label: member.user.name || member.user.email,
      value: member.userId
    }))
  const memberLimitReached =
    maximumMembersPerTeam !== undefined &&
    (teamMembers.data?.length ?? 0) >= maximumMembersPerTeam
  const canRemoveTeam = allowRemovingAllTeams || teamCount > 1

  const handleUpdate = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!canUpdate.data?.success) return
    setIsUpdatingFields(true)
    try {
      const values = await parseAdditionalFieldValues(
        teamFields,
        new FormData(event.currentTarget)
      )
      updateTeam.mutate(
        {
          teamId: team.id,
          data: { ...values, name, organizationId }
        },
        { onSettled: () => setIsUpdatingFields(false) }
      )
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
      setIsUpdatingFields(false)
    }
  }

  return (
    <Card>
      <CardContent className="flex flex-col gap-4 pt-6">
        <form
          className="grid items-end gap-3 sm:grid-cols-2"
          onSubmit={handleUpdate}
        >
          <Field className="flex-1">
            <FieldLabel htmlFor={`team-name-${team.id}`}>
              {localization.name}
            </FieldLabel>
            <Input
              id={`team-name-${team.id}`}
              value={name}
              onChange={(event) => setName(event.target.value)}
              disabled={canUpdate.isPending || !canUpdate.data?.success}
            />
          </Field>
          {fieldsWithModelValues(teamFields, team).map((field) => (
            <AdditionalField
              key={field.name}
              field={field}
              name={field.name}
              isPending={
                canUpdate.isPending ||
                !canUpdate.data?.success ||
                updateTeam.isPending ||
                isUpdatingFields
              }
              optionalLabel={authLocalization.settings.optional}
            />
          ))}
          {(canUpdate.isPending || canUpdate.data?.success) && (
            <Button
              type="submit"
              disabled={
                canUpdate.isPending || updateTeam.isPending || isUpdatingFields
              }
              variant="outline"
            >
              {authLocalization.settings.saveChanges}
            </Button>
          )}
          {(canDelete.isPending || canDelete.data?.success) && (
            <Button
              type="button"
              disabled={
                canDelete.isPending || removeTeam.isPending || !canRemoveTeam
              }
              title={
                canRemoveTeam
                  ? localization.deleteTeam
                  : localization.lastTeamRemovalDisabled
              }
              variant="destructive"
              onClick={() => {
                if (!canDelete.data?.success) return
                if (!window.confirm(localization.deleteTeam)) return
                removeTeam.mutate({ teamId: team.id, organizationId })
              }}
            >
              {localization.deleteTeam}
            </Button>
          )}
        </form>
        {!canRemoveTeam && canDelete.data?.success && (
          <p className="text-sm text-muted-foreground">
            {localization.lastTeamRemovalDisabled}
          </p>
        )}
        {(canAddMember.isPending || canAddMember.data?.success) && (
          <div className="flex items-end gap-2">
            <Field className="flex-1">
              <FieldLabel>{localization.addTeamMember}</FieldLabel>
              <Select
                items={availableMembers}
                value={userId}
                onValueChange={(value) => setUserId(value ?? "")}
                disabled={canAddMember.isPending || memberLimitReached}
              >
                <SelectTrigger className="w-full">
                  <SelectValue placeholder={localization.selectMember} />
                </SelectTrigger>
                <SelectContent>
                  <SelectGroup>
                    {availableMembers.map((member) => (
                      <SelectItem key={member.value} value={member.value}>
                        {member.label}
                      </SelectItem>
                    ))}
                  </SelectGroup>
                </SelectContent>
              </Select>
            </Field>
            <Button
              disabled={
                canAddMember.isPending ||
                !userId ||
                addMember.isPending ||
                memberLimitReached
              }
              onClick={() => {
                if (!canAddMember.data?.success || !userId) return
                addMember.mutate({ teamId: team.id, userId, organizationId })
              }}
            >
              {localization.addTeamMember}
            </Button>
          </div>
        )}
        {canAddMember.data?.success && memberLimitReached && (
          <p className="text-sm text-destructive" role="alert">
            {localization.teamMemberLimitReached}
          </p>
        )}
        <div className="flex flex-col gap-2">
          {teamMembers.data?.map((teamMember) => {
            const member = organizationMembers.find(
              (candidate) => candidate.userId === teamMember.userId
            )
            return (
              <div
                className="flex items-center justify-between gap-3"
                key={teamMember.id}
              >
                <span className="text-sm">
                  {member?.user.name || member?.user.email || teamMember.userId}
                </span>
                {(canRemoveMember.isPending ||
                  canRemoveMember.data?.success) && (
                  <Button
                    disabled={canRemoveMember.isPending}
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      if (!canRemoveMember.data?.success) return
                      removeMember.mutate({
                        teamId: team.id,
                        userId: teamMember.userId,
                        organizationId
                      })
                    }}
                  >
                    {localization.removeTeamMember}
                  </Button>
                )}
              </div>
            )
          })}
        </div>
      </CardContent>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-teams.tsx
import {
  type AdditionalFields,
  fieldsWithModelValues,
  parseAdditionalFieldValues
} from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useAddTeamMember,
  useCreateTeam,
  useHasPermission,
  useListOrganizationMembers,
  useListTeamMembers,
  useListTeams,
  useRemoveTeam,
  useRemoveTeamMember,
  useUpdateTeam
} from "@better-auth-ui/solid/plugins/organization"
import { createSignal, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue
} from "@/components/ui/select"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { AdditionalField } from "../additional-field"

type MemberOption = { id: string; label: string }

export function OrganizationTeams() {
  const auth = useAuth<OrganizationAuthClient>()
  const activeOrganization = useActiveOrganization(auth.authClient)
  const config = useAuthPlugin(organizationPlugin)
  const teams = useListTeams(auth.authClient, () => ({
    query: { organizationId: activeOrganization.data?.id }
  }))
  const members = useListOrganizationMembers(auth.authClient)
  const createTeam = useCreateTeam(auth.authClient, () => ({
    onSuccess: () => toast.success(config.localization.teamCreated)
  }))
  const canCreate = useHasPermission(auth.authClient, () => ({
    organizationId: activeOrganization.data?.id,
    permissions: { team: ["create"] }
  }))
  const [isCreatingFields, setIsCreatingFields] = createSignal(false)
  const teamLimitReached = () =>
    config.teamPolicy.maximumTeams !== undefined &&
    (teams.data?.length ?? 0) >= config.teamPolicy.maximumTeams

  async function handleCreate(event: SubmitEvent) {
    event.preventDefault()
    const form = event.currentTarget as HTMLFormElement
    const name = String(new FormData(form).get("name") ?? "").trim()
    if (
      !name ||
      !activeOrganization.data ||
      !canCreate.data?.success ||
      teamLimitReached()
    )
      return

    setIsCreatingFields(true)
    try {
      const values = await parseAdditionalFieldValues(
        config.modelFields.team,
        new FormData(form)
      )
      createTeam.mutate(
        { ...values, name, organizationId: activeOrganization.data.id },
        {
          onSuccess: () => form.reset(),
          onSettled: () => setIsCreatingFields(false)
        }
      )
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
      setIsCreatingFields(false)
    }
  }

  return (
    <div class="flex flex-col gap-4">
      <div class="flex flex-col justify-between gap-3 sm:flex-row sm:items-end">
        <div>
          <h2 class="text-sm font-semibold">{config.localization.teams}</h2>
          <p class="text-sm text-muted-foreground">
            {config.localization.teamsDescription}
          </p>
        </div>
        <Show when={canCreate.isPending || canCreate.data?.success}>
          <form
            class="grid w-full gap-3 sm:max-w-xl sm:grid-cols-2"
            onSubmit={handleCreate}
          >
            <Field>
              <FieldLabel for="new-team-name">
                {config.localization.name}
              </FieldLabel>
              <Input
                disabled={canCreate.isPending || teamLimitReached()}
                id="new-team-name"
                name="name"
                required
              />
            </Field>
            <For each={config.modelFields.team}>
              {(field) => (
                <AdditionalField
                  field={field}
                  isPending={
                    canCreate.isPending ||
                    createTeam.isPending ||
                    isCreatingFields()
                  }
                  name={field.name}
                  optionalLabel={auth.localization.settings.optional}
                />
              )}
            </For>
            <Button
              class="self-end"
              type="submit"
              disabled={
                canCreate.isPending ||
                createTeam.isPending ||
                isCreatingFields() ||
                teamLimitReached()
              }
            >
              {config.localization.createTeam}
            </Button>
            <Show when={teamLimitReached()}>
              <p class="text-destructive text-sm sm:col-span-2" role="alert">
                {config.localization.teamLimitReached}
              </p>
            </Show>
          </form>
        </Show>
      </div>
      <Show
        when={teams.data?.length}
        fallback={
          <Card>
            <CardContent class="flex flex-col gap-1">
              <p class="text-sm font-medium">{config.localization.noTeams}</p>
              <p class="text-sm text-muted-foreground">
                {config.localization.noTeamsDescription}
              </p>
            </CardContent>
          </Card>
        }
      >
        <For each={teams.data}>
          {(team) => (
            <TeamCard
              organizationId={activeOrganization.data?.id ?? ""}
              organizationMembers={members.data?.members ?? []}
              team={team}
              teamFields={config.modelFields.team}
              teamCount={teams.data?.length ?? 0}
              maximumMembersPerTeam={config.teamPolicy.maximumMembersPerTeam}
              allowRemovingAllTeams={config.teamPolicy.allowRemovingAllTeams}
            />
          )}
        </For>
      </Show>
    </div>
  )
}

function TeamCard(props: {
  organizationId: string
  organizationMembers: Array<{
    userId: string
    user: { name: string; email: string }
  }>
  team: { id: string; name: string }
  teamFields: AdditionalFields
  teamCount: number
  maximumMembersPerTeam?: number
  allowRemovingAllTeams: boolean
}) {
  const auth = useAuth<OrganizationAuthClient>()
  const config = useAuthPlugin(organizationPlugin)
  const teamMembers = useListTeamMembers(auth.authClient, () => ({
    query: { teamId: props.team.id }
  }))
  const canUpdate = useHasPermission(auth.authClient, () => ({
    organizationId: props.organizationId,
    permissions: { team: ["update"] }
  }))
  const canDelete = useHasPermission(auth.authClient, () => ({
    organizationId: props.organizationId,
    permissions: { team: ["delete"] }
  }))
  const canAddMember = useHasPermission(auth.authClient, () => ({
    organizationId: props.organizationId,
    permissions: { member: ["update"] }
  }))
  const canRemoveMember = useHasPermission(auth.authClient, () => ({
    organizationId: props.organizationId,
    permissions: { member: ["delete"] }
  }))
  const updateTeam = useUpdateTeam(auth.authClient)
  const removeTeam = useRemoveTeam(auth.authClient)
  const [name, setName] = createSignal(props.team.name)
  const [isUpdatingFields, setIsUpdatingFields] = createSignal(false)
  const [selectedMember, setSelectedMember] = createSignal<MemberOption>()
  const addMember = useAddTeamMember(auth.authClient, () => ({
    onSuccess: () => setSelectedMember(undefined)
  }))
  const removeMember = useRemoveTeamMember(auth.authClient)
  const memberOptions = () => {
    const memberIds = new Set(teamMembers.data?.map((member) => member.userId))
    return props.organizationMembers
      .filter((member) => !memberIds.has(member.userId))
      .map((member) => ({
        id: member.userId,
        label: member.user.name || member.user.email
      }))
  }
  const memberLimitReached = () =>
    props.maximumMembersPerTeam !== undefined &&
    (teamMembers.data?.length ?? 0) >= props.maximumMembersPerTeam
  const canRemoveTeam = () => props.allowRemovingAllTeams || props.teamCount > 1

  const handleUpdate = async (event: SubmitEvent) => {
    event.preventDefault()
    if (!canUpdate.data?.success) return
    setIsUpdatingFields(true)
    try {
      const values = await parseAdditionalFieldValues(
        props.teamFields,
        new FormData(event.currentTarget as HTMLFormElement)
      )
      updateTeam.mutate(
        {
          teamId: props.team.id,
          data: {
            ...values,
            name: name(),
            organizationId: props.organizationId
          }
        },
        { onSettled: () => setIsUpdatingFields(false) }
      )
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
      setIsUpdatingFields(false)
    }
  }

  return (
    <Card>
      <CardContent class="flex flex-col gap-4">
        <form
          class="grid items-end gap-3 sm:grid-cols-2"
          onSubmit={handleUpdate}
        >
          <Field class="flex-1">
            <FieldLabel for={`team-name-${props.team.id}`}>
              {config.localization.name}
            </FieldLabel>
            <Input
              id={`team-name-${props.team.id}`}
              value={name()}
              onInput={(event) => setName(event.currentTarget.value)}
              disabled={canUpdate.isPending || !canUpdate.data?.success}
            />
          </Field>
          <For
            each={fieldsWithModelValues(
              props.teamFields,
              props.team as Record<string, unknown>
            )}
          >
            {(field) => (
              <AdditionalField
                field={field}
                isPending={
                  canUpdate.isPending ||
                  !canUpdate.data?.success ||
                  updateTeam.isPending ||
                  isUpdatingFields()
                }
                name={field.name}
                optionalLabel={auth.localization.settings.optional}
              />
            )}
          </For>
          <Show when={canUpdate.isPending || canUpdate.data?.success}>
            <Button
              type="submit"
              disabled={
                canUpdate.isPending ||
                updateTeam.isPending ||
                isUpdatingFields()
              }
              variant="outline"
            >
              {auth.localization.settings.saveChanges}
            </Button>
          </Show>
          <Show when={canDelete.isPending || canDelete.data?.success}>
            <Button
              type="button"
              disabled={
                canDelete.isPending || removeTeam.isPending || !canRemoveTeam()
              }
              title={
                canRemoveTeam()
                  ? config.localization.deleteTeam
                  : config.localization.lastTeamRemovalDisabled
              }
              variant="destructive"
              onClick={() => {
                if (!canDelete.data?.success) return
                if (!window.confirm(config.localization.deleteTeam)) return
                removeTeam.mutate({
                  teamId: props.team.id,
                  organizationId: props.organizationId
                })
              }}
            >
              {config.localization.deleteTeam}
            </Button>
          </Show>
        </form>
        <Show when={!canRemoveTeam() && canDelete.data?.success}>
          <p class="text-sm text-muted-foreground">
            {config.localization.lastTeamRemovalDisabled}
          </p>
        </Show>
        <Show when={canAddMember.isPending || canAddMember.data?.success}>
          <div class="flex items-end gap-2">
            <Field class="flex-1">
              <FieldLabel>{config.localization.addTeamMember}</FieldLabel>
              <Select<MemberOption>
                disabled={canAddMember.isPending || memberLimitReached()}
                options={memberOptions()}
                optionTextValue="label"
                optionValue="id"
                value={selectedMember()}
                onChange={(value) => setSelectedMember(value ?? undefined)}
                itemComponent={(itemProps) => (
                  <SelectItem item={itemProps.item}>
                    {itemProps.item.rawValue.label}
                  </SelectItem>
                )}
              >
                <SelectTrigger class="w-full">
                  <SelectValue<MemberOption>>
                    {(state) =>
                      (state.selectedOption() as MemberOption | undefined)
                        ?.label
                    }
                  </SelectValue>
                </SelectTrigger>
                <SelectContent />
              </Select>
            </Field>
            <Button
              disabled={
                canAddMember.isPending ||
                !selectedMember() ||
                addMember.isPending ||
                memberLimitReached()
              }
              onClick={() => {
                const member = selectedMember()
                if (!canAddMember.data?.success || !member) return
                addMember.mutate({
                  teamId: props.team.id,
                  userId: member.id,
                  organizationId: props.organizationId
                })
              }}
            >
              {config.localization.addTeamMember}
            </Button>
          </div>
        </Show>
        <Show when={canAddMember.data?.success && memberLimitReached()}>
          <p class="text-destructive text-sm" role="alert">
            {config.localization.teamMemberLimitReached}
          </p>
        </Show>
        <For each={teamMembers.data}>
          {(teamMember) => {
            const member = () =>
              props.organizationMembers.find(
                (candidate) => candidate.userId === teamMember.userId
              )
            return (
              <div class="flex items-center justify-between gap-3">
                <span class="text-sm">
                  {member()?.user.name ||
                    member()?.user.email ||
                    teamMember.userId}
                </span>
                <Show
                  when={
                    canRemoveMember.isPending || canRemoveMember.data?.success
                  }
                >
                  <Button
                    disabled={canRemoveMember.isPending}
                    size="sm"
                    variant="outline"
                    onClick={() => {
                      if (!canRemoveMember.data?.success) return
                      removeMember.mutate({
                        teamId: props.team.id,
                        userId: teamMember.userId,
                        organizationId: props.organizationId
                      })
                    }}
                  >
                    {config.localization.removeTeamMember}
                  </Button>
                </Show>
              </div>
            )
          }}
        </For>
      </CardContent>
    </Card>
  )
}
