// packages/heroui/src/components/auth/organization/organization-member-row-skeleton.tsx
import { Skeleton, Table } from "@heroui/react"

import { UserView } from "../user/user-view"

/**
 * Placeholder row matching {@link OrganizationMemberRow} while members load.
 */
export function OrganizationMemberRowSkeleton({
  showTeams
}: {
  showTeams?: boolean
}) {
  return (
    <Table.Row>
      <Table.Cell>
        <UserView isPending />
      </Table.Cell>

      <Table.Cell>
        <Skeleton className="h-4 w-18 rounded-lg" />
      </Table.Cell>

      {showTeams && (
        <Table.Cell>
          <Skeleton className="h-4 w-24 rounded-lg" />
        </Table.Cell>
      )}

      <Table.Cell className="flex justify-end">
        <Skeleton className="size-8 rounded-full" />
      </Table.Cell>
    </Table.Row>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-member-row-skeleton.tsx
import { Show } from "solid-js"
import { Skeleton } from "@/components/ui/skeleton"
import { TableCell, TableRow } from "@/components/ui/table"

export function OrganizationMemberRowSkeleton(props: { showTeams?: boolean }) {
  return (
    <TableRow>
      <TableCell>
        <div class="flex items-center gap-3">
          <Skeleton class="size-8 rounded-full" />
          <div class="grid gap-1">
            <Skeleton class="h-4 w-32 rounded-md" />
            <Skeleton class="h-3 w-44 rounded-md" />
          </div>
        </div>
      </TableCell>
      <TableCell>
        <Skeleton class="h-4 w-40 rounded-md" />
      </TableCell>
      <Show when={props.showTeams}>
        <TableCell>
          <Skeleton class="h-4 w-24 rounded-md" />
        </TableCell>
      </Show>
      <TableCell class="text-right">
        <div class="flex justify-end gap-2">
          <Skeleton class="size-8 rounded-md" />
          <Skeleton class="size-8 rounded-md" />
        </div>
      </TableCell>
    </TableRow>
  )
}
