// apps/docs/src/components/auth/organization/organization-invitations.tsx
"use client"

import {
  hasMemberRole,
  type OrganizationAuthClient,
  type OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useCancelInvitation,
  useHasPermission,
  useListOrganizationInvitations
} from "@better-auth-ui/react/plugins/organization"
import type { Invitation } from "better-auth/client"
import { Filter, Search, X } from "lucide-react"
import { type ComponentProps, useState } from "react"
import { toast } from "sonner"

import { Badge } from "@/components/ui/badge"
import { Button, buttonVariants } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { InviteMemberDialog } from "./invite-member-dialog"
import { OrganizationInvitationRow } from "./organization-invitation-row"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import { OrganizationInvitationsEmpty } from "./organization-invitations-empty"
import { OrganizationSortableTableHead } from "./organization-sortable-table-head"
import {
  createOrganizationColumnHelper,
  ORGANIZATION_TABLE_PAGE_SIZE,
  useOrganizationTable
} from "./organization-table"
import { OrganizationTableBulkAction } from "./organization-table-bulk-action"
import { OrganizationTablePagination } from "./organization-table-pagination"
import { OrganizationTableSelectAll } from "./organization-table-selection"
import { useOrganizationTableState } from "./organization-table-state"
import { OrganizationTableViewOptions } from "./organization-table-view-options"

const invitationColumnHelper = createOrganizationColumnHelper<Invitation>()
const invitationColumns = invitationColumnHelper.columns([
  invitationColumnHelper.accessor("email", {
    enableHiding: false,
    filterFn: "includesString"
  }),
  invitationColumnHelper.accessor(
    (invitation) => new Date(invitation.createdAt).getTime(),
    { id: "createdAt", enableGlobalFilter: false }
  ),
  invitationColumnHelper.accessor("role", {
    enableGlobalFilter: false,
    filterFn: (row, columnId, value) =>
      hasMemberRole(row.getValue<string>(columnId), String(value))
  }),
  invitationColumnHelper.accessor("status", {
    enableGlobalFilter: false,
    filterFn: (row, columnId, value) => row.getValue(columnId) === String(value)
  })
])
const EMPTY_INVITATIONS: Invitation[] = []

/** Props for the `OrganizationInvitations` component. */
export type OrganizationInvitationsProps = {
  className?: string
}

/**
 * Organization invitations table with invite control and per-row actions.
 */
export function OrganizationInvitations({
  className,
  ...props
}: OrganizationInvitationsProps & ComponentProps<"div">) {
  const { authClient, localization } = useAuth<OrganizationAuthClient>()
  const { localization: organizationLocalization, roles } =
    useAuthPlugin(organizationPlugin)
  const { data: invitations, isPending: invitationsPending } =
    useListOrganizationInvitations(authClient)

  const canInvite = useHasPermission(authClient, {
    permissions: { invitation: ["create"] }
  })
  const canCancel = useHasPermission(authClient, {
    permissions: { invitation: ["cancel"] }
  })

  const isPending = invitationsPending || canCancel.isPending
  const tableState = useOrganizationTableState(
    "organizationInvitations",
    ORGANIZATION_TABLE_PAGE_SIZE
  )
  const {
    columnFilters,
    columnVisibility,
    globalFilter,
    pagination,
    rowSelection,
    sorting
  } = tableState

  const table = useOrganizationTable({
    columns: invitationColumns,
    data: invitations ?? EMPTY_INVITATIONS,
    enableRowSelection: (row) =>
      canCancel.data?.success === true && row.original.status === "pending",
    globalFilterFn: "includesString",
    getRowId: (invitation) => invitation.id,
    state: {
      columnFilters,
      columnVisibility,
      globalFilter,
      pagination,
      rowSelection,
      sorting
    },
    onColumnFiltersChange: tableState.setColumnFilters,
    onColumnVisibilityChange: tableState.setColumnVisibility,
    onGlobalFilterChange: tableState.setGlobalFilter,
    onPaginationChange: tableState.setPagination,
    onRowSelectionChange: tableState.setRowSelection,
    onSortingChange: tableState.setSorting
  })

  const cancelInvitations = useCancelInvitation(authClient)
  const roleFilter = String(table.getColumn("role")?.getFilterValue() ?? "all")
  const statusFilter = String(
    table.getColumn("status")?.getFilterValue() ?? "all"
  )
  const roleFacetRows = table.getColumn("role")?.getFacetedRowModel().flatRows
  const statusCounts = table.getColumn("status")?.getFacetedUniqueValues()
  const selectedInvitations = table.getSelectedRowModel().rows
  const showSelection = canCancel.data?.success === true
  const visibleColumnCount = table.getVisibleLeafColumns().length

  async function cancelSelectedInvitations() {
    const results = await Promise.allSettled(
      selectedInvitations.map((row) =>
        cancelInvitations.mutateAsync({ invitationId: row.original.id })
      )
    )
    const canceledCount = results.filter(
      (result) => result.status === "fulfilled"
    ).length
    const failed = results.find((result) => result.status === "rejected")

    if (canceledCount > 0) {
      toast.success(
        organizationLocalization.invitationsCanceled.replace(
          "{{count}}",
          String(canceledCount)
        )
      )
    }
    if (failed?.status === "rejected") {
      toast.error(
        failed.reason instanceof Error
          ? failed.reason.message
          : String(failed.reason)
      )
    }
    table.resetRowSelection(true)
  }

  const [inviteOpen, setInviteOpen] = useState(false)

  return (
    <div className={cn("flex flex-col gap-3", className)} {...props}>
      <h3 className="truncate text-sm font-semibold">
        {organizationLocalization.invitations}
      </h3>

      <div className="flex flex-col gap-4">
        <div className="flex flex-wrap items-center gap-3">
          <InputGroup className="min-w-0 sm:w-[220px]">
            <InputGroupInput
              type="search"
              value={globalFilter}
              onChange={(event) => table.setGlobalFilter(event.target.value)}
              aria-label={organizationLocalization.search}
              placeholder={organizationLocalization.search}
              disabled={isPending}
            />

            <InputGroupAddon>
              <Search className="text-muted-foreground" />
            </InputGroupAddon>
          </InputGroup>

          <DropdownMenu>
            <DropdownMenuTrigger
              className={cn(buttonVariants({ size: "sm", variant: "outline" }))}
              disabled={isPending}
            >
              <Filter />

              {organizationLocalization.role}
            </DropdownMenuTrigger>

            <DropdownMenuContent align="start">
              <DropdownMenuRadioGroup
                value={roleFilter}
                onValueChange={(value) =>
                  table
                    .getColumn("role")
                    ?.setFilterValue(value === "all" ? undefined : value)
                }
              >
                <DropdownMenuRadioItem value="all">
                  {organizationLocalization.all}
                </DropdownMenuRadioItem>

                {Object.entries(roles).map(([key, label]) => (
                  <DropdownMenuRadioItem key={key} value={key}>
                    {label} (
                    {roleFacetRows?.filter((row) =>
                      hasMemberRole(row.original.role, key)
                    ).length ?? 0}
                    )
                  </DropdownMenuRadioItem>
                ))}
              </DropdownMenuRadioGroup>
            </DropdownMenuContent>
          </DropdownMenu>

          <DropdownMenu>
            <DropdownMenuTrigger
              className={cn(buttonVariants({ size: "sm", variant: "outline" }))}
              disabled={isPending}
            >
              <Filter />

              {organizationLocalization.status}
            </DropdownMenuTrigger>

            <DropdownMenuContent align="start">
              <DropdownMenuRadioGroup
                value={statusFilter}
                onValueChange={(value) =>
                  table
                    .getColumn("status")
                    ?.setFilterValue(value === "all" ? undefined : value)
                }
              >
                <DropdownMenuRadioItem value="all">
                  {organizationLocalization.all}
                </DropdownMenuRadioItem>

                {(["pending", "accepted", "rejected", "canceled"] as const).map(
                  (status) => (
                    <DropdownMenuRadioItem key={status} value={status}>
                      {organizationLocalization[
                        status as keyof OrganizationLocalization
                      ] ?? status}{" "}
                      ({statusCounts?.get(status) ?? 0})
                    </DropdownMenuRadioItem>
                  )
                )}
              </DropdownMenuRadioGroup>
            </DropdownMenuContent>
          </DropdownMenu>

          <div className="ms-auto">
            <OrganizationTableViewOptions
              columns={[
                {
                  id: "createdAt",
                  label: organizationLocalization.invitedAt,
                  visible: table.getColumn("createdAt")?.getIsVisible() ?? true,
                  onVisibleChange: (visible) =>
                    table.getColumn("createdAt")?.toggleVisibility(visible)
                },
                {
                  id: "role",
                  label: organizationLocalization.role,
                  visible: table.getColumn("role")?.getIsVisible() ?? true,
                  onVisibleChange: (visible) =>
                    table.getColumn("role")?.toggleVisibility(visible)
                },
                {
                  id: "status",
                  label: organizationLocalization.status,
                  visible: table.getColumn("status")?.getIsVisible() ?? true,
                  onVisibleChange: (visible) =>
                    table.getColumn("status")?.toggleVisibility(visible)
                }
              ]}
              disabled={isPending}
              localization={organizationLocalization}
            />
          </div>
        </div>

        {(roleFilter !== "all" || statusFilter !== "all") && (
          <div className="flex flex-wrap gap-2">
            {roleFilter !== "all" && (
              <Badge variant="secondary" className="gap-1">
                {organizationLocalization.role}:{" "}
                <span className="capitalize">
                  {roles?.[roleFilter] ?? roleFilter}
                </span>
                <Button
                  aria-label={organizationLocalization.clear}
                  className="size-4 rounded-sm text-muted-foreground"
                  onClick={() =>
                    table.getColumn("role")?.setFilterValue(undefined)
                  }
                  size="icon-xs"
                  type="button"
                  variant="ghost"
                >
                  <X className="size-3" />
                </Button>
              </Badge>
            )}

            {statusFilter !== "all" && (
              <Badge variant="secondary" className="gap-1">
                {organizationLocalization.status}:{" "}
                {organizationLocalization[
                  statusFilter as keyof OrganizationLocalization
                ] ?? statusFilter}
                <Button
                  aria-label={organizationLocalization.clear}
                  className="size-4 rounded-sm text-muted-foreground"
                  onClick={() =>
                    table.getColumn("status")?.setFilterValue(undefined)
                  }
                  size="icon-xs"
                  type="button"
                  variant="ghost"
                >
                  <X className="size-3" />
                </Button>
              </Badge>
            )}
          </div>
        )}

        {selectedInvitations.length > 0 && (
          <OrganizationTableBulkAction
            actionLabel={organizationLocalization.cancelSelectedInvitations}
            cancelLabel={localization.settings.cancel}
            count={selectedInvitations.length}
            description={
              organizationLocalization.cancelSelectedInvitationsDescription
            }
            isPending={cancelInvitations.isPending}
            onConfirm={cancelSelectedInvitations}
            selectedLabel={organizationLocalization.selectedCount}
          />
        )}

        <Card className="p-0">
          <Table aria-label={organizationLocalization.invitations}>
            <TableHeader>
              <TableRow>
                {showSelection && (
                  <TableHead className="w-10">
                    <OrganizationTableSelectAll
                      allSelected={table.getIsAllPageRowsSelected()}
                      disabled={isPending}
                      localization={organizationLocalization}
                      onCheckedChange={(checked) =>
                        table.toggleAllPageRowsSelected(checked)
                      }
                      someSelected={table.getIsSomePageRowsSelected()}
                    />
                  </TableHead>
                )}

                <OrganizationSortableTableHead
                  column={table.getColumn("email")}
                >
                  {localization.auth.email}
                </OrganizationSortableTableHead>

                {table.getColumn("createdAt")?.getIsVisible() && (
                  <OrganizationSortableTableHead
                    column={table.getColumn("createdAt")}
                  >
                    {organizationLocalization.invitedAt}
                  </OrganizationSortableTableHead>
                )}

                {table.getColumn("role")?.getIsVisible() && (
                  <OrganizationSortableTableHead
                    column={table.getColumn("role")}
                  >
                    {organizationLocalization.role}
                  </OrganizationSortableTableHead>
                )}

                {table.getColumn("status")?.getIsVisible() && (
                  <OrganizationSortableTableHead
                    column={table.getColumn("status")}
                  >
                    {organizationLocalization.status}
                  </OrganizationSortableTableHead>
                )}

                <TableHead className="text-end">
                  {organizationLocalization.actions}
                </TableHead>
              </TableRow>
            </TableHeader>

            <TableBody>
              {isPending ? (
                <OrganizationInvitationRowSkeleton />
              ) : !table.getRowModel().rows.length ? (
                <TableRow>
                  <TableCell
                    colSpan={visibleColumnCount + 1 + Number(showSelection)}
                  >
                    <OrganizationInvitationsEmpty
                      isInvitePending={canInvite.isPending}
                      onInvitePress={
                        canInvite.data?.success
                          ? () => setInviteOpen(true)
                          : undefined
                      }
                    />
                  </TableCell>
                </TableRow>
              ) : (
                table
                  .getRowModel()
                  .rows.map((row) => (
                    <OrganizationInvitationRow
                      key={row.original.id}
                      invitation={row.original}
                      selectableRow={showSelection ? row : undefined}
                      showCreatedAt={table
                        .getColumn("createdAt")
                        ?.getIsVisible()}
                      showRole={table.getColumn("role")?.getIsVisible()}
                      showStatus={table.getColumn("status")?.getIsVisible()}
                    />
                  ))
              )}
            </TableBody>
          </Table>
        </Card>

        <OrganizationTablePagination
          canNextPage={table.getCanNextPage()}
          canPreviousPage={table.getCanPreviousPage()}
          disabled={isPending}
          localization={organizationLocalization}
          onFirstPage={() => table.firstPage()}
          onLastPage={() => table.lastPage()}
          onNextPage={() => table.nextPage()}
          onPageSizeChange={(pageSize) => table.setPageSize(pageSize)}
          onPreviousPage={() => table.previousPage()}
          pageCount={table.getPageCount()}
          pageIndex={pagination.pageIndex}
          pageSize={pagination.pageSize}
          rowCount={table.getRowCount()}
          visibleRowCount={table.getRowModel().rows.length}
        />
      </div>

      {canInvite.data?.success && (
        <InviteMemberDialog open={inviteOpen} onOpenChange={setInviteOpen} />
      )}
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-invitations.tsx
import {
  hasMemberRole,
  type OrganizationAuthClient,
  type OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import {
  useCancelInvitation,
  useHasPermission,
  useListOrganizationInvitations
} from "@better-auth-ui/solid/plugins/organization"
import { Filter, Search, X } from "lucide-solid"
import { createMemo, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Card } from "@/components/ui/card"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuRadioGroup,
  DropdownMenuRadioItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow
} from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"
import { OrganizationInvitationRow } from "./organization-invitation-row"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import { OrganizationInvitationsEmpty } from "./organization-invitations-empty"
import { OrganizationSortableTableHead } from "./organization-sortable-table-head"
import {
  createOrganizationColumnHelper,
  createOrganizationTable,
  ORGANIZATION_TABLE_PAGE_SIZE
} from "./organization-table"
import { OrganizationTableBulkAction } from "./organization-table-bulk-action"
import { OrganizationTablePagination } from "./organization-table-pagination"
import { OrganizationTableSelectAll } from "./organization-table-selection"
import { createOrganizationTableState } from "./organization-table-state"
import { OrganizationTableViewOptions } from "./organization-table-view-options"

export type OrganizationInvitationsProps = {
  class?: string
}

type RoleMap = Record<string, string>

const fallbackLocalization = {
  search: "Search...",
  clear: "Clear",
  all: "All",
  role: "Role",
  status: "Status",
  pending: "Pending",
  accepted: "Accepted",
  rejected: "Rejected",
  canceled: "Canceled",
  member: "Member",
  admin: "Admin",
  owner: "Owner",
  previousPage: "Previous page",
  nextPage: "Next page",
  paginationRange: "{{from}}–{{to}} of {{total}}",
  firstPage: "First page",
  lastPage: "Last page",
  pageOf: "Page {{page}} of {{pages}}",
  rowsPerPage: "Rows per page",
  columns: "Columns",
  selectedCount: "{{count}} selected",
  selectRow: "Select row",
  selectAllRows: "Select all rows",
  cancelSelectedInvitations: "Cancel selected invitations",
  cancelSelectedInvitationsDescription:
    "Cancel every selected pending invitation?",
  invitationsCanceled: "Canceled {{count}} invitations"
} satisfies Pick<
  OrganizationLocalization,
  | "search"
  | "clear"
  | "all"
  | "role"
  | "status"
  | "pending"
  | "accepted"
  | "rejected"
  | "canceled"
  | "member"
  | "admin"
  | "owner"
  | "previousPage"
  | "nextPage"
  | "paginationRange"
  | "firstPage"
  | "lastPage"
  | "pageOf"
  | "rowsPerPage"
  | "columns"
  | "selectedCount"
  | "selectRow"
  | "selectAllRows"
  | "cancelSelectedInvitations"
  | "cancelSelectedInvitationsDescription"
  | "invitationsCanceled"
>

const invitationStatuses = [
  "pending",
  "accepted",
  "rejected",
  "canceled"
] as const

const fallbackRoles: RoleMap = {
  owner: fallbackLocalization.owner,
  admin: fallbackLocalization.admin,
  member: fallbackLocalization.member
}

type OrganizationInvitation = {
  createdAt?: Date | string | null
  email?: string | null
  id: string
  organizationId: string
  role?: string | null
  status?: string | null
}

const invitationColumnHelper =
  createOrganizationColumnHelper<OrganizationInvitation>()
const invitationColumns = invitationColumnHelper.columns([
  invitationColumnHelper.accessor((invitation) => invitation.email ?? "", {
    id: "email",
    enableHiding: false,
    filterFn: "includesString"
  }),
  invitationColumnHelper.accessor(
    (invitation) =>
      invitation.createdAt
        ? new Date(invitation.createdAt).getTime()
        : Number.POSITIVE_INFINITY,
    { id: "createdAt", enableGlobalFilter: false }
  ),
  invitationColumnHelper.accessor((invitation) => invitation.role ?? "", {
    id: "role",
    enableGlobalFilter: false,
    filterFn: (row, columnId, value) =>
      hasMemberRole(row.getValue<string>(columnId), String(value))
  }),
  invitationColumnHelper.accessor((invitation) => invitation.status ?? "", {
    id: "status",
    enableGlobalFilter: false,
    filterFn: (row, columnId, value) => row.getValue(columnId) === String(value)
  })
])

function formatStatus(status?: string | null) {
  if (!status) return "Pending"

  return status.charAt(0).toUpperCase() + status.slice(1)
}

export function OrganizationInvitations(props: OrganizationInvitationsProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const tableState = createOrganizationTableState(
    "organizationInvitations",
    ORGANIZATION_TABLE_PAGE_SIZE
  )
  const invitations = useListOrganizationInvitations(auth.authClient)
  const invitationRows = () =>
    (invitations.data ?? []) as OrganizationInvitation[]
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | {
          localization?: Pick<
            OrganizationLocalization,
            | "search"
            | "clear"
            | "all"
            | "role"
            | "status"
            | "pending"
            | "accepted"
            | "rejected"
            | "canceled"
            | "previousPage"
            | "nextPage"
            | "paginationRange"
            | "firstPage"
            | "lastPage"
            | "pageOf"
            | "rowsPerPage"
            | "columns"
            | "selectedCount"
            | "selectRow"
            | "selectAllRows"
            | "cancelSelectedInvitations"
            | "cancelSelectedInvitationsDescription"
            | "invitationsCanceled"
          >
          roles?: RoleMap
        }
      | undefined
  const localization = () =>
    organizationPluginConfig()?.localization ?? fallbackLocalization
  const roles = createMemo(
    () => organizationPluginConfig()?.roles ?? fallbackRoles
  )
  const invitationRoleFilter = () =>
    String(table.getColumn("role")?.getFilterValue() ?? "all")
  const invitationStatusFilter = () =>
    String(table.getColumn("status")?.getFilterValue() ?? "all")
  const selectedRoleLabel = () =>
    roles()[invitationRoleFilter()] ?? invitationRoleFilter()
  const selectedStatusLabel = () =>
    invitationStatusFilter() === "all"
      ? localization().all
      : invitationStatusLabel(
          invitationStatusFilter() as (typeof invitationStatuses)[number]
        )
  const invitationStatusLabel = (status: (typeof invitationStatuses)[number]) =>
    localization()[status] ?? formatStatus(status)
  const table = createOrganizationTable({
    columns: invitationColumns,
    get data() {
      return invitationRows()
    },
    enableRowSelection: (row) =>
      canCancel.data?.success === true && row.original.status === "pending",
    globalFilterFn: "includesString",
    get state() {
      return {
        columnFilters: tableState.columnFilters(),
        columnVisibility: tableState.columnVisibility(),
        globalFilter: tableState.globalFilter(),
        pagination: tableState.pagination(),
        rowSelection: tableState.rowSelection(),
        sorting: tableState.sorting()
      }
    },
    getRowId: (invitation) => invitation.id,
    onColumnFiltersChange: tableState.setColumnFilters,
    onColumnVisibilityChange: tableState.setColumnVisibility,
    onGlobalFilterChange: tableState.setGlobalFilter,
    onPaginationChange: tableState.setPagination,
    onRowSelectionChange: tableState.setRowSelection,
    onSortingChange: tableState.setSorting
  })
  const canCancel = useHasPermission(auth.authClient, () => ({
    permissions: { invitation: ["cancel"] }
  }))
  const cancelInvitations = useCancelInvitation(auth.authClient)
  const selectedInvitations = () => table.getSelectedRowModel().rows
  const statusCounts = () => table.getColumn("status")?.getFacetedUniqueValues()
  const roleFacetRows = () =>
    table.getColumn("role")?.getFacetedRowModel().flatRows
  const cancelSelectedInvitations = async () => {
    const results = await Promise.allSettled(
      selectedInvitations().map((row) =>
        cancelInvitations.mutateAsync({ invitationId: row.original.id })
      )
    )
    const count = results.filter(
      (result) => result.status === "fulfilled"
    ).length
    const failed = results.find((result) => result.status === "rejected")
    if (count)
      toast.success(
        localization().invitationsCanceled.replace("{{count}}", String(count))
      )
    if (failed?.status === "rejected")
      toast.error(
        failed.reason instanceof Error
          ? failed.reason.message
          : String(failed.reason)
      )
    table.resetRowSelection(true)
  }

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <h3 class="truncate text-sm font-semibold">Invitations</h3>
      <Show
        when={!invitations.isPending}
        fallback={
          <Card class="z-card-padding-none">
            <Table>
              <TableBody>
                <OrganizationInvitationRowSkeleton />
                <OrganizationInvitationRowSkeleton />
              </TableBody>
            </Table>
          </Card>
        }
      >
        <Show
          when={invitationRows().length > 0}
          fallback={
            <Card class="z-card-padding-none">
              <Table>
                <TableBody>
                  <TableRow>
                    <TableCell colSpan={5}>
                      <OrganizationInvitationsEmpty />
                    </TableCell>
                  </TableRow>
                </TableBody>
              </Table>
            </Card>
          }
        >
          <div class="flex flex-col gap-2 sm:flex-row sm:items-center">
            <InputGroup class="min-w-0 sm:w-[220px]">
              <InputGroupAddon>
                <Search class="size-4 text-muted-foreground" />
              </InputGroupAddon>
              <InputGroupInput
                aria-label={localization().search}
                onInput={(event) =>
                  table.setGlobalFilter(event.currentTarget.value)
                }
                placeholder={localization().search}
                type="search"
                value={tableState.globalFilter()}
              />
            </InputGroup>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                class="shrink-0"
                variant="outline"
              >
                <Filter class="size-4" />
                {localization().role}
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuRadioGroup
                  onChange={(value) =>
                    table
                      .getColumn("role")
                      ?.setFilterValue(value === "all" ? undefined : value)
                  }
                  value={invitationRoleFilter()}
                >
                  <DropdownMenuRadioItem value="all">
                    {localization().all}
                  </DropdownMenuRadioItem>
                  <For each={Object.entries(roles())}>
                    {([role, label]) => (
                      <DropdownMenuRadioItem value={role}>
                        {label} (
                        {roleFacetRows()?.filter((row) =>
                          hasMemberRole(row.original.role, role)
                        ).length ?? 0}
                        )
                      </DropdownMenuRadioItem>
                    )}
                  </For>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <DropdownMenu>
              <DropdownMenuTrigger
                as={Button}
                class="shrink-0"
                variant="outline"
              >
                <Filter class="size-4" />
                {localization().status}
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuRadioGroup
                  onChange={(value) =>
                    table
                      .getColumn("status")
                      ?.setFilterValue(value === "all" ? undefined : value)
                  }
                  value={invitationStatusFilter()}
                >
                  <DropdownMenuRadioItem value="all">
                    {localization().all}
                  </DropdownMenuRadioItem>
                  <For each={invitationStatuses}>
                    {(status) => (
                      <DropdownMenuRadioItem value={status}>
                        {invitationStatusLabel(status)} (
                        {statusCounts()?.get(status) ?? 0})
                      </DropdownMenuRadioItem>
                    )}
                  </For>
                </DropdownMenuRadioGroup>
              </DropdownMenuContent>
            </DropdownMenu>
            <div class="ms-auto">
              <OrganizationTableViewOptions
                columns={[
                  {
                    id: "createdAt",
                    label: "Invited",
                    visible:
                      table.getColumn("createdAt")?.getIsVisible() ?? true,
                    onVisibleChange: (visible) =>
                      table.getColumn("createdAt")?.toggleVisibility(visible)
                  },
                  {
                    id: "role",
                    label: localization().role,
                    visible: table.getColumn("role")?.getIsVisible() ?? true,
                    onVisibleChange: (visible) =>
                      table.getColumn("role")?.toggleVisibility(visible)
                  },
                  {
                    id: "status",
                    label: localization().status,
                    visible: table.getColumn("status")?.getIsVisible() ?? true,
                    onVisibleChange: (visible) =>
                      table.getColumn("status")?.toggleVisibility(visible)
                  }
                ]}
                localization={localization()}
              />
            </div>
          </div>
          <Show
            when={
              invitationRoleFilter() !== "all" ||
              invitationStatusFilter() !== "all"
            }
          >
            <div class="flex flex-wrap gap-2">
              <Show when={invitationRoleFilter() !== "all"}>
                <Badge class="gap-1 pr-1" variant="secondary">
                  {localization().role}: {selectedRoleLabel()}
                  <Button
                    aria-label={`${localization().clear} invitation role filter`}
                    class="size-4 rounded-sm"
                    onClick={() =>
                      table.getColumn("role")?.setFilterValue(undefined)
                    }
                    size="icon-xs"
                    type="button"
                    variant="ghost"
                  >
                    <X class="size-3" />
                  </Button>
                </Badge>
              </Show>
              <Show when={invitationStatusFilter() !== "all"}>
                <Badge class="gap-1 pr-1" variant="secondary">
                  {localization().status}: {selectedStatusLabel()}
                  <Button
                    aria-label={`${localization().clear} invitation status filter`}
                    class="size-4 rounded-sm"
                    onClick={() =>
                      table.getColumn("status")?.setFilterValue(undefined)
                    }
                    size="icon-xs"
                    type="button"
                    variant="ghost"
                  >
                    <X class="size-3" />
                  </Button>
                </Badge>
              </Show>
            </div>
          </Show>
          <OrganizationTableBulkAction
            cancelLabel={auth.localization.settings.cancel}
            confirmLabel={localization().cancelSelectedInvitations}
            description={localization().cancelSelectedInvitationsDescription}
            localization={localization()}
            onConfirm={cancelSelectedInvitations}
            pending={cancelInvitations.isPending}
            selectedCount={selectedInvitations().length}
            title={localization().cancelSelectedInvitations}
          />
          <Card class="z-card-padding-none">
            <Table aria-label="Invitations">
              <TableHeader>
                <TableRow>
                  <Show when={canCancel.data?.success}>
                    <TableHead>
                      <OrganizationTableSelectAll
                        allSelected={table.getIsAllPageRowsSelected()}
                        localization={localization()}
                        onCheckedChange={(checked) =>
                          table.toggleAllPageRowsSelected(checked)
                        }
                        someSelected={table.getIsSomePageRowsSelected()}
                      />
                    </TableHead>
                  </Show>
                  <OrganizationSortableTableHead
                    column={table.getColumn("email")}
                  >
                    Email
                  </OrganizationSortableTableHead>
                  <Show when={table.getColumn("createdAt")?.getIsVisible()}>
                    <OrganizationSortableTableHead
                      column={table.getColumn("createdAt")}
                    >
                      Invited
                    </OrganizationSortableTableHead>
                  </Show>
                  <Show when={table.getColumn("role")?.getIsVisible()}>
                    <OrganizationSortableTableHead
                      column={table.getColumn("role")}
                    >
                      {localization().role}
                    </OrganizationSortableTableHead>
                  </Show>
                  <Show when={table.getColumn("status")?.getIsVisible()}>
                    <OrganizationSortableTableHead
                      column={table.getColumn("status")}
                    >
                      {localization().status}
                    </OrganizationSortableTableHead>
                  </Show>
                  <TableHead class="z-table-head-align-end">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <Show
                  when={table.getRowModel().rows.length > 0}
                  fallback={
                    <TableRow>
                      <TableCell
                        class="text-muted-foreground text-sm"
                        colSpan={5}
                      >
                        No invitations match the current filters.
                      </TableCell>
                    </TableRow>
                  }
                >
                  <For each={table.getRowModel().rows}>
                    {(row) => (
                      <OrganizationInvitationRow
                        invitation={row.original}
                        roles={roles()}
                        selectableRow={
                          canCancel.data?.success ? row : undefined
                        }
                        showCreatedAt={table
                          .getColumn("createdAt")
                          ?.getIsVisible()}
                        showRole={table.getColumn("role")?.getIsVisible()}
                        showStatus={table.getColumn("status")?.getIsVisible()}
                      />
                    )}
                  </For>
                </Show>
              </TableBody>
            </Table>
          </Card>
          <OrganizationTablePagination
            canNextPage={table.getCanNextPage()}
            canPreviousPage={table.getCanPreviousPage()}
            disabled={invitations.isPending}
            localization={localization()}
            onFirstPage={() => table.firstPage()}
            onLastPage={() => table.lastPage()}
            onNextPage={() => table.nextPage()}
            onPageSizeChange={(size) => table.setPageSize(size)}
            onPreviousPage={() => table.previousPage()}
            pageCount={table.getPageCount()}
            pageIndex={tableState.pagination().pageIndex}
            pageSize={tableState.pagination().pageSize}
            rowCount={table.getRowCount()}
            visibleRowCount={table.getRowModel().rows.length}
          />
        </Show>
      </Show>
    </div>
  )
}
