// packages/react-native/src/components/auth/organization/organization-switcher.tsx
import {
  type OrganizationAuthClient,
  useActiveOrganization,
  useAuth,
  useAuthPlugin,
  useListOrganizations,
  useSession,
  useSetActiveOrganization
} from "@better-auth-ui/react"
import type { Organization } from "better-auth/client"
import { type ReactNode, useState } from "react"
import { Pressable, Text, View } from "react-native"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { cn } from "../../../lib/cn"
import { useThemeColors } from "../../../lib/theme-colors"
import { useAuthNavigation } from "../../../navigation/navigation-context"
import { Button, type ButtonProps } from "../../../primitives/button"
import { Menu } from "../../../primitives/menu"
import {
  ChevronsExpandVertical,
  CirclePlus,
  Gear
} from "../../../primitives/ui-icons"
import { UserView } from "../user/user-view"
import { CreateOrganizationDialog } from "./create-organization-dialog"
import { OrganizationView } from "./organization-view"

/** Props for the {@link OrganizationSwitcher} component. */
export type OrganizationSwitcherProps = {
  className?: string
  variant?: ButtonProps["variant"]
  trigger?: ReactNode
  hideCreate?: boolean
  hidePersonal?: boolean
  hideSettings?: boolean
  hideSlug?: boolean
  setActive?: (organization: Organization | null) => void
}

/**
 * Renders an organizations menu with a trigger button, header summary, and a
 * list of organizations to switch to. Mirrors the heroui `OrganizationSwitcher`,
 * adapted for React Native: the `Dropdown` popover becomes the shared `Menu`
 * bottom-sheet primitive (same pattern as `UserButton`'s menu), and the
 * "Manage" affordance and organization switching go through
 * `useAuthNavigation().push(...)` / `setActiveOrganization` instead of raw
 * URL navigation.
 */
export function OrganizationSwitcher({
  className,
  hideCreate,
  hidePersonal,
  hideSettings,
  hideSlug = true,
  setActive,
  variant = "ghost",
  size = "md",
  trigger,
  ...props
}: OrganizationSwitcherProps & ButtonProps) {
  const { authClient, localization } = useAuth()
  const { data: session, isPending: sessionPending } = useSession(authClient)
  const { localization: organizationLocalization, slug } =
    useAuthPlugin(organizationPlugin)

  const navigation = useAuthNavigation()
  const colors = useThemeColors()

  const { data: activeOrganization, isPending: activeOrganizationPending } =
    useActiveOrganization(authClient as OrganizationAuthClient)

  const { data: organizations, isPending: organizationsPending } =
    useListOrganizations(authClient as OrganizationAuthClient)

  const { mutate: setActiveOrganization } = useSetActiveOrganization(
    authClient as OrganizationAuthClient
  )

  const isPending =
    sessionPending ||
    (!!session && (organizationsPending || activeOrganizationPending))

  const [createOpen, setCreateOpen] = useState(false)
  const [menuOpen, setMenuOpen] = useState(false)

  function handleSetActive(organization: Organization | null) {
    if (setActive) {
      setActive(organization)
    } else if (slug !== undefined && organization) {
      navigation.push({
        section: "organization",
        view: "settings",
        slug: organization.slug
      })
    } else if (slug !== undefined) {
      navigation.push({ section: "settings", view: "account" })
    } else {
      setActiveOrganization({ organizationId: organization?.id ?? null })
    }
  }

  function manageActiveOrganization() {
    setMenuOpen(false)
    if (slug !== undefined && activeOrganization) {
      navigation.push({
        section: "organization",
        view: "settings",
        slug: activeOrganization.slug
      })
    } else {
      navigation.push({ section: "organization", view: "settings" })
    }
  }

  function managePersonalAccount() {
    setMenuOpen(false)
    navigation.push({ section: "settings", view: "account" })
  }

  const otherOrganizations = organizations?.filter(
    (organization) => organization.id !== activeOrganization?.id
  )

  return (
    <>
      {trigger ? (
        <Pressable onPress={() => setMenuOpen(true)}>{trigger}</Pressable>
      ) : (
        <Button
          variant={variant}
          className={cn("h-auto flex-row items-center px-2 py-2", className)}
          isDisabled={!session || isPending}
          aria-label={organizationLocalization.organization}
          onPress={() => setMenuOpen(true)}
          {...props}
        >
          {isPending ? (
            <OrganizationView
              size={size}
              isPending
              hideRole
              hideSlug={hideSlug}
            />
          ) : activeOrganization ? (
            <OrganizationView size={size} hideRole hideSlug={hideSlug} />
          ) : session && !hidePersonal ? (
            <UserView size={size} hideSubtitle={hideSlug} />
          ) : (
            <OrganizationView
              size={size}
              hideRole
              hideSlug={hideSlug}
              organization={{ name: organizationLocalization.organization }}
            />
          )}

          <ChevronsExpandVertical
            width={12}
            height={12}
            color={colors.muted}
            className="ml-auto shrink-0"
          />
        </Button>
      )}

      <Menu isOpen={menuOpen} onOpenChange={setMenuOpen}>
        {activeOrganization ? (
          <View className="flex-row items-center justify-between gap-4 px-2 pt-1 pb-2">
            <OrganizationView
              hideRole
              hideSlug={hideSlug}
              organization={activeOrganization}
            />

            {!hideSettings && (
              <Button
                variant="outline"
                size="sm"
                className="shrink-0 gap-2"
                onPress={manageActiveOrganization}
              >
                <Gear width={16} height={16} color={colors.muted} />
                {organizationLocalization.manage}
              </Button>
            )}
          </View>
        ) : !isPending && session?.user && !hidePersonal ? (
          <View className="flex-row items-center justify-between gap-4 px-2 pt-1 pb-2">
            <UserView hideSubtitle={hideSlug} />

            {!hideSettings && (
              <Button
                variant="outline"
                size="sm"
                className="shrink-0 gap-2"
                onPress={managePersonalAccount}
              >
                <Gear width={16} height={16} color={colors.muted} />
                {localization.settings.settings}
              </Button>
            )}
          </View>
        ) : null}

        {!!activeOrganization && !hidePersonal && (
          <Menu.Item onPress={() => handleSetActive(null)}>
            <UserView hideSubtitle={hideSlug} />
          </Menu.Item>
        )}

        {otherOrganizations?.map((organization) => (
          <Menu.Item
            key={organization.id}
            onPress={() => handleSetActive(organization)}
          >
            <OrganizationView
              hideRole
              hideSlug={hideSlug}
              organization={organization}
            />
          </Menu.Item>
        ))}

        {!hideCreate && (
          <Menu.Item
            icon={<CirclePlus width={18} height={18} color={colors.muted} />}
            onPress={() => setCreateOpen(true)}
          >
            <Text className="text-sm text-foreground">
              {organizationLocalization.createOrganization}
            </Text>
          </Menu.Item>
        )}
      </Menu>

      <CreateOrganizationDialog
        isOpen={createOpen}
        onOpenChange={setCreateOpen}
      />
    </>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-switcher.tsx
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import {
  organizationLocalization as defaultOrganizationLocalization,
  type OrganizationLocalization
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useSession } from "@better-auth-ui/solid"
import {
  useActiveOrganization,
  useListOrganizations,
  useSetActiveOrganization
} from "@better-auth-ui/solid/plugins/organization"
import type { Organization } from "better-auth/client"
import {
  ChevronsUpDown,
  PlusCircle,
  Settings as SettingsIcon
} from "lucide-solid"
import type { JSX } from "solid-js"
import { createMemo, createSignal, For, onMount, Show } from "solid-js"
import { UserView } from "@/components/auth/user/user-view"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "cn"
import { CreateOrganizationDialog } from "./create-organization-dialog"
import { createOrganizationPath } from "./organization-path"
import { OrganizationView } from "./organization-view"

export type OrganizationSwitcherProps = {
  class?: string
  trigger?: JSX.Element
  hidePersonal?: boolean
  hideSettings?: boolean
  hideSlug?: boolean
  hideCreate?: boolean
  setActive?: (organization: Organization | null) => void
}

type OrganizationPluginConfig = {
  slug?: string | null
  hideSlug?: boolean
  slugPrefix?: string
  localization?: Pick<
    OrganizationLocalization,
    "createOrganization" | "organization" | "organizations" | "manage"
  >
}

function OrganizationSwitcherTrigger(rawProps: OrganizationSwitcherProps = {}) {
  const props = rawProps
  const auth = useAuth()
  const hideSlug = () =>
    props.hideSlug ??
    (
      auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
        | OrganizationPluginConfig
        | undefined
    )?.hideSlug ??
    true

  return (
    <Show
      when={props.trigger}
      fallback={
        <Button
          class={cn("h-auto px-2 py-2 text-left", props.class)}
          disabled
          variant="ghost"
        >
          <OrganizationView isPending hideRole hideSlug={hideSlug()} />
          <ChevronsUpDown class="size-4 shrink-0 text-muted-foreground" />
        </Button>
      }
    >
      {props.trigger}
    </Show>
  )
}

function MountedOrganizationSwitcher(rawProps: OrganizationSwitcherProps = {}) {
  const props = rawProps
  const auth = useAuth<OrganizationAuthClient>()
  const client = auth.authClient
  const session = useSession(client)
  const activeOrganization = useActiveOrganization(client)
  const organizations = useListOrganizations(client)
  const setActiveOrganization = useSetActiveOrganization(client)
  const [createOpen, setCreateOpen] = createSignal(false)
  const [isOpen, setIsOpen] = createSignal(false)
  const organizationPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === organizationPlugin.id) as
      | OrganizationPluginConfig
      | undefined
  const organizationViewPaths = () =>
    organizationPlugin().viewPaths.organization ?? { settings: "settings" }
  const localization = () =>
    organizationPluginConfig()?.localization ?? defaultOrganizationLocalization
  const isSlugMode = () => {
    const plugin = organizationPluginConfig()

    if (!plugin) return false

    return plugin.slug !== undefined
  }
  const isPending = () =>
    session.isPending ||
    (!!session.data &&
      (organizations.isPending || activeOrganization.isPending))
  const hideSlug = () =>
    props.hideSlug ?? organizationPluginConfig()?.hideSlug ?? true
  const shouldShowSlug = () => !hideSlug()
  const selectableOrganizations = () =>
    ((organizations.data ?? []) as Organization[]).filter(
      (organization) => organization.id !== activeOrganization.data?.id
    )
  const hasOtherEntries = () =>
    selectableOrganizations().length > 0 ||
    (!!activeOrganization.data && !props.hidePersonal)

  const navigateToOrganization = (organization: Organization) => {
    auth.navigate({
      to: createOrganizationPath({
        basePath: auth.basePaths.organization,
        slugPrefix: organizationPluginConfig()?.slugPrefix,
        slug: organization.slug,
        path: organizationViewPaths().settings
      })
    })
  }

  const navigateToPersonal = () => {
    auth.navigate({
      to: `${auth.basePaths.settings}/${auth.viewPaths.settings.account}`
    })
  }

  const navigateToActiveOrganizationSettings = () => {
    const active = activeOrganization.data

    if (!active) {
      navigateToPersonal()
      return
    }

    if (isSlugMode()) {
      navigateToOrganization(active as Organization)
      return
    }

    auth.navigate({
      to: `${auth.basePaths.organization}/${organizationViewPaths().settings}`
    })
  }

  const handleSetActive = (organization: Organization | null) => {
    setIsOpen(false)

    if (organization) props.setActive?.(organization)
    if (!organization) props.setActive?.(null)
    if (props.setActive) return

    if (isSlugMode()) {
      if (organization) {
        navigateToOrganization(organization)
        return
      }

      navigateToPersonal()
      return
    }

    setActiveOrganization.mutate(
      { organizationId: organization?.id ?? null },
      {
        onSuccess: () => {
          if (organization) {
            auth.navigate({
              to: `${auth.basePaths.organization}/${organizationViewPaths().settings}`
            })
            return
          }

          navigateToPersonal()
        }
      }
    )
  }

  return (
    <>
      <DropdownMenu open={isOpen()} onOpenChange={setIsOpen}>
        <Show
          when={props.trigger}
          fallback={
            <DropdownMenuTrigger
              as={Button}
              variant="ghost"
              class={cn("h-auto px-2 py-2 text-left", props.class)}
              disabled={!session.data || isPending()}
            >
              <Show
                when={!isPending()}
                fallback={
                  <OrganizationView isPending hideRole hideSlug={hideSlug()} />
                }
              >
                <Show
                  when={activeOrganization.data}
                  fallback={
                    <Show
                      when={
                        !props.hidePersonal ? session.data?.user : undefined
                      }
                      fallback={
                        <OrganizationView
                          hideRole
                          hideSlug={hideSlug()}
                          organization={{
                            name: localization().organization
                          }}
                        />
                      }
                    >
                      {(user) => (
                        <UserView hideSubtitle={hideSlug()} user={user()} />
                      )}
                    </Show>
                  }
                >
                  {(organization) => (
                    <OrganizationView
                      hideRole
                      hideSlug={!shouldShowSlug()}
                      organization={organization()}
                    />
                  )}
                </Show>
              </Show>

              <ChevronsUpDown class="size-4 shrink-0 text-muted-foreground" />
            </DropdownMenuTrigger>
          }
        >
          <DropdownMenuTrigger as="span" class={props.class}>
            {props.trigger}
          </DropdownMenuTrigger>
        </Show>
        <DropdownMenuContent class="min-w-64 max-w-svw">
          <Show when={activeOrganization.data}>
            {(organization) => (
              <div class="flex items-center justify-between gap-4 px-2 py-2">
                <OrganizationView
                  hideRole
                  hideSlug={hideSlug()}
                  organization={organization()}
                />

                <Show when={!props.hideSettings}>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={navigateToActiveOrganizationSettings}
                  >
                    <SettingsIcon class="text-muted-foreground" />
                    {localization().manage}
                  </Button>
                </Show>
              </div>
            )}
          </Show>

          <Show
            when={
              !activeOrganization.data && !isPending() && !props.hidePersonal
                ? session.data?.user
                : undefined
            }
          >
            {(resolvedSession) => (
              <div class="flex items-center justify-between gap-4 px-2 py-2">
                <UserView hideSubtitle={hideSlug()} user={resolvedSession()} />

                <Show when={!props.hideSettings}>
                  <Button
                    variant="outline"
                    size="sm"
                    onClick={navigateToPersonal}
                  >
                    <SettingsIcon class="text-muted-foreground" />
                    {auth.localization.settings.settings}
                  </Button>
                </Show>
              </div>
            )}
          </Show>

          <DropdownMenuSeparator />

          <Show when={activeOrganization.data && !props.hidePersonal}>
            <DropdownMenuItem onSelect={() => handleSetActive(null)}>
              <UserView hideSubtitle={hideSlug()} />
            </DropdownMenuItem>
          </Show>

          <For each={selectableOrganizations()}>
            {(organization) => (
              <DropdownMenuItem onSelect={() => handleSetActive(organization)}>
                <OrganizationView
                  hideRole
                  hideSlug={hideSlug()}
                  organization={organization}
                />
              </DropdownMenuItem>
            )}
          </For>

          <Show when={!props.hideCreate}>
            <Show when={hasOtherEntries()}>
              <DropdownMenuSeparator />
            </Show>

            <DropdownMenuItem
              onSelect={() => {
                setIsOpen(false)
                setCreateOpen(true)
              }}
            >
              <PlusCircle class="text-muted-foreground" />
              {localization().createOrganization}
            </DropdownMenuItem>
          </Show>
        </DropdownMenuContent>
      </DropdownMenu>
      <CreateOrganizationDialog
        hideSlug={hideSlug()}
        open={createOpen()}
        onOpenChange={setCreateOpen}
      />
    </>
  )
}

export function OrganizationSwitcher(props: OrganizationSwitcherProps = {}) {
  const [isMounted, setIsMounted] = createSignal(false)

  onMount(() => setIsMounted(true))

  const content = createMemo(() =>
    isMounted() ? (
      <MountedOrganizationSwitcher {...props} />
    ) : (
      <OrganizationSwitcherTrigger {...props} />
    )
  )

  return <>{content()}</>
}
