// packages/heroui/src/components/auth/organization/organization-invitation-row.tsx
import { formatAdditionalFieldValue } from "@better-auth-ui/core"
import {
  memberRoleLabels,
  type OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useCancelInvitation,
  useHasPermission,
  useInviteMember
} from "@better-auth-ui/react/plugins/organization"
import { PaperPlane, Xmark } from "@gravity-ui/icons"
import { Button, Chip, Spinner, Table, toast } from "@heroui/react"

import type { Invitation } from "better-auth/client"

import { organizationPlugin } from "../../../lib/auth/organization-plugin"
import { OrganizationInvitationRowSkeleton } from "./organization-invitation-row-skeleton"
import {
  type OrganizationSelectableRow,
  OrganizationTableSelectRow
} from "./organization-table-selection"

export type OrganizationInvitationTableRowProps = {
  invitation: Invitation
  selectableRow?: OrganizationSelectableRow<Invitation>
  showCreatedAt?: boolean
  showRole?: boolean
  showStatus?: boolean
}

export function OrganizationInvitationTableRow({
  invitation,
  selectableRow,
  showCreatedAt = false,
  showRole = false,
  showStatus = false
}: OrganizationInvitationTableRowProps) {
  const { authClient, locale } = useAuth()
  const {
    modelFields: { invitation: invitationFields },
    localization: organizationLocalization,
    roles
  } = useAuthPlugin(organizationPlugin)

  const {
    data: cancelInvitationPermission,
    isPending: cancelPermissionPending
  } = useHasPermission(authClient as OrganizationAuthClient, {
    permissions: { invitation: ["cancel"] }
  })

  const { mutate: cancelInvitation, isPending: cancelPending } =
    useCancelInvitation(authClient as OrganizationAuthClient)

  const { data: inviteMemberPermission, isPending: invitePermissionPending } =
    useHasPermission(authClient as OrganizationAuthClient, {
      permissions: { invitation: ["create"] }
    })

  // Better Auth treats a re-invite as a resend: it extends the existing
  // invitation's expiry and sends the email again rather than creating a
  // second row.
  const { mutate: resendInvitation, isPending: resendPending } =
    useInviteMember(authClient as OrganizationAuthClient, {
      onSuccess: () => toast.success(organizationLocalization.invitationResent)
    })

  const roleLabel = memberRoleLabels(invitation.role, roles).join(", ")

  const statusLabel =
    organizationLocalization[invitation.status] ?? invitation.status

  const statusColor =
    invitation.status === "pending"
      ? "warning"
      : invitation.status === "accepted"
        ? "success"
        : invitation.status === "rejected"
          ? "danger"
          : "default"

  if (cancelPermissionPending || invitePermissionPending) {
    return <OrganizationInvitationRowSkeleton />
  }

  const isPending = invitation.status === "pending"

  return (
    <Table.Row id={invitation.id}>
      {selectableRow && (
        <Table.Cell>
          <OrganizationTableSelectRow
            localization={organizationLocalization}
            row={selectableRow}
          />
        </Table.Cell>
      )}
      <Table.Cell>
        <div className="flex flex-col gap-1">
          <span className="font-medium text-sm">{invitation.email}</span>
          {invitationFields.map((field) => {
            const value = formatAdditionalFieldValue(
              (invitation as unknown as Record<string, unknown>)[field.name],
              locale.languageTag
            )
            return value ? (
              <span className="text-muted text-xs" key={field.name}>
                {field.label}: {value}
              </span>
            ) : null
          })}
        </div>
      </Table.Cell>

      {showCreatedAt && (
        <Table.Cell className="text-muted text-xs tabular-nums whitespace-nowrap">
          {new Date(invitation.createdAt).toLocaleString(locale.languageTag, {
            dateStyle: "short",
            timeStyle: "short"
          })}
        </Table.Cell>
      )}

      {showRole && <Table.Cell className="text-sm">{roleLabel}</Table.Cell>}

      {showStatus && (
        <Table.Cell className="text-sm">
          <Chip color={statusColor} size="sm" variant="soft">
            {statusLabel}
          </Chip>
        </Table.Cell>
      )}

      <Table.Cell className="text-end">
        <div className="flex justify-end gap-2">
          {inviteMemberPermission?.success && isPending && (
            <Button
              isIconOnly
              size="sm"
              variant="tertiary"
              isPending={resendPending}
              onPress={() =>
                resendInvitation({
                  ...Object.fromEntries(
                    invitationFields.flatMap((field) => {
                      const value = (
                        invitation as unknown as Record<string, unknown>
                      )[field.name]
                      return value === undefined ? [] : [[field.name, value]]
                    })
                  ),
                  email: invitation.email,
                  organizationId: invitation.organizationId,
                  role: invitation.role as Parameters<
                    typeof resendInvitation
                  >[0]["role"],
                  resend: true
                })
              }
              aria-label={organizationLocalization.resendInvitation}
            >
              {resendPending ? (
                <Spinner color="current" size="sm" />
              ) : (
                <PaperPlane />
              )}
            </Button>
          )}

          {cancelInvitationPermission?.success && isPending && (
            <Button
              isIconOnly
              size="sm"
              variant="danger-soft"
              isPending={cancelPending}
              onPress={() => cancelInvitation({ invitationId: invitation.id })}
              aria-label={organizationLocalization.cancelInvitation}
            >
              {cancelPending ? (
                <Spinner color="current" size="sm" />
              ) : (
                <Xmark />
              )}
            </Button>
          )}
        </div>
      </Table.Cell>
    </Table.Row>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/organization-invitation-row.tsx
import { formatAdditionalFieldValue } from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import {
  useCancelInvitation,
  useHasPermission,
  useInviteMember
} from "@better-auth-ui/solid/plugins/organization"
import { Send, X } from "lucide-solid"
import { For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Badge } from "@/components/ui/badge"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { TableCell, TableRow } from "@/components/ui/table"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import {
  type OrganizationSelectableRow,
  OrganizationTableSelectRow
} from "./organization-table-selection"

type OrganizationInvitation = {
  createdAt?: Date | string | null
  email?: string | null
  id: string
  organizationId: string
  role?: string | null
  status?: string | null
  [key: string]: unknown
}

type RoleMap = Record<string, string>

const statusBadgeClasses: Record<string, string> = {
  accepted: "z-badge-status-accepted",
  canceled: "z-badge-status-canceled",
  pending: "z-badge-status-pending",
  rejected: "z-badge-status-rejected"
}

export type OrganizationInvitationRowProps = {
  invitation: OrganizationInvitation
  roles: RoleMap
  selectableRow?: OrganizationSelectableRow
  showCreatedAt?: boolean
  showRole?: boolean
  showStatus?: boolean
}

function formatRole(role?: string | null) {
  if (!role) return "Member"

  return role.charAt(0).toUpperCase() + role.slice(1)
}

function formatStatus(status?: string | null) {
  if (!status) return "Pending"

  return status.charAt(0).toUpperCase() + status.slice(1)
}

function formatInvitationDate(createdAt?: Date | string | null) {
  if (!createdAt) return "—"

  const date = createdAt instanceof Date ? createdAt : new Date(createdAt)

  if (Number.isNaN(date.getTime())) return "—"

  return date.toLocaleString(undefined, {
    dateStyle: "short",
    timeStyle: "short"
  })
}

export function OrganizationInvitationRow(
  props: OrganizationInvitationRowProps
) {
  const auth = useAuth<OrganizationAuthClient>()
  const config = useAuthPlugin(organizationPlugin)
  const permission = useHasPermission(auth.authClient, () => ({
    permissions: { invitation: ["cancel"] }
  }))
  const invitePermission = useHasPermission(auth.authClient, () => ({
    permissions: { invitation: ["create"] }
  }))
  const cancelInvitation = useCancelInvitation(auth.authClient)

  // Better Auth treats a re-invite as a resend: it extends the existing
  // invitation's expiry and sends the email again rather than creating a
  // second row.
  const resendInvitation = useInviteMember(auth.authClient, () => ({
    onSuccess: () => toast.success(config.localization.invitationResent)
  }))
  const isPending = () => props.invitation.status === "pending"
  const roleLabel = () =>
    props.roles[props.invitation.role ?? ""] ??
    formatRole(props.invitation.role)
  const statusBadgeClass = () =>
    statusBadgeClasses[props.invitation.status ?? "pending"] ??
    statusBadgeClasses.pending

  return (
    <TableRow>
      <Show when={props.selectableRow}>
        {(row) => (
          <TableCell>
            <OrganizationTableSelectRow
              localization={config.localization}
              row={row()}
            />
          </TableCell>
        )}
      </Show>
      <TableCell>
        <div class="flex flex-col gap-1">
          <span class="font-medium">
            {props.invitation.email ?? "Invitation"}
          </span>
          <For each={config.modelFields.invitation}>
            {(field) => {
              const value = () =>
                formatAdditionalFieldValue(props.invitation[field.name])
              return (
                <Show when={value()}>
                  {(resolved) => (
                    <span class="text-muted-foreground text-xs">
                      {field.label}: {resolved()}
                    </span>
                  )}
                </Show>
              )
            }}
          </For>
        </div>
      </TableCell>
      <Show when={props.showCreatedAt !== false}>
        <TableCell class="whitespace-nowrap text-muted-foreground text-xs tabular-nums">
          {formatInvitationDate(props.invitation.createdAt)}
        </TableCell>
      </Show>
      <Show when={props.showRole !== false}>
        <TableCell class="text-sm">{roleLabel()}</TableCell>
      </Show>
      <Show when={props.showStatus !== false}>
        <TableCell>
          <Badge class={statusBadgeClass()} variant="secondary">
            {formatStatus(props.invitation.status)}
          </Badge>
        </TableCell>
      </Show>
      <TableCell class="text-end">
        <div class="flex justify-end gap-2">
          <Show when={invitePermission.data?.success && isPending()}>
            <Button
              aria-label={config.localization.resendInvitation}
              disabled={resendInvitation.isPending}
              onClick={() =>
                resendInvitation.mutate({
                  ...Object.fromEntries(
                    config.modelFields.invitation.flatMap((field) => {
                      const value = props.invitation[field.name]
                      return value === undefined ? [] : [[field.name, value]]
                    })
                  ),
                  email: props.invitation.email ?? "",
                  organizationId: props.invitation.organizationId,
                  resend: true,
                  role: (props.invitation.role ?? "member") as Parameters<
                    typeof resendInvitation.mutate
                  >[0]["role"]
                })
              }
              size="icon-sm"
              type="button"
              variant="outline"
            >
              <Show
                when={resendInvitation.isPending}
                fallback={<Send class="size-4" />}
              >
                <Spinner />
              </Show>
            </Button>
          </Show>

          <Show when={permission.data?.success && isPending()}>
            <Button
              aria-label={config.localization.cancelInvitation}
              disabled={cancelInvitation.isPending}
              onClick={() =>
                cancelInvitation.mutate({
                  invitationId: props.invitation.id
                })
              }
              size="icon-sm"
              type="button"
              variant="outline"
            >
              <Show
                when={cancelInvitation.isPending}
                fallback={<X class="size-4 text-destructive" />}
              >
                <Spinner class="text-destructive" />
              </Show>
            </Button>
          </Show>
        </div>
      </TableCell>
    </TableRow>
  )
}
