// examples/start-shadcn-baseui-example/src/components/auth/organization/team-switcher.tsx
"use client"

import type {
  ListedUserTeam,
  OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useListUserTeams,
  useSetActiveTeam
} from "@better-auth-ui/react/plugins/organization"
import { Check, ChevronsUpDown, Users } from "lucide-react"
import { type ReactElement, useState } from "react"
import { buttonVariants } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { Skeleton } from "@/components/ui/skeleton"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"

export type TeamSwitcherProps = {
  organizationId: string
  teamId?: string | null
  onTeamChange?: (team: ListedUserTeam | null) => void
  syncSession?: boolean
  allowClear?: boolean
  className?: string
  align?: "center" | "end" | "start"
  trigger?: ReactElement
}

export function TeamSwitcher({
  organizationId,
  teamId,
  onTeamChange,
  syncSession = false,
  allowClear = true,
  className,
  align,
  trigger
}: TeamSwitcherProps) {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { localization } = useAuthPlugin(organizationPlugin)
  const [open, setOpen] = useState(false)
  const teams = useListUserTeams(authClient, {
    query: { organizationId }
  })
  const setActiveTeam = useSetActiveTeam(authClient)
  const selectedTeam = teams.data?.find((team) => team.id === teamId)

  function selectTeam(team: ListedUserTeam | null) {
    onTeamChange?.(team)
    setOpen(false)

    if (syncSession) {
      setActiveTeam.mutate({ organizationId, teamId: team?.id ?? null })
    }
  }

  return (
    <DropdownMenu open={open} onOpenChange={setOpen}>
      {trigger ?? (
        <DropdownMenuTrigger
          className={cn(
            buttonVariants({ variant: "outline" }),
            "justify-between gap-3",
            className
          )}
          disabled={teams.isPending || setActiveTeam.isPending}
        >
          <span className="flex min-w-0 items-center gap-2">
            <Users className="size-4 shrink-0 text-muted-foreground" />
            {teams.isPending ? (
              <Skeleton className="h-4 w-24" />
            ) : (
              <span className="truncate">
                {selectedTeam?.name ?? localization.selectTeam}
              </span>
            )}
          </span>
          <ChevronsUpDown className="size-4 shrink-0 text-muted-foreground" />
        </DropdownMenuTrigger>
      )}
      <DropdownMenuContent align={align} className="min-w-56">
        {allowClear && (
          <DropdownMenuItem onClick={() => selectTeam(null)}>
            <span className="min-w-0 flex-1 truncate">
              {localization.allTeams}
            </span>
            {!teamId && <Check className="size-4" />}
          </DropdownMenuItem>
        )}
        {teams.data?.map((team) => (
          <DropdownMenuItem key={team.id} onClick={() => selectTeam(team)}>
            <span className="min-w-0 flex-1 truncate">{team.name}</span>
            {team.id === teamId && <Check className="size-4" />}
          </DropdownMenuItem>
        ))}
        {!teams.isPending && teams.data?.length === 0 && (
          <div className="px-2 py-1.5 text-sm text-muted-foreground">
            {localization.noTeams}
          </div>
        )}
      </DropdownMenuContent>
    </DropdownMenu>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/organization/team-switcher.tsx
import type {
  ListedUserTeam,
  OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth } from "@better-auth-ui/solid"
import {
  useListUserTeams,
  useSetActiveTeam
} from "@better-auth-ui/solid/plugins/organization"
import { Check, ChevronsUpDown, Users } from "lucide-solid"
import type { ValidComponent } from "solid-js"
import { createMemo, createSignal, For, Show } from "solid-js"
import { Button } from "@/components/ui/button"
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger
} from "@/components/ui/dropdown-menu"
import { Skeleton } from "@/components/ui/skeleton"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { cn } from "@/lib/utils"

export type TeamSwitcherProps = {
  organizationId: string
  teamId?: string | null
  onTeamChange?: (team: ListedUserTeam | null) => void
  syncSession?: boolean
  allowClear?: boolean
  class?: string
  trigger?: ValidComponent
}

export function TeamSwitcher(props: TeamSwitcherProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const localization = () => organizationPlugin().localization
  const [open, setOpen] = createSignal(false)
  const teams = useListUserTeams(auth.authClient, () => ({
    query: { organizationId: props.organizationId }
  }))
  const setActiveTeam = useSetActiveTeam(auth.authClient)
  const selectedTeam = createMemo(() =>
    teams.data?.find((team) => team.id === props.teamId)
  )

  function selectTeam(team: ListedUserTeam | null) {
    props.onTeamChange?.(team)
    setOpen(false)

    if (props.syncSession) {
      setActiveTeam.mutate({
        organizationId: props.organizationId,
        teamId: team?.id ?? null
      })
    }
  }

  return (
    <DropdownMenu open={open()} onOpenChange={setOpen}>
      <Show
        when={props.trigger}
        fallback={
          <DropdownMenuTrigger
            as={Button}
            variant="outline"
            class={cn("justify-between gap-3", props.class)}
            disabled={teams.isPending || setActiveTeam.isPending}
          >
            <span class="flex min-w-0 items-center gap-2">
              <Users class="size-4 shrink-0 text-muted-foreground" />
              <Show
                when={!teams.isPending}
                fallback={<Skeleton class="h-4 w-24" />}
              >
                <span class="truncate">
                  {selectedTeam()?.name ?? localization().selectTeam}
                </span>
              </Show>
            </span>
            <ChevronsUpDown class="size-4 shrink-0 text-muted-foreground" />
          </DropdownMenuTrigger>
        }
      >
        {(Trigger) => (
          <DropdownMenuTrigger as={Trigger()} class={props.class} />
        )}
      </Show>
      <DropdownMenuContent class="min-w-56">
        <Show when={props.allowClear !== false}>
          <DropdownMenuItem onClick={() => selectTeam(null)}>
            <span class="min-w-0 flex-1 truncate">
              {localization().allTeams}
            </span>
            <Show when={!props.teamId}>
              <Check class="size-4" />
            </Show>
          </DropdownMenuItem>
        </Show>
        <For each={teams.data ?? []}>
          {(team) => (
            <DropdownMenuItem onClick={() => selectTeam(team)}>
              <span class="min-w-0 flex-1 truncate">{team.name}</span>
              <Show when={team.id === props.teamId}>
                <Check class="size-4" />
              </Show>
            </DropdownMenuItem>
          )}
        </For>
        <Show when={!teams.isPending && teams.data?.length === 0}>
          <div class="px-2 py-1.5 text-sm text-muted-foreground">
            {localization().noTeams}
          </div>
        </Show>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
