// packages/solid/src/lib/auth-provider.tsx
import type { AuthConfig } from "@better-auth-ui/core"
import { QueryClient, QueryClientProvider } from "@tanstack/solid-query"
import { createContext, type JSX, useContext } from "solid-js"
import type { AuthClient } from "./auth-client"
import { resolveAuthConfig, type SolidAuthConfigInput } from "./auth-config"

const AuthContext = createContext<AuthConfig>()

const fallbackQueryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 5000
    }
  }
})

export type AuthProviderProps<TAuthClient = AuthClient> =
  SolidAuthConfigInput<TAuthClient> & {
    children?: JSX.Element
    /** TanStack QueryClient to use for your application's queries. */
    queryClient?: QueryClient
  }

export function AuthProvider(props: AuthProviderProps) {
  const config = resolveAuthConfig(props as AuthProviderProps<AuthClient>)

  return (
    <QueryClientProvider client={props.queryClient || fallbackQueryClient}>
      <AuthContext.Provider value={config}>
        {props.children}
      </AuthContext.Provider>
    </QueryClientProvider>
  )
}

export function useAuth(): AuthConfig {
  const context = useContext(AuthContext)

  if (!context) {
    throw new Error("[Better Auth UI] AuthProvider is required")
  }

  return context
}

// packages/react/src/components/auth/auth-provider.tsx
"use client"

import { deepmerge, defaultConfig } from "@better-auth-ui/core"
import {
  type AnyAuthClient,
  type AnyAuthConfig,
  type AuthConfig,
  AuthContext
} from "@better-auth-ui/react"
import {
  QueryClient,
  QueryClientContext,
  QueryClientProvider
} from "@tanstack/react-query"
import type { BetterFetchError } from "better-auth/react"
import { type PropsWithChildren, useContext, useEffect, useMemo } from "react"
import { useHydrated } from "../../hooks/use-hydrated"

const fallbackQueryClient = new QueryClient({
  defaultOptions: {
    queries: {
      staleTime: 1000
    }
  }
})

const baseAuthConfig: AnyAuthConfig = {
  ...defaultConfig,
  Link: (props) => <a {...props} />
}

export type AuthProviderProps = PropsWithChildren<AnyAuthConfig> & {
  authClient: AnyAuthClient
  queryClient?: QueryClient
}

/**
 * Provides AuthConfig to descendant components.
 */
export function AuthProvider({
  children,
  queryClient,
  ...config
}: AuthProviderProps) {
  const queryClientContext = useContext(QueryClientContext)
  const resolvedQueryClient =
    queryClient || queryClientContext || fallbackQueryClient

  const hydrated = useHydrated()

  const mergedConfig = useMemo(() => {
    const merged = deepmerge(baseAuthConfig, config) as AuthConfig
    if (hydrated) {
      merged.redirectTo =
        new URLSearchParams(window.location.search).get("redirectTo")?.trim() ||
        merged.redirectTo
    }
    return merged
    // biome-ignore lint/correctness/useExhaustiveDependencies: config is a serialized version of config
  }, [config, hydrated])

  useEffect(() => {
    resolvedQueryClient.getQueryCache().config.onError = (error) => {
      mergedConfig.toast.error(
        error.message || (error as BetterFetchError).statusText
      )
    }
  }, [resolvedQueryClient, mergedConfig.toast.error])

  return (
    <AuthContext.Provider value={mergedConfig}>
      <QueryClientProvider client={resolvedQueryClient}>
        {children}
      </QueryClientProvider>
    </AuthContext.Provider>
  )
}

/**
 * Returns the `AuthContext` configuration
 *
 * @returns The `AuthContext`
 * @throws If the `AuthContext` is not provided
 */
export function useAuth() {
  const context = useContext(AuthContext)

  if (!context) {
    throw new Error("[Better Auth UI] AuthProvider is required")
  }

  return context
}
