// apps/docs/src/components/auth/oauth-provider/authorized-applications.tsx
"use client"

import {
  groupOAuthConsents,
  type OAuthProviderAuthClient
} from "@better-auth-ui/core/plugins/oauth-provider"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useListOAuthConsents } from "@better-auth-ui/react/plugins/oauth-provider"

import { Card, CardContent } from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { oauthProviderPlugin } from "@/lib/auth/oauth-provider-plugin"
import { cn } from "@/lib/utils"
import { AuthorizedApplication } from "./authorized-application"
import { AuthorizedApplicationSkeleton } from "./authorized-application-skeleton"
import { AuthorizedApplicationsEmpty } from "./authorized-applications-empty"

export type AuthorizedApplicationsProps = {
  className?: string
}

/**
 * Security card listing the OAuth applications this account has authorized.
 *
 * It manages consent records, not sign-in sessions and not live access
 * tokens. Better Auth can store more than one consent per client, so records
 * are grouped by client ID and rendered as a single application.
 */
export function AuthorizedApplications({
  className
}: AuthorizedApplicationsProps) {
  const { authClient } = useAuth()
  const { localization } = useAuthPlugin(oauthProviderPlugin)

  const { data: consents, isPending } = useListOAuthConsents(
    authClient as OAuthProviderAuthClient
  )

  const applications = groupOAuthConsents(consents)

  return (
    <div className={cn("flex flex-col gap-3", className)}>
      <h2 className="truncate text-sm font-semibold">
        {localization.connectedApplications}
      </h2>

      <Card className="p-0">
        <CardContent className="p-0">
          {isPending ? (
            <AuthorizedApplicationSkeleton />
          ) : !applications.length ? (
            <AuthorizedApplicationsEmpty />
          ) : (
            applications.map((application, index) => (
              <div key={application.clientId}>
                {index > 0 && <Separator />}

                <AuthorizedApplication application={application} />
              </div>
            ))
          )}
        </CardContent>
      </Card>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/oauth-provider/authorized-applications.tsx
import { groupOAuthConsents } from "@better-auth-ui/core/plugins"
import {
  listOAuthConsentsOptions,
  type OAuthProviderAuthClient,
  useAuth,
  useAuthPlugin,
  useSession
} from "@better-auth-ui/solid"
import { createQuery } from "@tanstack/solid-query"
import { For, Show } from "solid-js"

import { Card, CardContent } from "@/components/ui/card"
import { ItemSeparator } from "@/components/ui/item"
import { oauthProviderPlugin } from "@/lib/auth/oauth-provider-plugin"
import { cn } from "@/lib/utils"
import { AuthorizedApplication } from "./authorized-application"
import { AuthorizedApplicationSkeleton } from "./authorized-application-skeleton"
import { AuthorizedApplicationsEmpty } from "./authorized-applications-empty"

export type AuthorizedApplicationsProps = {
  class?: string
}

/**
 * Security card listing the OAuth applications this account has authorized.
 *
 * It manages consent records, not sign-in sessions and not live access
 * tokens. Better Auth can store more than one consent per client, so records
 * are grouped by client ID and rendered as a single application.
 */
export function AuthorizedApplications(
  props: AuthorizedApplicationsProps = {}
) {
  const auth = useAuth()
  const { localization } = useAuthPlugin(oauthProviderPlugin)
  const oauthClient = auth.authClient as OAuthProviderAuthClient
  const session = useSession(oauthClient)

  const consents = createQuery(() => ({
    ...listOAuthConsentsOptions(oauthClient, session.data?.user.id),
    enabled: Boolean(session.data?.user.id)
  }))

  const applications = () => groupOAuthConsents(consents.data)

  return (
    <div class={cn("flex flex-col gap-3", props.class)}>
      <h2 class="truncate font-semibold text-sm">
        {localization.connectedApplications}
      </h2>

      <Card class="z-card-padding-none">
        <CardContent class="z-card-content-padding-none">
          <Show
            when={!consents.isPending}
            fallback={<AuthorizedApplicationSkeleton />}
          >
            <Show
              when={applications().length > 0}
              fallback={<AuthorizedApplicationsEmpty />}
            >
              <For each={applications()}>
                {(application, index) => (
                  <>
                    <Show when={index() > 0}>
                      <ItemSeparator />
                    </Show>
                    <AuthorizedApplication application={application} />
                  </>
                )}
              </For>
            </Show>
          </Show>
        </CardContent>
      </Card>
    </div>
  )
}
