// examples/next-shadcn-example/src/components/auth/oauth-provider/oauth-consent.tsx
"use client"

import {
  type OAuthAuthorizationRequest,
  parseOAuthAuthorizationRequest,
  sanitizeOAuthClientUrl
} from "@better-auth-ui/core/plugins"
import {
  type OAuthProviderAuthClient,
  useAuth,
  useAuthPlugin,
  useOAuthConsent,
  usePublicOAuthClient,
  useSession
} from "@better-auth-ui/react"
import { Check, ShieldCheck } from "lucide-react"
import { useEffect, useState } from "react"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { oauthProviderPlugin } from "@/lib/auth/oauth-provider-plugin"
import { cn } from "@/lib/utils"
import { UserAvatar } from "../user/user-avatar"

export type OAuthConsentProps = {
  className?: string
}

const interpolateClient = (template: string, clientName: string) =>
  template.replace("{{client}}", clientName)

export function OAuthConsent({ className }: OAuthConsentProps) {
  const { authClient } = useAuth()
  const { localization, scopeMetadata } = useAuthPlugin(oauthProviderPlugin)
  const oauthClient = authClient as OAuthProviderAuthClient
  const { data: session, isPending: isSessionPending } = useSession(oauthClient)
  const [request, setRequest] = useState<OAuthAuthorizationRequest>()

  useEffect(() => {
    setRequest(parseOAuthAuthorizationRequest(window.location.search))
  }, [])

  const publicClient = usePublicOAuthClient(oauthClient, request?.clientId, {
    enabled: Boolean(session && request?.clientId)
  })
  const consent = useOAuthConsent(oauthClient)
  const client = publicClient.data
  const clientName = client?.client_name || localization.application
  const logoUrl = sanitizeOAuthClientUrl(client?.logo_uri)
  const policyUrl = sanitizeOAuthClientUrl(client?.policy_uri)
  const termsUrl = sanitizeOAuthClientUrl(client?.tos_uri)
  const requestResolved = request !== undefined
  const invalidRequest =
    requestResolved &&
    (!request.clientId ||
      (!isSessionPending && !session) ||
      publicClient.isError ||
      (!publicClient.isPending && session && !client))
  const canRespond = Boolean(
    request?.clientId && session && client && !consent.isPending
  )

  if (invalidRequest) {
    return (
      <Card className={cn("w-full max-w-md", className)}>
        <CardHeader>
          <CardTitle className="text-xl">
            {localization.invalidRequest}
          </CardTitle>
          <CardDescription>
            {localization.invalidRequestDescription}
          </CardDescription>
        </CardHeader>
      </Card>
    )
  }

  return (
    <Card className={cn("w-full max-w-md", className)}>
      <CardHeader className="gap-4">
        <div className="flex items-center gap-3">
          {client ? (
            <Avatar size="lg">
              <AvatarImage
                alt={clientName}
                referrerPolicy="no-referrer"
                src={logoUrl}
              />
              <AvatarFallback>
                <ShieldCheck className="size-5" />
              </AvatarFallback>
            </Avatar>
          ) : (
            <Skeleton className="size-10 rounded-full" />
          )}

          <div className="min-w-0 flex-1">
            {client ? (
              <p className="truncate font-medium">{clientName}</p>
            ) : (
              <Skeleton className="h-4 w-36" />
            )}
            {client?.client_uri ? (
              <p className="truncate text-xs text-muted-foreground">
                {client.client_uri}
              </p>
            ) : null}
          </div>
        </div>

        <div className="grid gap-1">
          <CardTitle className="text-xl">
            {interpolateClient(localization.authorize, clientName)}
          </CardTitle>
          <CardDescription>
            {interpolateClient(
              localization.authorizationDescription,
              clientName
            )}
          </CardDescription>
        </div>
      </CardHeader>

      <CardContent className="flex flex-col gap-5">
        <div className="grid gap-3">
          <p className="text-sm font-medium">
            {interpolateClient(localization.requestedPermissions, clientName)}
          </p>

          {request ? (
            <ul className="grid gap-3">
              {request.scopes.map((scope) => {
                const metadata = scopeMetadata[scope]

                return (
                  <li className="flex gap-3" key={scope}>
                    <Check className="mt-0.5 size-4 shrink-0 text-primary" />
                    <div className="grid gap-0.5">
                      <p className="text-sm font-medium">
                        {metadata?.label ?? scope}
                      </p>
                      {metadata?.description ? (
                        <p className="text-xs text-muted-foreground">
                          {metadata.description}
                        </p>
                      ) : null}
                    </div>
                  </li>
                )
              })}
            </ul>
          ) : (
            <div className="flex gap-3">
              <Skeleton className="mt-0.5 size-4 shrink-0 rounded-full" />
              <div className="grid flex-1 gap-2">
                <Skeleton className="h-4 w-32" />
                <Skeleton className="h-3 w-full max-w-64" />
              </div>
            </div>
          )}
        </div>

        <Separator />

        <div className="flex items-center gap-3">
          <UserAvatar isPending={isSessionPending} user={session?.user} />
          <div className="min-w-0 flex-1">
            <p className="text-xs text-muted-foreground">
              {localization.signedInAs}
            </p>
            {session ? (
              <>
                <p className="truncate text-sm font-medium">
                  {session.user.name || session.user.email}
                </p>
                {session.user.name ? (
                  <p className="truncate text-xs text-muted-foreground">
                    {session.user.email}
                  </p>
                ) : null}
              </>
            ) : (
              <Skeleton className="mt-1 h-4 w-40" />
            )}
          </div>
        </div>

        {policyUrl || termsUrl ? (
          <div className="flex flex-wrap gap-x-4 gap-y-2 text-xs">
            {policyUrl ? (
              <a
                className="text-muted-foreground underline underline-offset-4 hover:text-foreground"
                href={policyUrl}
                rel="noreferrer"
                target="_blank"
              >
                {localization.privacyPolicy}
              </a>
            ) : null}
            {termsUrl ? (
              <a
                className="text-muted-foreground underline underline-offset-4 hover:text-foreground"
                href={termsUrl}
                rel="noreferrer"
                target="_blank"
              >
                {localization.termsOfService}
              </a>
            ) : null}
          </div>
        ) : null}
      </CardContent>

      <CardFooter className="grid grid-cols-2 gap-2">
        <Button
          disabled={!canRespond}
          variant="outline"
          onClick={() => consent.mutate({ accept: false })}
        >
          {consent.isPending && consent.variables?.accept === false ? (
            <Spinner />
          ) : null}
          {localization.cancel}
        </Button>
        <Button
          disabled={!canRespond}
          onClick={() => consent.mutate({ accept: true })}
        >
          {consent.isPending && consent.variables?.accept === true ? (
            <Spinner />
          ) : null}
          {localization.allow}
        </Button>
      </CardFooter>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/oauth-provider/oauth-consent.tsx
import {
  type OAuthAuthorizationRequest,
  type OAuthProviderAuthClient,
  parseOAuthAuthorizationRequest,
  sanitizeOAuthClientUrl
} from "@better-auth-ui/core/plugins/oauth-provider"
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/solid"
import {
  useOAuthConsent,
  usePublicOAuthClient
} from "@better-auth-ui/solid/plugins/oauth-provider"
import { Check, ShieldCheck } from "lucide-solid"
import { createSignal, For, onMount, Show } from "solid-js"

import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Separator } from "@/components/ui/separator"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { oauthProviderPlugin } from "@/lib/auth/oauth-provider-plugin"
import { cn } from "@/lib/utils"
import { UserAvatar } from "../user/user-avatar"

export type OAuthConsentProps = {
  class?: string
}

const interpolateClient = (template: string, clientName: string) =>
  template.replace("{{client}}", clientName)

export function OAuthConsent(props: OAuthConsentProps) {
  const auth = useAuth()
  const { localization, scopeMetadata } = useAuthPlugin(oauthProviderPlugin)
  const oauthClient = auth.authClient as OAuthProviderAuthClient
  const session = useSession(oauthClient)
  const [request, setRequest] = createSignal<OAuthAuthorizationRequest>()

  onMount(() => {
    setRequest(parseOAuthAuthorizationRequest(window.location.search))
  })

  const publicClient = usePublicOAuthClient(
    oauthClient,
    () => request()?.clientId
  )
  const consent = useOAuthConsent(oauthClient)
  const clientName = () =>
    publicClient.data?.client_name || localization.application
  const logoUrl = () => sanitizeOAuthClientUrl(publicClient.data?.logo_uri)
  const policyUrl = () => sanitizeOAuthClientUrl(publicClient.data?.policy_uri)
  const termsUrl = () => sanitizeOAuthClientUrl(publicClient.data?.tos_uri)
  const invalidRequest = () =>
    request() !== undefined &&
    (!request()?.clientId ||
      (!session.isPending && !session.data) ||
      publicClient.isError ||
      (!publicClient.isPending && session.data && !publicClient.data))
  const canRespond = () =>
    Boolean(
      request()?.clientId &&
        session.data &&
        publicClient.data &&
        !consent.isPending
    )

  return (
    <Show
      when={!invalidRequest()}
      fallback={
        <Card class={cn("w-full max-w-md", props.class)}>
          <CardHeader>
            <CardTitle class="text-xl">{localization.invalidRequest}</CardTitle>
            <CardDescription>
              {localization.invalidRequestDescription}
            </CardDescription>
          </CardHeader>
        </Card>
      }
    >
      <Card class={cn("w-full max-w-md", props.class)}>
        <CardHeader class="gap-4">
          <div class="flex items-center gap-3">
            <Show
              when={publicClient.data}
              fallback={<Skeleton class="size-10 rounded-full" />}
            >
              {(_client) => (
                <Avatar size="lg">
                  <AvatarImage
                    alt={clientName()}
                    referrerpolicy="no-referrer"
                    src={logoUrl()}
                  />
                  <AvatarFallback>
                    <ShieldCheck class="size-5" />
                  </AvatarFallback>
                </Avatar>
              )}
            </Show>

            <div class="min-w-0 flex-1">
              <Show
                when={publicClient.data}
                fallback={<Skeleton class="h-4 w-36" />}
              >
                {(client) => (
                  <>
                    <p class="truncate font-medium">{clientName()}</p>
                    <Show when={client().client_uri}>
                      {(uri) => (
                        <p class="truncate text-muted-foreground text-xs">
                          {uri()}
                        </p>
                      )}
                    </Show>
                  </>
                )}
              </Show>
            </div>
          </div>

          <div class="grid gap-1">
            <CardTitle class="text-xl">
              {interpolateClient(localization.authorize, clientName())}
            </CardTitle>
            <CardDescription>
              {interpolateClient(
                localization.authorizationDescription,
                clientName()
              )}
            </CardDescription>
          </div>
        </CardHeader>

        <CardContent class="flex flex-col gap-5">
          <div class="grid gap-3">
            <p class="text-sm font-medium">
              {interpolateClient(
                localization.requestedPermissions,
                clientName()
              )}
            </p>

            <Show
              when={request()}
              fallback={
                <div class="flex gap-3">
                  <Skeleton class="mt-0.5 size-4 shrink-0 rounded-full" />
                  <div class="grid flex-1 gap-2">
                    <Skeleton class="h-4 w-32" />
                    <Skeleton class="h-3 w-full max-w-64" />
                  </div>
                </div>
              }
            >
              {(authorizationRequest) => (
                <ul class="grid gap-3">
                  <For each={authorizationRequest().scopes}>
                    {(scope) => {
                      const metadata = () => scopeMetadata[scope]

                      return (
                        <li class="flex gap-3">
                          <Check class="mt-0.5 size-4 shrink-0 text-primary" />
                          <div class="grid gap-0.5">
                            <p class="text-sm font-medium">
                              {metadata()?.label ?? scope}
                            </p>
                            <Show when={metadata()?.description}>
                              {(description) => (
                                <p class="text-muted-foreground text-xs">
                                  {description()}
                                </p>
                              )}
                            </Show>
                          </div>
                        </li>
                      )
                    }}
                  </For>
                </ul>
              )}
            </Show>
          </div>

          <Separator />

          <div class="flex items-center gap-3">
            <UserAvatar
              isPending={session.isPending}
              user={session.data?.user}
            />
            <div class="min-w-0 flex-1">
              <p class="text-muted-foreground text-xs">
                {localization.signedInAs}
              </p>
              <Show
                when={session.data}
                fallback={<Skeleton class="mt-1 h-4 w-40" />}
              >
                {(currentSession) => (
                  <>
                    <p class="truncate text-sm font-medium">
                      {currentSession().user.name ||
                        currentSession().user.email}
                    </p>
                    <Show when={currentSession().user.name}>
                      <p class="truncate text-muted-foreground text-xs">
                        {currentSession().user.email}
                      </p>
                    </Show>
                  </>
                )}
              </Show>
            </div>
          </div>

          <Show when={policyUrl() || termsUrl()}>
            <div class="flex flex-wrap gap-x-4 gap-y-2 text-xs">
              <Show when={policyUrl()}>
                {(uri) => (
                  <a
                    class="text-muted-foreground underline underline-offset-4 hover:text-foreground"
                    href={uri()}
                    rel="noreferrer"
                    target="_blank"
                  >
                    {localization.privacyPolicy}
                  </a>
                )}
              </Show>
              <Show when={termsUrl()}>
                {(uri) => (
                  <a
                    class="text-muted-foreground underline underline-offset-4 hover:text-foreground"
                    href={uri()}
                    rel="noreferrer"
                    target="_blank"
                  >
                    {localization.termsOfService}
                  </a>
                )}
              </Show>
            </div>
          </Show>
        </CardContent>

        <CardFooter class="grid grid-cols-2 gap-2">
          <Button
            disabled={!canRespond()}
            variant="outline"
            onClick={() => consent.mutate({ accept: false })}
          >
            <Show
              when={consent.isPending && consent.variables?.accept === false}
            >
              <Spinner />
            </Show>
            {localization.cancel}
          </Button>
          <Button
            disabled={!canRespond()}
            onClick={() => consent.mutate({ accept: true })}
          >
            <Show
              when={consent.isPending && consent.variables?.accept === true}
            >
              <Spinner />
            </Show>
            {localization.allow}
          </Button>
        </CardFooter>
      </Card>
    </Show>
  )
}
