// packages/heroui/src/components/auth/oauth-provider/remove-authorization-dialog.tsx
"use client"

import type {
  AuthorizedOAuthApplication,
  OAuthProviderAuthClient
} from "@better-auth-ui/core/plugins/oauth-provider"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useDeleteOAuthConsent } from "@better-auth-ui/react/plugins/oauth-provider"
import { ShieldExclamation } from "@gravity-ui/icons"
import { AlertDialog, Button, Spinner } from "@heroui/react"
import { useState } from "react"

import { oauthProviderPlugin } from "../../../lib/auth/oauth-provider-plugin"

export type RemoveAuthorizationDialogProps = {
  /** @remarks `AuthorizedOAuthApplication` */
  application: AuthorizedOAuthApplication
  clientName: string
  isOpen: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Confirmation for removing every consent record tied to one OAuth client.
 *
 * The copy is deliberate: Better Auth's consent deletion removes the stored
 * approval, so the application must ask again — it does not revoke access or
 * refresh tokens that were already issued.
 */
export function RemoveAuthorizationDialog({
  application,
  clientName,
  isOpen,
  onOpenChange
}: RemoveAuthorizationDialogProps) {
  const { authClient, localization } = useAuth()
  const { localization: oauthLocalization } = useAuthPlugin(oauthProviderPlugin)
  const [isRemoving, setIsRemoving] = useState(false)

  const { mutateAsync: deleteConsent } = useDeleteOAuthConsent(
    authClient as OAuthProviderAuthClient
  )

  const removeAuthorization = async () => {
    setIsRemoving(true)

    try {
      // Sequential so a mid-list failure leaves a predictable server state
      // that the refetched list reflects accurately.
      for (const id of application.consentIds) {
        await deleteConsent({ id })
      }

      onOpenChange(false)
    } catch {
      // The error toaster reports the failure; the dialog stays open so the
      // remaining records can be retried.
    } finally {
      setIsRemoving(false)
    }
  }

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={onOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog>
          <AlertDialog.CloseTrigger />

          <AlertDialog.Header>
            <AlertDialog.Icon status="danger">
              <ShieldExclamation />
            </AlertDialog.Icon>

            <AlertDialog.Heading>
              {oauthLocalization.removeAuthorizationTitle}
            </AlertDialog.Heading>
          </AlertDialog.Header>

          <AlertDialog.Body className="flex flex-col gap-4">
            <p className="text-muted text-sm">
              {oauthLocalization.removeAuthorizationDescription}
            </p>

            <p className="text-sm font-medium">{clientName}</p>
          </AlertDialog.Body>

          <AlertDialog.Footer>
            <Button slot="close" variant="tertiary" isDisabled={isRemoving}>
              {localization.settings.cancel}
            </Button>

            <Button
              variant="danger"
              isPending={isRemoving}
              onPress={removeAuthorization}
            >
              {isRemoving && <Spinner color="current" size="sm" />}

              {oauthLocalization.remove}
            </Button>
          </AlertDialog.Footer>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/oauth-provider/remove-authorization-dialog.tsx
import type {
  AuthorizedOAuthApplication,
  OAuthProviderAuthClient
} from "@better-auth-ui/core/plugins/oauth-provider"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useDeleteOAuthConsent } from "@better-auth-ui/solid/plugins/oauth-provider"
import { ShieldOff } from "lucide-solid"
import { createSignal, Show } from "solid-js"

import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Spinner } from "@/components/ui/spinner"
import { oauthProviderPlugin } from "@/lib/auth/oauth-provider-plugin"

export type RemoveAuthorizationDialogProps = {
  /** @remarks `AuthorizedOAuthApplication` */
  application: AuthorizedOAuthApplication
  clientName: string
  onOpenChange: (open: boolean) => void
}

/**
 * Confirmation for removing every consent record tied to one OAuth client.
 *
 * The copy is deliberate: Better Auth's consent deletion removes the stored
 * approval, so the application must ask again — it does not revoke access or
 * refresh tokens that were already issued.
 */
export function RemoveAuthorizationDialog(
  props: RemoveAuthorizationDialogProps
) {
  const auth = useAuth()
  const { localization } = useAuthPlugin(oauthProviderPlugin)
  const [isRemoving, setIsRemoving] = createSignal(false)

  const deleteConsent = useDeleteOAuthConsent(
    auth.authClient as OAuthProviderAuthClient
  )

  const removeAuthorization = async () => {
    setIsRemoving(true)

    try {
      // Sequential so a mid-list failure leaves a predictable server state
      // that the refetched list reflects accurately.
      for (const id of props.application.consentIds) {
        await deleteConsent.mutateAsync({ id })
      }

      props.onOpenChange(false)
    } catch {
      // The error toaster reports the failure; the dialog stays open so the
      // remaining records can be retried.
    } finally {
      setIsRemoving(false)
    }
  }

  return (
    <DialogContent>
      <DialogHeader>
        <div class="flex size-10 items-center justify-center rounded-md bg-muted">
          <ShieldOff class="size-4.5" />
        </div>
        <DialogTitle>{localization.removeAuthorizationTitle}</DialogTitle>
        <DialogDescription>
          {localization.removeAuthorizationDescription}
        </DialogDescription>
      </DialogHeader>

      <p class="font-medium text-sm">{props.clientName}</p>

      <DialogFooter>
        <DialogClose
          as={Button}
          disabled={isRemoving()}
          type="button"
          variant="outline"
        >
          {auth.localization.settings.cancel}
        </DialogClose>

        <Button
          disabled={isRemoving()}
          type="button"
          variant="destructive"
          onClick={removeAuthorization}
        >
          <Show when={isRemoving()}>
            <Spinner />
          </Show>
          {localization.remove}
        </Button>
      </DialogFooter>
    </DialogContent>
  )
}
