// packages/heroui/src/components/auth/settings/security/active-sessions.tsx
import { isReauthenticationRequiredError } from "@better-auth-ui/core"
import { useAuth, useListSessions, useSession } from "@better-auth-ui/react"
import { Card, type CardProps, cn, Skeleton } from "@heroui/react"
import { ReauthenticationAction } from "../../reauthentication"
import { ActiveSession } from "./active-session"
import { SessionActions } from "./session-actions"

export type ActiveSessionsProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Render a card listing all active sessions for the current user with revoke controls.
 *
 * Shows each session's browser, OS, IP address, and creation time. The current session is marked
 * and navigates to sign-out on click, while other sessions can be revoked individually.
 *
 * @returns A JSX element containing the sessions card
 */
export function ActiveSessions({
  className,
  variant,
  ...props
}: ActiveSessionsProps & Omit<CardProps, "children">) {
  const { authClient, localization } = useAuth()
  const { data: session } = useSession(authClient)

  const sessionsQuery = useListSessions(authClient, {
    meta: { errorPresentation: "inline" }
  })
  const { data: sessions, error, isPending } = sessionsQuery

  const activeSessions =
    sessions &&
    [...sessions].sort((a, b) =>
      a.id === session?.session.id ? -1 : b.id === session?.session.id ? 1 : 0
    )

  return (
    <div>
      <h2 className={cn("text-sm font-semibold mb-3")}>
        {localization.settings.activeSessions}
      </h2>

      <Card className={cn("gap-0", className)} variant={variant} {...props}>
        <Card.Content className="gap-0 p-0">
          {isReauthenticationRequiredError(error) ? (
            <ReauthenticationAction />
          ) : error ? (
            <div className="p-4 text-danger text-sm">{error.message}</div>
          ) : isPending ? (
            <SessionRowSkeleton />
          ) : (
            activeSessions?.map((activeSession) => (
              <div
                className="border-b border-divider px-4 py-3 last:border-b-0"
                key={activeSession.id}
              >
                <ActiveSession activeSession={activeSession} />
              </div>
            ))
          )}
        </Card.Content>

        {!isPending && !error && (
          <SessionActions
            hasOtherSessions={
              activeSessions?.some(
                (activeSession) => activeSession.id !== session?.session.id
              ) ?? false
            }
          />
        )}
      </Card>
    </div>
  )
}

function SessionRowSkeleton() {
  return (
    <div className="flex items-center justify-between">
      <div className="flex items-center gap-3">
        <Skeleton className="size-10 rounded-xl" />

        <div className="flex flex-col gap-1">
          <Skeleton className="h-4 w-32 rounded-lg" />
          <Skeleton className="h-3 w-24 rounded-lg" />
        </div>
      </div>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/settings/security/active-sessions.tsx
import {
  isReauthenticationRequiredError,
  type ListSession
} from "@better-auth-ui/core"
import {
  useAuth,
  useListSessions,
  useRevokeSession,
  useSession
} from "@better-auth-ui/solid"
import { For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { resolveUserLabel } from "@/components/auth/settings/shared/helpers"
import { Card, CardContent } from "@/components/ui/card"
import { ItemGroup, ItemSeparator } from "@/components/ui/item"
import { cn } from "cn"
import { ReauthenticationAction } from "../../reauthentication"
import { ActiveSessionRow, ActiveSessionRowSkeleton } from "./active-session"
import { SessionActions } from "./session-actions"

export type ActiveSessionsSettingsProps = {
  class?: string
}

export function ActiveSessionsSettings(
  props: ActiveSessionsSettingsProps = {}
) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const activeSessions = useListSessions(auth.authClient, () => ({
    meta: { errorPresentation: "inline" }
  }))
  const sessions = () =>
    [...(activeSessions.data ?? [])].sort((activeSession) =>
      activeSession.id === session.data?.session.id ? -1 : 1
    )
  const revokeSession = useRevokeSession(auth.authClient, () => ({
    onSuccess: () =>
      toast.success(auth.localization.settings.revokeSessionSuccess)
  }))
  const displayName = () =>
    resolveUserLabel(session.data?.user.name, session.data?.user.email)

  const signOut = () => {
    auth.navigate({
      to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signOut}`
    })
  }

  const revoke = (activeSession: ListSession) => {
    revokeSession.mutate(activeSession)
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.activeSessions}
      </h2>

      <Card class="z-card-padding-none gap-0!">
        <CardContent class="z-card-content-padding-none">
          <Show
            fallback={
              <ItemGroup class="gap-0!">
                <ActiveSessionRowSkeleton />
              </ItemGroup>
            }
            when={!activeSessions.isPending}
          >
            <Show
              fallback={
                <ItemGroup class="gap-0!">
                  <For each={sessions()}>
                    {(activeSession, index) => (
                      <>
                        <Show when={index() > 0}>
                          <ItemSeparator class="my-0!" />
                        </Show>
                        <ActiveSessionRow
                          activeSession={activeSession}
                          displayName={displayName()}
                          isRevoking={revokeSession.isPending}
                          isCurrentSession={
                            activeSession.id === session.data?.session.id
                          }
                          onRevoke={revoke}
                          onSignOut={signOut}
                        />
                      </>
                    )}
                  </For>
                </ItemGroup>
              }
              when={activeSessions.error}
            >
              {(error) => (
                <Show
                  fallback={
                    <p class="p-4 text-destructive text-sm">
                      {error().message}
                    </p>
                  }
                  when={isReauthenticationRequiredError(error())}
                >
                  <ReauthenticationAction />
                </Show>
              )}
            </Show>
          </Show>
        </CardContent>
        <Show
          when={
            !activeSessions.isPending && !activeSessions.error && session.data
          }
        >
          <SessionActions
            hasOtherSessions={sessions().some(
              (activeSession) => activeSession.id !== session.data?.session.id
            )}
          />
        </Show>
      </Card>
    </div>
  )
}
