// packages/heroui/src/components/auth/settings/security/change-password.tsx
import {
  getViewURL,
  isPasswordCompromisedError,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import {
  useAuth,
  useChangePassword,
  useFetchOptions,
  useListAccounts,
  useRequestPasswordReset,
  useSession
} from "@better-auth-ui/react"
import { Eye, EyeSlash } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  cn,
  FieldError,
  Fieldset,
  InputGroup,
  Label,
  Skeleton,
  Spinner,
  TextField,
  toast
} from "@heroui/react"
import { useState } from "react"
import { isAuthFormFieldInvalid, useAuthForm } from "../../auth-form"

import { OpenEmailButton } from "../../open-email-button"
import { PasswordStrengthMeter } from "../../password-strength-meter"

export type ChangePasswordProps = {
  className?: string
  variant?: CardProps["variant"]
}

/**
 * Render a card form for changing the authenticated user's password.
 *
 * When the user has a credential account, displays fields for current password,
 * new password, and optionally confirm password. When the user only has social
 * accounts, displays a prompt to set a password via the reset flow.
 *
 * @returns A JSX element containing the change-password or set-password card
 */
export function ChangePassword({
  className,
  variant,
  ...props
}: ChangePasswordProps & Omit<CardProps, "children">) {
  const { authClient, emailAndPassword, localization } = useAuth()
  const { data: session } = useSession(authClient)
  const { data: accounts, isPending: isAccountsPending } =
    useListAccounts(authClient)

  const hasCredentialAccount = accounts?.some(
    (account) => account.providerId === "credential"
  )

  if (!isAccountsPending && !hasCredentialAccount) {
    return <SetPassword className={className} variant={variant} {...props} />
  }

  return (
    <ChangePasswordForm
      className={className}
      variant={variant}
      emailAndPassword={emailAndPassword}
      localization={localization}
      session={isAccountsPending ? undefined : session}
      {...props}
    />
  )
}

function SetPassword({
  className,
  variant,
  ...props
}: Omit<CardProps, "children">) {
  const { authClient, basePaths, baseURL, localization, plugins, viewPaths } =
    useAuth()
  const { data: session } = useSession(authClient)
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const [sentEmail, setSentEmail] = useState("")

  const { mutate: requestPasswordReset, isPending } = useRequestPasswordReset(
    authClient,
    {
      onError: () => {
        resetFetchOptions()
      },
      onSuccess: (_data, { email }) => {
        setSentEmail(email)
      }
    }
  )

  const Captcha = plugins.find(
    (plugin) => plugin.captchaComponent
  )?.captchaComponent

  const handleSetPassword = () => {
    if (!session?.user.email) return
    requestPasswordReset({
      email: session.user.email,
      redirectTo: getViewURL(
        baseURL,
        basePaths.auth,
        viewPaths.auth.resetPassword
      ),
      fetchOptions
    })
  }

  return (
    <div>
      <h2 className={cn("text-sm font-semibold mb-3")}>
        {localization.settings.changePassword}
      </h2>

      <Card className={cn(className)} variant={variant} {...props}>
        <Card.Content className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm font-medium leading-tight">
              {localization.settings.setPassword}
            </p>

            <p className="text-muted text-xs mt-0.5">
              {localization.settings.setPasswordDescription}
            </p>
          </div>

          {sentEmail ? (
            <div className="flex flex-col gap-3 items-start sm:items-end">
              <p className="text-sm" role="status">
                {localization.auth.resetLinkSentTo.replace(
                  "{{email}}",
                  sentEmail
                )}
              </p>

              <OpenEmailButton email={sentEmail} className="w-auto" />
            </div>
          ) : (
            <div className="flex flex-col gap-3 items-start sm:items-end">
              {Captcha && <div>{Captcha}</div>}

              <Button
                size="sm"
                isPending={isPending}
                isDisabled={!session?.user.email}
                onPress={handleSetPassword}
              >
                {isPending && <Spinner color="current" size="sm" />}
                {localization.auth.sendResetLink}
              </Button>
            </div>
          )}
        </Card.Content>
      </Card>
    </div>
  )
}

function ChangePasswordForm({
  className,
  variant,
  emailAndPassword,
  localization,
  session,
  ...props
}: {
  emailAndPassword: ReturnType<typeof useAuth>["emailAndPassword"]
  localization: ReturnType<typeof useAuth>["localization"]
  session: ReturnType<typeof useSession>["data"]
} & Omit<CardProps, "children">) {
  const { authClient } = useAuth()
  const [isCompromised, setIsCompromised] = useState(false)
  const [isCurrentPasswordVisible, setIsCurrentPasswordVisible] =
    useState(false)

  const { mutateAsync: changePassword, isPending } = useChangePassword(
    authClient,
    {
      onError: (error) => {
        // The haveIBeenPwned plugin rejects on the password itself, so it
        // belongs against the field rather than in a toast.
        setIsCompromised(isPasswordCompromisedError(error))
      },
      onSuccess: () => {
        form.reset()
        toast.success(localization.settings.changePasswordSuccess)
      }
    }
  )

  const [isNewPasswordVisible, setIsNewPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  const form = useAuthForm({
    defaultValues: {
      confirmPassword: "",
      currentPassword: "",
      newPassword: ""
    },
    onSubmit: async ({ value }) => {
      try {
        await changePassword({
          currentPassword: value.currentPassword,
          newPassword: value.newPassword,
          revokeOtherSessions: true
        })
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  })

  return (
    <div>
      <h2 className={cn("text-sm font-semibold mb-3")}>
        {localization.settings.changePassword}
      </h2>

      <Card className={cn("p-4 gap-4", className)} variant={variant} {...props}>
        <Card.Content>
          <form.AppForm>
            <form.AuthFormRoot>
              <Fieldset className="w-full gap-4">
                <Fieldset.Group>
                  <form.AppField
                    name="currentPassword"
                    validators={{
                      onChange: ({ value }) =>
                        validateStringLength(value, {
                          requiredMessage: localization.auth.fieldRequired
                        })
                    }}
                  >
                    {(field) => (
                      <TextField
                        name={field.name}
                        isDisabled={isPending || !session}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={field.handleChange}
                        isInvalid={
                          isAuthFormFieldInvalid(field.state.meta) || undefined
                        }
                        validationBehavior="aria"
                      >
                        <Label>{localization.settings.currentPassword}</Label>

                        <InputGroup
                          className={cn(!session && "hidden")}
                          variant={
                            variant === "transparent" ? "primary" : "secondary"
                          }
                        >
                          <InputGroup.Input
                            autoComplete="current-password"
                            name="currentPassword"
                            placeholder={
                              localization.settings.currentPasswordPlaceholder
                            }
                            required
                            type={
                              isCurrentPasswordVisible ? "text" : "password"
                            }
                          />

                          <InputGroup.Suffix className="px-0">
                            <Button
                              isIconOnly
                              aria-label={
                                isCurrentPasswordVisible
                                  ? localization.auth.hidePassword
                                  : localization.auth.showPassword
                              }
                              size="sm"
                              variant="ghost"
                              onPress={() =>
                                setIsCurrentPasswordVisible(
                                  !isCurrentPasswordVisible
                                )
                              }
                              isDisabled={isPending}
                            >
                              {isCurrentPasswordVisible ? (
                                <EyeSlash />
                              ) : (
                                <Eye />
                              )}
                            </Button>
                          </InputGroup.Suffix>
                        </InputGroup>

                        {!session && (
                          <Skeleton className="h-10 md:h-9 w-full rounded-xl" />
                        )}

                        <field.AuthFormFieldError />
                      </TextField>
                    )}
                  </form.AppField>

                  <form.AppField
                    name="newPassword"
                    validators={{
                      onChange: ({ value }) =>
                        validateStringLength(value, {
                          maxLength: emailAndPassword?.maxPasswordLength,
                          maxLengthMessage: localization.auth.tooLong.replace(
                            "{{max}}",
                            String(emailAndPassword?.maxPasswordLength)
                          ),
                          minLength: emailAndPassword?.minPasswordLength,
                          minLengthMessage: localization.auth.tooShort.replace(
                            "{{min}}",
                            String(emailAndPassword?.minPasswordLength)
                          ),
                          requiredMessage: localization.auth.fieldRequired
                        })
                    }}
                  >
                    {(field) => {
                      const isInvalid =
                        isAuthFormFieldInvalid(field.state.meta) ||
                        isCompromised

                      return (
                        <TextField
                          minLength={emailAndPassword?.minPasswordLength}
                          maxLength={emailAndPassword?.maxPasswordLength}
                          isDisabled={isPending || !session}
                          value={field.state.value}
                          onBlur={field.handleBlur}
                          onChange={(value) => {
                            field.handleChange(value)
                            setIsCompromised(false)
                          }}
                          isInvalid={isInvalid || undefined}
                          validationBehavior="aria"
                        >
                          <Label>{localization.auth.newPassword}</Label>

                          <InputGroup
                            className={cn(!session && "hidden")}
                            variant={
                              variant === "transparent"
                                ? "primary"
                                : "secondary"
                            }
                          >
                            <InputGroup.Input
                              name="newPassword"
                              type={isNewPasswordVisible ? "text" : "password"}
                              autoComplete="new-password"
                              placeholder={
                                localization.auth.newPasswordPlaceholder
                              }
                              required
                            />

                            <InputGroup.Suffix className="px-0">
                              <Button
                                isIconOnly
                                aria-label={
                                  isNewPasswordVisible
                                    ? localization.auth.hidePassword
                                    : localization.auth.showPassword
                                }
                                size="sm"
                                variant="ghost"
                                onPress={() =>
                                  setIsNewPasswordVisible(!isNewPasswordVisible)
                                }
                                isDisabled={isPending}
                              >
                                {isNewPasswordVisible ? <EyeSlash /> : <Eye />}
                              </Button>
                            </InputGroup.Suffix>
                          </InputGroup>

                          {!session && (
                            <Skeleton className="h-10 md:h-9 w-full rounded-xl" />
                          )}

                          {isCompromised ? (
                            <FieldError>
                              {localization.auth.passwordCompromised}
                            </FieldError>
                          ) : (
                            <field.AuthFormFieldError />
                          )}

                          <PasswordStrengthMeter password={field.state.value} />
                        </TextField>
                      )
                    }}
                  </form.AppField>

                  {emailAndPassword?.confirmPassword && (
                    <form.AppField
                      name="confirmPassword"
                      validators={{
                        onChangeListenTo: ["newPassword"],
                        onChange: ({ fieldApi, value }) =>
                          validateStringLength(value, {
                            maxLength: emailAndPassword?.maxPasswordLength,
                            maxLengthMessage: localization.auth.tooLong.replace(
                              "{{max}}",
                              String(emailAndPassword?.maxPasswordLength)
                            ),
                            minLength: emailAndPassword?.minPasswordLength,
                            minLengthMessage:
                              localization.auth.tooShort.replace(
                                "{{min}}",
                                String(emailAndPassword?.minPasswordLength)
                              ),
                            requiredMessage: localization.auth.fieldRequired
                          }) ??
                          validateMatchingValue(
                            value,
                            fieldApi.form.getFieldValue("newPassword"),
                            localization.auth.passwordsDoNotMatch
                          )
                      }}
                    >
                      {(field) => (
                        <TextField
                          minLength={emailAndPassword?.minPasswordLength}
                          maxLength={emailAndPassword?.maxPasswordLength}
                          isDisabled={isPending || !session}
                          isRequired
                          value={field.state.value}
                          onBlur={field.handleBlur}
                          onChange={field.handleChange}
                          isInvalid={
                            isAuthFormFieldInvalid(field.state.meta) ||
                            undefined
                          }
                          validationBehavior="aria"
                        >
                          <Label>{localization.auth.confirmPassword}</Label>

                          <InputGroup
                            className={cn(!session && "hidden")}
                            variant={
                              variant === "transparent"
                                ? "primary"
                                : "secondary"
                            }
                          >
                            <InputGroup.Input
                              name="confirmPassword"
                              type={
                                isConfirmPasswordVisible ? "text" : "password"
                              }
                              autoComplete="new-password"
                              placeholder={
                                localization.auth.confirmPasswordPlaceholder
                              }
                              required
                            />

                            <InputGroup.Suffix className="px-0">
                              <Button
                                isIconOnly
                                aria-label={
                                  isConfirmPasswordVisible
                                    ? localization.auth.hidePassword
                                    : localization.auth.showPassword
                                }
                                size="sm"
                                variant="ghost"
                                onPress={() =>
                                  setIsConfirmPasswordVisible(
                                    !isConfirmPasswordVisible
                                  )
                                }
                                isDisabled={isPending}
                              >
                                {isConfirmPasswordVisible ? (
                                  <EyeSlash />
                                ) : (
                                  <Eye />
                                )}
                              </Button>
                            </InputGroup.Suffix>
                          </InputGroup>

                          {!session && (
                            <Skeleton className="h-10 md:h-9 w-full rounded-xl" />
                          )}

                          <field.AuthFormFieldError />
                        </TextField>
                      )}
                    </form.AppField>
                  )}
                </Fieldset.Group>

                <Fieldset.Actions>
                  <form.AuthFormSubmitButton isDisabled={!session} size="sm">
                    {localization.settings.updatePassword}
                  </form.AuthFormSubmitButton>
                </Fieldset.Actions>
              </Fieldset>
            </form.AuthFormRoot>
          </form.AppForm>
        </Card.Content>
      </Card>
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/settings/security/change-password.tsx
import {
  getViewURL,
  isPasswordCompromisedError,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import {
  useAuth,
  useChangePassword,
  useListAccounts,
  useRequestPasswordReset,
  useSession
} from "@better-auth-ui/solid"
import type { BetterFetchError } from "better-auth/client"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { OpenEmailButton } from "@/components/auth/open-email-button"
import { PasswordStrengthMeter } from "@/components/auth/password-strength-meter"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "cn"
import { createAuthForm, isAuthFormFieldInvalid } from "../../auth-form"

function ChangePasswordSkeletonInput() {
  return (
    <Skeleton>
      <Input class="invisible" />
    </Skeleton>
  )
}

export type ChangePasswordSettingsProps = {
  class?: string
  confirmPassword?: boolean
}

export function ChangePasswordSettings(
  props: ChangePasswordSettingsProps = {}
) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const userId = () => session.data?.user.id
  const linkedAccounts = useListAccounts(auth.authClient, () => ({
    enabled: !import.meta.env.SSR && Boolean(userId())
  }))
  const hasCredentialAccount = () =>
    linkedAccounts.data?.some(
      (account: { providerId?: string }) => account.providerId === "credential"
    )
  const requestPasswordReset = useRequestPasswordReset(auth.authClient)
  const changePassword = useChangePassword(auth.authClient, () => ({
    onError: (error: BetterFetchError) => {
      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setIsCompromised(true)
        return
      }
    },
    onSuccess: () => {
      form.reset()
      toast.success(auth.localization.settings.changePasswordSuccess)
    }
  }))
  const [isCurrentPasswordVisible, setIsCurrentPasswordVisible] =
    createSignal(false)
  const [isNewPasswordVisible, setIsNewPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const [isCompromised, setIsCompromised] = createSignal(false)

  const sendResetLink = () => {
    if (!session.data) return

    requestPasswordReset.mutate({
      email: session.data.user.email,
      redirectTo: getViewURL(
        auth.baseURL,
        auth.basePaths.auth,
        auth.viewPaths.auth.resetPassword
      )
    } as Parameters<typeof requestPasswordReset.mutate>[0])
  }

  const form = createAuthForm(() => ({
    defaultValues: {
      confirmPassword: "",
      currentPassword: "",
      newPassword: ""
    },
    onSubmit: async ({ value }) => {
      try {
        await changePassword.mutateAsync({
          currentPassword: value.currentPassword,
          newPassword: value.newPassword,
          revokeOtherSessions: true
        } as Parameters<typeof changePassword.mutate>[0])
      } catch {
        // The mutation reports the error through its configured handler.
      }
    }
  }))

  const isPasswordPending = () =>
    changePassword.isPending || requestPasswordReset.isPending

  if (!linkedAccounts.isPending && !hasCredentialAccount()) {
    return (
      <div class={cn(props.class)}>
        <h2 class="mb-3 text-sm font-semibold">
          {auth.localization.settings.changePassword}
        </h2>

        <Card>
          <CardContent class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p class="font-medium text-sm leading-tight">
                {auth.localization.settings.setPassword}
              </p>
              <p class="mt-0.5 text-muted-foreground text-xs">
                {auth.localization.settings.setPasswordDescription}
              </p>
            </div>

            <Show
              fallback={
                <Button
                  disabled={requestPasswordReset.isPending || !session.data}
                  onClick={sendResetLink}
                  size="sm"
                  type="button"
                >
                  {requestPasswordReset.isPending
                    ? `${auth.localization.auth.sendResetLink}…`
                    : auth.localization.auth.sendResetLink}
                </Button>
              }
              when={requestPasswordReset.isSuccess && session.data?.user.email}
              keyed
            >
              {(sentEmail) => (
                <div class="flex flex-col items-start gap-3 sm:items-end">
                  <p class="text-sm" role="status">
                    {auth.localization.auth.resetLinkSentTo.replace(
                      "{{email}}",
                      sentEmail
                    )}
                  </p>

                  <OpenEmailButton class="w-auto" email={sentEmail} />
                </div>
              )}
            </Show>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.changePassword}
      </h2>

      <form.AppForm>
        <form.AuthFormRoot>
          <Card>
            <CardContent class="flex flex-col gap-6">
              <form.AppField
                name="currentPassword"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta)

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="currentPassword">
                        {auth.localization.settings.currentPassword}
                      </FieldLabel>
                      <Show
                        fallback={<ChangePasswordSkeletonInput />}
                        when={session.data && !linkedAccounts.isPending}
                      >
                        <InputGroup>
                          <InputGroupInput
                            aria-invalid={isInvalid()}
                            autocomplete="current-password"
                            disabled={isPasswordPending()}
                            id="currentPassword"
                            name={field().name}
                            onBlur={field().handleBlur}
                            onInput={(event) =>
                              field().handleChange(event.currentTarget.value)
                            }
                            placeholder={
                              auth.localization.settings
                                .currentPasswordPlaceholder
                            }
                            required
                            type={
                              isCurrentPasswordVisible() ? "text" : "password"
                            }
                            value={field().state.value}
                          />
                          <InputGroupAddon align="inline-end">
                            <InputGroupButton
                              aria-label={
                                isCurrentPasswordVisible()
                                  ? auth.localization.auth.hidePassword
                                  : auth.localization.auth.showPassword
                              }
                              disabled={isPasswordPending()}
                              onClick={() =>
                                setIsCurrentPasswordVisible(
                                  (visible) => !visible
                                )
                              }
                              size="icon-sm"
                              title={
                                isCurrentPasswordVisible()
                                  ? auth.localization.auth.hidePassword
                                  : auth.localization.auth.showPassword
                              }
                            >
                              <Show
                                when={isCurrentPasswordVisible()}
                                fallback={<Eye aria-hidden class="size-4" />}
                              >
                                <EyeOff aria-hidden class="size-4" />
                              </Show>
                            </InputGroupButton>
                          </InputGroupAddon>
                        </InputGroup>
                      </Show>
                      <field.AuthFormFieldError />
                    </Field>
                  )
                }}
              </form.AppField>

              <form.AppField
                name="newPassword"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      maxLength: auth.emailAndPassword.maxPasswordLength,
                      maxLengthMessage: auth.localization.auth.tooLong.replace(
                        "{{max}}",
                        String(auth.emailAndPassword.maxPasswordLength)
                      ),
                      minLength: auth.emailAndPassword.minPasswordLength,
                      minLengthMessage: auth.localization.auth.tooShort.replace(
                        "{{min}}",
                        String(auth.emailAndPassword.minPasswordLength)
                      ),
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = () =>
                    isAuthFormFieldInvalid(field().state.meta) ||
                    isCompromised()

                  return (
                    <Field data-invalid={isInvalid()}>
                      <FieldLabel for="newPassword">
                        {auth.localization.auth.newPassword}
                      </FieldLabel>
                      <Show
                        fallback={<ChangePasswordSkeletonInput />}
                        when={session.data && !linkedAccounts.isPending}
                      >
                        <InputGroup>
                          <InputGroupInput
                            aria-invalid={isInvalid()}
                            autocomplete="new-password"
                            disabled={isPasswordPending()}
                            id="newPassword"
                            maxLength={auth.emailAndPassword.maxPasswordLength}
                            minLength={auth.emailAndPassword.minPasswordLength}
                            name={field().name}
                            onBlur={field().handleBlur}
                            onInput={(event) => {
                              field().handleChange(event.currentTarget.value)
                              setIsCompromised(false)
                            }}
                            placeholder={
                              auth.localization.auth.newPasswordPlaceholder
                            }
                            required
                            type={isNewPasswordVisible() ? "text" : "password"}
                            value={field().state.value}
                          />
                          <InputGroupAddon align="inline-end">
                            <InputGroupButton
                              aria-label={
                                isNewPasswordVisible()
                                  ? auth.localization.auth.hidePassword
                                  : auth.localization.auth.showPassword
                              }
                              disabled={isPasswordPending()}
                              onClick={() =>
                                setIsNewPasswordVisible((visible) => !visible)
                              }
                              size="icon-sm"
                              title={
                                isNewPasswordVisible()
                                  ? auth.localization.auth.hidePassword
                                  : auth.localization.auth.showPassword
                              }
                              type="button"
                            >
                              {isNewPasswordVisible() ? (
                                <EyeOff aria-hidden class="size-4" />
                              ) : (
                                <Eye aria-hidden class="size-4" />
                              )}
                            </InputGroupButton>
                          </InputGroupAddon>
                        </InputGroup>
                      </Show>
                      <Show
                        when={
                          isCompromised()
                            ? auth.localization.auth.passwordCompromised
                            : undefined
                        }
                        fallback={<field.AuthFormFieldError />}
                      >
                        {(message) => <FieldError>{message()}</FieldError>}
                      </Show>

                      <PasswordStrengthMeter password={field().state.value} />
                    </Field>
                  )
                }}
              </form.AppField>

              <Show when={props.confirmPassword}>
                <form.AppField
                  name="confirmPassword"
                  validators={{
                    onChangeListenTo: ["newPassword"],
                    onChange: ({ fieldApi, value }) =>
                      validateStringLength(value, {
                        maxLength: auth.emailAndPassword.maxPasswordLength,
                        maxLengthMessage:
                          auth.localization.auth.tooLong.replace(
                            "{{max}}",
                            String(auth.emailAndPassword.maxPasswordLength)
                          ),
                        minLength: auth.emailAndPassword.minPasswordLength,
                        minLengthMessage:
                          auth.localization.auth.tooShort.replace(
                            "{{min}}",
                            String(auth.emailAndPassword.minPasswordLength)
                          ),
                        requiredMessage: auth.localization.auth.fieldRequired
                      }) ??
                      validateMatchingValue(
                        value,
                        fieldApi.form.getFieldValue("newPassword"),
                        auth.localization.auth.passwordsDoNotMatch
                      )
                  }}
                >
                  {(field) => {
                    const isInvalid = () =>
                      isAuthFormFieldInvalid(field().state.meta)

                    return (
                      <Field data-invalid={isInvalid()}>
                        <FieldLabel for="confirmPassword">
                          {auth.localization.auth.confirmPassword}
                        </FieldLabel>
                        <Show
                          fallback={<ChangePasswordSkeletonInput />}
                          when={session.data && !linkedAccounts.isPending}
                        >
                          <InputGroup>
                            <InputGroupInput
                              aria-invalid={isInvalid()}
                              autocomplete="new-password"
                              disabled={isPasswordPending()}
                              id="confirmPassword"
                              maxLength={
                                auth.emailAndPassword.maxPasswordLength
                              }
                              minLength={
                                auth.emailAndPassword.minPasswordLength
                              }
                              name={field().name}
                              onBlur={field().handleBlur}
                              onInput={(event) =>
                                field().handleChange(event.currentTarget.value)
                              }
                              placeholder={
                                auth.localization.auth
                                  .confirmPasswordPlaceholder
                              }
                              required
                              type={
                                isConfirmPasswordVisible() ? "text" : "password"
                              }
                              value={field().state.value}
                            />
                            <InputGroupAddon align="inline-end">
                              <InputGroupButton
                                aria-label={
                                  isConfirmPasswordVisible()
                                    ? auth.localization.auth.hidePassword
                                    : auth.localization.auth.showPassword
                                }
                                disabled={isPasswordPending()}
                                onClick={() =>
                                  setIsConfirmPasswordVisible(
                                    (visible) => !visible
                                  )
                                }
                                size="icon-sm"
                                title={
                                  isConfirmPasswordVisible()
                                    ? auth.localization.auth.hidePassword
                                    : auth.localization.auth.showPassword
                                }
                                type="button"
                              >
                                {isConfirmPasswordVisible() ? (
                                  <EyeOff aria-hidden class="size-4" />
                                ) : (
                                  <Eye aria-hidden class="size-4" />
                                )}
                              </InputGroupButton>
                            </InputGroupAddon>
                          </InputGroup>
                        </Show>
                        <field.AuthFormFieldError />
                      </Field>
                    )
                  }}
                </form.AppField>
              </Show>
            </CardContent>

            <CardFooter>
              <form.AuthFormSubmitButton
                disabled={isPasswordPending() || !session.data}
                size="sm"
              >
                {auth.localization.settings.updatePassword}
              </form.AuthFormSubmitButton>
            </CardFooter>
          </Card>
        </form.AuthFormRoot>
      </form.AppForm>
    </div>
  )
}
