// apps/docs/src/components/settings/security/security-settings.tsx
"use client"

import { useAuth } from "@better-auth-ui/react"
import { cn } from "@/lib/utils"
import { ActiveSessions } from "./active-sessions"
import { ChangePassword } from "./change-password"
import { DangerZone } from "./danger-zone"
import { LinkedAccounts, type LinkedAccountsProps } from "./linked-accounts"
import { Passkeys } from "./passkeys"

export type SecuritySettingsProps = {
  className?: string
  linkedAccounts?: Pick<LinkedAccountsProps, "allowMultipleAccountsPerProvider">
}

/**
 * Renders the security settings layout including password management, linked accounts, and active sessions.
 *
 * ChangePassword is rendered when password authentication is enabled; LinkedAccounts is rendered when social providers are present.
 * DangerZone is rendered when `deleteUser.enabled` is true in auth config.
 *
 * @param className - Optional additional CSS class names for the outer container.
 * @returns The security settings container as a JSX element.
 */
export function SecuritySettings({
  className,
  linkedAccounts
}: SecuritySettingsProps) {
  const { deleteUser, emailAndPassword, passkey, socialProviders } = useAuth()

  return (
    <div className={cn("flex w-full flex-col gap-4 md:gap-6", className)}>
      {emailAndPassword?.enabled && <ChangePassword />}
      {!!socialProviders?.length && <LinkedAccounts {...linkedAccounts} />}
      {passkey && <Passkeys />}
      <ActiveSessions />
      {deleteUser?.enabled && <DangerZone />}
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/settings/security/security-settings.tsx
import { useAuth } from "@better-auth-ui/solid"
import { Show } from "solid-js"
import { ApiKeysSettings } from "@/components/auth/api-key/api-keys"
import { DangerZone } from "@/components/auth/delete-user/danger-zone"
import { PasskeysSettings } from "@/components/auth/passkey/passkeys"
import { ActiveSessionsSettings } from "@/components/auth/settings/security/active-sessions"
import { ChangePasswordSettings } from "@/components/auth/settings/security/change-password"
import { LinkedAccountsSettings } from "@/components/auth/settings/security/linked-accounts"
import { hasAuthPlugin } from "@/components/auth/settings/shared/helpers"
import type { SecurityCardsPlugin } from "@/components/auth/settings/shared/types"

export function SecuritySettings() {
  const auth = useAuth()

  return (
    <div class="flex w-full flex-col gap-4 md:gap-6">
      <Show when={auth.emailAndPassword?.enabled}>
        <ChangePasswordSettings
          confirmPassword={auth.emailAndPassword.confirmPassword}
        />
      </Show>

      <Show when={!!auth.socialProviders?.length}>
        <LinkedAccountsSettings />
      </Show>

      <ActiveSessionsSettings />

      <Show when={hasAuthPlugin(auth.plugins, "apiKey")}>
        <ApiKeysSettings />
      </Show>

      <Show when={hasAuthPlugin(auth.plugins, "passkey")}>
        <PasskeysSettings />
      </Show>

      <Show when={hasAuthPlugin(auth.plugins, "deleteUser")}>
        <DangerZone />
      </Show>

      {auth.plugins.flatMap((plugin) => {
        const securityCards = plugin.securityCards as
          | SecurityCardsPlugin["securityCards"]
          | undefined

        return securityCards?.map((SecurityCard) => <SecurityCard />) ?? []
      })}
    </div>
  )
}
