// packages/react-native/src/components/auth/settings/security/security-settings.tsx
import { getOrganizationCardKey, useAuth } from "@better-auth-ui/react"
import { cn } from "../../../../lib/cn"
import type { CardVariant } from "../../../../primitives/card"
import { Box } from "../../../../primitives/styled"
import { ActiveSessions } from "./active-sessions"
import { ChangePassword } from "./change-password"
import { LinkedAccounts } from "./linked-accounts"

export type SecuritySettingsProps = {
  className?: string
  variant?: CardVariant
}

/**
 * Renders the security settings layout including password management, linked accounts, and active sessions.
 *
 * ChangePassword is rendered when password authentication is enabled; LinkedAccounts is rendered when social providers are present.
 * Each registered auth plugin may contribute `securityCards` (for example delete-user, passkeys).
 *
 * @param className - Optional additional CSS class names for the outer container.
 * @param variant - Card variant forwarded to each security settings card.
 * @returns The security settings container as a JSX element.
 */
export function SecuritySettings({
  className,
  variant
}: SecuritySettingsProps) {
  const { emailAndPassword, plugins, socialProviders } = useAuth()

  return (
    <Box className={cn("w-full flex-col gap-4", className)}>
      {emailAndPassword?.enabled && <ChangePassword variant={variant} />}
      {!!socialProviders?.length && <LinkedAccounts variant={variant} />}
      <ActiveSessions variant={variant} />
      {plugins.flatMap((plugin) =>
        plugin.securityCards?.map((Card) => (
          <Card
            key={getOrganizationCardKey(plugin.id, Card)}
            variant={variant}
          />
        ))
      )}
    </Box>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/settings/security/security-settings.tsx
import { useAuth } from "@better-auth-ui/solid"
import { Show } from "solid-js"
import { ApiKeys } from "@/components/auth/api-key/api-keys"
import { DangerZone } from "@/components/auth/delete-user/danger-zone"
import { ActiveSessionsSettings } from "@/components/auth/settings/security/active-sessions"
import { ChangePasswordSettings } from "@/components/auth/settings/security/change-password"
import { LinkedAccountsSettings } from "@/components/auth/settings/security/linked-accounts"
import { hasAuthPlugin } from "@/components/auth/settings/shared/helpers"
import type { SecurityCardsPlugin } from "@/components/auth/settings/shared/types"
import { cn } from "cn"

export type SecuritySettingsProps = {
  class?: string
}

export function SecuritySettings(props: SecuritySettingsProps = {}) {
  const auth = useAuth()

  return (
    <div class={cn("flex w-full flex-col gap-4 md:gap-6", props.class)}>
      <Show when={auth.emailAndPassword?.enabled}>
        <ChangePasswordSettings
          confirmPassword={auth.emailAndPassword.confirmPassword}
        />
      </Show>

      <Show when={!!auth.socialProviders?.length}>
        <LinkedAccountsSettings />
      </Show>

      <ActiveSessionsSettings />

      <Show when={hasAuthPlugin(auth.plugins, "apiKey")}>
        <ApiKeys />
      </Show>

      <Show when={hasAuthPlugin(auth.plugins, "deleteUser")}>
        <DangerZone />
      </Show>

      {auth.plugins.flatMap((plugin) => {
        const securityCards = (plugin as SecurityCardsPlugin).securityCards as
          | SecurityCardsPlugin["securityCards"]
          | undefined

        return securityCards?.map((SecurityCard) => <SecurityCard />) ?? []
      })}
    </div>
  )
}
