// examples/start-solid-zaidan-example/src/components/auth/phone-number/remove-phone-number-dialog.tsx
import { Show } from "solid-js"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"

export type RemovePhoneNumberDialogProps = {
  cancelLabel: string
  description: string
  isPending: boolean
  label: string
  title: string
  onConfirm: () => void
}

/** Confirm removal because it can disable a sign-in and recovery method. */
export function RemovePhoneNumberDialog(props: RemovePhoneNumberDialogProps) {
  return (
    <AlertDialog>
      <AlertDialogTrigger
        as={Button}
        disabled={props.isPending}
        size="sm"
        variant="outline"
      >
        {props.label}
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{props.title}</AlertDialogTitle>
          <AlertDialogDescription>{props.description}</AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={props.isPending}>
            {props.cancelLabel}
          </AlertDialogCancel>
          <AlertDialogAction
            disabled={props.isPending}
            variant="destructive"
            onClick={props.onConfirm}
          >
            <Show when={props.isPending}>
              <Spinner />
            </Show>
            {props.label}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}

// examples/start-shadcn-example/src/components/auth/phone-number/remove-phone-number-dialog.tsx
"use client"

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"

export type RemovePhoneNumberDialogProps = {
  description: string
  isPending: boolean
  label: string
  title: string
  cancelLabel: string
  onConfirm: () => void
}

/** Confirm removal because it can disable a sign-in and recovery method. */
export function RemovePhoneNumberDialog({
  cancelLabel,
  description,
  isPending,
  label,
  onConfirm,
  title
}: RemovePhoneNumberDialogProps) {
  return (
    <AlertDialog>
      <AlertDialogTrigger asChild>
        <Button type="button" size="sm" variant="outline" disabled={isPending}>
          {label}
        </Button>
      </AlertDialogTrigger>
      <AlertDialogContent>
        <AlertDialogHeader>
          <AlertDialogTitle>{title}</AlertDialogTitle>
          <AlertDialogDescription>{description}</AlertDialogDescription>
        </AlertDialogHeader>
        <AlertDialogFooter>
          <AlertDialogCancel disabled={isPending}>
            {cancelLabel}
          </AlertDialogCancel>
          <AlertDialogAction
            variant="destructive"
            disabled={isPending}
            onClick={onConfirm}
          >
            {isPending && <Spinner />}
            {label}
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  )
}
