// examples/start-solid-zaidan-example/src/components/auth/phone-number/reset-phone-number-password.tsx
import {
  isPasswordCompromisedError,
  validateStringLength
} from "@better-auth-ui/core"
import type { PhoneNumberAuthClient } from "@better-auth-ui/core/plugins/phone-number"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useResetPhoneNumberPassword } from "@better-auth-ui/solid/plugins/phone-number"
import { Show } from "solid-js"
import { toast } from "solid-sonner"

import { OtpField } from "@/components/auth/otp-field"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { FieldGroup } from "@/components/ui/field"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "@/lib/utils"
import { createAuthForm, setAuthFormServerError } from "../auth-form"
import { PasswordStrengthMeter } from "../password-strength-meter"
import { PHONE_NUMBER_RESET_STORAGE_KEY } from "./forgot-phone-number-password"

export type ResetPhoneNumberPasswordProps = {
  class?: string
}

/** Reset a phone credential password with a verification code. */
export function ResetPhoneNumberPassword(props: ResetPhoneNumberPasswordProps) {
  const auth = useAuth()
  const {
    localization,
    otpLength,
    viewPaths: phoneNumberViewPaths
  } = useAuthPlugin(phoneNumberPlugin)
  const storedPhoneNumber =
    typeof sessionStorage === "undefined"
      ? ""
      : (sessionStorage.getItem(PHONE_NUMBER_RESET_STORAGE_KEY) ?? "")
  const resetPassword = useResetPhoneNumberPassword(
    auth.authClient as PhoneNumberAuthClient,
    () => ({
      onError: (error) => {
        // The haveIBeenPwned plugin rejects on the password itself, so it
        // belongs against the field rather than in a toast.
        if (isPasswordCompromisedError(error)) {
          setAuthFormServerError(
            form,
            {
              fields: { password: auth.localization.auth.passwordCompromised }
            },
            auth.localization.auth.passwordCompromised
          )
        }

        form.setFieldValue("code", "")
      },
      onSuccess: () => {
        sessionStorage.removeItem(PHONE_NUMBER_RESET_STORAGE_KEY)
        toast.success(auth.localization.auth.passwordResetSuccess)
        auth.navigate({
          to: `${auth.basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumber}`
        })
      }
    })
  )
  const validatePassword = (value: string) =>
    validateStringLength(value, {
      maxLength: auth.emailAndPassword?.maxPasswordLength,
      maxLengthMessage: auth.localization.auth.tooLong.replace(
        "{{max}}",
        String(auth.emailAndPassword?.maxPasswordLength)
      ),
      minLength: auth.emailAndPassword?.minPasswordLength,
      minLengthMessage: auth.localization.auth.tooShort.replace(
        "{{min}}",
        String(auth.emailAndPassword?.minPasswordLength)
      ),
      requiredMessage: auth.localization.auth.fieldRequired
    })
  const form = createAuthForm(() => ({
    defaultValues: {
      code: "",
      confirmPassword: "",
      password: "",
      phoneNumber: storedPhoneNumber
    },
    onSubmit: async ({ value }) => {
      await resetPassword.mutateAsync({
        phoneNumber: value.phoneNumber,
        otp: value.code,
        newPassword: value.password
      } as Parameters<typeof resetPassword.mutateAsync>[0])
    }
  }))
  const phoneNumber = form.useSelector((state) => state.values.phoneNumber)
  const password = form.useSelector((state) => state.values.password)
  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {localization.resetPassword}
        </CardTitle>
        <Show when={storedPhoneNumber}>
          <CardDescription>
            {localization.codeSentTo.replace("{{phoneNumber}}", phoneNumber())}
          </CardDescription>
        </Show>
      </CardHeader>
      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot aria-label={localization.resetPassword}>
            <FieldGroup>
              <Show when={!storedPhoneNumber}>
                <form.AppField
                  name="phoneNumber"
                  validators={{
                    onChange: ({ value }) =>
                      value.trim()
                        ? undefined
                        : auth.localization.auth.fieldRequired
                  }}
                >
                  {(field) => (
                    <field.AuthFormTextField
                      autocomplete="tel"
                      disabled={resetPassword.isPending}
                      id="reset-phone-number"
                      inputmode="tel"
                      label={localization.phoneNumber}
                      placeholder={localization.phoneNumberPlaceholder}
                      type="tel"
                    />
                  )}
                </form.AppField>
              </Show>
              <form.AppField
                name="code"
                validators={{
                  onChange: ({ value }) =>
                    value.length === otpLength
                      ? undefined
                      : localization.codeLengthMismatch.replace(
                          "{{length}}",
                          String(otpLength)
                        )
                }}
              >
                {(field) => (
                  <OtpField
                    autofocus={Boolean(storedPhoneNumber)}
                    disabled={resetPassword.isPending}
                    id="reset-phone-code"
                    label={localization.phoneCode}
                    length={otpLength}
                    name={field().name}
                    onInput={field().handleChange}
                    value={field().state.value}
                  />
                )}
              </form.AppField>
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) => validatePassword(value)
                }}
              >
                {(field) => (
                  <>
                    <field.AuthFormTextField
                      autocomplete="new-password"
                      disabled={resetPassword.isPending}
                      id="reset-phone-password"
                      label={auth.localization.auth.newPassword}
                      placeholder={
                        auth.localization.auth.newPasswordPlaceholder
                      }
                      type="password"
                    />
                    <PasswordStrengthMeter password={password()} />
                  </>
                )}
              </form.AppField>
              <Show when={auth.emailAndPassword?.confirmPassword}>
                <form.AppField
                  name="confirmPassword"
                  validators={{
                    onChangeListenTo: ["password"],
                    onChange: ({ value }) =>
                      value === password()
                        ? undefined
                        : auth.localization.auth.passwordsDoNotMatch
                  }}
                >
                  {(field) => (
                    <field.AuthFormTextField
                      autocomplete="new-password"
                      disabled={resetPassword.isPending}
                      id="reset-phone-confirm-password"
                      label={auth.localization.auth.confirmPassword}
                      placeholder={
                        auth.localization.auth.confirmPasswordPlaceholder
                      }
                      type="password"
                    />
                  )}
                </form.AppField>
              </Show>
              <form.AuthFormSubmitButton
                class="w-full"
                disabled={resetPassword.isPending}
              >
                {localization.resetPassword}
              </form.AuthFormSubmitButton>
              <form.AuthFormServerError />
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>
      </CardContent>
    </Card>
  )
}

// examples/start-shadcn-example/src/components/auth/phone-number/reset-phone-number-password.tsx
"use client"

import {
  isPasswordCompromisedError,
  validateMatchingValue,
  validateStringLength
} from "@better-auth-ui/core"
import type { PhoneNumberAuthClient } from "@better-auth-ui/core/plugins/phone-number"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useResetPhoneNumberPassword } from "@better-auth-ui/react/plugins/phone-number"
import { useSelector } from "@tanstack/react-form"
import { Eye, EyeOff } from "lucide-react"
import { useEffect, useState } from "react"
import { toast } from "sonner"

import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "cn"
import {
  isAuthFormFieldInvalid,
  setAuthFormServerError,
  useAuthForm
} from "../auth-form"
import { OtpField } from "../otp-field"
import { PasswordStrengthMeter } from "../password-strength-meter"
import { useIsHydrated } from "../use-is-hydrated"
import { PHONE_NUMBER_RESET_STORAGE_KEY } from "./forgot-phone-number-password"

export type ResetPhoneNumberPasswordProps = {
  className?: string
}

/** Reset a phone credential password with the code sent to the user. */
export function ResetPhoneNumberPassword({
  className
}: ResetPhoneNumberPasswordProps) {
  const { authClient, basePaths, emailAndPassword, localization, navigate } =
    useAuth()
  const {
    localization: phoneLocalization,
    otpLength,
    viewPaths: phoneNumberViewPaths
  } = useAuthPlugin(phoneNumberPlugin)
  const isHydrated = useIsHydrated()
  const initialPhoneNumber =
    (isHydrated && sessionStorage.getItem(PHONE_NUMBER_RESET_STORAGE_KEY)) || ""
  const [hasStoredPhoneNumber, setHasStoredPhoneNumber] = useState(
    Boolean(initialPhoneNumber)
  )
  const [isPasswordVisible, setIsPasswordVisible] = useState(false)

  const { mutateAsync: resetPassword, isPending } = useResetPhoneNumberPassword(
    authClient as PhoneNumberAuthClient,
    {
      onError: (error) => {
        // The haveIBeenPwned plugin rejects on the password itself, so it
        // belongs against the field rather than in a toast.
        if (isPasswordCompromisedError(error)) {
          setAuthFormServerError(
            form,
            { fields: { password: localization.auth.passwordCompromised } },
            localization.auth.passwordCompromised
          )
        }

        form.setFieldValue("code", "")
      },
      onSuccess: () => {
        sessionStorage.removeItem(PHONE_NUMBER_RESET_STORAGE_KEY)
        toast.success(localization.auth.passwordResetSuccess)
        navigate({
          to: `${basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumber}`
        })
      }
    }
  )

  const validatePassword = (value: string) =>
    validateStringLength(value, {
      maxLength: emailAndPassword?.maxPasswordLength,
      maxLengthMessage: localization.auth.tooLong.replace(
        "{{max}}",
        String(emailAndPassword?.maxPasswordLength)
      ),
      minLength: emailAndPassword?.minPasswordLength,
      minLengthMessage: localization.auth.tooShort.replace(
        "{{min}}",
        String(emailAndPassword?.minPasswordLength)
      ),
      requiredMessage: localization.auth.fieldRequired
    })

  const form = useAuthForm({
    defaultValues: {
      code: "",
      confirmPassword: "",
      password: "",
      phoneNumber: initialPhoneNumber
    },
    onSubmit: async ({ value }) => {
      await resetPassword({
        phoneNumber: value.phoneNumber,
        otp: value.code,
        newPassword: value.password
      })
    }
  })
  const phoneNumber = useSelector(
    form.store,
    (formState) => formState.values.phoneNumber
  )

  useEffect(() => {
    const stored = sessionStorage.getItem(PHONE_NUMBER_RESET_STORAGE_KEY) ?? ""
    form.setFieldValue("phoneNumber", stored)
    setHasStoredPhoneNumber(Boolean(stored))
  }, [form.setFieldValue])

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl">
          {phoneLocalization.resetPassword}
        </CardTitle>
        {hasStoredPhoneNumber && (
          <CardDescription>
            {phoneLocalization.codeSentTo.replace(
              "{{phoneNumber}}",
              phoneNumber
            )}
          </CardDescription>
        )}
      </CardHeader>
      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot>
            <FieldGroup>
              {!hasStoredPhoneNumber && (
                <form.AppField
                  name="phoneNumber"
                  validators={{
                    onChange: ({ value }) =>
                      value.trim() ? undefined : localization.auth.fieldRequired
                  }}
                >
                  {(field) => (
                    <Field
                      data-invalid={isAuthFormFieldInvalid(field.state.meta)}
                    >
                      <FieldLabel htmlFor="passwordResetPhoneNumber">
                        {phoneLocalization.phoneNumber}
                      </FieldLabel>
                      <Input
                        id="passwordResetPhoneNumber"
                        name={field.name}
                        type="tel"
                        autoComplete="tel"
                        inputMode="tel"
                        value={field.state.value}
                        placeholder={phoneLocalization.phoneNumberPlaceholder}
                        required
                        disabled={isPending}
                        onBlur={field.handleBlur}
                        onChange={(event) =>
                          field.handleChange(event.target.value)
                        }
                        aria-invalid={isAuthFormFieldInvalid(field.state.meta)}
                      />
                      <field.AuthFormFieldError />
                    </Field>
                  )}
                </form.AppField>
              )}

              <form.AppField
                name="code"
                validators={{
                  onChange: ({ value }) =>
                    value.length === otpLength
                      ? undefined
                      : phoneLocalization.codeLengthMismatch.replace(
                          "{{length}}",
                          String(otpLength)
                        )
                }}
              >
                {(field) => (
                  <OtpField
                    autoFocus={hasStoredPhoneNumber}
                    disabled={isPending}
                    label={phoneLocalization.phoneCode}
                    length={otpLength}
                    name="otp"
                    value={field.state.value}
                    onChange={field.handleChange}
                  />
                )}
              </form.AppField>

              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) => validatePassword(value)
                }}
              >
                {(field) => (
                  <Field
                    data-invalid={isAuthFormFieldInvalid(field.state.meta)}
                  >
                    <FieldLabel htmlFor="phoneNumberNewPassword">
                      {localization.auth.newPassword}
                    </FieldLabel>
                    <InputGroup>
                      <InputGroupInput
                        id="phoneNumberNewPassword"
                        name={field.name}
                        type={isPasswordVisible ? "text" : "password"}
                        autoComplete="new-password"
                        value={field.state.value}
                        placeholder={localization.auth.newPasswordPlaceholder}
                        required
                        minLength={emailAndPassword?.minPasswordLength}
                        maxLength={emailAndPassword?.maxPasswordLength}
                        disabled={isPending}
                        onBlur={field.handleBlur}
                        onChange={(event) => {
                          field.handleChange(event.target.value)
                        }}
                        aria-invalid={isAuthFormFieldInvalid(field.state.meta)}
                      />
                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          type="button"
                          size="icon-xs"
                          aria-label={
                            isPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          onClick={() =>
                            setIsPasswordVisible((visible) => !visible)
                          }
                        >
                          {isPasswordVisible ? <EyeOff /> : <Eye />}
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>
                    <field.AuthFormFieldError />

                    <PasswordStrengthMeter password={field.state.value} />
                  </Field>
                )}
              </form.AppField>

              {emailAndPassword?.confirmPassword && (
                <form.AppField
                  name="confirmPassword"
                  validators={{
                    onChangeListenTo: ["password"],
                    onChange: ({ value, fieldApi }) =>
                      validateMatchingValue(
                        value,
                        fieldApi.form.getFieldValue("password"),
                        localization.auth.passwordsDoNotMatch
                      )
                  }}
                >
                  {(field) => (
                    <Field
                      data-invalid={isAuthFormFieldInvalid(field.state.meta)}
                    >
                      <FieldLabel htmlFor="phoneNumberConfirmPassword">
                        {localization.auth.confirmPassword}
                      </FieldLabel>
                      <Input
                        id="phoneNumberConfirmPassword"
                        name={field.name}
                        type="password"
                        autoComplete="new-password"
                        placeholder={
                          localization.auth.confirmPasswordPlaceholder
                        }
                        required
                        minLength={emailAndPassword?.minPasswordLength}
                        maxLength={emailAndPassword?.maxPasswordLength}
                        disabled={isPending}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(event) =>
                          field.handleChange(event.target.value)
                        }
                        aria-invalid={isAuthFormFieldInvalid(field.state.meta)}
                      />

                      <field.AuthFormFieldError />
                    </Field>
                  )}
                </form.AppField>
              )}

              <form.AuthFormSubmitButton disabled={isPending}>
                {phoneLocalization.resetPassword}
              </form.AuthFormSubmitButton>
              <form.AuthFormServerError />
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>
      </CardContent>
    </Card>
  )
}
