// examples/start-solid-zaidan-example/src/components/auth/phone-number/reset-phone-number-password.tsx
import {
  isPasswordCompromisedError,
  validateStringLength
} from "@better-auth-ui/core"
import type { PhoneNumberAuthClient } from "@better-auth-ui/core/plugins/phone-number"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useResetPhoneNumberPassword } from "@better-auth-ui/solid/plugins/phone-number"
import { Show } from "solid-js"
import { toast } from "solid-sonner"

import { OtpField } from "@/components/auth/otp-field"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { FieldGroup } from "@/components/ui/field"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "@/lib/utils"
import { createAuthForm, setAuthFormServerError } from "../auth-form"
import { PasswordStrengthMeter } from "../password-strength-meter"
import { PHONE_NUMBER_RESET_STORAGE_KEY } from "./forgot-phone-number-password"

export type ResetPhoneNumberPasswordProps = {
  class?: string
}

/** Reset a phone credential password with a verification code. */
export function ResetPhoneNumberPassword(props: ResetPhoneNumberPasswordProps) {
  const auth = useAuth()
  const {
    localization,
    otpLength,
    viewPaths: phoneNumberViewPaths
  } = useAuthPlugin(phoneNumberPlugin)
  const storedPhoneNumber =
    typeof sessionStorage === "undefined"
      ? ""
      : (sessionStorage.getItem(PHONE_NUMBER_RESET_STORAGE_KEY) ?? "")
  const resetPassword = useResetPhoneNumberPassword(
    auth.authClient as PhoneNumberAuthClient,
    () => ({
      onError: (error) => {
        // The haveIBeenPwned plugin rejects on the password itself, so it
        // belongs against the field rather than in a toast.
        if (isPasswordCompromisedError(error)) {
          setAuthFormServerError(
            form,
            {
              fields: { password: auth.localization.auth.passwordCompromised }
            },
            auth.localization.auth.passwordCompromised
          )
        }

        form.setFieldValue("code", "")
      },
      onSuccess: () => {
        sessionStorage.removeItem(PHONE_NUMBER_RESET_STORAGE_KEY)
        toast.success(auth.localization.auth.passwordResetSuccess)
        auth.navigate({
          to: `${auth.basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumber}`
        })
      }
    })
  )
  const validatePassword = (value: string) =>
    validateStringLength(value, {
      maxLength: auth.emailAndPassword?.maxPasswordLength,
      maxLengthMessage: auth.localization.auth.tooLong.replace(
        "{{max}}",
        String(auth.emailAndPassword?.maxPasswordLength)
      ),
      minLength: auth.emailAndPassword?.minPasswordLength,
      minLengthMessage: auth.localization.auth.tooShort.replace(
        "{{min}}",
        String(auth.emailAndPassword?.minPasswordLength)
      ),
      requiredMessage: auth.localization.auth.fieldRequired
    })
  const form = createAuthForm(() => ({
    defaultValues: {
      code: "",
      confirmPassword: "",
      password: "",
      phoneNumber: storedPhoneNumber
    },
    onSubmit: async ({ value }) => {
      await resetPassword.mutateAsync({
        phoneNumber: value.phoneNumber,
        otp: value.code,
        newPassword: value.password
      } as Parameters<typeof resetPassword.mutateAsync>[0])
    }
  }))
  const phoneNumber = form.useSelector((state) => state.values.phoneNumber)
  const password = form.useSelector((state) => state.values.password)
  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {localization.resetPassword}
        </CardTitle>
        <Show when={storedPhoneNumber}>
          <CardDescription>
            {localization.codeSentTo.replace("{{phoneNumber}}", phoneNumber())}
          </CardDescription>
        </Show>
      </CardHeader>
      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot aria-label={localization.resetPassword}>
            <FieldGroup>
              <Show when={!storedPhoneNumber}>
                <form.AppField
                  name="phoneNumber"
                  validators={{
                    onChange: ({ value }) =>
                      value.trim()
                        ? undefined
                        : auth.localization.auth.fieldRequired
                  }}
                >
                  {(field) => (
                    <field.AuthFormTextField
                      autocomplete="tel"
                      disabled={resetPassword.isPending}
                      id="reset-phone-number"
                      inputmode="tel"
                      label={localization.phoneNumber}
                      placeholder={localization.phoneNumberPlaceholder}
                      type="tel"
                    />
                  )}
                </form.AppField>
              </Show>
              <form.AppField
                name="code"
                validators={{
                  onChange: ({ value }) =>
                    value.length === otpLength
                      ? undefined
                      : localization.codeLengthMismatch.replace(
                          "{{length}}",
                          String(otpLength)
                        )
                }}
              >
                {(field) => (
                  <OtpField
                    autofocus={Boolean(storedPhoneNumber)}
                    disabled={resetPassword.isPending}
                    id="reset-phone-code"
                    label={localization.phoneCode}
                    length={otpLength}
                    name={field().name}
                    onInput={field().handleChange}
                    value={field().state.value}
                  />
                )}
              </form.AppField>
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) => validatePassword(value)
                }}
              >
                {(field) => (
                  <>
                    <field.AuthFormTextField
                      autocomplete="new-password"
                      disabled={resetPassword.isPending}
                      id="reset-phone-password"
                      label={auth.localization.auth.newPassword}
                      placeholder={
                        auth.localization.auth.newPasswordPlaceholder
                      }
                      type="password"
                    />
                    <PasswordStrengthMeter password={password()} />
                  </>
                )}
              </form.AppField>
              <Show when={auth.emailAndPassword?.confirmPassword}>
                <form.AppField
                  name="confirmPassword"
                  validators={{
                    onChangeListenTo: ["password"],
                    onChange: ({ value }) =>
                      value === password()
                        ? undefined
                        : auth.localization.auth.passwordsDoNotMatch
                  }}
                >
                  {(field) => (
                    <field.AuthFormTextField
                      autocomplete="new-password"
                      disabled={resetPassword.isPending}
                      id="reset-phone-confirm-password"
                      label={auth.localization.auth.confirmPassword}
                      placeholder={
                        auth.localization.auth.confirmPasswordPlaceholder
                      }
                      type="password"
                    />
                  )}
                </form.AppField>
              </Show>
              <form.AuthFormSubmitButton
                class="w-full"
                disabled={resetPassword.isPending}
              >
                {localization.resetPassword}
              </form.AuthFormSubmitButton>
              <form.AuthFormServerError />
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>
      </CardContent>
    </Card>
  )
}

// packages/heroui/src/components/auth/phone-number/reset-phone-number-password.tsx
import {
  isPasswordCompromisedError,
  validateStringLength
} from "@better-auth-ui/core"
import type { PhoneNumberAuthClient } from "@better-auth-ui/core/plugins/phone-number"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useResetPhoneNumberPassword } from "@better-auth-ui/react/plugins/phone-number"
import { Eye, EyeSlash } from "@gravity-ui/icons"
import {
  Button,
  Card,
  type CardProps,
  cn,
  Input,
  InputGroup,
  Label,
  TextField,
  toast,
  useIsHydrated
} from "@heroui/react"
import { useSelector } from "@tanstack/react-form"
import { useEffect, useState } from "react"

import { phoneNumberPlugin } from "../../../lib/auth/phone-number-plugin"
import {
  isAuthFormFieldInvalid,
  setAuthFormServerError,
  useAuthForm
} from "../auth-form"
import { OtpField } from "../otp-field"
import { PasswordStrengthMeter } from "../password-strength-meter"
import { PHONE_NUMBER_RESET_STORAGE_KEY } from "./forgot-phone-number-password"

export type ResetPhoneNumberPasswordProps = {
  className?: string
  variant?: CardProps["variant"]
}

/** Reset a phone credential password with a verification code. */
export function ResetPhoneNumberPassword({
  className,
  variant
}: ResetPhoneNumberPasswordProps) {
  const { authClient, basePaths, emailAndPassword, localization, navigate } =
    useAuth()
  const {
    localization: phoneLocalization,
    otpLength,
    viewPaths: phoneNumberViewPaths
  } = useAuthPlugin(phoneNumberPlugin)
  const isHydrated = useIsHydrated()
  const initialPhoneNumber =
    (isHydrated && sessionStorage.getItem(PHONE_NUMBER_RESET_STORAGE_KEY)) || ""
  const [hasStoredPhoneNumber, setHasStoredPhoneNumber] = useState(
    Boolean(initialPhoneNumber)
  )
  const [isPasswordVisible, setIsPasswordVisible] = useState(false)

  const { mutateAsync: resetPassword, isPending } = useResetPhoneNumberPassword(
    authClient as PhoneNumberAuthClient,
    {
      onError: (error) => {
        // The haveIBeenPwned plugin rejects on the password itself, so
        // it belongs against the field rather than in a toast.
        if (isPasswordCompromisedError(error)) {
          setAuthFormServerError(
            form,
            { fields: { password: localization.auth.passwordCompromised } },
            localization.auth.passwordCompromised
          )
        }
        form.setFieldValue("code", "")
      },
      onSuccess: () => {
        sessionStorage.removeItem(PHONE_NUMBER_RESET_STORAGE_KEY)
        toast.success(localization.auth.passwordResetSuccess)
        navigate({
          to: `${basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumber}`
        })
      }
    }
  )

  const validatePassword = (value: string) =>
    validateStringLength(value, {
      maxLength: emailAndPassword?.maxPasswordLength,
      maxLengthMessage: localization.auth.tooLong.replace(
        "{{max}}",
        String(emailAndPassword?.maxPasswordLength)
      ),
      minLength: emailAndPassword?.minPasswordLength,
      minLengthMessage: localization.auth.tooShort.replace(
        "{{min}}",
        String(emailAndPassword?.minPasswordLength)
      ),
      requiredMessage: localization.auth.fieldRequired
    })

  const form = useAuthForm({
    defaultValues: {
      code: "",
      confirmPassword: "",
      password: "",
      phoneNumber: initialPhoneNumber
    },
    onSubmit: async ({ value }) => {
      await resetPassword({
        phoneNumber: value.phoneNumber,
        otp: value.code,
        newPassword: value.password
      })
    }
  })
  const codeComplete = useSelector(
    form.store,
    (state) => state.values.code.length === otpLength
  )
  const phoneNumber = useSelector(
    form.store,
    (state) => state.values.phoneNumber
  )

  useEffect(() => {
    const stored = sessionStorage.getItem(PHONE_NUMBER_RESET_STORAGE_KEY) ?? ""
    form.setFieldValue("phoneNumber", stored)
    setHasStoredPhoneNumber(Boolean(stored))
  }, [form.setFieldValue])

  return (
    <Card
      className={cn("w-full max-w-sm gap-4 md:p-6", className)}
      variant={variant}
    >
      <Card.Header>
        <Card.Title className="mb-1 text-xl font-semibold">
          {phoneLocalization.resetPassword}
        </Card.Title>
        {hasStoredPhoneNumber && (
          <Card.Description>
            {phoneLocalization.codeSentTo.replace(
              "{{phoneNumber}}",
              phoneNumber
            )}
          </Card.Description>
        )}
      </Card.Header>
      <Card.Content className="gap-4">
        <form.AppForm>
          <form.AuthFormRoot className="flex flex-col gap-4">
            {!hasStoredPhoneNumber && (
              <form.AppField
                name="phoneNumber"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => (
                  <TextField
                    type="tel"
                    autoComplete="tel"
                    value={field.state.value}
                    name={field.name}
                    isDisabled={isPending}
                    isInvalid={isAuthFormFieldInvalid(field.state.meta)}
                    validationBehavior="aria"
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                  >
                    <Label>{phoneLocalization.phoneNumber}</Label>
                    <Input
                      inputMode="tel"
                      placeholder={phoneLocalization.phoneNumberPlaceholder}
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    />
                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>
            )}
            <form.AppField
              name="code"
              validators={{
                onChange: ({ value }) =>
                  value.length === otpLength
                    ? undefined
                    : phoneLocalization.codeLengthMismatch.replace(
                        "{{length}}",
                        String(otpLength)
                      )
              }}
            >
              {(field) => (
                <OtpField
                  autoFocus={hasStoredPhoneNumber}
                  isDisabled={isPending}
                  label={phoneLocalization.phoneCode}
                  length={otpLength}
                  name="otp"
                  value={field.state.value}
                  variant={variant}
                  onChange={field.handleChange}
                />
              )}
            </form.AppField>
            <form.AppField
              name="password"
              validators={{ onChange: ({ value }) => validatePassword(value) }}
            >
              {(field) => (
                <TextField
                  name={field.name}
                  autoComplete="new-password"
                  value={field.state.value}
                  isDisabled={isPending}
                  isInvalid={isAuthFormFieldInvalid(field.state.meta)}
                  validationBehavior="aria"
                  onBlur={field.handleBlur}
                  onChange={field.handleChange}
                >
                  <Label>{localization.auth.newPassword}</Label>
                  <InputGroup
                    variant={
                      variant === "transparent" ? "primary" : "secondary"
                    }
                  >
                    <InputGroup.Input
                      placeholder={localization.auth.newPasswordPlaceholder}
                      type={isPasswordVisible ? "text" : "password"}
                    />
                    <InputGroup.Suffix className="px-0">
                      <Button
                        isIconOnly
                        aria-label={
                          isPasswordVisible
                            ? localization.auth.hidePassword
                            : localization.auth.showPassword
                        }
                        size="sm"
                        variant="ghost"
                        isDisabled={isPending}
                        onPress={() => setIsPasswordVisible(!isPasswordVisible)}
                      >
                        {isPasswordVisible ? <EyeSlash /> : <Eye />}
                      </Button>
                    </InputGroup.Suffix>
                  </InputGroup>
                  <field.AuthFormFieldError />

                  <PasswordStrengthMeter password={field.state.value} />
                </TextField>
              )}
            </form.AppField>
            {emailAndPassword?.confirmPassword && (
              <form.AppField
                name="confirmPassword"
                validators={{
                  onChangeListenTo: ["password"],
                  onChange: ({ value, fieldApi }) =>
                    validatePassword(value) ??
                    (value === fieldApi.form.getFieldValue("password")
                      ? undefined
                      : localization.auth.passwordsDoNotMatch)
                }}
              >
                {(field) => (
                  <TextField
                    name={field.name}
                    autoComplete="new-password"
                    isDisabled={isPending}
                    isInvalid={isAuthFormFieldInvalid(field.state.meta)}
                    validationBehavior="aria"
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={field.handleChange}
                  >
                    <Label>{localization.auth.confirmPassword}</Label>
                    <Input
                      type="password"
                      placeholder={localization.auth.confirmPasswordPlaceholder}
                      variant={
                        variant === "transparent" ? "primary" : "secondary"
                      }
                    />
                    <field.AuthFormFieldError />
                  </TextField>
                )}
              </form.AppField>
            )}
            <form.AuthFormServerError />
            <form.AuthFormSubmitButton
              isPending={isPending}
              className="w-full"
              isDisabled={!codeComplete || isPending}
            >
              {phoneLocalization.resetPassword}
            </form.AuthFormSubmitButton>
          </form.AuthFormRoot>
        </form.AppForm>
      </Card.Content>
    </Card>
  )
}
