// packages/heroui/src/components/auth/username/username-field.tsx
import { getFormFieldErrorMessage } from "@better-auth-ui/core"
import type { UsernameAuthClient } from "@better-auth-ui/core/plugins/username"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useIsUsernameAvailable } from "@better-auth-ui/react/plugins/username"
import { Check, Xmark } from "@gravity-ui/icons"
import {
  FieldError,
  InputGroup,
  Label,
  Spinner,
  TextField
} from "@heroui/react"
import { useDebouncer } from "@tanstack/react-pacer"
import { usernamePlugin } from "../../../lib/auth/username-plugin"
import type { AdditionalFieldProps } from "../additional-field"

/**
 * Renderer for the `username` additional field. Owns availability checking,
 * length limits, and visual indicators. `FieldError` automatically surfaces
 * native validation messages. Availability feedback is shown via the icon and
 * aria-label without affecting the field's invalid state.
 */
export function UsernameField({
  name,
  field,
  value,
  onBlur,
  onChange,
  isInvalid,
  errors,
  isPending,
  variant
}: AdditionalFieldProps) {
  const { authClient } = useAuth()
  const {
    localization,
    minUsernameLength,
    maxUsernameLength,
    isUsernameAvailable: checkAvailability,
    usernamePrefix
  } = useAuthPlugin(usernamePlugin)

  const currentUsername = String(field.defaultValue ?? "")
  const username = typeof value === "string" ? value : ""
  const errorMessage = getFormFieldErrorMessage(errors ?? [])

  const {
    mutate: requestAvailability,
    data: availability,
    error: availabilityError,
    reset: resetAvailability
  } = useIsUsernameAvailable(authClient as UsernameAuthClient, {
    // Bypass global error toast
    onError: () => {}
  })

  const debouncer = useDebouncer(
    (next: string) => {
      const trimmed = next.trim()
      // Skip blank input and the user's own current username (profile view).
      if (!trimmed || trimmed === currentUsername) {
        resetAvailability()
        return
      }

      requestAvailability({ username: trimmed })
    },
    { wait: 500 }
  )

  function handleChange(next: string) {
    onChange(next || null)
    resetAvailability()

    if (checkAvailability) {
      debouncer.maybeExecute(next)
    }
  }

  const isCheckingAvailability =
    !!checkAvailability &&
    !!username.trim() &&
    username.trim() !== currentUsername

  const { localization: authLocalization } = useAuth()

  return (
    <TextField
      name={name}
      type="text"
      autoComplete="username"
      minLength={minUsernameLength}
      maxLength={maxUsernameLength}
      isDisabled={isPending}
      isReadOnly={field.readOnly}
      value={username}
      onBlur={onBlur}
      onChange={handleChange}
      isInvalid={isInvalid}
      validate={(val) => {
        if (!val) {
          if (field.required) return authLocalization.auth.fieldRequired
          return
        }
        if (minUsernameLength && val.length < minUsernameLength)
          return authLocalization.auth.tooShort.replace(
            "{{min}}",
            String(minUsernameLength)
          )
        if (maxUsernameLength && val.length > maxUsernameLength)
          return authLocalization.auth.tooLong.replace(
            "{{max}}",
            String(maxUsernameLength)
          )
      }}
    >
      <Label>{field.label}</Label>

      <InputGroup variant={variant === "transparent" ? "primary" : "secondary"}>
        {usernamePrefix && (
          <InputGroup.Prefix className="pr-1.5 text-muted">
            {usernamePrefix}
          </InputGroup.Prefix>
        )}

        <InputGroup.Input
          placeholder={field.placeholder}
          required={field.required}
        />

        {isCheckingAvailability && (
          <InputGroup.Suffix
            aria-label={
              availability?.available
                ? localization.usernameAvailable
                : availability?.available === false
                  ? localization.usernameTaken
                  : undefined
            }
            className="px-2"
          >
            {availability?.available ? (
              <Check className="text-success" />
            ) : availabilityError || availability?.available === false ? (
              <Xmark className="text-danger" />
            ) : (
              <Spinner size="sm" color="current" />
            )}
          </InputGroup.Suffix>
        )}
      </InputGroup>

      <FieldError>{errorMessage}</FieldError>
    </TextField>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/username/username-field.tsx
import { getFormFieldErrors } from "@better-auth-ui/core"
import type { UsernameAuthClient } from "@better-auth-ui/core/plugins/username"
import { useAuth } from "@better-auth-ui/solid"
import { useIsUsernameAvailable } from "@better-auth-ui/solid/plugins/username"
import { Check, X } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import type { AdditionalFieldProps } from "@/components/auth/additional-field"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput
} from "@/components/ui/input-group"
import { Spinner } from "@/components/ui/spinner"

export function UsernameField(props: AdditionalFieldProps) {
  const auth = useAuth<UsernameAuthClient>()
  const usernamePlugin = () =>
    auth.plugins.find((plugin) => plugin.id === "username") as
      | {
          isUsernameAvailable?: boolean
          localization?: {
            usernameAvailable?: string
            usernameTaken?: string
          }
          usernamePrefix?: string
          maxUsernameLength?: number
          minUsernameLength?: number
        }
      | undefined
  const currentUsername = String(props.field.defaultValue ?? "")
  const username = () => (typeof props.value === "string" ? props.value : "")
  const [nativeError, setNativeError] = createSignal<string>()
  const fieldErrors = () => getFormFieldErrors(props.errors ?? [])
  const availability = useIsUsernameAvailable(auth.authClient, () => ({
    onError: () => undefined
  }))
  const shouldCheckAvailability = () =>
    Boolean(usernamePlugin()?.isUsernameAvailable) &&
    Boolean(username().trim()) &&
    username().trim() !== currentUsername

  const handleInput = (next: string) => {
    props.onChange(next || null)
    setNativeError(undefined)

    if (shouldCheckAvailability()) {
      availability.mutate({ username: next.trim() })
    } else {
      availability.reset()
    }
  }

  return (
    <Field data-invalid={props.isInvalid || Boolean(nativeError())}>
      <FieldLabel for={props.name}>{props.field.label}</FieldLabel>
      <InputGroup>
        <InputGroupInput
          aria-invalid={props.isInvalid || Boolean(nativeError())}
          autocomplete="username"
          disabled={props.isPending}
          id={props.name}
          maxLength={usernamePlugin()?.maxUsernameLength}
          minLength={usernamePlugin()?.minUsernameLength}
          name={props.name}
          onBlur={props.onBlur}
          onInput={(event) => handleInput(event.currentTarget.value)}
          onInvalid={(event) => {
            event.preventDefault()
            setNativeError(event.currentTarget.validationMessage)
          }}
          placeholder={props.field.placeholder}
          readonly={props.field.readOnly}
          required={props.field.required}
          type="text"
          value={username()}
        />
        <Show when={usernamePlugin()?.usernamePrefix}>
          {(usernamePrefix) => (
            <InputGroupAddon align="inline-start">
              {usernamePrefix()}
            </InputGroupAddon>
          )}
        </Show>
        <Show when={shouldCheckAvailability()}>
          <InputGroupAddon
            align="inline-end"
            aria-label={
              availability.data?.available
                ? usernamePlugin()?.localization?.usernameAvailable
                : availability.data?.available === false
                  ? usernamePlugin()?.localization?.usernameTaken
                  : undefined
            }
            role="status"
          >
            {availability.data?.available ? (
              <Check class="size-4" />
            ) : availability.error || availability.data?.available === false ? (
              <X class="size-4 text-destructive" />
            ) : (
              <Spinner />
            )}
          </InputGroupAddon>
        </Show>
      </InputGroup>
      <FieldError errors={fieldErrors()}>{nativeError()}</FieldError>
    </Field>
  )
}
