// examples/start-solid-zaidan-example/src/components/auth/settings/security/fresh-session-prompt.tsx
import { validateStringLength } from "@better-auth-ui/core"
import { isTwoFactorRedirect } from "@better-auth-ui/core/plugins/two-factor"
import { useAuth, useSession, useSignInEmail } from "@better-auth-ui/solid"
import { Show } from "solid-js"
import { Button } from "@/components/ui/button"
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { useSignInContinuation } from "@/lib/auth/use-sign-in-continuation"
import { createAuthForm, isAuthFormFieldInvalid } from "../../auth-form"

export interface FreshSessionPromptProps {
  onFresh: () => unknown | Promise<unknown>
}

export function FreshSessionPrompt(props: FreshSessionPromptProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const continueSignIn = useSignInContinuation()
  const signIn = useSignInEmail(auth.authClient, () => ({
    meta: { errorPresentation: "inline" },
    onError: () => form.setFieldValue("password", ""),
    onSuccess: async (data) => {
      if (isTwoFactorRedirect(data)) {
        continueSignIn(data)
        return
      }
      form.setFieldValue("password", "")
      await props.onFresh()
    }
  }))

  const form = createAuthForm(() => ({
    defaultValues: { password: "" },
    onSubmit: async ({ value }) => {
      const email = session.data?.user.email
      if (!email) return
      await signIn.mutateAsync({ email, password: value.password })
    }
  }))

  return (
    <div class="p-4">
      <FieldGroup class="gap-4">
        <div class="flex flex-col gap-1">
          <h3 class="text-sm font-medium">
            {auth.localization.settings.freshSessionTitle}
          </h3>
          <FieldDescription>
            {auth.localization.settings.freshSessionDescription}
          </FieldDescription>
        </div>
        <Show
          fallback={
            <Button
              onClick={() =>
                auth.navigate({
                  to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
                })
              }
            >
              {auth.localization.settings.freshSessionSignIn}
            </Button>
          }
          when={auth.emailAndPassword?.enabled}
        >
          <form.AppForm>
            <form.AuthFormRoot class="flex flex-col gap-3">
              <form.AppField
                name="password"
                validators={{
                  onChange: ({ value }) =>
                    validateStringLength(value, {
                      requiredMessage: auth.localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => (
                  <Field
                    data-invalid={isAuthFormFieldInvalid(field().state.meta)}
                  >
                    <FieldLabel for="fresh-session-password">
                      {auth.localization.auth.password}
                    </FieldLabel>
                    <Input
                      id="fresh-session-password"
                      autocomplete="current-password"
                      disabled={signIn.isPending}
                      name={field().name}
                      value={field().state.value}
                      onBlur={field().handleBlur}
                      onInput={(event) =>
                        field().handleChange(event.currentTarget.value)
                      }
                      type="password"
                    />
                    <field.AuthFormFieldError />
                  </Field>
                )}
              </form.AppField>
              <form.AuthFormServerError />
              <form.AuthFormSubmitButton disabled={signIn.isPending}>
                {auth.localization.settings.freshSessionSubmit}
              </form.AuthFormSubmitButton>
            </form.AuthFormRoot>
          </form.AppForm>
        </Show>
      </FieldGroup>
    </div>
  )
}

// apps/docs/src/components/auth/settings/security/fresh-session-prompt.tsx
"use client"

import { isTwoFactorRedirect } from "@better-auth-ui/core/plugins/two-factor"
import { useAuth, useSession, useSignInEmail } from "@better-auth-ui/react"
import { Button } from "@/components/ui/button"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { useSignInContinuation } from "@/lib/auth/use-sign-in-continuation"
import { useAuthForm } from "../../auth-form"

export interface FreshSessionPromptProps {
  onFresh: () => unknown | Promise<unknown>
}

export function FreshSessionPrompt({ onFresh }: FreshSessionPromptProps) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const continueSignIn = useSignInContinuation()
  const signIn = useSignInEmail(auth.authClient, {
    meta: { errorPresentation: "inline" },
    onError: () => form.reset(),
    onSuccess: async (data) => {
      if (isTwoFactorRedirect(data)) {
        continueSignIn(data)
        return
      }
      form.reset()
      await onFresh()
    }
  })
  const form = useAuthForm({
    defaultValues: { password: "" },
    onSubmit: async ({ value }) => {
      const email = session.data?.user.email
      if (email) await signIn.mutateAsync({ email, password: value.password })
    }
  })

  return (
    <div className="p-4">
      <FieldGroup className="gap-4">
        <div className="flex flex-col gap-1">
          <h3 className="text-sm font-medium">
            {auth.localization.settings.freshSessionTitle}
          </h3>
          <FieldDescription>
            {auth.localization.settings.freshSessionDescription}
          </FieldDescription>
        </div>
        {auth.emailAndPassword?.enabled ? (
          <form.AppForm>
            <form.AuthFormRoot className="flex flex-col gap-3">
              <form.AppField name="password">
                {(field) => (
                  <Field data-invalid={signIn.isError}>
                    <FieldLabel htmlFor="fresh-session-password">
                      {auth.localization.auth.password}
                    </FieldLabel>
                    <Input
                      id="fresh-session-password"
                      autoComplete="current-password"
                      disabled={signIn.isPending}
                      name={field.name}
                      value={field.state.value}
                      onBlur={field.handleBlur}
                      onChange={(event) =>
                        field.handleChange(event.target.value)
                      }
                      type="password"
                      required
                    />
                    {signIn.error && (
                      <FieldError>
                        {signIn.error.error?.message ?? signIn.error.message}
                      </FieldError>
                    )}
                  </Field>
                )}
              </form.AppField>
              <form.AuthFormSubmitButton disabled={signIn.isPending}>
                {signIn.isPending && <Spinner />}
                {auth.localization.settings.freshSessionSubmit}
              </form.AuthFormSubmitButton>
            </form.AuthFormRoot>
          </form.AppForm>
        ) : (
          <Button
            onClick={() =>
              auth.navigate({
                to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
              })
            }
          >
            {auth.localization.settings.freshSessionSignIn}
          </Button>
        )}
      </FieldGroup>
    </div>
  )
}
