// examples/start-solid-zaidan-example/src/components/ui/field.tsx
import { cva, type VariantProps } from "class-variance-authority"
import type { ComponentProps, JSX } from "solid-js"
import { createMemo, For, Show, splitProps } from "solid-js"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"

type FieldSetProps = ComponentProps<"fieldset"> & {
  class?: string | undefined
}

const FieldSet = (props: FieldSetProps) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <fieldset
      data-slot="field-set"
      class={cn("z-field-set flex flex-col", local.class)}
      {...others}
    />
  )
}

type FieldLegendProps = ComponentProps<"legend"> & {
  class?: string | undefined
  variant?: "legend" | "label"
}

const FieldLegend = (props: FieldLegendProps) => {
  const [local, others] = splitProps(props, ["class", "variant"])
  return (
    <legend
      data-slot="field-legend"
      data-variant={local.variant ?? "legend"}
      class={cn("z-field-legend", local.class)}
      {...others}
    />
  )
}

type FieldGroupProps = ComponentProps<"div"> & {
  class?: string | undefined
}

const FieldGroup = (props: FieldGroupProps) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <div
      data-slot="field-group"
      class={cn(
        "group/field-group @container/field-group z-field-group flex w-full flex-col",
        local.class
      )}
      {...others}
    />
  )
}

const fieldVariants = cva("group/field z-field flex w-full", {
  variants: {
    orientation: {
      vertical:
        "z-field-orientation-vertical flex-col *:w-full [&>.sr-only]:w-auto",
      horizontal:
        "z-field-orientation-horizontal flex-row items-center has-[>[data-slot=field-content]]:items-start *:data-[slot=field-label]:flex-auto has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
      responsive:
        "z-field-orientation-responsive @md/field-group:flex-row flex-col @md/field-group:items-center *:w-full @md/field-group:*:w-auto @md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:*:data-[slot=field-label]:flex-auto [&>.sr-only]:w-auto @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px"
    }
  },
  defaultVariants: {
    orientation: "vertical"
  }
})

type FieldProps = ComponentProps<"div"> &
  VariantProps<typeof fieldVariants> & {
    class?: string | undefined
  }

const Field = (props: FieldProps) => {
  const [local, others] = splitProps(props, ["class", "orientation"])
  return (
    // Role="group" is intentional per shadcn design for accessibility.
    <div
      role="group"
      data-slot="field"
      data-orientation={local.orientation ?? "vertical"}
      class={cn(fieldVariants({ orientation: local.orientation }), local.class)}
      {...others}
    />
  )
}

type FieldContentProps = ComponentProps<"div"> & {
  class?: string | undefined
}

const FieldContent = (props: FieldContentProps) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <div
      data-slot="field-content"
      class={cn(
        "group/field-content z-field-content flex flex-1 flex-col leading-snug",
        local.class
      )}
      {...others}
    />
  )
}

type FieldLabelProps = ComponentProps<typeof Label> & {
  class?: string | undefined
}

const FieldLabel = (props: FieldLabelProps) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <Label
      data-slot="field-label"
      class={cn(
        "group/field-label peer/field-label z-field-label flex w-fit leading-snug",
        "has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col",
        local.class
      )}
      {...others}
    />
  )
}

type FieldTitleProps = ComponentProps<"div"> & {
  class?: string | undefined
}

const FieldTitle = (props: FieldTitleProps) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <div
      data-slot="field-label"
      class={cn(
        "z-field-title z-font-heading flex w-fit items-center leading-snug",
        local.class
      )}
      {...others}
    />
  )
}

type FieldDescriptionProps = ComponentProps<"p"> & {
  class?: string | undefined
}

const FieldDescription = (props: FieldDescriptionProps) => {
  const [local, others] = splitProps(props, ["class"])
  return (
    <p
      data-slot="field-description"
      class={cn(
        "z-field-description font-normal leading-normal group-has-data-[orientation=horizontal]/field:text-balance",
        "nth-last-2:-mt-1 last:mt-0",
        "[&>a:hover]:text-primary [&>a]:underline [&>a]:underline-offset-4",
        local.class
      )}
      {...others}
    />
  )
}

type FieldSeparatorProps = ComponentProps<"div"> & {
  class?: string | undefined
  children?: JSX.Element
}

const FieldSeparator = (props: FieldSeparatorProps) => {
  const [local, others] = splitProps(props, ["class", "children"])
  return (
    <div
      data-slot="field-separator"
      data-content={!!local.children}
      class={cn("relative z-field-separator", local.class)}
      {...others}
    >
      <Separator class="absolute inset-0 top-1/2" />
      <Show when={local.children}>
        <span
          class="relative z-field-separator-content mx-auto block w-fit bg-background"
          data-slot="field-separator-content"
        >
          {local.children}
        </span>
      </Show>
    </div>
  )
}

type FieldErrorProps = ComponentProps<"div"> & {
  class?: string | undefined
  children?: JSX.Element
  errors?: Array<{ message?: string } | undefined>
}

const FieldError = (props: FieldErrorProps) => {
  const [local, others] = splitProps(props, ["class", "children", "errors"])

  const content = createMemo(() => {
    if (local.children) {
      return local.children
    }

    if (!local.errors?.length) {
      return null
    }

    const uniqueErrors = [
      ...new Map(local.errors.map((error) => [error?.message, error])).values()
    ]

    if (uniqueErrors?.length === 1) {
      return uniqueErrors[0]?.message
    }

    return (
      <ul class="ml-4 flex list-disc flex-col gap-1">
        <For each={uniqueErrors}>
          {(error) => (
            <Show when={error?.message}>
              <li>{error?.message}</li>
            </Show>
          )}
        </For>
      </ul>
    )
  })

  return (
    <Show when={content()}>
      <div
        role="alert"
        data-slot="field-error"
        class={cn("z-field-error font-normal", local.class)}
        {...others}
      >
        {content()}
      </div>
    </Show>
  )
}

export {
  Field,
  FieldContent,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLabel,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldTitle,
  fieldVariants
}

// examples/next-shadcn-registry-example/src/components/ui/field.tsx
"use client"

import { useMemo } from "react"
import { cva, type VariantProps } from "class-variance-authority"

import { cn } from "@/lib/utils"
import { Label } from "@/components/ui/label"
import { Separator } from "@/components/ui/separator"

/**
 * Renders a styled fieldset container for grouping related form fields.
 *
 * Adds a `data-slot="field-set"` attribute and applies responsive layout classes;
 * merges any provided `className` with the component's default spacing and gap rules.
 *
 * @returns A `fieldset` element with `data-slot="field-set"` and the combined `className`
 */
function FieldSet({ className, ...props }: React.ComponentProps<"fieldset">) {
  return (
    <fieldset
      data-slot="field-set"
      className={cn(
        "flex flex-col gap-6",
        "has-[>[data-slot=checkbox-group]]:gap-3 has-[>[data-slot=radio-group]]:gap-3",
        className
      )}
      {...props}
    />
  )
}

/**
 * Render a fieldset legend element with variant-controlled styling.
 *
 * @param variant - Controls visual variant: `"legend"` (larger text) or `"label"` (smaller text). Defaults to `"legend"`.
 * @returns A `legend` element with `data-slot="field-legend"`, the `data-variant` attribute, and merged styling classes.
 */
function FieldLegend({
  className,
  variant = "legend",
  ...props
}: React.ComponentProps<"legend"> & { variant?: "legend" | "label" }) {
  return (
    <legend
      data-slot="field-legend"
      data-variant={variant}
      className={cn(
        "mb-3 font-medium",
        "data-[variant=legend]:text-base",
        "data-[variant=label]:text-sm",
        className
      )}
      {...props}
    />
  )
}

/**
 * Renders a container div for grouping related form fields and applies the component's layout and responsive spacing classes.
 *
 * @param className - Optional additional classes to merge with the component's default layout and spacing classes
 * @returns A div element used to group related fields with consistent spacing and responsive behavior
 */
function FieldGroup({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="field-group"
      className={cn(
        "group/field-group @container/field-group flex w-full flex-col gap-7 data-[slot=checkbox-group]:gap-3 [&>[data-slot=field-group]]:gap-4",
        className
      )}
      {...props}
    />
  )
}

const fieldVariants = cva(
  "group/field flex w-full gap-3 data-[invalid=true]:text-destructive",
  {
    variants: {
      orientation: {
        vertical: ["flex-col [&>*]:w-full [&>.sr-only]:w-auto"],
        horizontal: [
          "flex-row items-center",
          "[&>[data-slot=field-label]]:flex-auto",
          "has-[>[data-slot=field-content]]:items-start has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        ],
        responsive: [
          "flex-col [&>*]:w-full [&>.sr-only]:w-auto @md/field-group:flex-row @md/field-group:items-center @md/field-group:[&>*]:w-auto",
          "@md/field-group:[&>[data-slot=field-label]]:flex-auto",
          "@md/field-group:has-[>[data-slot=field-content]]:items-start @md/field-group:has-[>[data-slot=field-content]]:[&>[role=checkbox],[role=radio]]:mt-px",
        ],
      },
    },
    defaultVariants: {
      orientation: "vertical",
    },
  }
)

/**
 * Renders a grouped field container that applies orientation-based styling and slot attributes.
 *
 * @param orientation - Layout orientation for the field; either `"vertical"` or `"horizontal"`. Defaults to `"vertical"`.
 * @returns The field container div with role="group", data-slot="field", a data-orientation attribute, and computed classes for the requested orientation.
 */
function Field({
  className,
  orientation = "vertical",
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof fieldVariants>) {
  return (
    <div
      role="group"
      data-slot="field"
      data-orientation={orientation}
      className={cn(fieldVariants({ orientation }), className)}
      {...props}
    />
  )
}

/**
 * Renders the content container for a Field, providing a flexible, vertically stacked region for inputs and related elements.
 *
 * @param props - Standard `div` props; `className` is merged with the component's layout classes.
 * @returns A `div` element with `data-slot="field-content"` and classes that create a flexible, columnar content area.
 */
function FieldContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="field-content"
      className={cn(
        "group/field-content flex flex-1 flex-col gap-1.5 leading-snug",
        className
      )}
      {...props}
    />
  )
}

/**
 * Renders a Label configured as the field's label slot with the component's default styling.
 *
 * @param className - Additional class names that are merged with the component's default styles
 * @param props - Remaining props forwarded to the underlying `Label` component
 * @returns A `Label` element set up for use as a field label (includes `data-slot="field-label"` and merged styling)
 */
function FieldLabel({
  className,
  ...props
}: React.ComponentProps<typeof Label>) {
  return (
    <Label
      data-slot="field-label"
      className={cn(
        "group/field-label peer/field-label flex w-fit gap-2 leading-snug group-data-[disabled=true]/field:opacity-50",
        "has-[>[data-slot=field]]:w-full has-[>[data-slot=field]]:flex-col has-[>[data-slot=field]]:rounded-md has-[>[data-slot=field]]:border [&>*]:data-[slot=field]:p-4",
        "has-data-[state=checked]:bg-primary/5 has-data-[state=checked]:border-primary dark:has-data-[state=checked]:bg-primary/10",
        className
      )}
      {...props}
    />
  )
}

/**
 * Renders the field's title container with compact, left-aligned styling.
 *
 * @returns The title container element for use within a Field
 */
function FieldTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="field-label"
      className={cn(
        "flex w-fit items-center gap-2 text-sm leading-snug font-medium group-data-[disabled=true]/field:opacity-50",
        className
      )}
      {...props}
    />
  )
}

/**
 * Renders the description text for a field with contextual, responsive styling.
 *
 * @returns A paragraph element styled as the field description
 */
function FieldDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="field-description"
      className={cn(
        "text-muted-foreground text-sm leading-normal font-normal group-has-[[data-orientation=horizontal]]/field:text-balance",
        "last:mt-0 nth-last-2:-mt-1 [[data-variant=legend]+&]:-mt-1.5",
        "[&>a:hover]:text-primary [&>a]:underline [&>a]:underline-offset-4",
        className
      )}
      {...props}
    />
  )
}

/**
 * Render a horizontal separator with optional centered content.
 *
 * When `children` is provided, the children are displayed centered above the divider;
 * otherwise only the divider line is rendered.
 *
 * @param children - Content to display centered above the separator; if omitted, no content is shown
 */
function FieldSeparator({
  children,
  className,
  ...props
}: React.ComponentProps<"div"> & {
  children?: React.ReactNode
}) {
  return (
    <div
      data-slot="field-separator"
      data-content={!!children}
      className={cn(
        "relative -my-2 h-5 text-sm group-data-[variant=outline]/field-group:-mb-2",
        className
      )}
      {...props}
    >
      <Separator className="absolute inset-0 top-1/2" />
      {children && (
        <span
          className="bg-background text-muted-foreground relative mx-auto block w-fit px-2"
          data-slot="field-separator-content"
        >
          {children}
        </span>
      )}
    </div>
  )
}

/**
 * Render field error messages or provided custom content.
 *
 * When `children` is provided it is rendered verbatim. Otherwise, deduplicates
 * error messages from `errors` and renders a single message or a list of messages.
 *
 * @param errors - Optional array of error objects; each error's `message` is used for display.
 * @returns The rendered error element (with role="alert") or `null` when there is no content to show.
 */
function FieldError({
  className,
  children,
  errors,
  ...props
}: React.ComponentProps<"div"> & {
  errors?: Array<{ message?: string } | undefined>
}) {
  const content = useMemo(() => {
    if (children) {
      return children
    }

    if (!errors?.length) {
      return null
    }

    const uniqueErrors = [
      ...new Map(errors.map((error) => [error?.message, error])).values(),
    ]

    if (uniqueErrors?.length == 1) {
      return uniqueErrors[0]?.message
    }

    return (
      <ul className="ml-4 flex list-disc flex-col gap-1">
        {uniqueErrors.map(
          (error, index) =>
            error?.message && <li key={index}>{error.message}</li>
        )}
      </ul>
    )
  }, [children, errors])

  if (!content) {
    return null
  }

  return (
    <div
      role="alert"
      data-slot="field-error"
      className={cn("text-destructive text-sm font-normal", className)}
      {...props}
    >
      {content}
    </div>
  )
}

export {
  Field,
  FieldLabel,
  FieldDescription,
  FieldError,
  FieldGroup,
  FieldLegend,
  FieldSeparator,
  FieldSet,
  FieldContent,
  FieldTitle,
}
