// examples/start-solid-zaidan-example/src/components/auth/siwe/sign-in-ethereum-button.tsx
import {
  type AuthView,
  authMutationKeys,
  validateEmailAddress
} from "@better-auth-ui/core"
import {
  type SiweAuthClient,
  siweMutationKeys
} from "@better-auth-ui/core/plugins/siwe"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useSignInSiwe } from "@better-auth-ui/solid/plugins/siwe"
import { useIsMutating } from "@tanstack/solid-query"
import { Wallet } from "lucide-solid"
import { createSignal, Show } from "solid-js"

import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldDescription, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { siwePlugin } from "@/lib/auth/siwe-plugin"
import { cn } from "cn"
import { createAuthForm, isAuthFormFieldInvalid } from "../auth-form"

export type SignInEthereumButtonProps = {
  /** @remarks `AuthView` */
  view?: AuthView
}

/**
 * "Continue with Ethereum" button backed by Better Auth's SIWE plugin.
 *
 * Signs straight in when the plugin's `email` mode is `"none"`. Otherwise it
 * collects an address-linked email first, because the server needs one to
 * create the account.
 */
export function SignInEthereumButton(props: SignInEthereumButtonProps) {
  const auth = useAuth<SiweAuthClient>()
  const plugin = useAuthPlugin(siwePlugin)
  const [open, setOpen] = createSignal(false)

  const signIn = useSignInSiwe(auth.authClient, () => ({
    connector: plugin.connector,
    domain: plugin.domain,
    uri: plugin.uri,
    statement: plugin.statement
  }))

  const signInMutating = useIsMutating(() => ({
    mutationKey: authMutationKeys.signIn.all
  }))
  const signUpMutating = useIsMutating(() => ({
    mutationKey: authMutationKeys.signUp.all
  }))
  const siweMutating = useIsMutating(() => ({
    mutationKey: siweMutationKeys.all
  }))
  const isPending = () =>
    signInMutating() + signUpMutating() + siweMutating() > 0

  const complete = async (email?: string) => {
    await signIn.mutateAsync(email ? { email } : undefined, {
      onSuccess: () => {
        setOpen(false)
        auth.navigate({ to: auth.redirectTo })
      }
    })
  }

  const form = createAuthForm(() => ({
    defaultValues: { email: "" },
    onSubmit: async ({ value }) => complete(value.email.trim() || undefined)
  }))

  return (
    <Show when={props.view !== "signUp"}>
      <Button
        class={cn("w-full", isPending() && "pointer-events-none")}
        disabled={isPending()}
        onClick={() =>
          plugin.email === "none"
            ? void complete().catch(() => undefined)
            : setOpen(true)
        }
        type="button"
        variant="outline"
      >
        <Show
          fallback={<Wallet data-icon="inline-start" />}
          when={signIn.isPending}
        >
          <Spinner data-icon="inline-start" />
        </Show>
        {plugin.localization.continueWithEthereum}
      </Button>

      <Dialog onOpenChange={setOpen} open={open()}>
        <DialogContent>
          <form.AppForm>
            <form.AuthFormRoot class="flex flex-col gap-6">
              <DialogHeader>
                <DialogTitle>
                  {plugin.localization.continueWithEthereum}
                </DialogTitle>
                <DialogDescription>
                  {plugin.localization.emailDescription}
                </DialogDescription>
              </DialogHeader>

              <form.AppField
                name="email"
                validators={{
                  onChange: ({ value }) =>
                    !value && plugin.email !== "required"
                      ? undefined
                      : validateEmailAddress(value, {
                          invalidMessage: auth.localization.auth.invalidEmail,
                          requiredMessage: auth.localization.auth.fieldRequired
                        })
                }}
              >
                {(field) => (
                  <Field
                    data-invalid={isAuthFormFieldInvalid(field().state.meta)}
                  >
                    <FieldLabel for="siwe-email">
                      {plugin.email === "required"
                        ? plugin.localization.email
                        : plugin.localization.emailOptional}
                    </FieldLabel>
                    <Input
                      autocomplete="email"
                      disabled={signIn.isPending}
                      id="siwe-email"
                      name={field().name}
                      type="email"
                      value={field().state.value}
                      onBlur={field().handleBlur}
                      onInput={(event) =>
                        field().handleChange(event.currentTarget.value)
                      }
                    />
                    <FieldDescription>
                      {plugin.localization.emailDescription}
                    </FieldDescription>
                    <field.AuthFormFieldError />
                  </Field>
                )}
              </form.AppField>

              <DialogFooter>
                <Button
                  disabled={signIn.isPending}
                  onClick={() => setOpen(false)}
                  type="button"
                  variant="outline"
                >
                  {auth.localization.settings.cancel}
                </Button>
                <form.AuthFormSubmitButton
                  isPending={signIn.isPending}
                  disabled={signIn.isPending}
                >
                  {plugin.localization.signMessage}
                </form.AuthFormSubmitButton>
              </DialogFooter>
              <form.AuthFormServerError />
            </form.AuthFormRoot>
          </form.AppForm>
        </DialogContent>
      </Dialog>
    </Show>
  )
}

// packages/heroui/src/components/auth/siwe/sign-in-ethereum-button.tsx
"use client"

import {
  type AuthView,
  authMutationKeys,
  validateEmailAddress
} from "@better-auth-ui/core"
import {
  type SiweAuthClient,
  siweMutationKeys
} from "@better-auth-ui/core/plugins/siwe"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useSignInSiwe } from "@better-auth-ui/react/plugins/siwe"
import { Wallet } from "@gravity-ui/icons"
import { Button, Input, Label, Modal, Spinner, TextField } from "@heroui/react"
import { useIsMutating } from "@tanstack/react-query"
import { useState } from "react"

import { siwePlugin } from "../../../lib/auth/siwe-plugin"
import { isAuthFormFieldInvalid, useAuthForm } from "../auth-form"

export type SignInEthereumButtonProps = {
  view?: AuthView
}

export function SignInEthereumButton({ view }: SignInEthereumButtonProps) {
  const { authClient, localization, navigate, redirectTo } = useAuth()
  const plugin = useAuthPlugin(siwePlugin)
  const [isOpen, setIsOpen] = useState(false)
  const signIn = useSignInSiwe(authClient as SiweAuthClient, {
    connector: plugin.connector,
    domain: plugin.domain,
    uri: plugin.uri,
    statement: plugin.statement
  })
  const authPending =
    useIsMutating({ mutationKey: authMutationKeys.signIn.all }) +
      useIsMutating({ mutationKey: authMutationKeys.signUp.all }) +
      useIsMutating({ mutationKey: siweMutationKeys.all }) >
    0

  const completeSignIn = async (email?: string) => {
    await signIn.mutateAsync(email ? { email } : undefined, {
      onSuccess: () => {
        setIsOpen(false)
        navigate({ to: redirectTo })
      }
    })
  }

  const handlePress = () => {
    if (plugin.email === "none") {
      void completeSignIn().catch(() => undefined)
    } else setIsOpen(true)
  }

  const form = useAuthForm({
    defaultValues: { email: "" },
    onSubmit: async ({ value }) => {
      const email = value.email.trim()
      await completeSignIn(email || undefined)
    }
  })

  if (view === "signUp") return null

  return (
    <>
      <Button
        className="w-full"
        variant="tertiary"
        isDisabled={authPending}
        isPending={signIn.isPending}
        onPress={handlePress}
      >
        {signIn.isPending ? <Spinner color="current" size="sm" /> : <Wallet />}
        {plugin.localization.continueWithEthereum}
      </Button>

      <Modal.Backdrop isOpen={isOpen} onOpenChange={setIsOpen}>
        <Modal.Container>
          <Modal.Dialog className="sm:max-w-md">
            <form.AppForm>
              <form.AuthFormRoot>
                <Modal.CloseTrigger />
                <Modal.Header>
                  <Modal.Icon className="bg-accent-soft text-accent-soft-foreground">
                    <Wallet />
                  </Modal.Icon>
                  <Modal.Heading>
                    {plugin.localization.continueWithEthereum}
                  </Modal.Heading>
                  <p className="mt-1.5 text-muted text-sm">
                    {plugin.localization.emailDescription}
                  </p>
                </Modal.Header>
                <Modal.Body className="overflow-visible">
                  <form.AppField
                    name="email"
                    validators={
                      plugin.email === "required"
                        ? {
                            onChange: ({ value }) =>
                              validateEmailAddress(value, {
                                invalidMessage: localization.auth.invalidEmail,
                                requiredMessage: localization.auth.fieldRequired
                              })
                          }
                        : undefined
                    }
                  >
                    {(field) => (
                      <TextField
                        className="w-full"
                        isInvalid={isAuthFormFieldInvalid(field.state.meta)}
                        name={field.name}
                        type="email"
                        isRequired={plugin.email === "required"}
                        isDisabled={signIn.isPending}
                        variant="secondary"
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={field.handleChange}
                      >
                        <Label>
                          {plugin.email === "required"
                            ? plugin.localization.email
                            : plugin.localization.emailOptional}
                        </Label>
                        <Input autoFocus autoComplete="email" />
                        <field.AuthFormFieldError />
                      </TextField>
                    )}
                  </form.AppField>
                  <form.AuthFormServerError />
                </Modal.Body>
                <Modal.Footer>
                  <Button
                    slot="close"
                    variant="tertiary"
                    isDisabled={signIn.isPending}
                  >
                    {localization.settings.cancel}
                  </Button>
                  <form.AuthFormSubmitButton
                    isPending={signIn.isPending}
                    isDisabled={signIn.isPending}
                  >
                    {plugin.localization.signMessage}
                  </form.AuthFormSubmitButton>
                </Modal.Footer>
              </form.AuthFormRoot>
            </form.AppForm>
          </Modal.Dialog>
        </Modal.Container>
      </Modal.Backdrop>
    </>
  )
}
