// examples/start-solid-zaidan-example/src/components/auth/settings/security/change-password.tsx
import { getViewURL, isPasswordCompromisedError } from "@better-auth-ui/core"
import {
  useAuth,
  useChangePassword,
  useListAccounts,
  useRequestPasswordReset,
  useSession
} from "@better-auth-ui/solid"
import { createForm } from "@tanstack/solid-form"
import type { BetterFetchError } from "better-auth/client"
import { Eye, EyeOff } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { OpenEmailButton } from "@/components/auth/open-email-button"
import { PasswordStrengthMeter } from "@/components/auth/password-strength-meter"
import type { ChangePasswordFieldErrors } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Skeleton } from "@/components/ui/skeleton"
import { cn } from "@/lib/utils"

function ChangePasswordSkeletonInput() {
  return (
    <Skeleton>
      <Input class="invisible" />
    </Skeleton>
  )
}

export type ChangePasswordSettingsProps = {
  class?: string
  confirmPassword?: boolean
}

export function ChangePasswordSettings(
  props: ChangePasswordSettingsProps = {}
) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const userId = () => session.data?.user.id
  const linkedAccounts = useListAccounts(auth.authClient, () => ({
    enabled: !import.meta.env.SSR && Boolean(userId())
  }))
  const hasCredentialAccount = () =>
    linkedAccounts.data?.some(
      (account: { providerId?: string }) => account.providerId === "credential"
    )
  const requestPasswordReset = useRequestPasswordReset(auth.authClient)
  const changePassword = useChangePassword(auth.authClient, () => ({
    onError: (error: BetterFetchError) => {
      form.reset()

      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setPasswordFieldError(
          "newPassword",
          auth.localization.auth.passwordCompromised
        )
        return
      }

      toast.error(error.error?.message || error.message)
    },
    onSuccess: () => {
      form.reset()
      toast.success(auth.localization.settings.changePasswordSuccess)
    }
  }))
  const [isCurrentPasswordVisible, setIsCurrentPasswordVisible] =
    createSignal(false)
  const [isNewPasswordVisible, setIsNewPasswordVisible] = createSignal(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    createSignal(false)
  const [fieldErrors, setFieldErrors] = createSignal<ChangePasswordFieldErrors>(
    {}
  )

  const setPasswordFieldError = (
    field: keyof ChangePasswordFieldErrors,
    message?: string
  ) => {
    setFieldErrors((previous) => ({ ...previous, [field]: message }))
  }

  const sendResetLink = () => {
    if (!session.data) return

    requestPasswordReset.mutate({
      email: session.data.user.email,
      redirectTo: getViewURL(
        auth.baseURL,
        auth.basePaths.auth,
        auth.viewPaths.auth.resetPassword
      )
    } as Parameters<typeof requestPasswordReset.mutate>[0])
  }

  const form = createForm(() => ({
    defaultValues: {
      confirmPassword: "",
      currentPassword: "",
      newPassword: ""
    },
    onSubmit: ({ value }) => {
      if (
        props.confirmPassword &&
        value.newPassword !== value.confirmPassword
      ) {
        form.reset()
        toast.error(auth.localization.auth.passwordsDoNotMatch)
        return
      }

      changePassword.mutate({
        currentPassword: value.currentPassword,
        newPassword: value.newPassword,
        revokeOtherSessions: true
      } as Parameters<typeof changePassword.mutate>[0])
    }
  }))

  const isPasswordPending = () =>
    changePassword.isPending || requestPasswordReset.isPending

  if (!linkedAccounts.isPending && !hasCredentialAccount()) {
    return (
      <div class={cn(props.class)}>
        <h2 class="mb-3 text-sm font-semibold">
          {auth.localization.settings.changePassword}
        </h2>

        <Card>
          <CardContent class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div>
              <p class="font-medium text-sm leading-tight">
                {auth.localization.settings.setPassword}
              </p>
              <p class="mt-0.5 text-muted-foreground text-xs">
                {auth.localization.settings.setPasswordDescription}
              </p>
            </div>

            <Show
              fallback={
                <Button
                  disabled={requestPasswordReset.isPending || !session.data}
                  onClick={sendResetLink}
                  size="sm"
                  type="button"
                >
                  {requestPasswordReset.isPending
                    ? `${auth.localization.auth.sendResetLink}…`
                    : auth.localization.auth.sendResetLink}
                </Button>
              }
              when={requestPasswordReset.isSuccess && session.data?.user.email}
              keyed
            >
              {(sentEmail) => (
                <div class="flex flex-col items-start gap-3 sm:items-end">
                  <p class="text-sm" role="status">
                    {auth.localization.auth.resetLinkSentTo.replace(
                      "{{email}}",
                      sentEmail
                    )}
                  </p>

                  <OpenEmailButton class="w-auto" email={sentEmail} />
                </div>
              )}
            </Show>
          </CardContent>
        </Card>
      </div>
    )
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.changePassword}
      </h2>

      <form
        onSubmit={(event) => {
          event.preventDefault()
          void form.handleSubmit()
        }}
      >
        <Card>
          <CardContent class="flex flex-col gap-6">
            <form.Field name="currentPassword">
              {(field) => (
                <Field data-invalid={Boolean(fieldErrors().currentPassword)}>
                  <FieldLabel for="currentPassword">
                    {auth.localization.settings.currentPassword}
                  </FieldLabel>
                  <Show
                    fallback={<ChangePasswordSkeletonInput />}
                    when={session.data && !linkedAccounts.isPending}
                  >
                    <InputGroup>
                      <InputGroupInput
                        aria-invalid={!!fieldErrors().currentPassword}
                        autocomplete="current-password"
                        disabled={isPasswordPending()}
                        id="currentPassword"
                        name={field().name}
                        onInput={(event) => {
                          field().handleChange(event.currentTarget.value)
                          setPasswordFieldError("currentPassword")
                        }}
                        onInvalid={(event) => {
                          event.preventDefault()
                          setPasswordFieldError(
                            "currentPassword",
                            event.currentTarget.validationMessage
                          )
                        }}
                        placeholder={
                          auth.localization.settings.currentPasswordPlaceholder
                        }
                        required
                        type={isCurrentPasswordVisible() ? "text" : "password"}
                        value={field().state.value}
                      />
                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          aria-label={
                            isCurrentPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          disabled={isPasswordPending()}
                          onClick={() =>
                            setIsCurrentPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isCurrentPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                        >
                          <Show
                            when={isCurrentPasswordVisible()}
                            fallback={<Eye aria-hidden class="size-4" />}
                          >
                            <EyeOff aria-hidden class="size-4" />
                          </Show>
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>
                  </Show>
                  <Show when={fieldErrors().currentPassword}>
                    {(message) => <FieldError>{message()}</FieldError>}
                  </Show>
                </Field>
              )}
            </form.Field>

            <form.Field name="newPassword">
              {(field) => (
                <Field data-invalid={Boolean(fieldErrors().newPassword)}>
                  <FieldLabel for="newPassword">
                    {auth.localization.auth.newPassword}
                  </FieldLabel>
                  <Show
                    fallback={<ChangePasswordSkeletonInput />}
                    when={session.data && !linkedAccounts.isPending}
                  >
                    <InputGroup>
                      <InputGroupInput
                        aria-invalid={!!fieldErrors().newPassword}
                        autocomplete="new-password"
                        disabled={isPasswordPending()}
                        id="newPassword"
                        maxLength={auth.emailAndPassword.maxPasswordLength}
                        minLength={auth.emailAndPassword.minPasswordLength}
                        name={field().name}
                        onInput={(event) => {
                          field().handleChange(event.currentTarget.value)
                          setPasswordFieldError("newPassword")
                        }}
                        onInvalid={(event) => {
                          event.preventDefault()
                          setPasswordFieldError(
                            "newPassword",
                            event.currentTarget.validationMessage
                          )
                        }}
                        placeholder={
                          auth.localization.auth.newPasswordPlaceholder
                        }
                        required
                        type={isNewPasswordVisible() ? "text" : "password"}
                        value={field().state.value}
                      />
                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          aria-label={
                            isNewPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          disabled={isPasswordPending()}
                          onClick={() =>
                            setIsNewPasswordVisible((visible) => !visible)
                          }
                          size="icon-sm"
                          title={
                            isNewPasswordVisible()
                              ? auth.localization.auth.hidePassword
                              : auth.localization.auth.showPassword
                          }
                          type="button"
                        >
                          {isNewPasswordVisible() ? (
                            <EyeOff aria-hidden class="size-4" />
                          ) : (
                            <Eye aria-hidden class="size-4" />
                          )}
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>
                  </Show>
                  <Show when={fieldErrors().newPassword}>
                    {(message) => <FieldError>{message()}</FieldError>}
                  </Show>

                  <PasswordStrengthMeter password={field().state.value} />
                </Field>
              )}
            </form.Field>

            <Show when={props.confirmPassword}>
              <form.Field name="confirmPassword">
                {(field) => (
                  <Field data-invalid={Boolean(fieldErrors().confirmPassword)}>
                    <FieldLabel for="confirmPassword">
                      {auth.localization.auth.confirmPassword}
                    </FieldLabel>
                    <Show
                      fallback={<ChangePasswordSkeletonInput />}
                      when={session.data && !linkedAccounts.isPending}
                    >
                      <InputGroup>
                        <InputGroupInput
                          aria-invalid={!!fieldErrors().confirmPassword}
                          autocomplete="new-password"
                          disabled={isPasswordPending()}
                          id="confirmPassword"
                          maxLength={auth.emailAndPassword.maxPasswordLength}
                          minLength={auth.emailAndPassword.minPasswordLength}
                          name={field().name}
                          onInput={(event) => {
                            field().handleChange(event.currentTarget.value)
                            setPasswordFieldError("confirmPassword")
                          }}
                          onInvalid={(event) => {
                            event.preventDefault()
                            setPasswordFieldError(
                              "confirmPassword",
                              event.currentTarget.validationMessage
                            )
                          }}
                          placeholder={
                            auth.localization.auth.confirmPasswordPlaceholder
                          }
                          required
                          type={
                            isConfirmPasswordVisible() ? "text" : "password"
                          }
                          value={field().state.value}
                        />
                        <InputGroupAddon align="inline-end">
                          <InputGroupButton
                            aria-label={
                              isConfirmPasswordVisible()
                                ? auth.localization.auth.hidePassword
                                : auth.localization.auth.showPassword
                            }
                            disabled={isPasswordPending()}
                            onClick={() =>
                              setIsConfirmPasswordVisible((visible) => !visible)
                            }
                            size="icon-sm"
                            title={
                              isConfirmPasswordVisible()
                                ? auth.localization.auth.hidePassword
                                : auth.localization.auth.showPassword
                            }
                            type="button"
                          >
                            {isConfirmPasswordVisible() ? (
                              <EyeOff aria-hidden class="size-4" />
                            ) : (
                              <Eye aria-hidden class="size-4" />
                            )}
                          </InputGroupButton>
                        </InputGroupAddon>
                      </InputGroup>
                    </Show>
                    <Show when={fieldErrors().confirmPassword}>
                      {(message) => <FieldError>{message()}</FieldError>}
                    </Show>
                  </Field>
                )}
              </form.Field>
            </Show>
          </CardContent>

          <CardFooter>
            <Button
              disabled={isPasswordPending() || !session.data}
              size="sm"
              type="submit"
            >
              {changePassword.isPending
                ? `${auth.localization.settings.updatePassword}…`
                : auth.localization.settings.updatePassword}
            </Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}

// examples/start-shadcn-baseui-example/src/components/auth/settings/security/change-password.tsx
"use client"

import { getViewURL, isPasswordCompromisedError } from "@better-auth-ui/core"
import {
  useAuth,
  useChangePassword,
  useFetchOptions,
  useListAccounts,
  useRequestPasswordReset,
  useSession
} from "@better-auth-ui/react"
import { useForm } from "@tanstack/react-form"
import { Eye, EyeOff } from "lucide-react"
import { useState } from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import {
  InputGroup,
  InputGroupAddon,
  InputGroupButton,
  InputGroupInput
} from "@/components/ui/input-group"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"
import { OpenEmailButton } from "../../open-email-button"
import { PasswordStrengthMeter } from "../../password-strength-meter"

export type ChangePasswordProps = {
  className?: string
}

/**
 * Render a card form for changing the authenticated user's password.
 *
 * When the user has a credential account, displays fields for current password,
 * new password, and optionally confirm password. When the user only has social
 * accounts, displays a prompt to set a password via the reset flow.
 *
 * @returns A JSX element containing the change-password or set-password card
 */
export function ChangePassword({ className }: ChangePasswordProps) {
  const { authClient, emailAndPassword, localization } = useAuth()
  const { data: session } = useSession(authClient)
  const { data: accounts, isPending: isAccountsPending } =
    useListAccounts(authClient)

  const hasCredentialAccount = accounts?.some(
    (account) => account.providerId === "credential"
  )

  if (!isAccountsPending && !hasCredentialAccount) {
    return <SetPassword className={className} />
  }

  return (
    <ChangePasswordForm
      className={className}
      emailAndPassword={emailAndPassword}
      localization={localization}
      session={isAccountsPending ? undefined : session}
    />
  )
}

function SetPassword({ className }: { className?: string }) {
  const { authClient, basePaths, baseURL, localization, plugins, viewPaths } =
    useAuth()
  const { data: session } = useSession(authClient)
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const [sentEmail, setSentEmail] = useState("")

  const { mutate: requestPasswordReset, isPending } = useRequestPasswordReset(
    authClient,
    {
      onError: () => {
        resetFetchOptions()
      },
      onSuccess: (_data, { email }) => {
        setSentEmail(email)
      }
    }
  )

  const Captcha = plugins.find(
    (plugin) => plugin.captchaComponent
  )?.captchaComponent

  const handleSetPassword = () => {
    if (!session) return

    requestPasswordReset({
      email: session.user.email,
      redirectTo: getViewURL(
        baseURL,
        basePaths.auth,
        viewPaths.auth.resetPassword
      ),
      fetchOptions
    })
  }

  return (
    <div>
      <h2 className="text-sm font-semibold mb-3">
        {localization.settings.changePassword}
      </h2>

      <Card className={cn(className)}>
        <CardContent className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <p className="text-sm font-medium leading-tight">
              {localization.settings.setPassword}
            </p>

            <p className="text-muted-foreground text-xs mt-0.5">
              {localization.settings.setPasswordDescription}
            </p>
          </div>

          {sentEmail ? (
            <div className="flex flex-col gap-3 items-start sm:items-end">
              <p className="text-sm" role="status">
                {localization.auth.resetLinkSentTo.replace(
                  "{{email}}",
                  sentEmail
                )}
              </p>

              <OpenEmailButton email={sentEmail} className="w-auto" />
            </div>
          ) : (
            <div className="flex flex-col gap-3 items-start sm:items-end">
              {Captcha && <div>{Captcha}</div>}

              <Button
                size="sm"
                disabled={isPending || !session?.user.email}
                onClick={handleSetPassword}
              >
                {isPending && <Spinner />}

                {localization.auth.sendResetLink}
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}

function ChangePasswordForm({
  className,
  emailAndPassword,
  localization,
  session
}: {
  className?: string
  emailAndPassword: ReturnType<typeof useAuth>["emailAndPassword"]
  localization: ReturnType<typeof useAuth>["localization"]
  session: ReturnType<typeof useSession>["data"]
}) {
  const { authClient } = useAuth()
  const { mutate: changePassword, isPending } = useChangePassword(authClient, {
    onError: (error) => {
      // The haveIBeenPwned plugin rejects on the password itself, so it
      // belongs against the field rather than in a toast.
      if (isPasswordCompromisedError(error)) {
        setFieldErrors((prev) => ({
          ...prev,
          newPassword: localization.auth.passwordCompromised
        }))
      }

      form.reset()
    },
    onSuccess: () => {
      form.reset()
      toast.success(localization.settings.changePasswordSuccess)
    }
  })

  const [isCurrentPasswordVisible, setIsCurrentPasswordVisible] =
    useState(false)
  const [isNewPasswordVisible, setIsNewPasswordVisible] = useState(false)
  const [isConfirmPasswordVisible, setIsConfirmPasswordVisible] =
    useState(false)

  const [fieldErrors, setFieldErrors] = useState<{
    currentPassword?: string
    newPassword?: string
    confirmPassword?: string
  }>({})

  const form = useForm({
    defaultValues: {
      confirmPassword: "",
      currentPassword: "",
      newPassword: ""
    },
    onSubmit: ({ value }) => {
      if (
        emailAndPassword.confirmPassword &&
        value.newPassword !== value.confirmPassword
      ) {
        form.reset()
        toast.error(localization.auth.passwordsDoNotMatch)
        return
      }

      changePassword({
        currentPassword: value.currentPassword,
        newPassword: value.newPassword,
        revokeOtherSessions: true
      })
    }
  })

  return (
    <div>
      <h2 className="text-sm font-semibold mb-3">
        {localization.settings.changePassword}
      </h2>

      <form
        onSubmit={(event) => {
          event.preventDefault()
          void form.handleSubmit()
        }}
      >
        <Card className={cn(className)}>
          <CardContent className="flex flex-col gap-6">
            <form.Field name="currentPassword">
              {(field) => (
                <Field data-invalid={!!fieldErrors.currentPassword}>
                  <FieldLabel htmlFor="currentPassword">
                    {localization.settings.currentPassword}
                  </FieldLabel>

                  {session ? (
                    <InputGroup>
                      <InputGroupInput
                        id="currentPassword"
                        name={field.name}
                        type={isCurrentPasswordVisible ? "text" : "password"}
                        autoComplete="current-password"
                        placeholder={
                          localization.settings.currentPasswordPlaceholder
                        }
                        value={field.state.value}
                        onChange={(e) => {
                          field.handleChange(e.target.value)

                          setFieldErrors((prev) => ({
                            ...prev,
                            currentPassword: undefined
                          }))
                        }}
                        disabled={isPending}
                        required
                        onInvalid={(e) => {
                          e.preventDefault()

                          setFieldErrors((prev) => ({
                            ...prev,
                            currentPassword: (e.target as HTMLInputElement)
                              .validationMessage
                          }))
                        }}
                        aria-invalid={!!fieldErrors.currentPassword}
                      />

                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          size="icon-xs"
                          aria-label={
                            isCurrentPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          title={
                            isCurrentPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          onClick={() => {
                            setIsCurrentPasswordVisible((visible) => !visible)
                          }}
                        >
                          {isCurrentPasswordVisible ? <EyeOff /> : <Eye />}
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>
                  ) : (
                    <Skeleton>
                      <Input className="invisible" />
                    </Skeleton>
                  )}

                  <FieldError>{fieldErrors.currentPassword}</FieldError>
                </Field>
              )}
            </form.Field>

            <form.Field name="newPassword">
              {(field) => (
                <Field data-invalid={!!fieldErrors.newPassword}>
                  <FieldLabel htmlFor="newPassword">
                    {localization.auth.newPassword}
                  </FieldLabel>

                  {session ? (
                    <InputGroup>
                      <InputGroupInput
                        id="newPassword"
                        name={field.name}
                        type={isNewPasswordVisible ? "text" : "password"}
                        autoComplete="new-password"
                        placeholder={localization.auth.newPasswordPlaceholder}
                        value={field.state.value}
                        onChange={(e) => {
                          field.handleChange(e.target.value)

                          setFieldErrors((prev) => ({
                            ...prev,
                            newPassword: undefined
                          }))
                        }}
                        minLength={emailAndPassword.minPasswordLength}
                        maxLength={emailAndPassword.maxPasswordLength}
                        disabled={isPending}
                        required
                        onInvalid={(e) => {
                          e.preventDefault()
                          setFieldErrors((prev) => ({
                            ...prev,
                            newPassword: (e.target as HTMLInputElement)
                              .validationMessage
                          }))
                        }}
                        aria-invalid={!!fieldErrors.newPassword}
                      />

                      <InputGroupAddon align="inline-end">
                        <InputGroupButton
                          size="icon-xs"
                          aria-label={
                            isNewPasswordVisible
                              ? localization.auth.hidePassword
                              : localization.auth.showPassword
                          }
                          onClick={() =>
                            setIsNewPasswordVisible((visible) => !visible)
                          }
                        >
                          {isNewPasswordVisible ? <EyeOff /> : <Eye />}
                        </InputGroupButton>
                      </InputGroupAddon>
                    </InputGroup>
                  ) : (
                    <Skeleton>
                      <Input className="invisible" />
                    </Skeleton>
                  )}

                  <FieldError>{fieldErrors.newPassword}</FieldError>

                  <PasswordStrengthMeter password={field.state.value} />
                </Field>
              )}
            </form.Field>

            {emailAndPassword.confirmPassword && (
              <form.Field name="confirmPassword">
                {(field) => (
                  <Field data-invalid={!!fieldErrors.confirmPassword}>
                    <FieldLabel htmlFor="confirmPassword">
                      {localization.auth.confirmPassword}
                    </FieldLabel>

                    {session ? (
                      <InputGroup>
                        <InputGroupInput
                          id="confirmPassword"
                          name={field.name}
                          type={isConfirmPasswordVisible ? "text" : "password"}
                          autoComplete="new-password"
                          placeholder={
                            localization.auth.confirmPasswordPlaceholder
                          }
                          value={field.state.value}
                          onChange={(e) => {
                            field.handleChange(e.target.value)

                            setFieldErrors((prev) => ({
                              ...prev,
                              confirmPassword: undefined
                            }))
                          }}
                          minLength={emailAndPassword.minPasswordLength}
                          maxLength={emailAndPassword.maxPasswordLength}
                          disabled={isPending}
                          required
                          onInvalid={(e) => {
                            e.preventDefault()

                            setFieldErrors((prev) => ({
                              ...prev,
                              confirmPassword: (e.target as HTMLInputElement)
                                .validationMessage
                            }))
                          }}
                          aria-invalid={!!fieldErrors.confirmPassword}
                        />

                        <InputGroupAddon align="inline-end">
                          <InputGroupButton
                            size="icon-xs"
                            aria-label={
                              isConfirmPasswordVisible
                                ? localization.auth.hidePassword
                                : localization.auth.showPassword
                            }
                            onClick={() =>
                              setIsConfirmPasswordVisible((visible) => !visible)
                            }
                          >
                            {isConfirmPasswordVisible ? <EyeOff /> : <Eye />}
                          </InputGroupButton>
                        </InputGroupAddon>
                      </InputGroup>
                    ) : (
                      <Skeleton>
                        <Input className="invisible" />
                      </Skeleton>
                    )}

                    <FieldError>{fieldErrors.confirmPassword}</FieldError>
                  </Field>
                )}
              </form.Field>
            )}
          </CardContent>

          <CardFooter>
            <Button type="submit" size="sm" disabled={isPending || !session}>
              {isPending && <Spinner />}

              {localization.settings.updatePassword}
            </Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}
