// packages/react-native/src/components/auth/delete-user/delete-account.tsx
import { authQueryKeys } from "@better-auth-ui/core"
import {
  useAuth,
  useAuthPlugin,
  useDeleteUser,
  useListAccounts
} from "@better-auth-ui/react"
import { useQueryClient } from "@tanstack/react-query"
import { useState } from "react"
import { Text, View } from "react-native"

import { deleteUserPlugin } from "../../../lib/auth/delete-user-plugin"
import type { SettingsViewProps } from "../../../lib/auth-plugin"
import { useThemeColors } from "../../../lib/theme-colors"
import { useAuthNavigation } from "../../../navigation/navigation-context"
import { AlertDialog } from "../../../primitives/alert-dialog"
import { Button } from "../../../primitives/button"
import { Card } from "../../../primitives/card"
import { FieldError, Label, TextField } from "../../../primitives/field"
import { Form } from "../../../primitives/form"
import { InputGroup } from "../../../primitives/input"
import { toast } from "../../../primitives/toast"
import { TriangleExclamation } from "../../../primitives/ui-icons"

export type DeleteAccountProps = SettingsViewProps

/**
 * Danger-zone card to delete the authenticated account, with a confirmation
 * dialog and toasts. Mirrors the heroui `DeleteAccount`, adapted for React
 * Native: the confirm dialog is the RN `AlertDialog` (a `Modal`, controlled
 * via `isOpen`/`onOpenChange` instead of `AlertDialog.Backdrop`), the password
 * field (when required) is controlled state (no `FormData`), and success
 * navigates via the RN navigation adapter instead of a `basePaths`/`viewPaths`
 * URL join.
 */
export function DeleteAccount({ className, variant }: DeleteAccountProps) {
  const { authClient, localization } = useAuth()

  const {
    localization: deleteUserLocalization,
    sendDeleteAccountVerification
  } = useAuthPlugin(deleteUserPlugin)

  const { data: accounts } = useListAccounts(authClient)

  const queryClient = useQueryClient()
  const navigation = useAuthNavigation()
  const colors = useThemeColors()

  const [confirmOpen, setConfirmOpen] = useState(false)
  const [password, setPassword] = useState("")

  const hasCredentialAccount = accounts?.some(
    (account) => account.providerId === "credential"
  )
  const needsPassword = !sendDeleteAccountVerification && hasCredentialAccount

  const { mutate: deleteUser, isPending } = useDeleteUser(authClient)

  const handleDialogOpenChange = (open: boolean) => {
    setConfirmOpen(open)
    setPassword("")
  }

  const handleSubmit = () => {
    const params = {
      ...(needsPassword ? { password } : {})
    }

    deleteUser(params, {
      onSuccess: () => {
        setConfirmOpen(false)
        setPassword("")

        if (sendDeleteAccountVerification) {
          toast.success(deleteUserLocalization.deleteUserVerificationSent)
        } else {
          toast.success(deleteUserLocalization.deleteUserSuccess)
          queryClient.removeQueries({ queryKey: authQueryKeys.all })
          navigation.push("signIn", { replace: true })
        }
      }
    })
  }

  return (
    <Card className={className} variant={variant}>
      <Card.Content className="flex-row items-center justify-between gap-4">
        <View className="flex-1">
          <Text className="text-sm font-medium leading-tight text-foreground">
            {deleteUserLocalization.deleteAccount}
          </Text>

          <Text className="mt-0.5 text-xs text-muted">
            {deleteUserLocalization.deleteAccountDescription}
          </Text>
        </View>

        <Button
          isDisabled={!accounts}
          size="sm"
          variant="danger"
          onPress={() => setConfirmOpen(true)}
        >
          {deleteUserLocalization.deleteAccount}
        </Button>

        <AlertDialog isOpen={confirmOpen} onOpenChange={handleDialogOpenChange}>
          <Form onSubmit={handleSubmit}>
            <AlertDialog.CloseTrigger />

            <AlertDialog.Header>
              <AlertDialog.Icon status="danger">
                <TriangleExclamation
                  width={20}
                  height={20}
                  color={colors.danger}
                />
              </AlertDialog.Icon>

              <AlertDialog.Heading>
                {deleteUserLocalization.deleteAccount}
              </AlertDialog.Heading>
            </AlertDialog.Header>

            <AlertDialog.Body>
              <Text className="text-sm text-muted">
                {deleteUserLocalization.deleteAccountDescription}
              </Text>

              {needsPassword && (
                <TextField
                  className="mt-4 gap-1.5"
                  name="password"
                  type="password"
                  autoComplete="current-password"
                  isDisabled={isPending}
                  value={password}
                  onChange={setPassword}
                >
                  <Label>{localization.auth.password}</Label>

                  <InputGroup variant="secondary">
                    <InputGroup.Input
                      type="password"
                      placeholder={localization.auth.passwordPlaceholder}
                      required
                    />
                  </InputGroup>

                  <FieldError />
                </TextField>
              )}
            </AlertDialog.Body>

            <AlertDialog.Footer>
              <Button
                variant="tertiary"
                isDisabled={isPending}
                onPress={() => handleDialogOpenChange(false)}
              >
                {localization.settings.cancel}
              </Button>

              <Button type="submit" variant="danger" isPending={isPending}>
                {deleteUserLocalization.deleteAccount}
              </Button>
            </AlertDialog.Footer>
          </Form>
        </AlertDialog>
      </Card.Content>
    </Card>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/delete-user/delete-account.tsx
import { authQueryKeys } from "@better-auth-ui/core"
import { deleteUserLocalization } from "@better-auth-ui/core/plugins/delete-user"
import { useAuth, useDeleteUser, useListAccounts } from "@better-auth-ui/solid"
import { useQueryClient } from "@tanstack/solid-query"
import { TriangleAlert } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import type { DeleteUserPluginConfig } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Card, CardContent } from "@/components/ui/card"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { cn } from "@/lib/utils"

const defaultDeleteAccountLabel = "Delete account"

export type DeleteAccountProps = {
  class?: string
}

export function DeleteAccount(props: DeleteAccountProps = {}) {
  const auth = useAuth()
  const queryClient = useQueryClient()
  const [confirmOpen, setConfirmOpen] = createSignal(false)
  const [password, setPassword] = createSignal("")
  const deleteUserPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === "deleteUser") as
      | DeleteUserPluginConfig
      | undefined
  const deleteUserLabels = () => {
    const pluginLocalization = deleteUserPluginConfig()?.localization

    return {
      deleteUser:
        pluginLocalization?.deleteAccount ??
        deleteUserLocalization.deleteAccount ??
        defaultDeleteAccountLabel,
      deleteUserDescription:
        pluginLocalization?.deleteAccountDescription ??
        deleteUserLocalization.deleteAccountDescription,
      deleteUserSuccess:
        pluginLocalization?.deleteUserSuccess ??
        deleteUserLocalization.deleteUserSuccess,
      deleteUserVerificationSent:
        pluginLocalization?.deleteUserVerificationSent ??
        deleteUserLocalization.deleteUserVerificationSent
    }
  }
  const sendDeleteAccountVerification = () =>
    Boolean(deleteUserPluginConfig()?.sendDeleteAccountVerification)
  const accounts = useListAccounts(auth.authClient)
  const hasCredentialAccount = () =>
    accounts.data?.some(
      (account: { providerId?: string }) => account.providerId === "credential"
    )
  const needsPassword = () =>
    !sendDeleteAccountVerification() && Boolean(hasCredentialAccount())
  const deleteUser = useDeleteUser(auth.authClient, () => ({
    onSuccess: () => {
      setConfirmOpen(false)
      setPassword("")

      if (sendDeleteAccountVerification()) {
        toast.success(deleteUserLabels().deleteUserVerificationSent)
        return
      }

      toast.success(deleteUserLabels().deleteUserSuccess)
      queryClient.removeQueries({ queryKey: authQueryKeys.all })
      auth.navigate({
        replace: true,
        to: `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`
      })
    }
  }))

  const handleDialogOpenChange = (open: boolean) => {
    setConfirmOpen(open)
    setPassword("")
  }

  const submitDeleteUser = (event: SubmitEvent) => {
    event.preventDefault()

    deleteUser.mutate(
      (needsPassword() ? { password: password() } : {}) as Parameters<
        typeof deleteUser.mutate
      >[0]
    )
  }

  return (
    <Card class={cn("z-card-padding-none border-destructive", props.class)}>
      <CardContent class="flex flex-col gap-6 p-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <p class="font-medium text-sm leading-tight">
            {deleteUserLabels().deleteUser}
          </p>
          <p class="mt-0.5 text-muted-foreground text-xs">
            {deleteUserLabels().deleteUserDescription}
          </p>
        </div>

        <Dialog open={confirmOpen()} onOpenChange={handleDialogOpenChange}>
          <DialogTrigger
            as={Button}
            disabled={!accounts.data || accounts.isPending}
            size="sm"
            variant="destructive"
          >
            {deleteUserLabels().deleteUser}
          </DialogTrigger>

          <DialogContent>
            <form class="flex flex-col gap-6" onSubmit={submitDeleteUser}>
              <DialogHeader>
                <div class="flex size-10 items-center justify-center rounded-md bg-destructive/10 text-destructive dark:bg-destructive/20">
                  <TriangleAlert class="size-4.5" />
                </div>
                <DialogTitle>{deleteUserLabels().deleteUser}</DialogTitle>
                <DialogDescription>
                  {deleteUserLabels().deleteUserDescription}
                </DialogDescription>
              </DialogHeader>

              <Show when={needsPassword()}>
                <div class="grid gap-2">
                  <Label for="delete-password">
                    {auth.localization.auth.password}
                  </Label>
                  <Input
                    autocomplete="current-password"
                    disabled={deleteUser.isPending}
                    id="delete-password"
                    name="password"
                    onInput={(event) => setPassword(event.currentTarget.value)}
                    placeholder={auth.localization.auth.passwordPlaceholder}
                    required
                    type="password"
                    value={password()}
                  />
                </div>
              </Show>

              <DialogFooter>
                <DialogClose
                  as={Button}
                  disabled={deleteUser.isPending}
                  type="button"
                  variant="outline"
                >
                  {auth.localization.settings.cancel}
                </DialogClose>
                <Button
                  disabled={deleteUser.isPending}
                  type="submit"
                  variant="destructive"
                >
                  {deleteUser.isPending
                    ? `${deleteUserLabels().deleteUser}…`
                    : deleteUserLabels().deleteUser}
                </Button>
              </DialogFooter>
            </form>
          </DialogContent>
        </Dialog>
      </CardContent>
    </Card>
  )
}
