// examples/start-solid-zaidan-example/src/components/auth/phone-number/forgot-phone-number-password.tsx
import {
  createPhoneNumberValue,
  type PhoneNumberAuthClient
} from "@better-auth-ui/core/plugins/phone-number"
import {
  AuthLink,
  useAuth,
  useAuthPlugin,
  useFetchOptions
} from "@better-auth-ui/solid"
import { useRequestPhoneNumberPasswordReset } from "@better-auth-ui/solid/plugins/phone-number"
import { Show } from "solid-js"

import {
  Card,
  CardContent,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { FieldGroup } from "@/components/ui/field"
import { Spinner } from "@/components/ui/spinner"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "@/lib/utils"
import { createAuthForm } from "../auth-form"
import { InternationalPhoneField } from "./international-phone-field"

export const PHONE_NUMBER_RESET_STORAGE_KEY =
  "better-auth-ui.phone-number-reset"

export type ForgotPhoneNumberPasswordProps = {
  class?: string
}

/** Request the code used to reset a phone credential password. */
export function ForgotPhoneNumberPassword(
  props: ForgotPhoneNumberPasswordProps
) {
  const auth = useAuth()
  const {
    adapter,
    countries,
    defaultCountry,
    locale,
    localization,
    viewPaths: phoneNumberViewPaths
  } = useAuthPlugin(phoneNumberPlugin)
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const requestReset = useRequestPhoneNumberPasswordReset(
    auth.authClient as PhoneNumberAuthClient,
    () => ({
      onError: () => resetFetchOptions(),
      onSuccess: (_data, variables) => {
        const phoneNumber = (variables as { phoneNumber: string }).phoneNumber
        sessionStorage.setItem(PHONE_NUMBER_RESET_STORAGE_KEY, phoneNumber)
        auth.navigate({
          to: `${auth.basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumberResetPassword}`
        })
      }
    })
  )
  const form = createAuthForm(() => ({
    defaultValues: {
      phoneNumber: createPhoneNumberValue("", defaultCountry, adapter)
    },
    onSubmit: async ({ value }) => {
      if (!value.phoneNumber.e164) return
      await requestReset.mutateAsync({
        phoneNumber: value.phoneNumber.e164,
        fetchOptions: fetchOptions()
      } as Parameters<typeof requestReset.mutateAsync>[0])
    }
  }))

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {localization.forgotPassword}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot aria-label={localization.forgotPassword}>
            <FieldGroup>
              <form.AppField
                name="phoneNumber"
                validators={{
                  onChange: ({ value }) =>
                    value.e164 ? undefined : localization.invalidPhoneNumber
                }}
              >
                {(field) => (
                  <InternationalPhoneField
                    adapter={adapter}
                    countryCodes={countries}
                    countryLabel={localization.country}
                    disabled={requestReset.isPending}
                    error={field().state.meta.errors[0]?.toString()}
                    locale={locale}
                    phoneLabel={localization.phoneNumber}
                    placeholder={localization.phoneNumberPlaceholder}
                    value={field().state.value}
                    onChange={field().handleChange}
                  />
                )}
              </form.AppField>
              <form.AuthFormSubmitButton
                class="w-full"
                disabled={requestReset.isPending}
              >
                <Show when={requestReset.isPending}>
                  <Spinner />
                </Show>
                {localization.sendCode}
              </form.AuthFormSubmitButton>
              <form.AuthFormServerError />
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>
      </CardContent>
      <CardFooter class="justify-center">
        <p class="text-sm text-muted-foreground">
          {auth.localization.auth.rememberYourPassword}{" "}
          <AuthLink
            class="underline underline-offset-4"
            href={`${auth.basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumber}`}
          >
            {auth.localization.auth.signIn}
          </AuthLink>
        </p>
      </CardFooter>
    </Card>
  )
}

// apps/docs/src/components/auth/phone-number/forgot-phone-number-password.tsx
"use client"

import {
  createPhoneNumberValue,
  type PhoneNumberAuthClient
} from "@better-auth-ui/core/plugins/phone-number"
import { useAuth, useAuthPlugin, useFetchOptions } from "@better-auth-ui/react"
import { useRequestPhoneNumberPasswordReset } from "@better-auth-ui/react/plugins/phone-number"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { FieldDescription, FieldGroup } from "@/components/ui/field"
import { Spinner } from "@/components/ui/spinner"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "@/lib/utils"
import { useAuthForm } from "../auth-form"
import { InternationalPhoneField } from "./international-phone-field"

export const PHONE_NUMBER_RESET_STORAGE_KEY =
  "better-auth-ui.phone-number-reset"

export type ForgotPhoneNumberPasswordProps = {
  className?: string
}

/** Request the verification code used to reset a phone credential password. */
export function ForgotPhoneNumberPassword({
  className
}: ForgotPhoneNumberPasswordProps) {
  const { authClient, basePaths, localization, navigate, plugins, Link } =
    useAuth()
  const {
    adapter,
    countries,
    defaultCountry,
    locale,
    localization: phoneLocalization,
    viewPaths: phoneNumberViewPaths
  } = useAuthPlugin(phoneNumberPlugin)
  const { fetchOptions, resetFetchOptions } = useFetchOptions()
  const { mutate: requestReset, isPending } =
    useRequestPhoneNumberPasswordReset(authClient as PhoneNumberAuthClient, {
      onError: () => resetFetchOptions(),
      onSuccess: (_data, { phoneNumber }) => {
        sessionStorage.setItem(PHONE_NUMBER_RESET_STORAGE_KEY, phoneNumber)
        navigate({
          to: `${basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumberResetPassword}`
        })
      }
    })
  const Captcha = plugins.find(
    (plugin) => plugin.captchaComponent
  )?.captchaComponent

  const form = useAuthForm({
    defaultValues: {
      phoneNumber: createPhoneNumberValue("", defaultCountry, adapter)
    },
    onSubmit: ({ value }) => {
      if (!value.phoneNumber.e164) return
      requestReset({ phoneNumber: value.phoneNumber.e164, fetchOptions })
    }
  })

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl">
          {phoneLocalization.forgotPassword}
        </CardTitle>
      </CardHeader>
      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot>
            <FieldGroup>
              <form.AppField
                name="phoneNumber"
                validators={{
                  onChange: ({ value }) =>
                    value.e164
                      ? undefined
                      : phoneLocalization.invalidPhoneNumber
                }}
              >
                {(field) => (
                  <InternationalPhoneField
                    adapter={adapter}
                    countryCodes={countries}
                    countryLabel={phoneLocalization.country}
                    disabled={isPending}
                    error={field.state.meta.errors[0]?.toString()}
                    locale={locale}
                    phoneLabel={phoneLocalization.phoneNumber}
                    placeholder={phoneLocalization.phoneNumberPlaceholder}
                    value={field.state.value}
                    onChange={field.handleChange}
                  />
                )}
              </form.AppField>
              {Captcha && <div className="flex justify-center">{Captcha}</div>}
              <form.AuthFormSubmitButton disabled={isPending}>
                {isPending && <Spinner />}
                {phoneLocalization.sendCode}
              </form.AuthFormSubmitButton>
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>
        <FieldDescription className="mt-4 text-center">
          {localization.auth.rememberYourPassword}{" "}
          <Link
            href={`${basePaths.auth}/${phoneNumberViewPaths.auth.phoneNumber}`}
            className="underline underline-offset-4"
          >
            {localization.auth.signIn}
          </Link>
        </FieldDescription>
      </CardContent>
    </Card>
  )
}
