// examples/start-solid-zaidan-example/src/components/auth/phone-number/change-phone-number.tsx
import type { PhoneNumberAuthClient } from "@better-auth-ui/core/plugins/phone-number"
import {
  useAuth,
  useAuthPlugin,
  useSession,
  useUpdateUser
} from "@better-auth-ui/solid"
import {
  useSendPhoneNumberOtp,
  useVerifyPhoneNumber
} from "@better-auth-ui/solid/plugins/phone-number"
import { createEffect, createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"

import { OtpField } from "@/components/auth/otp-field"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "@/lib/utils"
import { RemovePhoneNumberDialog } from "./remove-phone-number-dialog"

type PhoneNumberUser = {
  phoneNumber?: string | null
}

export type ChangePhoneNumberProps = {
  class?: string
}

/** Add, replace, or remove the authenticated user's verified phone number. */
export function ChangePhoneNumber(props: ChangePhoneNumberProps = {}) {
  const auth = useAuth()
  const { localization, otpLength } = useAuthPlugin(phoneNumberPlugin)
  const phoneClient = () => auth.authClient as PhoneNumberAuthClient
  const session = useSession(phoneClient())
  const currentPhoneNumber = () =>
    (session.data?.user as PhoneNumberUser | undefined)?.phoneNumber ?? ""
  const [phoneNumber, setPhoneNumber] = createSignal("")
  const [fieldError, setFieldError] = createSignal<string>()
  const [code, setCode] = createSignal("")
  const [codeSent, setCodeSent] = createSignal(false)

  let initialized = false
  createEffect(() => {
    if (!session.data || initialized) return
    initialized = true
    setPhoneNumber(currentPhoneNumber())
  })

  const sendOtp = useSendPhoneNumberOtp(phoneClient(), () => ({
    onSuccess: () => setCodeSent(true)
  }))
  const verify = useVerifyPhoneNumber(phoneClient(), () => ({
    onError: () => setCode(""),
    onSuccess: () => {
      setCode("")
      setCodeSent(false)
      toast.success(localization.phoneNumberUpdated)
    }
  }))
  const remove = useUpdateUser(phoneClient(), () => ({
    onSuccess: () => {
      setPhoneNumber("")
      toast.success(localization.phoneNumberRemoved)
    }
  }))
  const isPending = () =>
    sendOtp.isPending || verify.isPending || remove.isPending
  const submit = (event: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    event.preventDefault()
    if (!codeSent()) {
      sendOtp.mutate({ phoneNumber: phoneNumber() } as Parameters<
        typeof sendOtp.mutate
      >[0])
      return
    }
    verify.mutate({
      phoneNumber: phoneNumber(),
      code: code(),
      updatePhoneNumber: true
    } as Parameters<typeof verify.mutate>[0])
  }
  const removePhoneNumber = () =>
    remove.mutate({
      phoneNumber: null
    } as Parameters<typeof remove.mutate>[0])

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {localization.changePhoneNumber}
      </h2>
      <form onSubmit={submit}>
        <Card>
          <CardContent class="flex flex-col gap-6">
            <Show
              when={codeSent()}
              fallback={
                <Field data-invalid={Boolean(fieldError())}>
                  <FieldLabel for="settings-phone-number">
                    {localization.phoneNumber}
                  </FieldLabel>
                  <Show
                    when={session.data}
                    fallback={
                      <Skeleton>
                        <Input class="invisible" />
                      </Skeleton>
                    }
                  >
                    <Input
                      aria-invalid={Boolean(fieldError())}
                      autocomplete="tel"
                      disabled={isPending()}
                      id="settings-phone-number"
                      inputmode="tel"
                      name="phoneNumber"
                      onInput={(event) => {
                        setPhoneNumber(event.currentTarget.value)
                        setFieldError(undefined)
                      }}
                      onInvalid={(event) => {
                        event.preventDefault()
                        setFieldError(event.currentTarget.validationMessage)
                      }}
                      placeholder={localization.phoneNumberPlaceholder}
                      required
                      type="tel"
                      value={phoneNumber()}
                    />
                  </Show>
                  <Show when={fieldError()}>
                    {(message) => <FieldError>{message()}</FieldError>}
                  </Show>
                </Field>
              }
            >
              <div class="flex flex-col gap-3">
                <p class="text-sm text-muted-foreground">
                  {localization.codeSentTo.replace(
                    "{{phoneNumber}}",
                    phoneNumber()
                  )}
                </p>
                <OtpField
                  autofocus
                  disabled={isPending()}
                  id="settings-phone-code"
                  label={localization.phoneCode}
                  length={otpLength}
                  name="otp"
                  onInput={setCode}
                  value={code()}
                />
              </div>
            </Show>
          </CardContent>
          <CardFooter class="gap-3">
            <Show when={codeSent()}>
              <Button
                disabled={isPending()}
                onClick={() => {
                  setCode("")
                  setCodeSent(false)
                  setPhoneNumber(currentPhoneNumber())
                }}
                size="sm"
                type="button"
                variant="outline"
              >
                {localization.cancel}
              </Button>
            </Show>
            <Button
              disabled={
                isPending() ||
                !session.data ||
                (codeSent() && code().length !== otpLength)
              }
              size="sm"
              type="submit"
            >
              <Show when={sendOtp.isPending || verify.isPending}>
                <Spinner />
              </Show>
              {codeSent()
                ? localization.verifyCode
                : localization.updatePhoneNumber}
            </Button>
            <Show when={!codeSent() && currentPhoneNumber()}>
              <RemovePhoneNumberDialog
                cancelLabel={localization.cancel}
                description={localization.removePhoneNumberDescription}
                isPending={remove.isPending}
                label={localization.removePhoneNumber}
                title={localization.removePhoneNumberTitle}
                onConfirm={removePhoneNumber}
              />
            </Show>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}

// examples/next-shadcn-example/src/components/auth/phone-number/change-phone-number.tsx
"use client"

import {
  type PhoneNumberAuthClient,
  useAuth,
  useAuthPlugin,
  useSendPhoneNumberOtp,
  useSession,
  useUpdateUser,
  useVerifyPhoneNumber
} from "@better-auth-ui/react"
import { type SyntheticEvent, useEffect, useState } from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldError,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { phoneNumberPlugin } from "@/lib/auth/phone-number-plugin"
import { cn } from "@/lib/utils"
import { OtpField } from "../otp-field"
import { RemovePhoneNumberDialog } from "./remove-phone-number-dialog"

type PhoneNumberUser = {
  phoneNumber?: string | null
}

export type ChangePhoneNumberProps = {
  className?: string
}

/** Add, replace, or remove the authenticated user's verified phone number. */
export function ChangePhoneNumber({ className }: ChangePhoneNumberProps) {
  const { authClient } = useAuth()
  const { localization, otpLength } = useAuthPlugin(phoneNumberPlugin)
  const phoneClient = authClient as PhoneNumberAuthClient
  const { data: session } = useSession(phoneClient)
  const currentPhoneNumber =
    (session?.user as PhoneNumberUser | undefined)?.phoneNumber ?? ""
  const [phoneNumber, setPhoneNumber] = useState("")
  const [code, setCode] = useState("")
  const [codeSent, setCodeSent] = useState(false)
  const [fieldError, setFieldError] = useState<string>()

  useEffect(() => {
    if (session) setPhoneNumber(currentPhoneNumber)
  }, [currentPhoneNumber, session])

  const { mutate: sendOtp, isPending: isSending } = useSendPhoneNumberOtp(
    phoneClient,
    { onSuccess: () => setCodeSent(true) }
  )
  const { mutate: verify, isPending: isVerifying } = useVerifyPhoneNumber(
    phoneClient,
    {
      onError: () => setCode(""),
      onSuccess: () => {
        setCode("")
        setCodeSent(false)
        toast.success(localization.phoneNumberUpdated)
      }
    }
  )
  const { mutate: updateUser, isPending: isRemoving } = useUpdateUser(
    phoneClient,
    {
      onSuccess: () => {
        setPhoneNumber("")
        toast.success(localization.phoneNumberRemoved)
      }
    }
  )
  const isPending = isSending || isVerifying || isRemoving

  const handleSubmit = (event: SyntheticEvent<HTMLFormElement>) => {
    event.preventDefault()
    if (!codeSent) {
      sendOtp({ phoneNumber })
      return
    }

    verify({ phoneNumber, code, updatePhoneNumber: true })
  }
  const removePhoneNumber = () =>
    updateUser({
      phoneNumber: null
    } as Parameters<PhoneNumberAuthClient["updateUser"]>[0])

  return (
    <div>
      <h2 className="mb-3 text-sm font-semibold">
        {localization.changePhoneNumber}
      </h2>
      <form onSubmit={handleSubmit}>
        <Card className={cn(className)}>
          <CardContent className="flex flex-col gap-6">
            {codeSent ? (
              <>
                <FieldDescription>
                  {localization.codeSentTo.replace(
                    "{{phoneNumber}}",
                    phoneNumber
                  )}
                </FieldDescription>
                <OtpField
                  autoFocus
                  disabled={isPending}
                  label={localization.phoneCode}
                  length={otpLength}
                  name="otp"
                  value={code}
                  onChange={setCode}
                />
              </>
            ) : (
              <Field data-invalid={Boolean(fieldError)}>
                <FieldLabel htmlFor="settingsPhoneNumber">
                  {localization.phoneNumber}
                </FieldLabel>
                {session ? (
                  <Input
                    id="settingsPhoneNumber"
                    name="phoneNumber"
                    type="tel"
                    autoComplete="tel"
                    inputMode="tel"
                    value={phoneNumber}
                    placeholder={localization.phoneNumberPlaceholder}
                    required
                    disabled={isPending}
                    onChange={(event) => {
                      setPhoneNumber(event.target.value)
                      setFieldError(undefined)
                    }}
                    onInvalid={(event) => {
                      event.preventDefault()
                      setFieldError(event.currentTarget.validationMessage)
                    }}
                    aria-invalid={Boolean(fieldError)}
                  />
                ) : (
                  <Skeleton>
                    <Input className="invisible" />
                  </Skeleton>
                )}
                <FieldError>{fieldError}</FieldError>
              </Field>
            )}
          </CardContent>
          <CardFooter className="gap-3">
            {codeSent && (
              <Button
                type="button"
                size="sm"
                variant="outline"
                disabled={isPending}
                onClick={() => {
                  setCode("")
                  setCodeSent(false)
                  setPhoneNumber(currentPhoneNumber)
                }}
              >
                {localization.cancel}
              </Button>
            )}
            <Button
              type="submit"
              size="sm"
              disabled={
                isPending || !session || (codeSent && code.length !== otpLength)
              }
            >
              {(isSending || isVerifying) && <Spinner />}
              {codeSent
                ? localization.verifyCode
                : localization.updatePhoneNumber}
            </Button>
            {!codeSent && currentPhoneNumber && (
              <RemovePhoneNumberDialog
                cancelLabel={localization.cancel}
                description={localization.removePhoneNumberDescription}
                isPending={isRemoving}
                label={localization.removePhoneNumber}
                title={localization.removePhoneNumberTitle}
                onConfirm={removePhoneNumber}
              />
            )}
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}
