// examples/start-solid-zaidan-example/src/components/auth/organization/create-organization-dialog.tsx
import { parseAdditionalFieldValue } from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useCreateOrganization } from "@better-auth-ui/solid/plugins/organization"
import { BriefcaseBusiness, LoaderCircle } from "lucide-solid"
import { createEffect, createSignal, For, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { AdditionalField } from "../additional-field"
import { SlugField, sanitizeSlug } from "./slug-field"

export type CreateOrganizationDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  hideSlug?: boolean
}

export function CreateOrganizationDialog(props: CreateOrganizationDialogProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const config = useAuthPlugin(organizationPlugin)
  const hideSlug = () => props.hideSlug ?? config.hideSlug ?? false
  const [name, setName] = createSignal("")
  const [slug, setSlug] = createSignal("")
  const [slugEdited, setSlugEdited] = createSignal(false)
  const [isSubmitting, setIsSubmitting] = createSignal(false)
  const createOrganization = useCreateOrganization(auth.authClient, () => ({
    onSuccess: () => props.onOpenChange(false),
    onSettled: () => setIsSubmitting(false)
  }))
  createEffect(() => {
    if (!props.open) {
      setName("")
      setSlug("")
      setSlugEdited(false)
      return
    }

    if (slugEdited()) return

    setSlug(sanitizeSlug(name()))
  })

  const handleSubmit = async (event: SubmitEvent) => {
    event.preventDefault()
    if (isSubmitting()) return

    setIsSubmitting(true)
    const formData = new FormData(event.currentTarget as HTMLFormElement)
    const additionalValues: Record<string, unknown> = {}
    try {
      for (const field of config.additionalFields) {
        const value = parseAdditionalFieldValue(
          field,
          formData.get(field.name) as string | null
        )
        await field.validate?.(value)
        if (value !== undefined) additionalValues[field.name] = value
      }
    } catch (error) {
      setIsSubmitting(false)
      toast.error(error instanceof Error ? error.message : String(error))
      return
    }
    createOrganization.mutate({
      ...additionalValues,
      name: name(),
      slug: hideSlug() ? undefined : slug()
    })
  }

  const isPending = () => createOrganization.isPending || isSubmitting()

  return (
    <Dialog open={props.open} onOpenChange={props.onOpenChange}>
      <DialogContent>
        <form class="flex flex-col gap-6" onSubmit={handleSubmit}>
          <DialogHeader>
            <div class="flex size-10 items-center justify-center rounded-md bg-muted">
              <BriefcaseBusiness class="size-4.5" />
            </div>
            <DialogTitle>{config.localization.createOrganization}</DialogTitle>
            <DialogDescription>
              {config.localization.organizationsDescription}
            </DialogDescription>
          </DialogHeader>

          <Field>
            <FieldLabel for="create-organization-name">
              {config.localization.name}
            </FieldLabel>
            <Input
              autofocus
              disabled={isPending()}
              id="create-organization-name"
              name="name"
              onInput={(event) => setName(event.currentTarget.value)}
              placeholder={config.localization.namePlaceholder}
              required
              value={name()}
            />
          </Field>

          <Show when={!hideSlug()}>
            <SlugField
              disabled={isPending()}
              id="create-organization-slug"
              onChange={(value) => {
                setSlug(value)
                setSlugEdited(true)
              }}
              value={slug()}
            />
          </Show>

          <For each={config.additionalFields}>
            {(field) => (
              <AdditionalField
                field={field}
                isPending={isPending()}
                name={field.name}
                optionalLabel={auth.localization.settings.optional}
              />
            )}
          </For>

          <DialogFooter>
            <DialogClose
              as={Button}
              disabled={isPending()}
              type="button"
              variant="outline"
            >
              {auth.localization.settings.cancel}
            </DialogClose>
            <Button disabled={isPending()} type="submit">
              {isPending() ? (
                <>
                  <LoaderCircle class="size-4 animate-spin" />
                  {config.localization.createOrganization}
                </>
              ) : (
                config.localization.createOrganization
              )}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}

// examples/start-shadcn-example/src/components/auth/organization/create-organization-dialog.tsx
"use client"

import { parseAdditionalFieldValue } from "@better-auth-ui/core"
import type { OrganizationAuthClient } from "@better-auth-ui/core/plugins/organization"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useCreateOrganization } from "@better-auth-ui/react/plugins/organization"
import { Briefcase } from "lucide-react"
import { type SyntheticEvent, useEffect, useRef, useState } from "react"
import { toast } from "sonner"
import { Button, buttonVariants } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { organizationPlugin } from "@/lib/auth/organization-plugin"
import { AdditionalField } from "../additional-field"
import { SlugField, sanitizeSlug } from "./slug-field"

/** Props for the `CreateOrganizationDialog` component. */
export type CreateOrganizationDialogProps = {
  open: boolean
  onOpenChange: (open: boolean) => void
  hideSlug?: boolean
}

export function CreateOrganizationDialog({
  open,
  onOpenChange,
  hideSlug: hideSlugProp
}: CreateOrganizationDialogProps) {
  const { authClient, localization } = useAuth<OrganizationAuthClient>()
  const {
    additionalFields,
    localization: organizationLocalization,
    hideSlug: pluginHideSlug
  } = useAuthPlugin(organizationPlugin)
  const hideSlug = hideSlugProp ?? pluginHideSlug ?? false

  const [name, setName] = useState("")
  const [slug, setSlug] = useState("")
  const [slugEdited, setSlugEdited] = useState(false)
  const [nameError, setNameError] = useState<string>()
  const [isSubmitting, setIsSubmitting] = useState(false)
  const submissionLocked = useRef(false)

  const { mutate: createOrganization, isPending: isCreating } =
    useCreateOrganization(authClient, {
      onSuccess: () => onOpenChange(false),
      onSettled: () => {
        submissionLocked.current = false
        setIsSubmitting(false)
      }
    })

  const handleSubmit = async (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()
    if (submissionLocked.current) return

    submissionLocked.current = true
    setIsSubmitting(true)
    const formData = new FormData(e.currentTarget)
    const additionalValues: Record<string, unknown> = {}
    try {
      for (const field of additionalFields) {
        const value = parseAdditionalFieldValue(
          field,
          formData.get(field.name) as string | null
        )
        await field.validate?.(value)
        if (value !== undefined) additionalValues[field.name] = value
      }
    } catch (error) {
      submissionLocked.current = false
      setIsSubmitting(false)
      toast.error(error instanceof Error ? error.message : String(error))
      return
    }
    createOrganization({
      ...additionalValues,
      name,
      slug: hideSlug ? undefined : slug
    })
  }

  const isPending = isCreating || isSubmitting

  useEffect(() => {
    if (!open) {
      setSlug("")
      setName("")
      setSlugEdited(false)
      setNameError(undefined)
    }
  }, [open])

  useEffect(() => {
    if (slugEdited) return
    setSlug(sanitizeSlug(name))
  }, [name, slugEdited])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <form onSubmit={handleSubmit} className="flex flex-col gap-6">
          <DialogHeader>
            <DialogTitle className="flex items-center gap-2">
              <Briefcase />
              {organizationLocalization.createOrganization}
            </DialogTitle>

            <DialogDescription>
              {organizationLocalization.organizationsDescription}
            </DialogDescription>
          </DialogHeader>

          <div className="flex flex-col gap-4">
            <Field data-invalid={!!nameError}>
              <FieldLabel htmlFor="create-organization-name">
                {organizationLocalization.name}
              </FieldLabel>

              <Input
                id="create-organization-name"
                name="name"
                autoFocus
                required
                placeholder={organizationLocalization.namePlaceholder}
                value={name}
                onChange={(e) => {
                  setName(e.target.value)
                  setNameError(undefined)
                }}
                onInvalid={(e) => {
                  e.preventDefault()
                  setNameError(localization.auth.fieldRequired)
                }}
                aria-invalid={!!nameError}
                disabled={isPending}
              />

              <FieldError>{nameError}</FieldError>
            </Field>

            {!hideSlug && (
              <SlugField
                id="create-organization-slug"
                value={slug}
                onChange={(value) => {
                  setSlug(value)
                  setSlugEdited(true)
                }}
                disabled={isPending}
              />
            )}

            {additionalFields.map((field) => (
              <AdditionalField
                key={field.name}
                field={field}
                isPending={isPending}
                name={field.name}
                optionalLabel={localization.settings.optional}
              />
            ))}
          </div>

          <DialogFooter>
            <DialogClose
              className={buttonVariants({ variant: "outline" })}
              disabled={isPending}
              type="button"
            >
              {localization.settings.cancel}
            </DialogClose>

            <Button type="submit" disabled={isPending}>
              {isPending && <Spinner />}

              {organizationLocalization.createOrganization}
            </Button>
          </DialogFooter>
        </form>
      </DialogContent>
    </Dialog>
  )
}
