// examples/start-solid-zaidan-example/src/components/auth/email-otp/verify-email-otp.tsx
import { getAuthLinkURL, validateEmailAddress } from "@better-auth-ui/core"
import {
  type EmailOtpAuthClient,
  sendVerificationOtpOptions,
  verifyEmailOtpOptions
} from "@better-auth-ui/core/plugins/email-otp"
import { AuthLink, useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { Show } from "solid-js"
import { toast } from "solid-sonner"

import { OpenEmailButton } from "@/components/auth/open-email-button"
import { OtpField } from "@/components/auth/otp-field"
import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import { FieldGroup } from "@/components/ui/field"
import { Spinner } from "@/components/ui/spinner"
import { emailOtpPlugin } from "@/lib/auth/email-otp-plugin"
import {
  RESEND_COOLDOWN_SECONDS,
  useResendCooldown
} from "@/lib/auth/use-resend-cooldown"
import { cn } from "@/lib/utils"
import { createAuthForm, submitAuthForm } from "../auth-form"

/** `sessionStorage` key the sign-up and sign-in flows store the pending address under. */
export const VERIFY_EMAIL_STORAGE_KEY = "better-auth-ui.verify-email"

export type VerifyEmailOtpProps = {
  class?: string
}

/**
 * Verify an email address with a code instead of a link.
 *
 * Replaces the built-in `<VerifyEmail />` view when the email-OTP plugin runs
 * with `emailVerification: true`. The address comes from session storage when
 * sign-up or sign-in put it there; otherwise the user types it and requests a
 * code. Sign-up already triggered a send, so the resend button starts on
 * cooldown just like the link-based view.
 */
export function VerifyEmailOtp(props: VerifyEmailOtpProps) {
  const auth = useAuth()
  const { localization: emailOtpLocalization, otpLength } =
    useAuthPlugin(emailOtpPlugin)

  const storedEmail =
    typeof sessionStorage === "undefined"
      ? ""
      : (sessionStorage.getItem(VERIFY_EMAIL_STORAGE_KEY) ?? "")

  const { cooldown, isCoolingDown, startCooldown } = useResendCooldown(
    storedEmail ? RESEND_COOLDOWN_SECONDS : 0
  )

  const otpClient = () => auth.authClient as EmailOtpAuthClient

  const sendCode = createMutation(() => ({
    ...sendVerificationOtpOptions(otpClient()),
    onSuccess: (_data, variables) => {
      const sentTo = (variables as { email: string }).email
      sessionStorage.setItem(VERIFY_EMAIL_STORAGE_KEY, sentTo)
      form.setFieldValue("email", sentTo)
      startCooldown()
      toast.success(emailOtpLocalization.codeSent)
    }
  }))

  const verifyEmail = createMutation(() => ({
    ...verifyEmailOtpOptions(otpClient()),
    onError: () => form.setFieldValue("code", ""),
    onSuccess: () => {
      sessionStorage.removeItem(VERIFY_EMAIL_STORAGE_KEY)
      toast.success(emailOtpLocalization.emailVerified)
      auth.navigate({ to: auth.redirectTo })
    }
  }))

  const isPending = () => sendCode.isPending || verifyEmail.isPending

  const form = createAuthForm(() => ({
    defaultValues: { code: "", email: storedEmail },
    onSubmit: async ({ value }) => {
      if (!storedEmail && !sessionStorage.getItem(VERIFY_EMAIL_STORAGE_KEY)) {
        await sendCode.mutateAsync({
          email: value.email,
          type: "email-verification"
        } as Parameters<typeof sendCode.mutateAsync>[0])
        return
      }
      await verifyEmail.mutateAsync({
        email: value.email,
        otp: value.code
      } as Parameters<typeof verifyEmail.mutateAsync>[0])
    }
  }))
  const email = () => form.state.values.email
  const code = () => form.state.values.code
  const verifyCode = async (completedCode: string) => {
    if (isPending() || !email()) return
    form.setFieldValue("code", completedCode)
    await submitAuthForm(form)
  }

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.verifyEmail}
        </CardTitle>

        <Show when={email()}>
          <CardDescription>
            {emailOtpLocalization.codeSentTo.replace("{{email}}", email())}
          </CardDescription>
        </Show>
      </CardHeader>

      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot aria-label={auth.localization.auth.verifyEmail}>
            <FieldGroup>
              <Show
                when={email()}
                fallback={
                  <form.AppField
                    name="email"
                    validators={{
                      onChange: ({ value }) =>
                        validateEmailAddress(value, {
                          invalidMessage: auth.localization.auth.invalidEmail,
                          requiredMessage: auth.localization.auth.fieldRequired
                        })
                    }}
                  >
                    {(field) => (
                      <field.AuthFormTextField
                        autocomplete="email"
                        disabled={isPending()}
                        id="verify-email-address"
                        label={auth.localization.auth.email}
                        placeholder={auth.localization.auth.emailPlaceholder}
                        type="email"
                      />
                    )}
                  </form.AppField>
                }
              >
                <OtpField
                  autofocus
                  disabled={isPending()}
                  id="verify-email-code"
                  label={emailOtpLocalization.code}
                  length={otpLength}
                  name="otp"
                  onInput={(value) => form.setFieldValue("code", value)}
                  onComplete={verifyCode}
                  value={code()}
                />
              </Show>

              <div class="flex flex-col gap-3">
                <Button
                  class="w-full"
                  disabled={
                    isPending() ||
                    (Boolean(email()) && code().length !== otpLength)
                  }
                  type="submit"
                >
                  <Show when={isPending()}>
                    <Spinner />
                  </Show>

                  {email()
                    ? emailOtpLocalization.verifyCode
                    : emailOtpLocalization.sendCode}
                </Button>

                <Show when={email()}>
                  <OpenEmailButton email={email()} variant="secondary" />

                  <Button
                    class="w-full"
                    disabled={isPending() || isCoolingDown()}
                    onClick={() =>
                      void sendCode.mutateAsync({
                        email: email(),
                        type: "email-verification"
                      } as Parameters<typeof sendCode.mutateAsync>[0])
                    }
                    type="button"
                    variant="outline"
                  >
                    {isCoolingDown()
                      ? auth.localization.auth.resendIn.replace(
                          "{{seconds}}",
                          String(cooldown())
                        )
                      : auth.localization.auth.resend}
                  </Button>
                </Show>
              </div>
              <form.AuthFormServerError />
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>
      </CardContent>

      <CardFooter class="justify-center">
        <p class="text-sm text-muted-foreground">
          {auth.localization.auth.alreadyVerifiedYourEmail}{" "}
          <AuthLink
            class="underline underline-offset-4"
            href={getAuthLinkURL(
              `${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`,
              auth.redirectTo
            )}
          >
            {auth.localization.auth.signIn}
          </AuthLink>
        </p>
      </CardFooter>
    </Card>
  )
}

// examples/start-shadcn-baseui-example/src/components/auth/email-otp/verify-email-otp.tsx
"use client"

import { getAuthLinkURL } from "@better-auth-ui/core"
import type { EmailOtpAuthClient } from "@better-auth-ui/core/plugins/email-otp"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import {
  useSendVerificationOtp,
  useVerifyEmailOtp
} from "@better-auth-ui/react/plugins/email-otp"
import { useSelector } from "@tanstack/react-form"
import { useEffect, useState } from "react"
import { toast } from "sonner"

import { Button } from "@/components/ui/button"
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle
} from "@/components/ui/card"
import {
  Field,
  FieldDescription,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { emailOtpPlugin } from "@/lib/auth/email-otp-plugin"
import {
  RESEND_COOLDOWN_SECONDS,
  useResendCooldown
} from "@/lib/auth/use-resend-cooldown"
import { cn } from "@/lib/utils"
import { useAuthForm } from "../auth-form"
import { OpenEmailButton } from "../open-email-button"
import { OtpField } from "../otp-field"
import { useIsHydrated } from "../use-is-hydrated"

/** `sessionStorage` key the sign-up and sign-in flows store the pending address under. */
export const VERIFY_EMAIL_STORAGE_KEY = "better-auth-ui.verify-email"

export type VerifyEmailOtpProps = {
  className?: string
}

/**
 * Verify an email address with a code instead of a link.
 *
 * Replaces the built-in `<VerifyEmail />` view when the email-OTP plugin runs
 * with `emailVerification: true`. The address comes from session storage when
 * sign-up or sign-in put it there; otherwise the user types it and requests a
 * code. Sign-up already triggered a send, so the resend button starts on
 * cooldown just like the link-based view.
 *
 * @param className - Additional CSS classes applied to the card.
 */
export function VerifyEmailOtp({ className }: VerifyEmailOtpProps) {
  const {
    authClient,
    basePaths,
    localization,
    navigate,
    redirectTo,
    viewPaths,
    Link
  } = useAuth()
  const { localization: emailOtpLocalization, otpLength } =
    useAuthPlugin(emailOtpPlugin)

  const otpClient = authClient as EmailOtpAuthClient
  const isHydrated = useIsHydrated()

  const [email, setEmail] = useState(
    (isHydrated && sessionStorage.getItem(VERIFY_EMAIL_STORAGE_KEY)) || ""
  )

  const { cooldown, isCoolingDown, startCooldown } = useResendCooldown()

  // Sign-up already sent a code to this address, so restoring it also starts
  // the cooldown — otherwise the hydrated render would offer an immediate
  // resend and walk straight into the server's rate limit.
  useEffect(() => {
    const pendingEmail = sessionStorage.getItem(VERIFY_EMAIL_STORAGE_KEY) ?? ""
    setEmail(pendingEmail)

    if (pendingEmail) startCooldown(RESEND_COOLDOWN_SECONDS)
  }, [startCooldown])

  const { mutateAsync: sendVerificationOtp, isPending: isSending } =
    useSendVerificationOtp(otpClient, {
      onSuccess: (_data, { email: sentTo }) => {
        sessionStorage.setItem(VERIFY_EMAIL_STORAGE_KEY, sentTo)
        setEmail(sentTo)
        startCooldown()
        toast.success(emailOtpLocalization.codeSent)
      }
    })

  const { mutateAsync: verifyEmailOtp, isPending: isVerifying } =
    useVerifyEmailOtp(otpClient, {
      onError: () => form.setFieldValue("code", ""),
      onSuccess: () => {
        sessionStorage.removeItem(VERIFY_EMAIL_STORAGE_KEY)
        toast.success(emailOtpLocalization.emailVerified)
        navigate({ to: redirectTo })
      }
    })

  const isPending = isSending || isVerifying

  const verifyCode = async (completedCode: string) => {
    if (isPending || !email) return

    await verifyEmailOtp({ email, otp: completedCode })
  }

  const form = useAuthForm({
    defaultValues: { code: "", email: "" },
    onSubmit: async ({ value }) => {
      if (!email) {
        await sendVerificationOtp({
          email: value.email,
          type: "email-verification"
        })
        return
      }
      await verifyCode(value.code)
    }
  })
  const codeComplete = useSelector(
    form.store,
    (state) => state.values.code.length === otpLength
  )

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl">
          {localization.auth.verifyEmail}
        </CardTitle>

        {email && (
          <CardDescription>
            {emailOtpLocalization.codeSentTo.replace("{{email}}", email)}
          </CardDescription>
        )}
      </CardHeader>

      <CardContent>
        <form.AppForm>
          <form.AuthFormRoot>
            <FieldGroup>
              {email ? (
                <form.AppField name="code">
                  {(field) => (
                    <OtpField
                      autoFocus
                      disabled={isPending}
                      label={emailOtpLocalization.code}
                      length={otpLength}
                      name="otp"
                      value={field.state.value}
                      onChange={field.handleChange}
                      onComplete={verifyCode}
                    />
                  )}
                </form.AppField>
              ) : (
                <form.AppField name="email">
                  {(field) => (
                    <Field>
                      <FieldLabel htmlFor="email">
                        {localization.auth.email}
                      </FieldLabel>

                      <Input
                        id="email"
                        name={field.name}
                        type="email"
                        autoComplete="email"
                        placeholder={localization.auth.emailPlaceholder}
                        required
                        disabled={isPending}
                        value={field.state.value}
                        onBlur={field.handleBlur}
                        onChange={(event) =>
                          field.handleChange(event.target.value)
                        }
                      />

                      <field.AuthFormFieldError />
                    </Field>
                  )}
                </form.AppField>
              )}

              <div className="flex flex-col gap-3">
                <form.AuthFormSubmitButton
                  disabled={isPending || (Boolean(email) && !codeComplete)}
                >
                  {isPending && <Spinner />}

                  {email
                    ? emailOtpLocalization.verifyCode
                    : emailOtpLocalization.sendCode}
                </form.AuthFormSubmitButton>

                {email && <OpenEmailButton email={email} variant="secondary" />}

                {email && (
                  <Button
                    type="button"
                    variant="outline"
                    disabled={isPending || isCoolingDown}
                    onClick={() =>
                      sendVerificationOtp({ email, type: "email-verification" })
                    }
                  >
                    {isCoolingDown
                      ? localization.auth.resendIn.replace(
                          "{{seconds}}",
                          String(cooldown)
                        )
                      : localization.auth.resend}
                  </Button>
                )}
              </div>
            </FieldGroup>
          </form.AuthFormRoot>
        </form.AppForm>

        <div className="flex flex-col gap-3 items-center w-full mt-4">
          <FieldDescription className="text-center">
            {localization.auth.alreadyVerifiedYourEmail}{" "}
            <Link
              href={getAuthLinkURL(
                `${basePaths.auth}/${viewPaths.auth.signIn}`,
                redirectTo
              )}
              className="underline underline-offset-4"
            >
              {localization.auth.signIn}
            </Link>
          </FieldDescription>
        </div>
      </CardContent>
    </Card>
  )
}
