// packages/react-native/src/components/auth/anonymous/anonymous-button.tsx
import { authMutationKeys } from "@better-auth-ui/core"
import type { AnonymousAuthClient } from "@better-auth-ui/core/plugins/anonymous"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useSignInAnonymous } from "@better-auth-ui/react/plugins/anonymous"
import { useIsMutating } from "@tanstack/react-query"
import { anonymousPlugin } from "../../../lib/auth/anonymous-plugin"
import { useSignInContinuation } from "../../../lib/auth/use-sign-in-continuation"
import { Button } from "../../../primitives/button"

export function AnonymousButton() {
  const { authClient } = useAuth()
  const { localization } = useAuthPlugin(anonymousPlugin)
  const onSuccess = useSignInContinuation()
  const mutation = useSignInAnonymous(authClient as AnonymousAuthClient, {
    onSuccess
  })
  const signInPending = useIsMutating({
    mutationKey: authMutationKeys.signIn.all
  })
  const signUpPending = useIsMutating({
    mutationKey: authMutationKeys.signUp.all
  })
  return (
    <Button
      onPress={() => mutation.mutate()}
      isPending={mutation.isPending}
      isDisabled={signInPending + signUpPending > 0}
    >
      {localization.continueAsGuest}
    </Button>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/anonymous/anonymous-button.tsx
import { authMutationKeys } from "@better-auth-ui/core"
import type { AnonymousAuthClient } from "@better-auth-ui/core/plugins/anonymous"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useSignInAnonymous } from "@better-auth-ui/solid/plugins/anonymous"
import { useIsMutating } from "@tanstack/solid-query"
import { UserRound } from "lucide-solid"
import { Show } from "solid-js"

import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"
import { anonymousPlugin } from "@/lib/auth/anonymous-plugin"
import { cn } from "cn"

/** Sign in with a temporary anonymous account. */
export function AnonymousButton() {
  const auth = useAuth()
  const { localization } = useAuthPlugin(anonymousPlugin)
  const signInAnonymous = useSignInAnonymous(
    auth.authClient as AnonymousAuthClient,
    () => ({
      onSuccess: () => auth.navigate({ to: auth.redirectTo })
    })
  )

  const signInMutating = useIsMutating(() => ({
    mutationKey: authMutationKeys.signIn.all
  }))
  const signUpMutating = useIsMutating(() => ({
    mutationKey: authMutationKeys.signUp.all
  }))
  const isPending = () => signInMutating() + signUpMutating() > 0

  return (
    <Button
      class={cn("w-full", isPending() && "pointer-events-none")}
      disabled={isPending()}
      onClick={() => signInAnonymous.mutate(undefined)}
      type="button"
      variant="outline"
    >
      <Show
        fallback={<UserRound data-icon="inline-start" />}
        when={signInAnonymous.isPending}
      >
        <Spinner data-icon="inline-start" />
      </Show>
      {localization.continueAsGuest}
    </Button>
  )
}
