// examples/start-solid-zaidan-example/src/components/ui/alert.tsx
import type { PolymorphicProps } from "@kobalte/core"
import { type AlertRootProps, Root } from "@kobalte/core/alert"
import { cva, type VariantProps } from "class-variance-authority"
import type { ComponentProps, ValidComponent } from "solid-js"
import { splitProps } from "solid-js"
import { cn } from "@/lib/utils"

const alertVariants = cva("group/alert relative z-alert w-full", {
  variants: {
    variant: {
      default: "z-alert-variant-default",
      destructive: "z-alert-variant-destructive"
    }
  },
  defaultVariants: {
    variant: "default"
  }
})

type AlertProps<T extends ValidComponent = "div"> = PolymorphicProps<
  T,
  AlertRootProps<T>
> &
  VariantProps<typeof alertVariants>

const Alert = <T extends ValidComponent = "div">(props: AlertProps<T>) => {
  const [local, others] = splitProps(props as AlertProps, ["class", "variant"])

  return (
    <Root
      class={cn(alertVariants({ variant: local.variant }), local.class)}
      data-slot="alert"
      role="alert"
      {...others}
    />
  )
}

type AlertTitleProps = ComponentProps<"div">

const AlertTitle = (props: AlertTitleProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <div
      class={cn(
        "z-alert-title z-font-heading [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground",
        local.class
      )}
      data-slot="alert-title"
      {...others}
    />
  )
}

type AlertDescriptionProps = ComponentProps<"div">

const AlertDescription = (props: AlertDescriptionProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <div
      class={cn(
        "z-alert-description [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground",
        local.class
      )}
      data-slot="alert-description"
      {...others}
    />
  )
}

type AlertActionProps = ComponentProps<"div">

const AlertAction = (props: AlertActionProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <div
      class={cn("z-alert-action", local.class)}
      data-slot="alert-action"
      {...others}
    />
  )
}

export { Alert, AlertAction, AlertDescription, AlertTitle, alertVariants }

// examples/start-shadcn-example/src/components/ui/alert.tsx
import { cva, type VariantProps } from "class-variance-authority"
import type * as React from "react"

import { cn } from "@/lib/utils"

const alertVariants = cva(
  "group/alert relative grid w-full gap-0.5 rounded-lg border px-2.5 py-2 text-left text-sm has-data-[slot=alert-action]:relative has-data-[slot=alert-action]:pr-18 has-[>svg]:grid-cols-[auto_1fr] has-[>svg]:gap-x-2 *:[svg]:row-span-2 *:[svg]:translate-y-0.5 *:[svg]:text-current *:[svg:not([class*='size-'])]:size-4",
  {
    variants: {
      variant: {
        default: "bg-card text-card-foreground",
        destructive:
          "bg-card text-destructive *:data-[slot=alert-description]:text-destructive/90 *:[svg]:text-current"
      }
    },
    defaultVariants: {
      variant: "default"
    }
  }
)

function Alert({
  className,
  variant,
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof alertVariants>) {
  return (
    <div
      data-slot="alert"
      role="alert"
      className={cn(alertVariants({ variant }), className)}
      {...props}
    />
  )
}

function AlertTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-title"
      className={cn(
        "font-medium group-has-[>svg]/alert:col-start-2 [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground",
        className
      )}
      {...props}
    />
  )
}

function AlertDescription({
  className,
  ...props
}: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-description"
      className={cn(
        "text-sm text-balance text-muted-foreground md:text-pretty [&_a]:underline [&_a]:underline-offset-3 [&_a]:hover:text-foreground [&_p:not(:last-child)]:mb-4",
        className
      )}
      {...props}
    />
  )
}

function AlertAction({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-action"
      className={cn("absolute top-2 right-2", className)}
      {...props}
    />
  )
}

export { Alert, AlertAction, AlertDescription, AlertTitle, alertVariants }
