// packages/heroui/src/components/auth/api-key/api-key.tsx
import type { ListedApiKey } from "@better-auth-ui/core/plugins/api-key"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { Key, Xmark } from "@gravity-ui/icons"
import { Button } from "@heroui/react"
import { useState } from "react"

import { apiKeyPlugin } from "../../../lib/auth/api-key-plugin"
import { DeleteApiKeyDialog } from "./delete-api-key-dialog"

export type ApiKeyProps = {
  apiKey: ListedApiKey
  /** Hide the row's delete button (e.g., when caller lacks `apiKey:delete`). */
  hideDelete?: boolean
  /** Scope the delete payload to an organization (sets `configId`). */
  organizationId?: string
}

export function ApiKey({ apiKey, hideDelete, organizationId }: ApiKeyProps) {
  const { localization } = useAuth()
  const { localization: apiKeyLocalization } = useAuthPlugin(apiKeyPlugin)
  const [deleteOpen, setDeleteOpen] = useState(false)

  const preview = `${apiKey.start}${"*".repeat(16)}`

  return (
    <div className="flex items-center gap-3">
      <div className="flex size-10 shrink-0 items-center justify-center rounded-xl bg-surface-secondary">
        <Key className="size-4.5" />
      </div>

      <div className="flex flex-col min-w-0">
        <span className="text-sm font-medium leading-tight truncate">
          {apiKey.name || apiKeyLocalization.apiKey}
        </span>

        <span className="text-xs text-muted font-mono truncate">{preview}</span>

        <span className="text-xs text-muted">
          {apiKeyLocalization.created}{" "}
          {new Date(apiKey.createdAt).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short"
          })}
        </span>

        <span className="text-xs text-muted">
          {apiKey.expiresAt
            ? `${apiKeyLocalization.expires} ${new Date(
                apiKey.expiresAt
              ).toLocaleString(undefined, {
                dateStyle: "medium",
                timeStyle: "short"
              })}`
            : apiKeyLocalization.neverExpires}
        </span>
      </div>

      {!hideDelete && (
        <>
          <Button
            className="ml-auto shrink-0"
            variant="outline"
            size="sm"
            onPress={() => setDeleteOpen(true)}
            aria-label={apiKeyLocalization.deleteApiKey}
          >
            <Xmark />

            {localization.settings.delete}
          </Button>

          <DeleteApiKeyDialog
            isOpen={deleteOpen}
            onOpenChange={setDeleteOpen}
            apiKey={apiKey}
            organizationId={organizationId}
          />
        </>
      )}
    </div>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/api-key.tsx
import { apiKeyLocalization } from "@better-auth-ui/core/plugins"
import { useAuth } from "@better-auth-ui/solid"
import { Key, X } from "lucide-solid"
import { createSignal } from "solid-js"
import { DeleteApiKeyDialog } from "@/components/auth/api-key/delete-api-key-dialog"
import type { ListedApiKey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import { Dialog, DialogTrigger } from "@/components/ui/dialog"

export function ApiKey(props: { apiKey: ListedApiKey }) {
  const auth = useAuth()
  const [deleteOpen, setDeleteOpen] = createSignal(false)
  const preview = () => `${props.apiKey.start}${"*".repeat(16)}`

  return (
    <div class="flex items-center gap-3 p-0">
      <div class="flex size-10 shrink-0 items-center justify-center rounded-md bg-muted">
        <Key class="size-4.5" />
      </div>

      <div class="flex min-w-0 flex-col">
        <span class="truncate font-medium text-sm leading-tight">
          {props.apiKey.name || apiKeyLocalization.apiKey}
        </span>
        <span class="truncate font-mono text-muted-foreground text-xs">
          {preview()}
        </span>
        <span class="text-muted-foreground text-xs">
          {new Date(props.apiKey.createdAt).toLocaleString(undefined, {
            dateStyle: "medium",
            timeStyle: "short"
          })}
        </span>
      </div>

      <Dialog open={deleteOpen()} onOpenChange={setDeleteOpen}>
        <DialogTrigger
          as={Button}
          aria-label={apiKeyLocalization.deleteApiKey}
          class="ml-auto shrink-0"
          size="sm"
          variant="outline"
        >
          <X />
          {auth.localization.settings.delete}
        </DialogTrigger>
        <DeleteApiKeyDialog
          apiKey={props.apiKey}
          onOpenChange={setDeleteOpen}
        />
      </Dialog>
    </div>
  )
}
