// packages/heroui/src/components/auth/api-key/edit-api-key-dialog.tsx
import type {
  ApiKeyAuthClient,
  ListedApiKey
} from "@better-auth-ui/core/plugins/api-key"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useUpdateApiKey } from "@better-auth-ui/react/plugins/api-key"
import {
  AlertDialog,
  Button,
  Form,
  Input,
  Label,
  Spinner,
  Switch,
  TextArea,
  TextField
} from "@heroui/react"
import { type FormEvent, useState } from "react"
import { apiKeyPlugin } from "../../../lib/auth/api-key-plugin"

const optionalNumber = (formData: FormData, name: string) => {
  const value = formData.get(name)
  return typeof value === "string" && value.trim() ? Number(value) : undefined
}

export function EditApiKeyDialog({
  apiKey,
  isOpen,
  onOpenChange
}: {
  apiKey: ListedApiKey
  isOpen: boolean
  onOpenChange: (open: boolean) => void
}) {
  const { authClient, localization } = useAuth()
  const { localization: labels } = useAuthPlugin(apiKeyPlugin)
  const [enabled, setEnabled] = useState(apiKey.enabled)
  const [rateLimitEnabled, setRateLimitEnabled] = useState(
    apiKey.rateLimitEnabled
  )
  const [formError, setFormError] = useState<string>()
  const updateApiKey = useUpdateApiKey(authClient as ApiKeyAuthClient, {
    onSuccess: () => onOpenChange(false)
  })

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault()
    setFormError(undefined)
    const formData = new FormData(event.currentTarget)
    try {
      const metadataText = String(formData.get("metadata") ?? "").trim()
      const permissionsText = String(formData.get("permissions") ?? "").trim()
      updateApiKey.mutate({
        keyId: apiKey.id,
        configId: apiKey.configId,
        name: String(formData.get("name") ?? "").trim(),
        enabled,
        rateLimitEnabled,
        remaining: optionalNumber(formData, "remaining"),
        refillAmount: optionalNumber(formData, "refillAmount"),
        refillInterval: optionalNumber(formData, "refillInterval"),
        rateLimitMax: optionalNumber(formData, "rateLimitMax"),
        rateLimitTimeWindow: optionalNumber(formData, "rateLimitTimeWindow"),
        metadata: metadataText ? JSON.parse(metadataText) : null,
        permissions: permissionsText ? JSON.parse(permissionsText) : null
      })
    } catch {
      setFormError("Metadata and permissions must contain valid JSON.")
    }
  }

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={onOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog className="max-w-xl">
          <Form onSubmit={submit}>
            <AlertDialog.CloseTrigger />
            <AlertDialog.Header>
              <AlertDialog.Heading>{labels.editApiKey}</AlertDialog.Heading>
            </AlertDialog.Header>
            <AlertDialog.Body className="overflow-visible">
              <div className="grid gap-4 sm:grid-cols-2">
                <TextField className="sm:col-span-2" name="name">
                  <Label>{labels.name}</Label>
                  <Input defaultValue={apiKey.name ?? ""} variant="secondary" />
                </TextField>
                <Switch isSelected={enabled} onChange={setEnabled}>
                  {labels.enabled}
                </Switch>
                <Switch
                  isSelected={rateLimitEnabled}
                  onChange={setRateLimitEnabled}
                >
                  {labels.rateLimit}
                </Switch>
                <NumericField
                  name="remaining"
                  label={labels.remaining}
                  value={apiKey.remaining}
                />
                <NumericField
                  name="refillAmount"
                  label={labels.refillAmount}
                  value={apiKey.refillAmount}
                />
                <NumericField
                  name="refillInterval"
                  label={labels.refillInterval}
                  value={apiKey.refillInterval}
                />
                <NumericField
                  name="rateLimitMax"
                  label={labels.rateLimitMax}
                  value={apiKey.rateLimitMax}
                />
                <NumericField
                  name="rateLimitTimeWindow"
                  label={labels.rateLimitWindow}
                  value={apiKey.rateLimitTimeWindow}
                />
                <TextField className="sm:col-span-2" name="metadata">
                  <Label>{labels.metadata}</Label>
                  <TextArea
                    defaultValue={
                      apiKey.metadata
                        ? JSON.stringify(apiKey.metadata, null, 2)
                        : ""
                    }
                    rows={3}
                    variant="secondary"
                  />
                </TextField>
                <TextField className="sm:col-span-2" name="permissions">
                  <Label>{labels.permissions}</Label>
                  <TextArea
                    defaultValue={
                      apiKey.permissions
                        ? JSON.stringify(apiKey.permissions, null, 2)
                        : ""
                    }
                    rows={3}
                    variant="secondary"
                  />
                </TextField>
              </div>
              {(formError || updateApiKey.error) && (
                <p className="mt-3 text-sm text-danger" role="alert">
                  {formError ??
                    updateApiKey.error?.error?.message ??
                    updateApiKey.error?.message}
                </p>
              )}
            </AlertDialog.Body>
            <AlertDialog.Footer>
              <Button slot="close" variant="tertiary">
                {localization.settings.cancel}
              </Button>
              <Button isPending={updateApiKey.isPending} type="submit">
                {updateApiKey.isPending && (
                  <Spinner color="current" size="sm" />
                )}
                {localization.settings.saveChanges}
              </Button>
            </AlertDialog.Footer>
          </Form>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}

function NumericField({
  name,
  label,
  value
}: {
  name: string
  label: string
  value: number | null
}) {
  return (
    <TextField name={name} type="number">
      <Label>{label}</Label>
      <Input defaultValue={value ?? undefined} min={0} variant="secondary" />
    </TextField>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/edit-api-key-dialog.tsx
import type { ApiKeyAuthClient } from "@better-auth-ui/core/plugins/api-key"
import { useAuth, useAuthPlugin } from "@better-auth-ui/solid"
import { useUpdateApiKey } from "@better-auth-ui/solid/plugins/api-key"
import { createSignal, Show } from "solid-js"
import type { ListedApiKey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import {
  Field,
  FieldError,
  FieldGroup,
  FieldLabel
} from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Switch } from "@/components/ui/switch"
import { Textarea } from "@/components/ui/textarea"
import { apiKeyPlugin } from "@/lib/auth/api-key-plugin"

const optionalNumber = (formData: FormData, name: string) => {
  const value = String(formData.get(name) ?? "").trim()
  return value ? Number(value) : undefined
}

export function EditApiKeyDialog(props: {
  apiKey: ListedApiKey
  onOpenChange: (open: boolean) => void
}) {
  const auth = useAuth<ApiKeyAuthClient>()
  const { localization: labels } = useAuthPlugin(apiKeyPlugin)
  const [enabled, setEnabled] = createSignal(props.apiKey.enabled)
  const [rateLimitEnabled, setRateLimitEnabled] = createSignal(
    props.apiKey.rateLimitEnabled
  )
  const [formError, setFormError] = createSignal<string>()
  const updateApiKey = useUpdateApiKey(auth.authClient, () => ({
    onSuccess: () => props.onOpenChange(false)
  }))
  const submit = (event: SubmitEvent) => {
    event.preventDefault()
    const formData = new FormData(event.currentTarget as HTMLFormElement)
    try {
      const metadata = String(formData.get("metadata") ?? "").trim()
      const permissions = String(formData.get("permissions") ?? "").trim()
      setFormError(undefined)
      updateApiKey.mutate({
        keyId: props.apiKey.id,
        configId: props.apiKey.configId,
        name: String(formData.get("name") ?? "").trim(),
        enabled: enabled(),
        rateLimitEnabled: rateLimitEnabled(),
        remaining: optionalNumber(formData, "remaining"),
        refillAmount: optionalNumber(formData, "refillAmount"),
        refillInterval: optionalNumber(formData, "refillInterval"),
        rateLimitMax: optionalNumber(formData, "rateLimitMax"),
        rateLimitTimeWindow: optionalNumber(formData, "rateLimitTimeWindow"),
        metadata: metadata ? JSON.parse(metadata) : null,
        permissions: permissions ? JSON.parse(permissions) : null
      })
    } catch {
      setFormError("Metadata and permissions must contain valid JSON.")
    }
  }
  return (
    <DialogContent class="sm:max-w-xl">
      <form class="flex flex-col gap-6" onSubmit={submit}>
        <DialogHeader>
          <DialogTitle>{labels.editApiKey}</DialogTitle>
        </DialogHeader>
        <FieldGroup class="grid gap-4 sm:grid-cols-2">
          <Field class="sm:col-span-2">
            <FieldLabel for={`api-key-name-${props.apiKey.id}`}>
              {labels.name}
            </FieldLabel>
            <Input
              id={`api-key-name-${props.apiKey.id}`}
              name="name"
              value={props.apiKey.name ?? ""}
            />
          </Field>
          <Field orientation="horizontal">
            <Switch checked={enabled()} onChange={setEnabled} />
            <FieldLabel>{labels.enabled}</FieldLabel>
          </Field>
          <Field orientation="horizontal">
            <Switch
              checked={rateLimitEnabled()}
              onChange={setRateLimitEnabled}
            />
            <FieldLabel>{labels.rateLimit}</FieldLabel>
          </Field>
          <NumericField
            name="remaining"
            label={labels.remaining}
            value={props.apiKey.remaining}
          />
          <NumericField
            name="refillAmount"
            label={labels.refillAmount}
            value={props.apiKey.refillAmount}
          />
          <NumericField
            name="refillInterval"
            label={labels.refillInterval}
            value={props.apiKey.refillInterval}
          />
          <NumericField
            name="rateLimitMax"
            label={labels.rateLimitMax}
            value={props.apiKey.rateLimitMax}
          />
          <NumericField
            name="rateLimitTimeWindow"
            label={labels.rateLimitWindow}
            value={props.apiKey.rateLimitTimeWindow}
          />
          <Field class="sm:col-span-2">
            <FieldLabel>{labels.metadata}</FieldLabel>
            <Textarea
              name="metadata"
              value={
                props.apiKey.metadata
                  ? JSON.stringify(props.apiKey.metadata, null, 2)
                  : ""
              }
            />
          </Field>
          <Field class="sm:col-span-2">
            <FieldLabel>{labels.permissions}</FieldLabel>
            <Textarea
              name="permissions"
              value={
                props.apiKey.permissions
                  ? JSON.stringify(props.apiKey.permissions, null, 2)
                  : ""
              }
            />
          </Field>
          <Show when={formError() || updateApiKey.error}>
            <FieldError class="sm:col-span-2">
              {formError() ??
                updateApiKey.error?.error?.message ??
                updateApiKey.error?.message}
            </FieldError>
          </Show>
        </FieldGroup>
        <DialogFooter>
          <DialogClose as={Button} variant="outline">
            {auth.localization.settings.cancel}
          </DialogClose>
          <Button disabled={updateApiKey.isPending} type="submit">
            {auth.localization.settings.saveChanges}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  )
}

function NumericField(props: {
  name: string
  label: string
  value: number | null
}) {
  return (
    <Field>
      <FieldLabel for={`api-key-${props.name}`}>{props.label}</FieldLabel>
      <Input
        id={`api-key-${props.name}`}
        name={props.name}
        type="number"
        min="0"
        value={props.value ?? undefined}
      />
    </Field>
  )
}
