// packages/react-native/src/components/auth/api-key/new-api-key-dialog.tsx
import { apiKeyPlugin } from "@better-auth-ui/core/plugins"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useState } from "react"
import { Text, View } from "react-native"
import { copyText } from "../../../lib/clipboard"
import { useThemeColors } from "../../../lib/theme-colors"
import { AlertDialog } from "../../../primitives/alert-dialog"
import { Button } from "../../../primitives/button"
import { Label, TextField } from "../../../primitives/field"
import { InputGroup } from "../../../primitives/input"
import { toast } from "../../../primitives/toast"
import { Check, Copy, Key } from "../../../primitives/ui-icons"

export type NewApiKeyDialogProps = {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
  name: string | null
  secretKey: string | null
}

/**
 * "Copy your key now" reveal dialog shown right after an API key is created.
 * Mirrors heroui's `NewApiKeyDialog`, adapted for React Native: the secret is
 * displayed as read-only text (RN's `InputGroup.Input` always binds to an
 * editable `TextInput`, so a masked/static `Text` row stands in for it) and
 * copying uses the RN clipboard helper + a success toast instead of the web
 * `navigator.clipboard` call + a 1.5s copied-icon flip.
 */
export function NewApiKeyDialog({
  isOpen,
  onOpenChange,
  name,
  secretKey
}: NewApiKeyDialogProps) {
  const { localization } = useAuth()
  const { localization: apiKeyLocalization } = useAuthPlugin(apiKeyPlugin)
  const colors = useThemeColors()

  const [copied, setCopied] = useState(false)

  const copySecretKey = async () => {
    if (!secretKey) return

    try {
      await copyText(secretKey)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch (error) {
      toast.danger(error instanceof Error ? error.message : String(error))
    }
  }

  return (
    <AlertDialog isOpen={isOpen} onOpenChange={onOpenChange}>
      <AlertDialog.CloseTrigger />

      <AlertDialog.Header>
        <AlertDialog.Icon status="warning">
          <Key width={20} height={20} color={colors.danger} />
        </AlertDialog.Icon>

        <AlertDialog.Heading>
          {apiKeyLocalization.newApiKey}
        </AlertDialog.Heading>
      </AlertDialog.Header>

      <AlertDialog.Body>
        <Text className="text-sm text-muted">
          {apiKeyLocalization.newApiKeyWarning}
        </Text>

        <TextField value={secretKey ?? ""} className="gap-1.5">
          <Label>{name || apiKeyLocalization.apiKey}</Label>

          <InputGroup>
            <View className="h-full flex-1 justify-center">
              <Text
                className="font-mono text-xs text-foreground"
                numberOfLines={1}
              >
                {secretKey ?? ""}
              </Text>
            </View>

            <InputGroup.Suffix className="px-0">
              <Button
                isIconOnly
                aria-label={localization.settings.copyToClipboard}
                size="sm"
                variant="ghost"
                onPress={copySecretKey}
              >
                {copied ? (
                  <Check width={16} height={16} color={colors.muted} />
                ) : (
                  <Copy width={16} height={16} color={colors.muted} />
                )}
              </Button>
            </InputGroup.Suffix>
          </InputGroup>
        </TextField>
      </AlertDialog.Body>

      <AlertDialog.Footer>
        <Button variant="tertiary" onPress={() => onOpenChange(false)}>
          {apiKeyLocalization.dismissNewKey}
        </Button>
      </AlertDialog.Footer>
    </AlertDialog>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/new-api-key-dialog.tsx
import { apiKeyLocalization } from "@better-auth-ui/core/plugins/api-key"
import { useAuth } from "@better-auth-ui/solid"
import { Check, Copy, Key } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function NewApiKeyDialog(props: {
  name: string | null
  secretKey: string | null
}) {
  const auth = useAuth()
  const [isCopied, setIsCopied] = createSignal(false)

  const copySecretKey = async () => {
    if (!props.secretKey) return

    try {
      await navigator.clipboard.writeText(props.secretKey)
      setIsCopied(true)
      setTimeout(() => setIsCopied(false), 1500)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
    }
  }

  return (
    <DialogContent>
      <DialogHeader>
        <div class="flex size-10 items-center justify-center rounded-md bg-muted">
          <Key class="size-4.5" />
        </div>
        <DialogTitle>{apiKeyLocalization.newApiKey}</DialogTitle>
        <DialogDescription>
          {apiKeyLocalization.newApiKeyWarning}
        </DialogDescription>
      </DialogHeader>

      <div class="flex flex-col gap-2">
        <Label for="new-api-key-secret">
          {props.name || apiKeyLocalization.apiKey}
        </Label>
        <div class="flex rounded-md border bg-background">
          <Input
            class="rounded-r-none border-0 font-mono text-xs"
            id="new-api-key-secret"
            readonly
            value={props.secretKey ?? ""}
          />
          <Button
            aria-label={auth.localization.settings.copyToClipboard}
            onClick={copySecretKey}
            size="icon-xs"
            type="button"
            variant="ghost"
          >
            <Show fallback={<Copy />} when={isCopied()}>
              <Check />
            </Show>
          </Button>
        </div>
      </div>

      <DialogFooter>
        <DialogClose as={Button}>
          {apiKeyLocalization.dismissNewKey}
        </DialogClose>
      </DialogFooter>
    </DialogContent>
  )
}
