// packages/heroui/src/components/auth/api-key/new-api-key-dialog.tsx
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { Check, Copy, Key } from "@gravity-ui/icons"
import {
  Button,
  InputGroup,
  Label,
  Modal,
  TextField,
  toast
} from "@heroui/react"
import { useState } from "react"

import { apiKeyPlugin } from "../../../lib/auth/api-key-plugin"

export type NewApiKeyDialogProps = {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
  name: string | null
  secretKey: string | null
}

export function NewApiKeyDialog({
  isOpen,
  onOpenChange,
  name,
  secretKey
}: NewApiKeyDialogProps) {
  const { localization } = useAuth()
  const { localization: apiKeyLocalization } = useAuthPlugin(apiKeyPlugin)

  const [copied, setCopied] = useState(false)

  const handleOpenChange = (open: boolean) => {
    if (!open) {
      setCopied(false)
    }

    onOpenChange(open)
  }

  const copySecretKey = async () => {
    if (!secretKey) return

    try {
      await navigator.clipboard.writeText(secretKey)
      setCopied(true)
      setTimeout(() => setCopied(false), 1500)
    } catch (error) {
      toast.danger(error instanceof Error ? error.message : String(error))
    }
  }

  return (
    <Modal.Backdrop isOpen={isOpen} onOpenChange={handleOpenChange}>
      <Modal.Container>
        <Modal.Dialog>
          <Modal.CloseTrigger />

          <Modal.Header>
            <Modal.Icon className="bg-warning-soft text-warning-soft-foreground">
              <Key />
            </Modal.Icon>

            <Modal.Heading>{apiKeyLocalization.newApiKey}</Modal.Heading>
          </Modal.Header>

          <Modal.Body className="flex flex-col gap-4 overflow-visible">
            <p className="text-muted text-sm">
              {apiKeyLocalization.newApiKeyWarning}
            </p>

            <TextField value={secretKey ?? ""} className="font-mono text-xs">
              <Label>{name || apiKeyLocalization.apiKey}</Label>

              <InputGroup variant="secondary">
                <InputGroup.Input readOnly className="font-mono text-xs" />

                <InputGroup.Suffix className="px-0">
                  <Button
                    isIconOnly
                    aria-label={localization.settings.copyToClipboard}
                    size="sm"
                    variant="ghost"
                    onPress={copySecretKey}
                  >
                    {copied ? <Check /> : <Copy />}
                  </Button>
                </InputGroup.Suffix>
              </InputGroup>
            </TextField>
          </Modal.Body>

          <Modal.Footer>
            <Button onPress={() => handleOpenChange(false)}>
              {apiKeyLocalization.dismissNewKey}
            </Button>
          </Modal.Footer>
        </Modal.Dialog>
      </Modal.Container>
    </Modal.Backdrop>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/new-api-key-dialog.tsx
import { apiKeyLocalization } from "@better-auth-ui/core/plugins/api-key"
import { useAuth } from "@better-auth-ui/solid"
import { Check, Copy, Key } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"

export function NewApiKeyDialog(props: {
  name: string | null
  secretKey: string | null
}) {
  const auth = useAuth()
  const [isCopied, setIsCopied] = createSignal(false)

  const copySecretKey = async () => {
    if (!props.secretKey) return

    try {
      await navigator.clipboard.writeText(props.secretKey)
      setIsCopied(true)
      setTimeout(() => setIsCopied(false), 1500)
    } catch (error) {
      toast.error(error instanceof Error ? error.message : String(error))
    }
  }

  return (
    <DialogContent>
      <DialogHeader>
        <div class="flex size-10 items-center justify-center rounded-md bg-muted">
          <Key class="size-4.5" />
        </div>
        <DialogTitle>{apiKeyLocalization.newApiKey}</DialogTitle>
        <DialogDescription>
          {apiKeyLocalization.newApiKeyWarning}
        </DialogDescription>
      </DialogHeader>

      <div class="flex flex-col gap-2">
        <Label for="new-api-key-secret">
          {props.name || apiKeyLocalization.apiKey}
        </Label>
        <div class="flex rounded-md border bg-background">
          <Input
            class="rounded-r-none border-0 font-mono text-xs"
            id="new-api-key-secret"
            readonly
            value={props.secretKey ?? ""}
          />
          <Button
            aria-label={auth.localization.settings.copyToClipboard}
            onClick={copySecretKey}
            size="icon-xs"
            type="button"
            variant="ghost"
          >
            <Show fallback={<Copy />} when={isCopied()}>
              <Check />
            </Show>
          </Button>
        </div>
      </div>

      <DialogFooter>
        <DialogClose as={Button}>
          {apiKeyLocalization.dismissNewKey}
        </DialogClose>
      </DialogFooter>
    </DialogContent>
  )
}
