// examples/start-shadcn-baseui-example/src/components/auth/api-key/organization-api-keys.tsx
"use client"

import {
  hasMemberRole,
  type OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useSession } from "@better-auth-ui/react"
import { useListOrganizationMembers } from "@better-auth-ui/react/plugins/organization"
import { ApiKeys } from "./api-keys"

export type OrganizationApiKeysProps = {
  className?: string
  organizationId: string
  organizationSlug: string
}

/**
 * {@link ApiKeys} scoped to an explicit organization.
 *
 * Hidden for members whose role isn't `owner`. Better Auth's
 * `/organization/has-permission` endpoint isn't usable for `apiKey:*` checks
 * (it doesn't pass `allowCreatorAllPermissions` and the default org AC has no
 * `apiKey` statements), so we gate on role directly.
 */
export function OrganizationApiKeys({
  className,
  organizationId
}: OrganizationApiKeysProps) {
  const { authClient } = useAuth<OrganizationAuthClient>()
  const { data: session } = useSession(authClient)

  const { data: membersData } = useListOrganizationMembers(authClient, {
    query: { organizationId }
  })

  const canManageApiKeys = membersData?.members.some(
    (member) =>
      hasMemberRole(member.role, "owner") && member.userId === session?.user.id
  )

  if (!canManageApiKeys) {
    return null
  }

  return <ApiKeys className={className} organizationId={organizationId} />
}

// examples/start-solid-zaidan-example/src/components/auth/api-key/organization-api-keys.tsx
import {
  hasMemberRole,
  type OrganizationAuthClient
} from "@better-auth-ui/core/plugins/organization"
import { useAuth, useSession } from "@better-auth-ui/solid"
import { useListOrganizationMembers } from "@better-auth-ui/solid/plugins/organization"
import { createMemo, Show } from "solid-js"
import { ApiKeys } from "@/components/auth/api-key/api-keys"

export type OrganizationApiKeysProps = {
  class?: string
  organizationId: string
  organizationSlug: string
}

/**
 * {@link ApiKeys} scoped to an explicit organization.
 *
 * Hidden for members whose role isn't `owner`. Better Auth's
 * `/organization/has-permission` endpoint isn't usable for `apiKey:*` checks
 * (it doesn't pass `allowCreatorAllPermissions` and the default org AC has no
 * `apiKey` statements), so we gate on role directly.
 */
export function OrganizationApiKeys(props: OrganizationApiKeysProps) {
  const auth = useAuth<OrganizationAuthClient>()
  const session = useSession(auth.authClient)
  const members = useListOrganizationMembers(auth.authClient, () => ({
    query: { organizationId: props.organizationId }
  }))
  const canManageApiKeys = createMemo(() =>
    Boolean(
      members.data?.members.some(
        (member: { role?: string | null; userId?: string | null }) =>
          hasMemberRole(member.role, "owner") &&
          member.userId === session.data?.user.id
      )
    )
  )

  return (
    <Show when={canManageApiKeys()}>
      <ApiKeys class={props.class} organizationId={props.organizationId} />
    </Show>
  )
}
