// examples/start-solid-zaidan-example/src/components/auth/settings/account/change-email.tsx
import { getViewURL } from "@better-auth-ui/core"
import { useAuth, useChangeEmail, useSession } from "@better-auth-ui/solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"
import { Button } from "@/components/ui/button"
import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldError, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { cn } from "@/lib/utils"

export type ChangeEmailProps = {
  class?: string
}

export function ChangeEmail(props: ChangeEmailProps = {}) {
  const auth = useAuth()
  const session = useSession(auth.authClient)
  const [emailFieldError, setEmailFieldError] = createSignal<string>()
  const changeEmail = useChangeEmail(auth.authClient, () => ({
    onSuccess: () =>
      toast.success(auth.localization.settings.changeEmailSuccess)
  }))

  const submitChangeEmail = (event: SubmitEvent) => {
    event.preventDefault()

    const formData = new FormData(event.currentTarget as HTMLFormElement)

    changeEmail.mutate({
      callbackURL: getViewURL(
        auth.baseURL,
        auth.basePaths.settings,
        auth.viewPaths.settings.account
      ),
      newEmail: String(formData.get("email") ?? "")
    } as Parameters<typeof changeEmail.mutate>[0])
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.changeEmail}
      </h2>
      <form onSubmit={submitChangeEmail}>
        <Card>
          <CardContent class="flex flex-col gap-6">
            <Field data-invalid={Boolean(emailFieldError())}>
              <FieldLabel for="settings-email">
                {auth.localization.auth.email}
              </FieldLabel>
              <Input
                aria-invalid={!!emailFieldError()}
                autocomplete="email"
                disabled={changeEmail.isPending || !session.data}
                id="settings-email"
                name="email"
                onInput={() => setEmailFieldError(undefined)}
                onInvalid={(event) => {
                  event.preventDefault()
                  setEmailFieldError(event.currentTarget.validationMessage)
                }}
                placeholder={auth.localization.auth.emailPlaceholder}
                required
                type="email"
                value={session.data?.user.email ?? ""}
              />
              <Show when={emailFieldError()}>
                {(message) => <FieldError>{message()}</FieldError>}
              </Show>
            </Field>
          </CardContent>
          <CardFooter>
            <Button
              disabled={changeEmail.isPending || !session.data}
              size="sm"
              type="submit"
            >
              {auth.localization.settings.updateEmail}
            </Button>
          </CardFooter>
        </Card>
      </form>
    </div>
  )
}

// examples/next-shadcn-example/src/components/auth/settings/account/change-email.tsx
"use client"

import { getViewURL, validateEmailAddress } from "@better-auth-ui/core"
import { useAuth, useChangeEmail, useSession } from "@better-auth-ui/react"
import { useEffect } from "react"
import { toast } from "sonner"

import { Card, CardContent, CardFooter } from "@/components/ui/card"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Skeleton } from "@/components/ui/skeleton"
import { Spinner } from "@/components/ui/spinner"
import { cn } from "@/lib/utils"
import { isAuthFormFieldInvalid, useAuthForm } from "../../auth-form"

export type ChangeEmailProps = {
  className?: string
}

/**
 * Render a card containing a form to view and update the authenticated user's email.
 *
 * Shows a loading skeleton until session data is available, displays the current
 * email as the form's default value, and sends a verification email to the
 * new address upon successful submission.
 *
 * @returns A JSX element rendering the change-email card and form
 */
export function ChangeEmail({ className }: ChangeEmailProps) {
  const { authClient, basePaths, baseURL, localization, viewPaths } = useAuth()
  const { data: session } = useSession(authClient)

  const { mutate: changeEmail, isPending } = useChangeEmail(authClient, {
    onSuccess: () => toast.success(localization.settings.changeEmailSuccess)
  })

  const form = useAuthForm({
    defaultValues: { email: "" },
    onSubmit: ({ value }) =>
      changeEmail({
        callbackURL: getViewURL(
          baseURL,
          basePaths.settings,
          viewPaths.settings.account
        ),
        newEmail: value.email
      })
  })

  useEffect(() => {
    if (session) form.reset({ email: session.user.email })
  }, [form, session])

  return (
    <div>
      <h2 className="text-sm font-semibold mb-3">
        {localization.settings.changeEmail}
      </h2>

      <form.AppForm>
        <form.AuthFormRoot>
          <Card className={cn(className)}>
            <CardContent className="flex flex-col gap-6">
              <form.AppField
                name="email"
                validators={{
                  onChange: ({ value }) =>
                    validateEmailAddress(value, {
                      invalidMessage: localization.auth.invalidEmail,
                      requiredMessage: localization.auth.fieldRequired
                    })
                }}
              >
                {(field) => {
                  const isInvalid = isAuthFormFieldInvalid(field.state.meta)
                  return (
                    <Field data-invalid={isInvalid}>
                      <FieldLabel htmlFor="email">
                        {localization.auth.email}
                      </FieldLabel>
                      {session ? (
                        <Input
                          id="email"
                          name={field.name}
                          type="email"
                          autoComplete="email"
                          value={field.state.value}
                          onBlur={field.handleBlur}
                          onChange={(event) =>
                            field.handleChange(event.target.value)
                          }
                          placeholder={localization.auth.emailPlaceholder}
                          disabled={isPending}
                          required
                          aria-invalid={isInvalid}
                        />
                      ) : (
                        <Skeleton>
                          <Input className="invisible" />
                        </Skeleton>
                      )}
                      <field.AuthFormFieldError />
                    </Field>
                  )
                }}
              </form.AppField>
            </CardContent>

            <CardFooter>
              <form.AuthFormSubmitButton
                size="sm"
                disabled={isPending || !session}
              >
                {isPending && <Spinner />}

                {localization.settings.updateEmail}
              </form.AuthFormSubmitButton>
            </CardFooter>
          </Card>
        </form.AuthFormRoot>
      </form.AppForm>
    </div>
  )
}
