// packages/heroui/src/components/auth/multi-session/switch-account-submenu-content.tsx
import type { MultiSessionAuthClient } from "@better-auth-ui/core/plugins/multi-session"
import { useAuth, useAuthPlugin, useSession } from "@better-auth-ui/react"
import { useListDeviceSessions } from "@better-auth-ui/react/plugins/multi-session"
import { Check, CirclePlus } from "@gravity-ui/icons"
import { Dropdown, Label } from "@heroui/react"

import { multiSessionPlugin } from "../../../lib/auth/multi-session-plugin"
import { UserView } from "../user/user-view"
import { SwitchAccountSubmenuItem } from "./switch-account-submenu-item"

/**
 * Render the submenu content for switching between multiple authenticated sessions.
 *
 * Shows the current session with a checkmark, lists other device sessions that can be activated,
 * and provides an option to add a new account. This component should be rendered inside a
 * Dropdown.SubmenuTrigger to defer the useListDeviceSessions query until the submenu is opened.
 *
 * @returns The switch account submenu content as a JSX element
 */
export function SwitchAccountSubmenuContent({
  hideSubtitle
}: {
  hideSubtitle?: boolean
}) {
  const { authClient, basePaths, viewPaths } = useAuth()
  const { localization: multiSessionLocalization } =
    useAuthPlugin(multiSessionPlugin)
  const { data: session } = useSession(authClient)
  const { data: deviceSessions, isPending } = useListDeviceSessions(
    authClient as MultiSessionAuthClient
  )

  return (
    <Dropdown.Popover className="min-w-40 md:min-w-56 max-w-[48svw]">
      <Dropdown.Menu>
        <Dropdown.Item className="px-2">
          <UserView isPending={isPending} hideSubtitle={hideSubtitle} />

          {!isPending && <Check className="ml-auto" />}
        </Dropdown.Item>

        {deviceSessions
          ?.filter(
            (deviceSession) => deviceSession.session.id !== session?.session?.id
          )
          .map((deviceSession) => (
            <SwitchAccountSubmenuItem
              key={deviceSession.session.id}
              deviceSession={deviceSession}
              hideSubtitle={hideSubtitle}
            />
          ))}

        <Dropdown.Item
          textValue={multiSessionLocalization.addAccount}
          href={`${basePaths.auth}/${viewPaths.auth.signIn}`}
        >
          <CirclePlus className="text-muted" />

          <Label>{multiSessionLocalization.addAccount}</Label>
        </Dropdown.Item>
      </Dropdown.Menu>
    </Dropdown.Popover>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/multi-session/switch-account-submenu-content.tsx
import type { MultiSessionAuthClient } from "@better-auth-ui/core/plugins/multi-session"
import {
  multiSessionPlugin as coreMultiSessionPlugin,
  type MultiSessionLocalization,
  multiSessionLocalization
} from "@better-auth-ui/core/plugins/multi-session"
import { AuthLink, useAuth, useSession } from "@better-auth-ui/solid"
import { useListDeviceSessions } from "@better-auth-ui/solid/plugins/multi-session"
import { Check, CirclePlus } from "lucide-solid"
import { For, Show } from "solid-js"
import type { DeviceSession } from "@/components/auth/settings/shared/types"
import { UserView } from "@/components/auth/user/user-view"
import {
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuSubContent
} from "@/components/ui/dropdown-menu"
import { SwitchAccountSubmenuItem } from "./switch-account-submenu-item"

export function SwitchAccountSubmenuContent() {
  const auth = useAuth<MultiSessionAuthClient>()
  const session = useSession(auth.authClient)
  const multiSessionPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMultiSessionPlugin.id)
  const multiSessionLabels = (): MultiSessionLocalization => ({
    ...multiSessionLocalization,
    ...(multiSessionPluginConfig()?.localization as
      | Partial<MultiSessionLocalization>
      | undefined)
  })
  const deviceSessions = useListDeviceSessions(auth.authClient)
  const otherDeviceSessions = () => {
    const sessions = (deviceSessions.data ?? []) as DeviceSession[]

    return sessions.filter(
      (deviceSession) => deviceSession.session.id !== session.data?.session.id
    )
  }

  return (
    <DropdownMenuSubContent class="min-w-48 max-w-[48svw] md:min-w-56">
      <DropdownMenuItem>
        <UserView
          isPending={deviceSessions.isPending}
          user={session.data?.user}
        />
        <Show when={!deviceSessions.isPending}>
          <Check class="ml-auto size-4" />
        </Show>
      </DropdownMenuItem>

      <For each={otherDeviceSessions()}>
        {(deviceSession) => (
          <SwitchAccountSubmenuItem deviceSession={deviceSession} />
        )}
      </For>

      <DropdownMenuSeparator />

      <DropdownMenuItem class="gap-1.5 rounded-md px-1.5 py-1 text-sm focus:bg-accent focus:text-accent-foreground">
        <AuthLink
          class="flex w-full items-center gap-1.5"
          href={`${auth.basePaths.auth}/${auth.viewPaths.auth.signIn}`}
        >
          <CirclePlus class="size-4 text-muted-foreground" />
          {multiSessionLabels().addAccount}
        </AuthLink>
      </DropdownMenuItem>
    </DropdownMenuSubContent>
  )
}
