// examples/start-solid-zaidan-example/src/components/auth/settings/security/linked-accounts.tsx
import { getProviderId } from "@better-auth-ui/core"
import { useAuth, useListAccounts } from "@better-auth-ui/solid"
import { For, Show } from "solid-js"
import type {
  LinkedAccount,
  LinkedProvider
} from "@/components/auth/settings/shared/types"
import { Card, CardContent } from "@/components/ui/card"
import { ItemGroup, ItemSeparator } from "@/components/ui/item"
import { cn } from "@/lib/utils"
import { LinkedAccountRow, LinkedAccountRowSkeleton } from "./linked-account"

export type LinkedAccountsSettingsProps = {
  class?: string
}

export function LinkedAccountsSettings(
  props: LinkedAccountsSettingsProps = {}
) {
  const auth = useAuth()
  const linkedAccounts = useListAccounts(auth.authClient)
  const socialProviders = () => auth.socialProviders ?? []
  const linkedSocialAccounts = () =>
    ((linkedAccounts.data ?? []) as LinkedAccount[]).filter(
      (account) => account.providerId !== "credential"
    )
  const canUnlink = () =>
    auth.allowUnlinkingAllAccounts === true ||
    ((linkedAccounts.data as LinkedAccount[] | undefined)?.length ?? 0) > 1
  const availableProviders = () => {
    if (auth.multipleAccountsPerProvider !== false) return socialProviders()

    const linkedProviderIds = new Set(
      linkedSocialAccounts().map((account) => account.providerId)
    )

    return socialProviders().filter(
      (provider) => !linkedProviderIds.has(getProviderId(provider))
    )
  }
  const accountRows = () => {
    const linked = linkedSocialAccounts().map((account: LinkedAccount) => ({
      account,
      key: account.id,
      provider:
        socialProviders().find(
          (provider) => getProviderId(provider) === account.providerId
        ) ?? (account.providerId as LinkedProvider)
    }))

    return [
      ...linked,
      ...availableProviders().map((provider) => ({
        account: undefined,
        key: getProviderId(provider),
        provider
      }))
    ]
  }

  return (
    <div class={cn(props.class)}>
      <h2 class="mb-3 text-sm font-semibold">
        {auth.localization.settings.linkedAccounts}
      </h2>

      <Card class="z-card-padding-none">
        <CardContent class="z-card-content-padding-none">
          <Show
            fallback={
              <ItemGroup class="gap-0">
                <For each={socialProviders()}>
                  {(_, index) => (
                    <>
                      <Show when={index() > 0}>
                        <ItemSeparator />
                      </Show>
                      <LinkedAccountRowSkeleton />
                    </>
                  )}
                </For>
              </ItemGroup>
            }
            when={!linkedAccounts.isPending}
          >
            <ItemGroup class="gap-0">
              <For each={accountRows()}>
                {(row, index) => (
                  <>
                    <Show when={index() > 0}>
                      <ItemSeparator />
                    </Show>
                    <LinkedAccountRow
                      account={row.account}
                      canUnlink={canUnlink()}
                      provider={row.provider}
                    />
                  </>
                )}
              </For>
            </ItemGroup>
          </Show>
        </CardContent>
      </Card>
    </div>
  )
}

// packages/react-native/src/components/auth/settings/security/linked-accounts.tsx
import { getProviderId } from "@better-auth-ui/core"
import { useAuth, useListAccounts } from "@better-auth-ui/react"
import { cn } from "../../../../lib/cn"
import { Card, type CardVariant } from "../../../../primitives/card"
import { Separator } from "../../../../primitives/separator"
import { Skeleton } from "../../../../primitives/skeleton"
import { Box, Txt } from "../../../../primitives/styled"
import { LinkedAccount } from "./linked-account"

export type LinkedAccountsProps = {
  className?: string
  variant?: CardVariant
}

/**
 * Render a card showing linked social accounts and available social providers to link.
 *
 * Linked accounts (excluding the "credential" provider) are shown with an unlink control;
 * available providers are shown with a link control. Button states and labels reflect
 * ongoing link/unlink activity and use localization for provider-specific text.
 *
 * @returns A JSX element containing the linked accounts card
 */
export function LinkedAccounts({ className, variant }: LinkedAccountsProps) {
  const {
    authClient,
    allowUnlinkingAllAccounts,
    localization,
    multipleAccountsPerProvider,
    socialProviders
  } = useAuth()

  const { data: accounts, isPending } = useListAccounts(authClient)

  const linkedAccounts = accounts?.filter(
    (account) => account.providerId !== "credential"
  )

  const canUnlink =
    allowUnlinkingAllAccounts === true || (accounts?.length ?? 0) > 1

  const linkedProviderIds = new Set(linkedAccounts?.map((a) => a.providerId))

  const availableProviders =
    multipleAccountsPerProvider === false
      ? socialProviders?.filter(
          (provider) => !linkedProviderIds.has(getProviderId(provider))
        )
      : socialProviders

  const allRows = [
    ...(linkedAccounts?.map((account) => ({
      key: account.id,
      account,
      provider:
        socialProviders?.find(
          (provider) => getProviderId(provider) === account.providerId
        ) ?? account.providerId
    })) ?? []),
    ...(availableProviders?.map((provider) => ({
      key: getProviderId(provider),
      account: undefined,
      provider
    })) ?? [])
  ]

  return (
    <Box>
      <Txt className={cn("text-sm font-semibold mb-3 text-foreground")}>
        {localization.settings.linkedAccounts}
      </Txt>

      <Card className={cn(className)} variant={variant}>
        <Card.Content className="gap-0">
          {isPending
            ? socialProviders?.map((provider, index) => (
                <Box key={getProviderId(provider)}>
                  {index > 0 && <Separator className="my-4" />}
                  <AccountRowSkeleton />
                </Box>
              ))
            : allRows.map((row, index) => (
                <Box key={row.key}>
                  {index > 0 && <Separator className="my-4" />}

                  <LinkedAccount
                    account={row.account}
                    canUnlink={canUnlink}
                    provider={row.provider}
                  />
                </Box>
              ))}
        </Card.Content>
      </Card>
    </Box>
  )
}

function AccountRowSkeleton() {
  return (
    <Box className="flex-row items-center justify-between">
      <Box className="flex-row items-center gap-3">
        <Skeleton className="size-10 rounded-xl" />

        <Box className="flex-col gap-1">
          <Skeleton className="h-4 w-20 rounded-lg" />
          <Skeleton className="h-3 w-32 rounded-lg" />
        </Box>
      </Box>
    </Box>
  )
}
