// examples/start-solid-zaidan-example/src/components/auth/settings/settings.tsx
import { useAuth, useSession } from "@better-auth-ui/solid"
import { createMemo, Show } from "solid-js"
import { AccountSettings } from "@/components/auth/settings/account/account-settings"
import { SecuritySettings } from "@/components/auth/settings/security/security-settings"
import type {
  SettingsPathViews,
  SettingsRouteResolution
} from "@/components/auth/settings/shared/types"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { cn } from "@/lib/utils"

export { AccountSettings } from "@/components/auth/settings/account/account-settings"
export { SecuritySettings } from "@/components/auth/settings/security/security-settings"

const settingsPathViews = () => {
  const auth = useAuth()

  return Object.fromEntries(
    Object.entries(auth.viewPaths.settings).map(([view, path]) => [path, view])
  ) as SettingsPathViews
}

export function resolveSettingsRoute(path: string): SettingsRouteResolution {
  if (path === "account") {
    return { component: AccountSettings, title: "Account" }
  }

  if (path === "security") {
    return { component: SecuritySettings, title: "Security" }
  }

  return { redirectTo: "/" }
}

export function Settings(props: { class?: string; path: string }) {
  const auth = useAuth()
  const session = useSession(auth.authClient, {
    enabled: !import.meta.env.SSR
  })
  const currentView = createMemo(() => settingsPathViews()[props.path])
  const activeRoute = createMemo(() => resolveSettingsRoute(props.path))

  const handleSettingsTabChange = (nextView: string) => {
    if (nextView !== "account" && nextView !== "security") return

    auth.navigate({
      to: `${auth.basePaths.settings}/${auth.viewPaths.settings[nextView]}`
    })
  }

  return (
    <div class={cn("w-full gap-4 md:gap-6", props.class)}>
      <Show
        when={!session.isPending && session.data}
        fallback={
          <p class="text-sm text-muted-foreground">Loading settings…</p>
        }
      >
        <Show when={!("redirectTo" in activeRoute())}>
          <Tabs
            aria-label={auth.localization.settings.settings}
            class="w-full gap-4 md:gap-6"
            onChange={handleSettingsTabChange}
            value={currentView()}
          >
            <div>
              <TabsList aria-label={auth.localization.settings.settings}>
                <TabsTrigger value="account">
                  {auth.localization.settings.account}
                </TabsTrigger>
                <TabsTrigger value="security">
                  {auth.localization.settings.security}
                </TabsTrigger>
              </TabsList>
            </div>

            <TabsContent tabIndex={-1} value="account">
              <AccountSettings />
            </TabsContent>
            <TabsContent tabIndex={-1} value="security">
              <SecuritySettings />
            </TabsContent>
          </Tabs>
        </Show>
      </Show>
    </div>
  )
}

// packages/shadcn/src/components/settings/settings.tsx
"use client"

import type { AnyAuthConfig } from "@better-auth-ui/react"
import type { SettingsView } from "@better-auth-ui/react/core"
import { Shield, UserCircle2 } from "lucide-react"
import { useMemo } from "react"

import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { useAuth } from "@/hooks/auth/use-auth"
import { cn } from "@/lib/utils"
import { AccountSettings } from "./settings/account-settings"

export type SettingsProps = AnyAuthConfig & {
  className?: string
  path?: string
  view?: SettingsView
  hideNav?: boolean
}

/**
 * Selects and renders the appropriate settings view component.
 *
 * @param path - Route path used to resolve a settings view when `view` is not provided
 * @param view - Explicit settings view to render (e.g., "account")
 * @param hideNav - Hide the navigation tabs
 */
export function Settings({
  className,
  view,
  path,
  hideNav,
  ...config
}: SettingsProps) {
  const { basePaths, localization, viewPaths, Link } = useAuth(config)

  if (!view && !path) {
    throw new Error("[Better Auth UI] Either `view` or `path` must be provided")
  }

  const settingsPathViews = useMemo(
    () =>
      Object.fromEntries(
        Object.entries(viewPaths.settings).map(([k, v]) => [v, k])
      ) as Record<string, SettingsView>,
    [viewPaths.settings]
  )

  const currentView = view || (path ? settingsPathViews[path] : undefined)

  return (
    <Tabs
      value={currentView}
      className={cn("w-full md:flex-row gap-4 md:gap-6", className)}
    >
      <div className={cn("overflow-auto rounded-md", hideNav && "hidden")}>
        <TabsList
          aria-label={localization.settings.settings}
          className="min-w-full md:w-64 lg:w-72 xl:w-80 md:flex-col md:h-fit md:items-stretch"
        >
          <TabsTrigger value="account" asChild>
            <Link href={`${basePaths.settings}/${viewPaths.settings.account}`}>
              <UserCircle2 />

              {localization.settings.account}
            </Link>
          </TabsTrigger>

          <TabsTrigger value="security" asChild>
            <Link href={`${basePaths.settings}/${viewPaths.settings.security}`}>
              <Shield />

              {localization.settings.security}
            </Link>
          </TabsTrigger>
        </TabsList>
      </div>

      <TabsContent value="account" tabIndex={-1}>
        <AccountSettings {...config} />
      </TabsContent>

      <TabsContent value="security" tabIndex={-1}>
        {localization.settings.security}
      </TabsContent>
    </Tabs>
  )
}
