// apps/docs/src/components/auth/passkey/rename-passkey-dialog.tsx
"use client"

import type { PasskeyAuthClient } from "@better-auth-ui/core/plugins/passkey"
import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useUpdatePasskey } from "@better-auth-ui/react/plugins/passkey"
import { useEffect } from "react"
import { buttonVariants } from "@/components/ui/button"
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { passkeyPlugin } from "@/lib/auth/passkey-plugin"
import { useAuthForm } from "../auth-form"
import type { ListedPasskey } from "./delete-passkey-dialog"

export function RenamePasskeyDialog({
  open,
  onOpenChange,
  passkey
}: {
  open: boolean
  onOpenChange: (open: boolean) => void
  passkey: ListedPasskey
}) {
  const { authClient, localization } = useAuth<PasskeyAuthClient>()
  const { localization: labels } = useAuthPlugin(passkeyPlugin)
  const updatePasskey = useUpdatePasskey(authClient, {
    onSuccess: () => onOpenChange(false)
  })
  const form = useAuthForm({
    defaultValues: { name: passkey.name ?? "" },
    onSubmit: ({ value }) => {
      const name = value.name.trim()
      if (name) updatePasskey.mutate({ id: passkey.id, name })
    }
  })

  useEffect(() => {
    if (open) form.reset({ name: passkey.name ?? "" })
  }, [form, open, passkey.name])

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <form.AppForm>
          <form.AuthFormRoot className="flex flex-col gap-6">
            <DialogHeader>
              <DialogTitle>{labels.renamePasskey}</DialogTitle>
            </DialogHeader>
            <form.AppField name="name">
              {(field) => (
                <Field>
                  <FieldLabel htmlFor={`passkey-name-${passkey.id}`}>
                    {labels.name}
                  </FieldLabel>
                  <Input
                    id={`passkey-name-${passkey.id}`}
                    name={field.name}
                    autoFocus
                    value={field.state.value}
                    onBlur={field.handleBlur}
                    onChange={(event) => field.handleChange(event.target.value)}
                    required
                  />
                </Field>
              )}
            </form.AppField>
            <DialogFooter>
              <DialogClose
                className={buttonVariants({ variant: "outline" })}
                type="button"
              >
                {localization.settings.cancel}
              </DialogClose>
              <form.AuthFormSubmitButton disabled={updatePasskey.isPending}>
                {updatePasskey.isPending && <Spinner />}
                {localization.settings.saveChanges}
              </form.AuthFormSubmitButton>
            </DialogFooter>
          </form.AuthFormRoot>
        </form.AppForm>
      </DialogContent>
    </Dialog>
  )
}

// examples/start-solid-zaidan-example/src/components/auth/passkey/rename-passkey-dialog.tsx
import { validateStringLength } from "@better-auth-ui/core"
import type { PasskeyAuthClient } from "@better-auth-ui/core/plugins/passkey"
import { useAuth } from "@better-auth-ui/solid"
import { useUpdatePasskey } from "@better-auth-ui/solid/plugins/passkey"
import { createEffect } from "solid-js"
import { passkeyLabels } from "@/components/auth/passkey/passkey-localization"
import type { ListedPasskey } from "@/components/auth/settings/shared/types"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Field, FieldLabel } from "@/components/ui/field"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import { createAuthForm } from "../auth-form"

export function RenamePasskeyDialog(props: {
  open: boolean
  onOpenChange: (open: boolean) => void
  passkey: ListedPasskey
}) {
  const auth = useAuth<PasskeyAuthClient>()
  const labels = () => passkeyLabels(auth)
  const updatePasskey = useUpdatePasskey(auth.authClient, () => ({
    onSuccess: () => props.onOpenChange(false)
  }))
  const form = createAuthForm(() => ({
    defaultValues: { name: props.passkey.name ?? "" },
    onSubmit: async ({ value }) => {
      await updatePasskey.mutateAsync({
        id: props.passkey.id,
        name: value.name.trim()
      })
    }
  }))
  createEffect(() => {
    if (props.open) form.setFieldValue("name", props.passkey.name ?? "")
  })

  return (
    <DialogContent>
      <form.AppForm>
        <form.AuthFormRoot class="flex flex-col gap-6">
          <DialogHeader>
            <DialogTitle>{labels().renamePasskey}</DialogTitle>
          </DialogHeader>
          <form.AppField
            name="name"
            validators={{
              onChange: ({ value }) =>
                validateStringLength(value, {
                  requiredMessage: auth.localization.auth.fieldRequired,
                  trim: true
                })
            }}
          >
            {(field) => (
              <Field>
                <FieldLabel for={`passkey-name-${props.passkey.id}`}>
                  {labels().name}
                </FieldLabel>
                <Input
                  id={`passkey-name-${props.passkey.id}`}
                  autofocus
                  name={field().name}
                  value={field().state.value}
                  onBlur={field().handleBlur}
                  onInput={(event) =>
                    field().handleChange(event.currentTarget.value)
                  }
                />
                <field.AuthFormFieldError />
              </Field>
            )}
          </form.AppField>
          <DialogFooter>
            <DialogClose as={Button} type="button" variant="outline">
              {auth.localization.settings.cancel}
            </DialogClose>
            <form.AuthFormSubmitButton disabled={updatePasskey.isPending}>
              {updatePasskey.isPending ? <Spinner /> : null}
              {auth.localization.settings.saveChanges}
            </form.AuthFormSubmitButton>
          </DialogFooter>
          <form.AuthFormServerError />
        </form.AuthFormRoot>
      </form.AppForm>
    </DialogContent>
  )
}
