// examples/start-solid-zaidan-example/src/components/auth/two-factor/regenerate-backup-codes-dialog.tsx
import {
  generateBackupCodesOptions,
  type TwoFactorAuthClient,
  useAuth,
  useAuthPlugin
} from "@better-auth-ui/solid"
import { createMutation } from "@tanstack/solid-query"
import { KeyRound } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import { toast } from "solid-sonner"

import { BackupCodes } from "@/components/auth/two-factor/backup-codes"
import { Button } from "@/components/ui/button"
import {
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle
} from "@/components/ui/dialog"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Spinner } from "@/components/ui/spinner"
import { twoFactorPlugin } from "@/lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "@/lib/auth/use-two-factor-password"

/**
 * Replace the existing backup codes with a fresh set.
 *
 * The new codes are shown once, in component state only — closing the dialog
 * is the point of no return, which is why the copy button sits right there.
 */
export function RegenerateBackupCodesDialog(props: {
  onOpenChange: (open: boolean) => void
}) {
  const auth = useAuth()
  const { localization: twoFactorLocalization } = useAuthPlugin(twoFactorPlugin)
  const { isPending: isResolvingPasswordRequirement, requiresPassword } =
    useTwoFactorPasswordRequirement()

  const [codes, setCodes] = createSignal<string[]>([])

  const generateBackupCodes = createMutation(() => ({
    ...generateBackupCodesOptions(auth.authClient as TwoFactorAuthClient),
    onSuccess: (data) => {
      setCodes(data.backupCodes)
      toast.success(twoFactorLocalization.backupCodesRegenerated)
    }
  }))

  const isPending = () =>
    generateBackupCodes.isPending || isResolvingPasswordRequirement()

  const submit = (event: SubmitEvent & { currentTarget: HTMLFormElement }) => {
    event.preventDefault()

    if (codes().length) {
      props.onOpenChange(false)
      return
    }

    const formData = new FormData(event.currentTarget)
    const password = String(formData.get("password") ?? "")

    generateBackupCodes.mutate(
      (requiresPassword() ? { password } : {}) as Parameters<
        typeof generateBackupCodes.mutate
      >[0]
    )
  }

  return (
    <DialogContent>
      <form class="flex flex-col gap-6" onSubmit={submit}>
        <DialogHeader>
          <div class="flex size-10 items-center justify-center rounded-md bg-muted">
            <KeyRound class="size-4.5" />
          </div>

          <DialogTitle>{twoFactorLocalization.backupCodes}</DialogTitle>

          <DialogDescription>
            {codes().length || !requiresPassword()
              ? twoFactorLocalization.backupCodesDescription
              : twoFactorLocalization.passwordConfirmation}
          </DialogDescription>
        </DialogHeader>

        <Show
          when={codes().length}
          fallback={
            <Show when={requiresPassword()}>
              <div class="grid gap-2">
                <Label for="regenerate-backup-codes-password">
                  {auth.localization.auth.password}
                </Label>

                <Input
                  autocomplete="current-password"
                  autofocus
                  disabled={isPending()}
                  id="regenerate-backup-codes-password"
                  name="password"
                  placeholder={auth.localization.auth.passwordPlaceholder}
                  required
                  type="password"
                />
              </div>
            </Show>
          }
        >
          <BackupCodes codes={codes()} />
        </Show>

        <DialogFooter>
          <Show when={!codes().length}>
            <DialogClose
              as={Button}
              disabled={isPending()}
              type="button"
              variant="outline"
            >
              {auth.localization.settings.cancel}
            </DialogClose>
          </Show>

          <Button disabled={isPending()} type="submit">
            <Show when={isPending()}>
              <Spinner />
            </Show>

            {codes().length
              ? twoFactorLocalization.done
              : twoFactorLocalization.regenerateBackupCodes}
          </Button>
        </DialogFooter>
      </form>
    </DialogContent>
  )
}

// packages/heroui/src/components/auth/two-factor/regenerate-backup-codes-dialog.tsx
import {
  type TwoFactorAuthClient,
  useAuth,
  useAuthPlugin,
  useGenerateBackupCodes
} from "@better-auth-ui/react"
import { Key } from "@gravity-ui/icons"
import {
  AlertDialog,
  Button,
  FieldError,
  Form,
  Input,
  Label,
  Spinner,
  TextField,
  toast
} from "@heroui/react"
import { type SyntheticEvent, useState } from "react"

import { twoFactorPlugin } from "../../../lib/auth/two-factor-plugin"
import { useTwoFactorPasswordRequirement } from "../../../lib/auth/use-two-factor-password"
import { BackupCodes } from "./backup-codes"

export type RegenerateBackupCodesDialogProps = {
  isOpen: boolean
  onOpenChange: (open: boolean) => void
}

/**
 * Replace the existing backup codes with a fresh set.
 *
 * The new codes are shown once, in component state only — closing the dialog
 * is the point of no return, which is why the copy button sits right there.
 *
 * @param isOpen - Whether the dialog is open.
 * @param onOpenChange - Called when the dialog requests an open state change.
 */
export function RegenerateBackupCodesDialog({
  isOpen,
  onOpenChange
}: RegenerateBackupCodesDialogProps) {
  const { authClient, localization } = useAuth()
  const { localization: twoFactorLocalization } = useAuthPlugin(twoFactorPlugin)
  const { requiresPassword } = useTwoFactorPasswordRequirement()

  const [codes, setCodes] = useState<string[]>([])

  const { mutate: generateBackupCodes, isPending } = useGenerateBackupCodes(
    authClient as TwoFactorAuthClient,
    {
      onSuccess: (data) => {
        setCodes(data.backupCodes)
        toast.success(twoFactorLocalization.backupCodesRegenerated)
      }
    }
  )

  const handleOpenChange = (open: boolean) => {
    onOpenChange(open)
    if (!open) setCodes([])
  }

  const handleSubmit = (e: SyntheticEvent<HTMLFormElement>) => {
    e.preventDefault()

    if (codes.length) {
      handleOpenChange(false)
      return
    }

    const formData = new FormData(e.currentTarget)
    const password = formData.get("password") as string

    generateBackupCodes(requiresPassword ? { password } : {})
  }

  return (
    <AlertDialog.Backdrop isOpen={isOpen} onOpenChange={handleOpenChange}>
      <AlertDialog.Container>
        <AlertDialog.Dialog>
          <Form onSubmit={handleSubmit}>
            <AlertDialog.CloseTrigger />

            <AlertDialog.Header>
              <AlertDialog.Icon status="default">
                <Key />
              </AlertDialog.Icon>

              <AlertDialog.Heading>
                {twoFactorLocalization.backupCodes}
              </AlertDialog.Heading>
            </AlertDialog.Header>

            <AlertDialog.Body className="overflow-visible">
              {codes.length ? (
                <BackupCodes codes={codes} />
              ) : (
                <>
                  <p className="text-muted text-sm">
                    {requiresPassword
                      ? twoFactorLocalization.passwordConfirmation
                      : twoFactorLocalization.backupCodesDescription}
                  </p>

                  {requiresPassword && (
                    <TextField
                      className="mt-4"
                      name="password"
                      autoComplete="current-password"
                      isDisabled={isPending}
                    >
                      <Label>{localization.auth.password}</Label>

                      <Input
                        autoFocus
                        required
                        type="password"
                        placeholder={localization.auth.passwordPlaceholder}
                        variant="secondary"
                      />

                      <FieldError />
                    </TextField>
                  )}
                </>
              )}
            </AlertDialog.Body>

            <AlertDialog.Footer>
              {!codes.length && (
                <Button slot="close" variant="tertiary" isDisabled={isPending}>
                  {localization.settings.cancel}
                </Button>
              )}

              <Button type="submit" isPending={isPending}>
                {isPending && <Spinner color="current" size="sm" />}

                {codes.length
                  ? twoFactorLocalization.done
                  : twoFactorLocalization.regenerateBackupCodes}
              </Button>
            </AlertDialog.Footer>
          </Form>
        </AlertDialog.Dialog>
      </AlertDialog.Container>
    </AlertDialog.Backdrop>
  )
}
