// examples/start-solid-zaidan-example/src/components/auth/organization/organization-table-bulk-action.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { Trash2 } from "lucide-solid"
import { createSignal, Show } from "solid-js"
import {
  AlertDialog,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogMedia,
  AlertDialogTitle,
  AlertDialogTrigger
} from "@/components/ui/alert-dialog"
import { Button } from "@/components/ui/button"

export function OrganizationTableBulkAction(props: {
  cancelLabel: string
  confirmLabel: string
  description: string
  disabled?: boolean
  localization: Pick<OrganizationLocalization, "selectedCount">
  onConfirm: () => Promise<void>
  pending: boolean
  selectedCount: number
  title: string
}) {
  const [open, setOpen] = createSignal(false)
  return (
    <Show when={props.selectedCount > 0}>
      <AlertDialog
        open={open()}
        onOpenChange={(next) => !props.pending && setOpen(next)}
      >
        <AlertDialogTrigger
          as={Button}
          disabled={props.disabled}
          size="sm"
          variant="destructive"
        >
          <Trash2 />
          {props.confirmLabel} ({props.selectedCount})
        </AlertDialogTrigger>
        <AlertDialogContent>
          <AlertDialogHeader>
            <AlertDialogMedia>
              <Trash2 />
            </AlertDialogMedia>
            <AlertDialogTitle>{props.title}</AlertDialogTitle>
            <AlertDialogDescription>{props.description}</AlertDialogDescription>
          </AlertDialogHeader>
          <p class="text-sm font-medium">
            {props.localization.selectedCount.replace(
              "{{count}}",
              String(props.selectedCount)
            )}
          </p>
          <AlertDialogFooter>
            <AlertDialogCancel disabled={props.pending}>
              {props.cancelLabel}
            </AlertDialogCancel>
            <Button
              disabled={props.pending}
              onClick={async () => {
                await props.onConfirm()
                setOpen(false)
              }}
              variant="destructive"
            >
              {props.confirmLabel}
            </Button>
          </AlertDialogFooter>
        </AlertDialogContent>
      </AlertDialog>
    </Show>
  )
}

// packages/heroui/src/components/auth/organization/organization-table-bulk-action.tsx
import type { OrganizationLocalization } from "@better-auth-ui/core/plugins/organization"
import { TrashBin } from "@gravity-ui/icons"
import { AlertDialog, Button, Spinner } from "@heroui/react"
import { useState } from "react"

export function OrganizationTableBulkAction({
  cancelLabel,
  confirmLabel,
  description,
  disabled,
  onConfirm,
  pending,
  selectedCount,
  title,
  localization
}: {
  cancelLabel: string
  confirmLabel: string
  description: string
  disabled?: boolean
  onConfirm: () => Promise<void>
  pending: boolean
  selectedCount: number
  title: string
  localization: OrganizationLocalization
}) {
  const [open, setOpen] = useState(false)
  if (!selectedCount) return null
  return (
    <AlertDialog
      isOpen={open}
      onOpenChange={(next) => !pending && setOpen(next)}
    >
      <Button
        size="sm"
        variant="danger-soft"
        isDisabled={disabled}
        onPress={() => setOpen(true)}
      >
        <TrashBin />
        {confirmLabel} ({selectedCount})
      </Button>
      <AlertDialog.Backdrop>
        <AlertDialog.Container>
          <AlertDialog.Dialog>
            <AlertDialog.CloseTrigger isDisabled={pending} />
            <AlertDialog.Header>
              <AlertDialog.Icon status="danger">
                <TrashBin />
              </AlertDialog.Icon>
              <AlertDialog.Heading>{title}</AlertDialog.Heading>
            </AlertDialog.Header>
            <AlertDialog.Body className="flex flex-col gap-3">
              <p className="text-muted text-sm">{description}</p>
              <p className="text-sm font-medium">
                {localization.selectedCount.replace(
                  "{{count}}",
                  String(selectedCount)
                )}
              </p>
            </AlertDialog.Body>
            <AlertDialog.Footer>
              <Button slot="close" variant="tertiary" isDisabled={pending}>
                {cancelLabel}
              </Button>
              <Button
                variant="danger"
                isPending={pending}
                isDisabled={pending}
                onPress={async () => {
                  await onConfirm()
                  setOpen(false)
                }}
              >
                {pending && <Spinner color="current" size="sm" />}
                {confirmLabel}
              </Button>
            </AlertDialog.Footer>
          </AlertDialog.Dialog>
        </AlertDialog.Container>
      </AlertDialog.Backdrop>
    </AlertDialog>
  )
}
