// examples/start-solid-zaidan-example/src/components/auth/magic-link-sent.tsx
import {
  magicLinkPlugin as coreMagicLinkPlugin,
  type MagicLinkLocalization,
  magicLinkLocalization
} from "@better-auth-ui/core/plugins/magic-link"
import { AuthLink, useAuth } from "@better-auth-ui/solid"
import { createSignal, onMount, Show } from "solid-js"
import { isServer } from "solid-js/web"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { cn } from "@/lib/utils"
import { OpenEmailButton } from "./open-email-button"

/** `sessionStorage` key the magic-link form stores the submitted email under. */
export const MAGIC_LINK_SENT_STORAGE_KEY = "better-auth-ui.magic-link-sent"

export type MagicLinkSentProps = {
  class?: string
}

/**
 * Magic-link-sent view. The target email is read from `sessionStorage` (set
 * when the magic-link form redirects here); if none is stored the user is
 * redirected back to the magic-link form. Offers a button to open the user's
 * email provider.
 */
export function MagicLinkSent(props: MagicLinkSentProps) {
  const auth = useAuth()
  const magicLinkPluginConfig = () =>
    auth.plugins.find((plugin) => plugin.id === coreMagicLinkPlugin.id)
  const magicLinkLabels = (): MagicLinkLocalization => ({
    ...magicLinkLocalization,
    ...(magicLinkPluginConfig()?.localization as
      | Partial<MagicLinkLocalization>
      | undefined)
  })
  const magicLinkPath = () =>
    magicLinkPluginConfig()?.viewPaths?.auth?.magicLink ?? "magic-link"

  const [email, setEmail] = createSignal(
    (!isServer && sessionStorage.getItem(MAGIC_LINK_SENT_STORAGE_KEY)) || ""
  )

  onMount(() => {
    const storedEmail = sessionStorage.getItem(MAGIC_LINK_SENT_STORAGE_KEY)

    if (!storedEmail) {
      auth.navigate({
        to: `${auth.basePaths.auth}/${magicLinkPath()}`
      })
      return
    }

    setEmail(storedEmail)
  })

  return (
    <Card class={cn("w-full max-w-sm", props.class)}>
      <CardHeader>
        <CardTitle class="text-xl font-semibold">
          {auth.localization.auth.checkYourEmailTitle}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <div class="flex flex-col gap-4">
          <p class="text-sm text-muted-foreground" role="status">
            {email()
              ? magicLinkLabels().magicLinkSentTo.replace("{{email}}", email())
              : magicLinkLabels().magicLinkSent}
          </p>

          <Show when={email()}>
            <OpenEmailButton email={email()} />
          </Show>
        </div>

        <Show when={auth.emailAndPassword?.enabled}>
          <p class="mt-4 text-center text-muted-foreground text-sm">
            {auth.localization.auth.needToCreateAnAccount}{" "}
            <AuthLink
              href={`${auth.basePaths.auth}/${auth.viewPaths.auth.signUp}`}
            >
              {auth.localization.auth.signUp}
            </AuthLink>
          </p>
        </Show>
      </CardContent>
    </Card>
  )
}

// examples/start-shadcn-example/src/components/auth/magic-link-sent.tsx
"use client"

import { useAuth, useAuthPlugin } from "@better-auth-ui/react"
import { useEffect, useState, useSyncExternalStore } from "react"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { FieldDescription } from "@/components/ui/field"
import { magicLinkPlugin } from "@/lib/auth/magic-link-plugin"
import { cn } from "@/lib/utils"
import { OpenEmailButton } from "./open-email-button"

export type MagicLinkSentProps = {
  className?: string
}

/**
 * Returns `true` once the component is mounted on the client (hydrated) and
 * `false` while rendering on the server, so client-only reads (e.g.
 * `sessionStorage`) stay safe during SSR.
 *
 * @returns Whether the component has hydrated on the client.
 */
function useIsHydrated() {
  const subscribe = () => () => {}
  return useSyncExternalStore(
    subscribe,
    () => true,
    () => false
  )
}

/**
 * Render a card confirming that a magic-link email was sent, with a button
 * to open the user's email provider.
 *
 * The target email is read from `sessionStorage` (set when the magic-link
 * form redirects here); the OpenEmail button is only shown when an email is
 * stored and resolves to a known provider.
 *
 * @param className - Additional CSS classes applied to the card
 * @returns The magic-link-sent card React element
 */
export function MagicLinkSent({ className }: MagicLinkSentProps) {
  const { basePaths, emailAndPassword, localization, viewPaths, Link } =
    useAuth()
  const { localization: magicLinkLocalization } = useAuthPlugin(magicLinkPlugin)

  const isHydrated = useIsHydrated()
  const [email, setEmail] = useState(
    (isHydrated && sessionStorage.getItem("better-auth-ui.magic-link-sent")) ||
      ""
  )

  useEffect(() => {
    setEmail(sessionStorage.getItem("better-auth-ui.magic-link-sent") ?? "")
  }, [])

  return (
    <Card className={cn("w-full max-w-sm", className)}>
      <CardHeader>
        <CardTitle className="text-xl font-semibold">
          {localization.auth.checkYourEmailTitle}
        </CardTitle>
      </CardHeader>

      <CardContent>
        <div className="flex flex-col gap-4">
          <FieldDescription>
            {email
              ? magicLinkLocalization.magicLinkSentTo.replace(
                  "{{email}}",
                  email
                )
              : magicLinkLocalization.magicLinkSent}
          </FieldDescription>

          {email && <OpenEmailButton email={email} />}
        </div>

        {emailAndPassword?.enabled && (
          <div className="flex flex-col gap-3 items-center w-full mt-4">
            <FieldDescription className="text-center">
              {localization.auth.needToCreateAnAccount}{" "}
              <Link
                href={`${basePaths.auth}/${viewPaths.auth.signUp}`}
                className="underline underline-offset-4"
              >
                {localization.auth.signUp}
              </Link>
            </FieldDescription>
          </div>
        )}
      </CardContent>
    </Card>
  )
}
