// examples/next-shadcn-registry-example/src/components/ui/label.tsx
"use client"

import * as React from "react"
import * as LabelPrimitive from "@radix-ui/react-label"

import { cn } from "@/lib/utils"

/**
 * Renders a label element with default layout, spacing, typography, and state-aware styles.
 *
 * @param className - Additional CSS class names to append to the component's default classes
 * @returns The rendered label element
 */
function Label({
  className,
  ...props
}: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "flex items-center gap-2 text-sm leading-none font-medium select-none group-data-[disabled=true]:pointer-events-none group-data-[disabled=true]:opacity-50 peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
        className
      )}
      {...props}
    />
  )
}

export { Label }

// examples/start-solid-zaidan-example/src/components/ui/label.tsx
/** Consumers provide for/htmlFor to connect this label to a control. */
import type { ComponentProps } from "solid-js"
import { splitProps } from "solid-js"
import { cn } from "@/lib/utils"

type LabelProps = ComponentProps<"label">

const Label = (props: LabelProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <label
      class={cn(
        "z-label flex select-none items-center peer-disabled:cursor-not-allowed group-data-[disabled=true]:pointer-events-none",
        local.class
      )}
      data-slot="label"
      {...others}
    />
  )
}

export { Label, type LabelProps }
