// examples/next-shadcn-registry-example/src/components/ui/spinner.tsx
import { Loader2Icon } from "lucide-react"

import { cn } from "@/lib/utils"

/**
 * Renders an accessible animated SVG spinner.
 *
 * @param className - Additional CSS class names to merge with the default sizing and animation classes.
 * @param props - Other SVG attributes forwarded to the underlying icon.
 * @returns An SVG element rendering an accessible, animated loading spinner.
 */
function Spinner({ className, ...props }: React.ComponentProps<"svg">) {
  return (
    <Loader2Icon
      role="status"
      aria-label="Loading"
      className={cn("size-4 animate-spin", className)}
      {...props}
    />
  )
}

export { Spinner }

// examples/start-solid-zaidan-example/src/components/ui/spinner.tsx
import { LoaderCircle } from "lucide-solid"
import type { ComponentProps } from "solid-js"
import { splitProps } from "solid-js"
import { cn } from "cn"

type SpinnerProps = ComponentProps<"svg"> & {
  class?: string | undefined
}

const Spinner = (props: SpinnerProps) => {
  const [local, others] = splitProps(props, ["class"])

  return (
    <LoaderCircle
      aria-label="Loading"
      class={cn("z-spinner size-4 animate-spin", local.class)}
      data-slot="spinner"
      role="status"
      {...others}
    />
  )
}

export { Spinner }
